### PR TITLE
[VCDA-4608] Add disk size to node pools

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

## Description
Please provide a brief description of the changes proposed in this Pull Request

- Update node pools with disk size 

## Checklist
- [ ] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/297)

### CODE REVIEW

**Review by lzichong — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/297#-:-NEItTCoAixclMDMp_O4:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Anirudh9794)

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/297)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @Anirudh9794)

___
*[`controllers/capi_objects_utils.go` line 279 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/297#-NESvFlVAVdqIUJTY0w1:-NESvFlVAVdqIUJTY0w2:bekfgrp) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ee88976fdbcb5e2abf4f0813a7f5d84180e041c2/controllers/capi_objects_utils.go#L279)):*
> ```Go
> 			NvidiaGpuEnabled:  vcdMachineTemplate.Spec.Template.Spec.EnableNvidiaGPU,
> 			StorageProfile:    vcdMachineTemplate.Spec.Template.Spec.StorageProfile,
> 			DiskSizeMb:        int32(vcdMachineTemplate.Spec.Template.Spec.DiskSize.Value() / (1024 * 1024)),
> ```

What if the user-specified diskSize is empty? Then we may have to get the value from the VM object. Please check. We don't want incorrect values getting displayed in the UI.

**Comment by Anirudh9794** [comment]
*[`controllers/capi_objects_utils.go` line 279 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/297#-NESvFlVAVdqIUJTY0w1:-NEbW6l81QhPTwhHnCPl:bdby5mb) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ee88976fdbcb5e2abf4f0813a7f5d84180e041c2/controllers/capi_objects_utils.go#L279)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

What if the user-specified diskSize is empty? Then we may have to get the value from the VM object. Please check. We don't want incorrect values getting displayed in the UI.
</blockquote></details>

I made sure that when disk size is not inputted, the RDE reflects 0 for this field.
I had to remove omitempty in the RDE types for DiskSizeMb to make sure RDE doesn't omit the key when the value is 0.

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/297#-:-NEh4QTU-nRox-WbYpJK:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Pull request merged**
