### PR TITLE
[CAFV-285] Refractor CAPVCD test automation AND use server side apply to do Kubernetes operations

### PR DESCRIPTION
**Pull request by ymo24**
## Description

- Use `Server Side Apply` to apply and delete objects of `capiYaml`.
- Update the instruction documents for `CAPVCD` test automation.
- 

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467)

### CODE REVIEW

**Review by Anirudh9794 — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @ymo24)

___
*[`tests/e2e/workload_cluster_test.go` line 49 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467#-NYz4WWQ4sySE604PqH0:-NYz4WWQ4sySE604PqH1:b-ip5i9z) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6b5c4f0a5482bed406b71638d909cc0c398b8e6b/tests/e2e/workload_cluster_test.go#L49)):*
> ```Go
> 			fmt.Println("Getting the CAPI YAML!")
> 			capiYaml, err = os.ReadFile(PathToWorkloadClusterCapiYaml)
> 			ExpectWithOffset(1, err).NotTo(HaveOccurred(), "Failed to read CAPI YAML")
> ```

Just curious. Why is `ExpectWithOffset` used here? Does `Expect()` not work here?
___
*[`tests/e2e/workload_cluster_test.go` line 106 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467#-NYz7DQ49GZI2K4_YcCX:-NYz7DQ49GZI2K4_YcCY:b-t9vs6d) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6b5c4f0a5482bed406b71638d909cc0c398b8e6b/tests/e2e/workload_cluster_test.go#L106)):*
> ```Go
> 			By("Getting the rdeID from the vcdCluster")
> 			rdeID = vcdCluster.Status.InfraId
> 			ExpectWithOffset(1, rdeID).NotTo(BeNil(), "rdeID is empty")
> ```

Since rdeID is a string, it won't be nil. We should check if the value is a zero value



_Code quote (i):_
```Go
ExpectWithOffset(1, rdeID).NotTo(BeNil(), "rdeID is empty")
```



_Code snippet (ii):_
```Go
ExpectWithOffset(1, rdeID).NotTo(BeZero(), "rdeID is empty")
```
___
*[`tests/e2e/workload_cluster_test.go` line 170 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467#-NYz95Eq-tybhBl_skRf:-NYz95Eq-tybhBl_skRg:bmwy12o) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6b5c4f0a5482bed406b71638d909cc0c398b8e6b/tests/e2e/workload_cluster_test.go#L170)):*
> ```Go
> 			ExpectWithOffset(1, err).NotTo(HaveOccurred(), "Failed to monitor cluster deletion")
> 			err = testClient.DeleteNameSpace(ctx, clusterName)
> 			ExpectWithOffset(1, err).NotTo(HaveOccurred(), "Failed to delete cluster namespace")
> ```

Can you please add a test case to verify if RDE is deleted ?

**Review by sahithi — APPROVED** [review]
:lgtm: after comments are addressed.
(Note that I did not review every line regarding the correctness and ginkgo construct usage; please ensure the correctness by testing your code).

Good work Yan, thanks for doing this!

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467#-:-NZ2vDhO7c_s3tpTe-Fe:b-fq0d7v)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @ymo24)

___
*[`tests/e2e/utils/k8s_util.go` line 231 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467#-NZ2ssZyAHW4MkZlf6Rc:-NZ2ssZyAHW4MkZlf6Rd:b-3j5nel) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6b5c4f0a5482bed406b71638d909cc0c398b8e6b/tests/e2e/utils/k8s_util.go#L231)):*
> ```Go
> 	hundredKB := 100 * 1024
> 	vcdCluster := &infrav2.VCDCluster{}
> 	resp, err := cs.RESTClient().Get().
> ```

See if you can use something like the below here, so that there is no hardcoding of API paths? 



_Code snippet:_
```Go
vcdCluster := &infrav1.VCDCluster{}
	
	if err := r.Client.Get(ctx, req.NamespacedName, vcdCluster); err != nil {
		if apierrors.IsNotFound(err) {
			return ctrl.Result{}, nil
		}
		return ctrl.Result{}, err
	}
```
___
*[`tests/e2e/utils/node_pool_scaling_utils.go` line 29 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467#-NZ2uz1o-clrpEhg58R8:-NZ2uz1o-clrpEhg58R9:b-94xx8k) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6b5c4f0a5482bed406b71638d909cc0c398b8e6b/tests/e2e/utils/node_pool_scaling_utils.go#L29)):*
> ```Go
> 
> 	// Iterate through YAML documents
> 	for err == nil {
> ```

Do we need to parse the capiyaml again? Can't we get the MachineDeployment by name and namespace and just edit MD.spec.replica directly?

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467)* status: 0 of 17 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`tests/e2e/workload_cluster_test.go` line 49 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467#-NYz4WWQ4sySE604PqH0:-NZ2vvdQ58ZBi0vhZRTc:b-fperks) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6b5c4f0a5482bed406b71638d909cc0c398b8e6b/tests/e2e/workload_cluster_test.go#L49)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Just curious. Why is `ExpectWithOffset` used here? Does `Expect()` not work here?
</blockquote></details>

By using `ExpectWithOffset`, you can have more accurate failure messages and easier debugging in your Ginkgo test cases.
___
*[`tests/e2e/workload_cluster_test.go` line 106 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467#-NYz7DQ49GZI2K4_YcCX:-NZ34X9E0Wi5LbRtMcP5:b-fv86ee) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6b5c4f0a5482bed406b71638d909cc0c398b8e6b/tests/e2e/workload_cluster_test.go#L106)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Since rdeID is a string, it won't be nil. We should check if the value is a zero value
</blockquote></details>

Done. Thanks Aniruddha
___
*[`tests/e2e/workload_cluster_test.go` line 170 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467#-NYz95Eq-tybhBl_skRf:-NZ34XbxE1Rc2SeiiAMh:b-fv86ee) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6b5c4f0a5482bed406b71638d909cc0c398b8e6b/tests/e2e/workload_cluster_test.go#L170)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Can you please add a test case to verify if RDE is deleted ?
</blockquote></details>

Done. Thanks Aniruddha

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467)* status: 0 of 17 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`tests/e2e/utils/k8s_util.go` line 231 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467#-NZ2ssZyAHW4MkZlf6Rc:-NZ3SJeY1S0PHsHIgA9n:b-9y0pwa) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6b5c4f0a5482bed406b71638d909cc0c398b8e6b/tests/e2e/utils/k8s_util.go#L231)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

See if you can use something like the below here, so that there is no hardcoding of API paths? 
</blockquote></details>

Done. Thanks Sahithi.
___
*[`tests/e2e/utils/node_pool_scaling_utils.go` line 29 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467#-NZ2uz1o-clrpEhg58R8:-NZ3SKIg8-sJLgdVWiZ3:b-9y0pwa) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6b5c4f0a5482bed406b71638d909cc0c398b8e6b/tests/e2e/utils/node_pool_scaling_utils.go#L29)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Do we need to parse the capiyaml again? Can't we get the MachineDeployment by name and namespace and just edit MD.spec.replica directly?
</blockquote></details>

Done. Thanks Sahithi.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: with minor comments

> Reviewed 2 of 5 files at r1, 7 of 14 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467#-:-NZ3VGR53exYTqa95mDa:b-ij5eeu)* status: 10 of 17 files reviewed, 4 unresolved discussions (waiting on @sahithi and @ymo24)

___
*[`tests/e2e/doc.md` line 31 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467#-NZ3PS1c0BcsB9aFVfKx:-NZ3PS1c0BcsB9aFVfKy:bm9zvrm) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0a68216fe7c549f1a7d58bf1bd2f8f9c9b51f6d6/tests/e2e/doc.md#L31)):*
> ```Markdown
>     - Wait for all the machine states become `running`
>   - Resize the workload cluster
>     - increase the worker pool node of the workload cluster
> ```

worker pool node count*
___
*[`tests/e2e/utils/k8s_util.go` line 87 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467#-NZ3TSut-3F8VvuxvYm3:-NZ3TSut-3F8VvuxvYm4:bzc4ezi) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0a68216fe7c549f1a7d58bf1bd2f8f9c9b51f6d6/tests/e2e/utils/k8s_util.go#L87)):*
> ```Go
> 		// Check if the object is a secret
> 		if unstructuredObj.GetKind() == SECRET {
> 			fmt.Printf("Skipping deletion of secret: %s/%s\n", unstructuredObj.GetNamespace(), unstructuredObj.GetName())
> ```

If we are not deleting the secret and if someone wants to re-use the kind cluster to run the tests again, do they have to delete the secret manually?

**Pull request merged**
