### PR TITLE
VCDA-4136 update rde with default storage class options in reconcileRDE

### PR DESCRIPTION
**Pull request by abaruni**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- 

## Checklist
- [ ] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/212)

### CODE REVIEW

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/212)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @abaruni and @Anirudh9794)

___
*[`controllers/vcdcluster_controller.go` line 463 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/212#-N7qvhRQE5pLwEDkOQYC:-N7qvhRQE5pLwEDkOQYD:bybybjs) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/de9753dc9d3e96f0d944cde9b9626c10988f9805/controllers/vcdcluster_controller.go#L463)):*
> ```Go
> 	}
> 
> 	if vcdCluster.Status.DefaultStorageClassOptions.VCDStorageProfileName != "" {
> ```

I think the following check will be more appropriate and will decrease the number of updates that need to be done ( if there are no changes to the RDE)
```
if vcdCluster.Status.DefaultStorageClassOptions.VCDStorageProfileName != "" {
    dsc := rdeType.DefaultStorageClass{ ... }
    if !reflect.DeepEqual(capvcdStatus.DefaultStorageClass, dsc) {
        capvcdStatusPatch["DefaultStorageClass"] = dsc
    }
}
```

**Review by abaruni — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/212)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @abaruni and @Anirudh9794)

___
*[`controllers/vcdcluster_controller.go` line 463 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/212#-N7qvhRQE5pLwEDkOQYC:-N7qwhna3KFwsQVlg1gf:b-d7bhn0) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/de9753dc9d3e96f0d944cde9b9626c10988f9805/controllers/vcdcluster_controller.go#L463)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think the following check will be more appropriate and will decrease the number of updates that need to be done ( if there are no changes to the RDE)
```
if vcdCluster.Status.DefaultStorageClassOptions.VCDStorageProfileName != "" {
    dsc := rdeType.DefaultStorageClass{ ... }
    if !reflect.DeepEqual(capvcdStatus.DefaultStorageClass, dsc) {
        capvcdStatusPatch["DefaultStorageClass"] = dsc
    }
}
```
</blockquote></details>

will do

**Review by abaruni — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/212)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[`controllers/vcdcluster_controller.go` line 463 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/212#-N7qvhRQE5pLwEDkOQYC:-N7qyvN_DU6dOcHjRorK:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/de9753dc9d3e96f0d944cde9b9626c10988f9805/controllers/vcdcluster_controller.go#L463)):*
<details><summary><i>Previously, abaruni (Adnan Baruni) wrote…</i></summary><blockquote>

will do
</blockquote></details>

Done.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/212#-:-N7r5F8c0ao_H5xxdRdm:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Pull request merged**
