### PR TITLE
[VCDA-3358] Doc improvements

### PR DESCRIPTION
**Pull request by Anirudh9794**
* Change git clone command to clone from 0.5.0 tag
* Change github link to https
* Update the clustectl version supported to 0.4.7
* Add comments suggesting users to use `system/administrator` over `administrator@system` when the user is system administrator
* Update CAPI version to v1alpha4 in README
* Add a table in README similar to what we have in CPI with link to 0.5.0 CAPVCD release tag
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/58)

### CODE REVIEW

**Comment by arunmk** [comment]
___
*[docs/MANAGEMENT_CLUSTER.md, line 31 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/58#-Mve2A34Bp31XtqoOott:-Mve2A34Bp31XtqoOotu:b-eqpe0d) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f94caca95630ad3294b6b82a2517986f7420b4ca/docs/MANAGEMENT_CLUSTER.md#L31)):*
> ```Markdown
> 2. Install Infrastructure provider - CAPVCD
>     1. Download CAPVCD repo - `git clone --branch 0.5.0 https://github.com/vmware/cluster-api-provider-cloud-director.git`
>     2. Fill in the VCD details in `cluster-api-provider-cloud-director/config/manager/controller_manager_config.yaml`
> ```

Can we also say: if we are using system administrator, use username as `system/administrator`. Many folks use administrator@system

**Review by arunmk — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/58)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @arunmk)

**Comment by Anirudh9794** [comment]
___
*[docs/MANAGEMENT_CLUSTER.md, line 31 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/58#-Mve2A34Bp31XtqoOott:-Mve4k1j8sJKH_tM9fob:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f94caca95630ad3294b6b82a2517986f7420b4ca/docs/MANAGEMENT_CLUSTER.md#L31)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we also say: if we are using system administrator, use username as `system/administrator`. Many folks use administrator@system
</blockquote></details>

Done.

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/58)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[docs/MANAGEMENT_CLUSTER.md, line 25 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/58#-MvePH1cDMMb_X_Z7aXD:-MvePH1cDMMb_X_Z7aXE:b-fuvb27) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/dce5953db1e70534310ca608db6c802b98333131/docs/MANAGEMENT_CLUSTER.md#L25)):*
> ```Markdown
> Typically, command `clusterctl init` enables the initialization of the core Cluster API and allows the installation of
> infrastructure provider specific Cluster API (in this case, CAPVCD). CAPVCD, as of now, is not yet available via
> `clusterctl init`. Therefore, a separate set of commands are provided below for the installation purposes.
> ```

Can you add the workaround for the certmanager issue?
___
*[docs/MANAGEMENT_CLUSTER.md, line 32 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/58#-MveP2HoAgQUIxhu1pTH:-MveP2HoAgQUIxhu1pTI:bgz82rc) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/dce5953db1e70534310ca608db6c802b98333131/docs/MANAGEMENT_CLUSTER.md#L32)):*
> ```Markdown
>     1. Download CAPVCD repo - `git clone --branch 0.5.0 https://github.com/vmware/cluster-api-provider-cloud-director.git`
>     2. Fill in the VCD details in `cluster-api-provider-cloud-director/config/manager/controller_manager_config.yaml`
>     3. Input username and password in `config/manager/kustomization.yaml`. Refer to the rights required for the role [here](VCD_SETUP.md). If system administrator is the user, please use 'system/administrator' as the username.
> ```

Please add this comment in the kustomization.yaml file as well (and also capi examples)

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/58)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[docs/MANAGEMENT_CLUSTER.md, line 25 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/58#-MvePH1cDMMb_X_Z7aXD:-MveVdrsDPDCklSzb0bB:b-3y7xcj) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/dce5953db1e70534310ca608db6c802b98333131/docs/MANAGEMENT_CLUSTER.md#L25)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you add the workaround for the certmanager issue?
</blockquote></details>

As per discussion, I have suggested the the clusterctl cli version to be used is 0.4.7.
The `clusterctl init ` command uses core-capi, kcp and bootstrap provider version as 0.4.2.
___
*[docs/MANAGEMENT_CLUSTER.md, line 32 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/58#-MveP2HoAgQUIxhu1pTH:-MveSf1mBcvJwvLXdtuY:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/dce5953db1e70534310ca608db6c802b98333131/docs/MANAGEMENT_CLUSTER.md#L32)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please add this comment in the kustomization.yaml file as well (and also capi examples)
</blockquote></details>

Done.



_Code quote:_
```Markdown
If system administrator is the user, please use 'system/administrator' as the username.
```

**Review by sahithi — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/58#-:-MveptXN2NCtDTe4Z6XJ:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @arunmk and @sahithi)

**Review by arunmk — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/58#-:-MveuzsB18lCBNeVHMnY:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[docs/MANAGEMENT_CLUSTER.md, line 31 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/58#-Mve2A34Bp31XtqoOott:-MveGugy3EIcABHNeY6g:b-mwc4l7) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f94caca95630ad3294b6b82a2517986f7420b4ca/docs/MANAGEMENT_CLUSTER.md#L31)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nit: use `system/administrator` with reverse quotes to highlight and also give code format

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/58)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[docs/MANAGEMENT_CLUSTER.md, line 31 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/58#-Mve2A34Bp31XtqoOott:-MvewmYH4W6yo4ajhiIH:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f94caca95630ad3294b6b82a2517986f7420b4ca/docs/MANAGEMENT_CLUSTER.md#L31)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Nit: use `system/administrator` with reverse quotes to highlight and also give code format
</blockquote></details>

Done.

**Pull request merged**
