### PR TITLE
[VCDA-4434] Schema changes on v1beta1 vcdcluster && vcdmachine (CapiYamlSchema)

### PR DESCRIPTION
**Pull request by ymo24**
Signed-off-by: ymo24 <ymo@vmware.com>

## Description
VCDCluster.Spec
Missing Kubebuilder defaults for UseAsManagementCluster
Rename ProxyConfig -> proxyConfigSpec (consistent with K8s naming convention)
Loadbalancer -> loadbalancerConfigSpec
VCDCluster.Status
vappmetadataUpdated -> vappMetadataUpdated
Missing properties
site, org, ovdc,ovdcnetwork, loadBalancerConfig
VCDMachineSpec
nvidiaGPU -> enableNvidiaGPU (bools are usually verbs )
VCDMachineStatus is missing below properties
sizingpolicy
placementpolicy
nvidiaGpuEnabled
diskSize

-  [VCDA-4434](https://jira.eng.vmware.com/browse/VCDA-4434)

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [x] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [x] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [x] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [x] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [x] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [x] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266)

### CODE REVIEW

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @sahithi)

___
*[`infrastructure-vcd/v1.0.0/cluster-template.yaml` line 54 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266#-NCWuSjF5Y4Z7N-zqArm:-NCX0HFe5w8dtUDIjcy4:b-i8u4cp) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3af7160a296edf445a6288779c0e9a8aedf2e2ed/infrastructure-vcd/v1.0.0/cluster-template.yaml#L54)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Typo loadBalancerConfigSpe -> loadBalancerConfigSpec
</blockquote></details>

Already fixed it. Thanks Aniruddha

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266)* status: 9 of 17 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @ymo24)

___
*[`infrastructure-vcd/v1.0.0/infrastructure-components.yaml` line 309 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266#-NCX3Dbo41i0Yvok4dHi:-NCaog8a1VR7i3QzYFaA:b-zhwefx) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3af7160a296edf445a6288779c0e9a8aedf2e2ed/infrastructure-vcd/v1.0.0/infrastructure-components.yaml#L309)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Shouldn't this be loadBalancerConfigSpec?
</blockquote></details>

For the vcdCluster.spec, we have loadBalancerConfigSpec. As for the vcdCluster.status, we use loadBalancerConfig. Should we change loadBalancerConfig to loadBalancerConfigSpec or loadBalancerConfigStatus for vcdCluster.status?



_Code quote:_
```YAML
loadBalancerConfig
```

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266)* status: 9 of 17 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @ymo24)

___
*[`infrastructure-vcd/v1.0.0/cluster-template.yaml` line 55 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266#-NCX0jae8pJcEOrwR6nn:-NCax-JE0YjQMruTh4mB:bfc4sjk) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3af7160a296edf445a6288779c0e9a8aedf2e2ed/infrastructure-vcd/v1.0.0/cluster-template.yaml#L55)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you add another property - useOneArm?
Also, can you ensure all the properties under VCDCluster.spec are present here in this template, like proxyConfig etc?
</blockquote></details>

Yes, I have added the parameters with explanation. Sorry I saw it was added without useOneArm, I thought there must be a reason.
___
*[`infrastructure-vcd/v1.0.0/cluster-template.yaml` line 8 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266#-NCanPZX-IWy9__2UIIA:-NCawsvh5n5esLzZ1UOk:bkxo7sb) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/751f3ef158f57e66282d5f752875fa9d7883ebff/infrastructure-vcd/v1.0.0/cluster-template.yaml#L8)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please update clusterctl.yaml with these new variablles.

Ensure the overall correctness of that file.
</blockquote></details>

I checked clusterctl.yaml and add every missing param in that file. Thanks Sahithi!
___
*[`infrastructure-vcd/v1.0.0/cluster-template.yaml` line 65 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266#-NCan6P67ayK7QT6LB3v:-NCasGF11m1Yt54rhD0x:bfszds7) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/751f3ef158f57e66282d5f752875fa9d7883ebff/infrastructure-vcd/v1.0.0/cluster-template.yaml#L65)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

missing noProxy variable?
</blockquote></details>

Already pushed. Thanks Sahithi.

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266)* status: 9 of 18 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`examples/capi-quickstart.yaml` line 61 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266#-NCamntj648re_LsN2B4:-NCb71k1BdGs1e5694l2:b-xgfews) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/751f3ef158f57e66282d5f752875fa9d7883ebff/examples/capi-quickstart.yaml#L61)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

You can remove "executeWithoutRDE" property, I don't see any property in the VCDCluster type
</blockquote></details>

Already pushed the changes. Thanks Sahithi!

**Review by sahithi — APPROVED** [review]
:lgtm:  after addressing the comments

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266#-:-NCbF0AG06as3wpUKkd4:b243xmo)* status: 9 of 18 files reviewed, 8 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @ymo24)

___
*[`infrastructure-vcd/v1.0.0/cluster-template.yaml` line 63 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266#-NCbFCaIAHYp1NJ8zNSa:-NCbFCaJ3MfK5yvkhl0Y:b-5svlrw) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/dfead6ce71f10dad2fa18965efae8438584a6e72/infrastructure-vcd/v1.0.0/cluster-template.yaml#L63)):*
> ```YAML
>   loadBalancerConfigSpec:
>     vipSubnet: ${IP_SUBNET} # Virtual IP CIDR for the external network
>     useOneArm: ${ENABLE_ONEARM}
> ```

Can you add a comment on the purpose of OneArm? I think this is only intended for capvcd 0.5 clusters. Please check with Arun.

Also add the comment on VCDCluster struct param so that it gets reflected in the CRDs.
___
*[`infrastructure-vcd/v1.0.0/clusterctl.yaml` line 32 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266#-NCbEb6a8ICM5LssJdJF:-NCbEb6a8ICM5LssJdJG:bmp3guh) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/dfead6ce71f10dad2fa18965efae8438584a6e72/infrastructure-vcd/v1.0.0/clusterctl.yaml#L32)):*
> ```YAML
> VCD_CATALOG: "test_catalog"
> VCD_CONTROL_PLANE_SIZING_POLICY: "large_4core16gb"
> VCD_CONTROL_PLANE_STORAGE_PROFIL: "*"
> ```

PROFILE - spelling
___
*[`infrastructure-vcd/v1.0.0/clusterctl.yaml` line 58 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266#-NCbExG13-IaR9fsjAdo:-NCbExG13-IaR9fsjAdp:b-d0wxhj) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/dfead6ce71f10dad2fa18965efae8438584a6e72/infrastructure-vcd/v1.0.0/clusterctl.yaml#L58)):*
> ```YAML
> SSH_PUBLIC_KEY: ""
> DISK_SIZE: 20Gi
> WORKER_POOL_NAME: "work-pool-1"
> ```

new line

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266)* status: 7 of 18 files reviewed, 8 unresolved discussions

___
*[`infrastructure-vcd/v1.0.0/cluster-template.yaml` line 63 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266#-NCbFCaIAHYp1NJ8zNSa:-NCbNeke0tL4oUvJYEjN:b-xf7ohx) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/dfead6ce71f10dad2fa18965efae8438584a6e72/infrastructure-vcd/v1.0.0/cluster-template.yaml#L63)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you add a comment on the purpose of OneArm? I think this is only intended for capvcd 0.5 clusters. Please check with Arun.

Also add the comment on VCDCluster struct param so that it gets reflected in the CRDs.
</blockquote></details>

Have already added description in CRDs. Thanks Sahithi
___
*[`infrastructure-vcd/v1.0.0/clusterctl.yaml` line 32 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266#-NCbEb6a8ICM5LssJdJF:-NCbNjv472bmikEGDaTT:br0fmem) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/dfead6ce71f10dad2fa18965efae8438584a6e72/infrastructure-vcd/v1.0.0/clusterctl.yaml#L32)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

PROFILE - spelling
</blockquote></details>

Thanks Sahithi! Have fixed it. 
___
*[`infrastructure-vcd/v1.0.0/clusterctl.yaml` line 58 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/266#-NCbExG13-IaR9fsjAdo:-NCbNmTf9Fm1VlDarAse:bzigzcb) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/dfead6ce71f10dad2fa18965efae8438584a6e72/infrastructure-vcd/v1.0.0/clusterctl.yaml#L58)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Would pay attention to that in my following PRs. Thanks for reminder.

**Pull request merged**
