### PR TITLE
VCDA-3245: Clean cleanup of objects

### PR DESCRIPTION
**Pull request by arunmk**
VCDMachine and VCDCluster should not wait for cluster creation events in deletion paths

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/34)

### CODE REVIEW

**Review by sahithi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/34)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @ltimothy7)

___
*[controllers/vcdcluster_controller.go, line 120 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/34#-MtPgIKT9xLs9DICdLVp:-MtPgIKT9xLs9DICdLVq:bco6jva) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f9df3b413bb6fd40a044eb04787c36786c6c04b8/controllers/vcdcluster_controller.go#L120)):*
> ```Go
> 	}
> 
> 	if clusterBeingDeleted {
> ```

If we want to skip all the conditions above, why can't we move this reconcileDelete() block to the top (or) move other conditions below the reconcileDelete() block?
___
*[controllers/vcdmachine_controller.go, line 115 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/34#-MtPg0Dj4sX-Xb_9Ub-C:-MtPg0Dj4sX-Xb_9Ub-D:bcug1is) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f9df3b413bb6fd40a044eb04787c36786c6c04b8/controllers/vcdmachine_controller.go#L115)):*
> ```Go
> 			return ctrl.Result{}, nil
> 		} else {
> 			log.Info("Will continue and try to delete the machine")
> ```

nit: to keep it consistent with your other log message 
Continuing to delete the VCDMachine, since deletion timestamp is set 
___
*[controllers/vcdmachine_controller.go, line 150 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/34#-MtPgylH43kgFSckq8SY:-MtPgylH43kgFSckq8SZ:b-lsaebg) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f9df3b413bb6fd40a044eb04787c36786c6c04b8/controllers/vcdmachine_controller.go#L150)):*
> ```Go
> 
> 	// Handle deleted machines
> 	if machineBeingDeleted {
> ```

same here, can this block be moved up?
___
*[controllers/vcdmachine_controller.go, line 727 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/34#-MtPiXjsBC0Uc0ZTJYHP:-MtPiXjsBC0Uc0ZTJYHQ:bxphjug) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f9df3b413bb6fd40a044eb04787c36786c6c04b8/controllers/vcdmachine_controller.go#L727)):*
> ```Go
> 	}
> 
> 	if vcdCluster.Spec.Site == "" {
> ```

Site is a required param, we may not even need this condition.

**Review by ltimothy7 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/34)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

**Review by sahithi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/34#-:-MtPrT3-DUxq5glIHnWY:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/34)* status: all files reviewed, 4 unresolved discussions (waiting on @arunmk)

**Review by arunmk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/34)* status: all files reviewed, 4 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[controllers/vcdmachine_controller.go, line 115 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/34#-MtPg0Dj4sX-Xb_9Ub-C:-MtQ2rR81qOmlqNP4toJ:b2nhysk) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f9df3b413bb6fd40a044eb04787c36786c6c04b8/controllers/vcdmachine_controller.go#L115)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

nit: to keep it consistent with your other log message 
Continuing to delete the VCDMachine, since deletion timestamp is set 
</blockquote></details>

ack

**Pull request merged**
