### PR TITLE
[CAFV-246] upgrade go version to 1.19

### PR DESCRIPTION
**Pull request by ymo24**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- Upgrade golang version to 1.19
   - go mod edit -go=1.19
   - go mod tidy
   - go mod vendor

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/440)

### CODE REVIEW

**Review by abaruni — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/440)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arunmk)

**Review by arunmk — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/440#-:-NUeqLZ5AztPs_VgJkmt:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ymo24)

**Review by arunmk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/440)* status: all files reviewed, 1 unresolved discussion (waiting on @ymo24)

___
*[`Makefile` line 93 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/440#-NUeqdB4-Kjed7nLbAqd:-NUeqdB52bNPzyTDMSxB:bslzghd) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8805aa37b5df3c06c1292195520e9305533ec994/Makefile#L93)):*
> ```Makefile
> vendor: ## Run go mod vendor
> 	go mod edit -go=1.19
> 	go mod tidy -compat=1.17
> ```

Shouldn't this also be 1.19?

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/440)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @abaruni and @arunmk)

___
*[`Makefile` line 93 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/440#-NUeqdB4-Kjed7nLbAqd:-NV0xlBq2-hNYHLwO3FC:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8805aa37b5df3c06c1292195520e9305533ec994/Makefile#L93)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Shouldn't this also be 1.19?
</blockquote></details>

Done.

**Review by arunmk — APPROVED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/440#-:-NV28v5u1j4hHGdHTv-6:bg7igkv)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @abaruni)

**Review by abaruni — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/440)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ymo24)

**Pull request merged**
