### PR TITLE
Change verbosity and add comments to controller manager config

### PR DESCRIPTION
**Pull request by Anirudh9794**
- Add comments for controller manager config map
- increase verbosity level for some logs in vcdcluster_controller.go
- change default versions for cpi and csi

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/36)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/36)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by sahithi — APPROVED** [review]
:lgtm: after comments

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/36#-:-MtnTm2wE8pdCDeCLHm-:b-lquxi1)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[config/manager/controller_manager_config.yaml, line 15 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/36#-MtnSCq33EgruC2og4Zy:-MtnSCq33EgruC2og4Zz:bezc89u) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/bb5770d7248787814f5064eac0950804849520a0/config/manager/controller_manager_config.yaml#L15)):*
> ```YAML
>     https: 443
>     tcp: 6443
> managementClusterRDEId: MANGEMENT_CLUSTER_RDE_ID # RDE ID associated with the management cluster deployed from bootstrap cluster
> ```

RDE ID of this management cluster if it exists (if this cluster is a child of another CAPVCD based cluster, an associated RDE would be created in VCD of Entity Type "urn:vcloud:type:vmware:capvcdCluster:1.0.0")
___
*[config/manager/controller_manager_config.yaml, line 19 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/36#-MtnS3wM7yCZKYIMQdH_:-MtnS3wM7yCZKYIMQdHa:b-u680x4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/bb5770d7248787814f5064eac0950804849520a0/config/manager/controller_manager_config.yaml#L19)):*
> ```YAML
>   csi: 1.1.0 # CSI version to be used in the workload cluster
>   cpi: 1.1.0 # CPI version to be used in the workload cluster
>   cni: ANTREA_VERSION # Antrea version to be used in the workload cluster
> ```

Give a sample antrea version format 0.11.3

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/36)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[config/manager/controller_manager_config.yaml, line 15 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/36#-MtnSCq33EgruC2og4Zy:-MtnTw-v2FYeX3_qMQJL:b-i0zaqq) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/bb5770d7248787814f5064eac0950804849520a0/config/manager/controller_manager_config.yaml#L15)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

RDE ID of this management cluster if it exists (if this cluster is a child of another CAPVCD based cluster, an associated RDE would be created in VCD of Entity Type "urn:vcloud:type:vmware:capvcdCluster:1.0.0")
</blockquote></details>

RDE ID of this management cluster if it exists; if this cluster is a child of another CAPVCD based cluster, an associated RDE will be created in VCD of Entity Type "urn:vcloud:type:vmware:capvcdCluster:1.0.0". Retrieve that RDEId using the API - ""

Provide the correct API format -- //entities/types/vmware/capvcdCluster/1.0.0?name==<clustername>

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/36)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ltimothy7 and @sahithi)

___
*[config/manager/controller_manager_config.yaml, line 15 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/36#-MtnSCq33EgruC2og4Zy:-MtsWZZr-CzjAzOjxBP6:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/bb5770d7248787814f5064eac0950804849520a0/config/manager/controller_manager_config.yaml#L15)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

RDE ID of this management cluster if it exists; if this cluster is a child of another CAPVCD based cluster, an associated RDE will be created in VCD of Entity Type "urn:vcloud:type:vmware:capvcdCluster:1.0.0". Retrieve that RDEId using the API - ""

Provide the correct API format -- //entities/types/vmware/capvcdCluster/1.0.0?name==<clustername>
</blockquote></details>

Done.
___
*[config/manager/controller_manager_config.yaml, line 19 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/36#-MtnS3wM7yCZKYIMQdH_:-MtsWZ1d7uGvVPyVS-Rx:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/bb5770d7248787814f5064eac0950804849520a0/config/manager/controller_manager_config.yaml#L19)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Give a sample antrea version format 0.11.3
</blockquote></details>

Done.

**Pull request merged**
