### PR TITLE
[CAFV-359, CAFV-371, CAFV-367] Refactor code for multiAZ work

### PR DESCRIPTION
**Pull request by Anirudh9794**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- 

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies - Not required (no API changes)
- [ ] updated any relevant documentation or examples - Not required (no API changes)

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [x] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [x] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [x] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [x] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [x] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573)* status: 0 of 16 files reviewed, 14 unresolved discussions (waiting on @Anirudh9794)

___
*[`controllers/vcdcluster_controller.go` line 286 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKKv8r9sty4jvAHKXn:-NnKKv8r9sty4jvAHKXo:bh269o) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/bb83a8308adf12d9e9cdb125e48ac810239dfe38/controllers/vcdcluster_controller.go#L286)):*
> ```Go
> 		return nil, fmt.Errorf("error creating VCD client from secrets to reconcile Cluster [%s] infrastructure: [%v]", vcdCluster.Name, err)
> 	}
> 	err = updateClientWithVDC(vcdCluster, workloadVCDClient)
> ```

There was a reason why we had to initialize VDC within the client. Is that now being done within the NewVCDClientFromSecrets()?
___
*[`controllers/vcdcluster_controller.go` line 456 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKLlxi6rP4uPsCmiuC:-NnKLlxi6rP4uPsCmiuD:beb9im8) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdcluster_controller.go#L456)):*
> ```Go
> 	if strings.HasPrefix(vcdCluster.Status.InfraId, NoRdePrefix) {
> 		// skip rde reconciliation
> 		log.Info("Skipping RDE reconciliation as the infra ID indicates that the RDE ID is generated",
> ```

"Skipping RDE reconciliation as this cluster has no RDE...."
(or)
"Skipping RDE reconciliation as this cluster is running in "skipRDE" mode.."
___
*[`controllers/vcdcluster_controller.go` line 722 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKNBDC4cnjl48eGCHM:-NnKNBDC4cnjl48eGCHN:bya3h8w) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdcluster_controller.go#L722)):*
> ```Go
> }
> 
> func (r *VCDClusterReconciler) reconcileInfraID(ctx context.Context, cluster *clusterv1.Cluster,
> ```

Did you rename _reconcileNormal_ into _reconcileInfraId_? (or) is this review diff got messed up a bit?
___
*[`controllers/vcdcluster_controller.go` line 952 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKOWvE8vMhXvXBAEnW:-NnKOWvE8vMhXvXBAEnX:b-svz94c) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdcluster_controller.go#L952)):*
> ```Go
> 
> func (r *VCDClusterReconciler) reconcileLoadBalancer(ctx context.Context, vcdCluster *infrav1beta3.VCDCluster,
> 	vcdClient *vcdsdk.Client, skipRDEEventUpdates bool) (ctrl.Result, error) {
> ```

Returning _error_ is sufficient as this now became a helper method to _reconcileNormal()_. I don't think returning ctrl.Result is needed. Let the _reconcileNormal()_ function decide whether to exit the reconcile loop. 
___
*[`controllers/vcdcluster_controller.go` line 1118 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKPZBH4excLbwrpdl3:-NnKPZBI4gHYsOrlZefc:bkwmgqu) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdcluster_controller.go#L1118)):*
> ```Go
> func (r *VCDClusterReconciler) reconcileVApp(ctx context.Context, cluster *clusterv1.Cluster,
> 	vcdCluster *infrav1beta3.VCDCluster, vcdClient *vcdsdk.Client, orgName string, ovdcName string,
> 	skipRDEEventUpdates bool) (ctrl.Result, error) {
> ```

same here. Just return the error if it cannot reconcile within this function.
___
*[`controllers/vcdcluster_controller.go` line 1281 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKQtYUB8-K8r3EqFym:-NnKQtYUB8-K8r3EqFyn:b-44vo7q) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdcluster_controller.go#L1281)):*
> ```Go
> 		log.Error(err, "Error occurred during RDE reconciliation", "InfraId", vcdCluster.Status.InfraId)
> 	}
> ```

Is reconcilevApp() missing here? or did we move it to VCDMachineController?
___
*[`controllers/vcdcluster_controller.go` line 1528 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKSh8oBevwQ6h12NvM:-NnKSh8oBevwQ6h12NvN:bgxhuig) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdcluster_controller.go#L1528)):*
> ```Go
> 
> 	capvcdRDEManager := capisdk.NewCapvcdRdeManager(vcdClient, vcdCluster.Status.InfraId)
> ```

Can you add a TODO if this func needs to be enhanced further to determine all the vapps associated with the cluster?
___
*[`controllers/vcdmachine_controller.go` line 342 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKTC6d8AcJJosNksRE:-NnKTC6d8AcJJosNksRF:beuz2q9) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdmachine_controller.go#L342)):*
> ```Go
> }
> 
> func (r *VCDMachineReconciler) reconcileVAppCreation(ctx context.Context, vcdClient *vcdsdk.Client,
> ```

There is a similar func in the VCDClusterController. What is the difference?
___
*[`controllers/vcdmachine_controller.go` line 464 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKTWaD2qW0kgrIUFkC:-NnKTWaD2qW0kgrIUFkD:b-4ayc7v) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdmachine_controller.go#L464)):*
> ```Go
> }
> 
> func (r *VCDMachineReconciler) reconcileCreateVM(ctx context.Context, vcdClient *vcdsdk.Client, vdcManager *vcdsdk.VdcManager,
> ```

nit: The naming pattern I have observed so far - reconcile<resourceName>. Verb may not be needed.
I think we can keep it _reconcileVM()_
___
*[`controllers/vcdmachine_controller.go` line 465 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKULO9CJY_x0sy_gQc:-NnKULO9CJY_x0sy_gQd:b-gomb23) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdmachine_controller.go#L465)):*
> ```Go
> 
> func (r *VCDMachineReconciler) reconcileCreateVM(ctx context.Context, vcdClient *vcdsdk.Client, vdcManager *vcdsdk.VdcManager,
> 	vApp *govcd.VApp, machine *clusterv1.Machine, vcdMachine *infrav1beta3.VCDMachine, vmName string, ovdcNetworkName string, vcdCluster *infrav1beta3.VCDCluster) (res ctrl.Result, vm *govcd.VM, machineAddress string, retErr error) {
> ```

Same here. Returning ctrl.Result is not needed. 
___
*[`controllers/vcdmachine_controller.go` line 832 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKVDb437Q7_eKLF12r:-NnKVDb510NTR0y8G-zy:b-z92bgw) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdmachine_controller.go#L832)):*
> ```Go
> 	}
> 
> 	vmName, err := getVMName(machine, vcdMachine, log)
> ```

can this logic _getVapp_ and _getVMName_ can move inside reconcileVM func()?
If needed for anything else, you can keep it. If not, we can move this logic to reconcileVM(). It improves readability.
___
*[`controllers/vcdmachine_controller.go` line 885 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKVwiD93a_oGcKLvbo:-NnKVwiGBr73NAcO6nB5:b-mz84by) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdmachine_controller.go#L885)):*
> ```Go
> 	// Construct a CloudInitScriptInput struct to pass into template.Execute() function to generate the necessary
> 	// cloud init script for the relevant node type, i.e. control plane or worker node
> 	cloudInitInput := CloudInitScriptInput{
> ```

See if you can extract the cloudinit logic into reconcileCloudInitScript().
___
*[`controllers/vcdmachine_controller.go` line 935 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKWYg046J47YksJ6ak:-NnKWYg046J47YksJ6al:blpt3ed) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdmachine_controller.go#L935)):*
> ```Go
> 	// Update loadbalancer pool with the IP of the control plane node as a new member.
> 	// Note that this must be done before booting on the VM!
> 	if isInitialControlPlane {
> ```

All control plane VMs need to go through reconcileLbPool(), isn't it?
Btw, is this if block added recently?
___
*[`controllers/vcdmachine_controller.go` line 1105 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKWrLW15dsGUGsr_-J:-NnKWrLW15dsGUGsr_-K:b-z5j802) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdmachine_controller.go#L1105)):*
> ```Go
> 	// Update load-balancer pool with the IP of the control plane node as a new member.
> 	// For joining nodes the LB Pool should be updated after the VM has joined.
> 	if isResizedControlPlane {
> ```

why two if blocks for initial and resized controlplane? Let me know if I am missing something here.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573)* status: 0 of 21 files reviewed, 13 unresolved discussions (waiting on @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 286 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKKv8r9sty4jvAHKXn:-NnKxJ5d6bTiY3_Abr8r:b-agqeuf) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/bb83a8308adf12d9e9cdb125e48ac810239dfe38/controllers/vcdcluster_controller.go#L286)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

There was a reason why we had to initialize VDC within the client. Is that now being done within the NewVCDClientFromSecrets()?
</blockquote></details>

Reverted this change back. This was a miss.
___
*[`controllers/vcdcluster_controller.go` line 456 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKLlxi6rP4uPsCmiuC:-NnL1U2m1ap5wU3_vZhu:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdcluster_controller.go#L456)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

"Skipping RDE reconciliation as this cluster has no RDE...."
(or)
"Skipping RDE reconciliation as this cluster is running in "skipRDE" mode.."
</blockquote></details>

Done.
___
*[`controllers/vcdcluster_controller.go` line 722 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKNBDC4cnjl48eGCHM:-NnL1XisEwOhuS4aWkdD:bn2mm6k) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdcluster_controller.go#L722)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Did you rename _reconcileNormal_ into _reconcileInfraId_? (or) is this review diff got messed up a bit?
</blockquote></details>

A new function reconcileInfraId() was added. The reconcileNormal() function still exists. The diff is messed up.
___
*[`controllers/vcdcluster_controller.go` line 952 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKOWvE8vMhXvXBAEnW:-NnLPFzWEHZMDIOKNvlj:bs1ui4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdcluster_controller.go#L952)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Returning _error_ is sufficient as this now became a helper method to _reconcileNormal()_. I don't think returning ctrl.Result is needed. Let the _reconcileNormal()_ function decide whether to exit the reconcile loop.
</blockquote></details>

This function will re-queue the request after 5 seconds if the load balancer is in pending state. So the ctrl.Result{} is necessary here.

However there was a bug where the vcdcluster will continue reconciliation even when `reconcileLoadBalancer()` returns a result with `RequeueAfter > 0`. I added the code to handle this case.
___
*[`controllers/vcdcluster_controller.go` line 1118 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKPZBH4excLbwrpdl3:-NnLOxEy5mZzU0jxK4HM:b3d53xw) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdcluster_controller.go#L1118)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

same here. Just return the error if it cannot reconcile within this function.
</blockquote></details>

Deleted this function as it is not called anywhere
___
*[`controllers/vcdcluster_controller.go` line 1281 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKQtYUB8-K8r3EqFym:-NnL2-Ti56LeVrTIuxCz:b-bafvq7) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdcluster_controller.go#L1281)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Is reconcilevApp() missing here? or did we move it to VCDMachineController?
</blockquote></details>

VApp creation logic is moved to VCDMachineController
___
*[`controllers/vcdcluster_controller.go` line 1528 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKSh8oBevwQ6h12NvM:-NnL3eWp3Dz9hP_1G-cw:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdcluster_controller.go#L1528)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you add a TODO if this func needs to be enhanced further to determine all the vapps associated with the cluster?
</blockquote></details>

Done.
___
*[`controllers/vcdmachine_controller.go` line 342 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKTC6d8AcJJosNksRE:-NnL3D80435xHkjtMdvX:b-6xs0ng) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdmachine_controller.go#L342)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

There is a similar func in the VCDClusterController. What is the difference?
</blockquote></details>

The reconcileVApp in vcdcluster_controller.go is not called anywhere. I will remove the function in vcdcluster_controller.go
___
*[`controllers/vcdmachine_controller.go` line 464 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKTWaD2qW0kgrIUFkC:-NnLOkmt6pYSw_1ND_vz:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdmachine_controller.go#L464)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

nit: The naming pattern I have observed so far - reconcile<resourceName>. Verb may not be needed.
I think we can keep it _reconcileVM()_
</blockquote></details>

Done.
___
*[`controllers/vcdmachine_controller.go` line 465 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKULO9CJY_x0sy_gQc:-NnLSST-5Hr7G6ykJgZ7:bhhqrjs) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdmachine_controller.go#L465)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Same here. Returning ctrl.Result is not needed.
</blockquote></details>

ctrl.Result{} is used to indicate if a requeue is needed here as well. But the checks for the result value was missing in the caller. Have added the logic to requeue.
___
*[`controllers/vcdmachine_controller.go` line 832 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKVDb437Q7_eKLF12r:-NnLT0GM9Z3vztH5GiiD:b-bpv2s2) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdmachine_controller.go#L832)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

can this logic _getVapp_ and _getVMName_ can move inside reconcileVM func()?
If needed for anything else, you can keep it. If not, we can move this logic to reconcileVM(). It improves readability.
</blockquote></details>

The vapp name is used in some log statements 
___
*[`controllers/vcdmachine_controller.go` line 885 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKVwiD93a_oGcKLvbo:-NnMBElbByK9wSTRTpdV:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdmachine_controller.go#L885)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

See if you can extract the cloudinit logic into reconcileCloudInitScript().
</blockquote></details>

Done.
___
*[`controllers/vcdmachine_controller.go` line 935 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKWYg046J47YksJ6ak:-NnMB9IqD0isUXyrJsfk:bpryqtm) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdmachine_controller.go#L935)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

All control plane VMs need to go through reconcileLbPool(), isn't it?
Btw, is this if block added recently?
</blockquote></details>

No, this if was already there
___
*[`controllers/vcdmachine_controller.go` line 1105 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKWrLW15dsGUGsr_-J:-NnLl849EF0we83qrrjG:bug1sx3) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdmachine_controller.go#L1105)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

why two if blocks for initial and resized controlplane? Let me know if I am missing something here.
</blockquote></details>

Resized control plane should be added to the pool after the node joins as a control plane or else the LB may route the requests to a non functional control plane node. (a resized control plane joins initially as a worker node)

**Review by sahithi — APPROVED** [review]
:lgtm: 
Aniruddha, please create a cluster and ensure the log messages and the flow of the log messages to meaningful enough to track the progress and troubleshoot. Ensure machine names and vApp names are now part of all the logs of VCDMachineController.

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-:-NnfUE7I99uFI9mrJ5U3:btmh99)* status: 0 of 21 files reviewed, 18 unresolved discussions (waiting on @Anirudh9794)

___
*[`controllers/vcdcluster_controller.go` line 952 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKOWvE8vMhXvXBAEnW:-NneVzg2ERxDMDaphE5c:b58m2pc) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdcluster_controller.go#L952)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

This function will re-queue the request after 5 seconds if the load balancer is in pending state. So the ctrl.Result{} is necessary here.

However there was a bug where the vcdcluster will continue reconciliation even when `reconcileLoadBalancer()` returns a result with `RequeueAfter > 0`. I added the code to handle this case.
</blockquote></details>

okay thanks
___
*[`controllers/vcdmachine_controller.go` line 1105 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKWrLW15dsGUGsr_-J:-NneWhY6Dcq6OpXyu7_E:b58m2pc) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdmachine_controller.go#L1105)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Resized control plane should be added to the pool after the node joins as a control plane or else the LB may route the requests to a non functional control plane node. (a resized control plane joins initially as a worker node)
</blockquote></details>

okay thanks
___
*[`controllers/vcdmachine_controller.go` line 400 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnfUlAZ19swrCKl3hd_:-NnfUlAZ19swrCKl3hda:b-sfqv8z) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/74456d1b481483295f39bf3ce40075e405571a6d/controllers/vcdmachine_controller.go#L400)):*
> ```Go
> 	isInitialControlPlane, isResizedControlPlane, skipRDEEventUpdates bool) error {
> 
> 	log := ctrl.LoggerFrom(ctx, "cluster", vcdCluster.Name, "machine", machine.Name)
> ```

Please include vApp name as part of log messages. This will be useful given cluster can span multiple vApps.
___
*[`controllers/vcdmachine_controller.go` line 554 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnfV25G4uI7TYT1EUJG:-NnfV25G4uI7TYT1EUJH:byyj2et) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/74456d1b481483295f39bf3ce40075e405571a6d/controllers/vcdmachine_controller.go#L554)):*
> ```Go
> 	vAppName string, ovdcNetworkName string, skipRDEEventUpdates bool) (ctrl.Result, error) {
> 
> 	log := ctrl.LoggerFrom(ctx, "machine", machineName, "cluster", vcdCluster.Name)
> ```

We can include vAppname as part of our log context. It will be useful for multiaz.
___
*[`controllers/vcdmachine_controller.go` line 652 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnfVGL2Bq4Cd8ySNkkh:-NnfVGL2Bq4Cd8ySNkki:b7sxpog) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/74456d1b481483295f39bf3ce40075e405571a6d/controllers/vcdmachine_controller.go#L652)):*
> ```Go
> 	vcdCluster *infrav1beta3.VCDCluster) (res ctrl.Result, vm *govcd.VM, machineAddress string, retErr error) {
> 
> 	log := ctrl.LoggerFrom(ctx, "machine", machine.Name, "cluster", vcdCluster.Name)
> ```

same here, we can have log context include the vapp name. If vapp name is not available here, at least add a TODO to cover it in the upcoming multiAZ PRs
___
*[`controllers/vcdmachine_controller.go` line 796 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnfVg1P28T1BhpeTpXM:-NnfVg1Q9YOdL4FJRtS1:b-bx4g0v) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/74456d1b481483295f39bf3ce40075e405571a6d/controllers/vcdmachine_controller.go#L796)):*
> ```Go
> 	vcdCluster *infrav1beta3.VCDCluster, vcdClient *vcdsdk.Client, gateway *vcdsdk.GatewayManager) error {
> 
> 	log := ctrl.LoggerFrom(ctx, "cluster", vcdCluster.Name, "machine", machine.Name)
> ```

Same here; logcontext and vapp name. Please check at other places too.
___
*[`controllers/vcdmachine_controller.go` line 932 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnfVp5-4KSvH65RwmHx:-NnfVp5-4KSvH65RwmHy:b-441gv2) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/74456d1b481483295f39bf3ce40075e405571a6d/controllers/vcdmachine_controller.go#L932)):*
> ```Go
> 	// since new zones could be added dynamically. In the non-AZ case, it can be done in the vcdCluster controller. However,
> 	// we do it in one place for simplicity.
> 	vAppName := CreateFullVAppName(vcdCluster)
> ```

Wondering if we can store the vAppname as part of Machine.Status. Not needed in this PR, but it can be usefulin general (logging and troubleshooting). Also see the location we are patching the VCDMachine object.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573)* status: 0 of 21 files reviewed, 18 unresolved discussions (waiting on @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 952 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnKOWvE8vMhXvXBAEnW:-NnksnVD7tzlTzjTgsXp:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8275dda923d3ed6e2930e74c6bb1ec72cd1781e5/controllers/vcdcluster_controller.go#L952)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

okay thanks
</blockquote></details>

Done.
___
*[`controllers/vcdmachine_controller.go` line 400 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnfUlAZ19swrCKl3hd_:-NnktHNTAPLKo3l1ZY0P:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/74456d1b481483295f39bf3ce40075e405571a6d/controllers/vcdmachine_controller.go#L400)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please include vApp name as part of log messages. This will be useful given cluster can span multiple vApps.
</blockquote></details>

Done.
___
*[`controllers/vcdmachine_controller.go` line 554 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnfV25G4uI7TYT1EUJG:-NnktOM577O6XvM1aXii:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/74456d1b481483295f39bf3ce40075e405571a6d/controllers/vcdmachine_controller.go#L554)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We can include vAppname as part of our log context. It will be useful for multiaz.
</blockquote></details>

Done.
___
*[`controllers/vcdmachine_controller.go` line 652 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnfVGL2Bq4Cd8ySNkkh:-NnktnrW0pZ1ICSvPFbF:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/74456d1b481483295f39bf3ce40075e405571a6d/controllers/vcdmachine_controller.go#L652)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

same here, we can have log context include the vapp name. If vapp name is not available here, at least add a TODO to cover it in the upcoming multiAZ PRs
</blockquote></details>

Done.
___
*[`controllers/vcdmachine_controller.go` line 796 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnfVg1P28T1BhpeTpXM:-NnktzV84Db80LXiKLFA:bv15cg9) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/74456d1b481483295f39bf3ce40075e405571a6d/controllers/vcdmachine_controller.go#L796)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Same here; logcontext and vapp name. Please check at other places too.
</blockquote></details>

The VApp name is not available in this function.
___
*[`controllers/vcdmachine_controller.go` line 932 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-NnfVp5-4KSvH65RwmHx:-Nnkvsfg8cvnpAeCzfs2:by66t75) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/74456d1b481483295f39bf3ce40075e405571a6d/controllers/vcdmachine_controller.go#L932)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Wondering if we can store the vAppname as part of Machine.Status. Not needed in this PR, but it can be usefulin general (logging and troubleshooting). Also see the location we are patching the VCDMachine object.
</blockquote></details>

Added a TODO to store the Vapp name within machine.status

**Review by Anirudh9794 — COMMENTED** [review]
I went through the tests again and they are not breaking.

With this change, there will be increase in the error logs which don't really cause an issue in cluster operations

1. vcdcluster_controller attempts to delete the cluster repeatedly but this will fail because vcdmachine_controller has not deleted the machine in the VApp
2. When 2 or more machines attempt creation of VApp, only one will succeed as a result there will be logs showing error on the other vcdmachine_controller threads.

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/573#-:-NnpDepA5YP6iWijDPRJ:bmqhfrl)* status: 0 of 21 files reviewed, 18 unresolved discussions (waiting on @sahithi)

**Pull request merged**
