### PR TITLE
VCDA-3133: pass credentials through spec

### PR DESCRIPTION
**Pull request by arunmk**
Pass username/password/refreshtoken through the Spec. This combined with kuberneted rbac can be used to provide multitenant clusters

Also make vcdmachine controller more reentrant.

Also make some fields mandatory.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: minor comments

> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8#-:-Mq04V14ChGhHnMIp7U7:b-kfw89e)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[main.go, line 55 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8#-Mq04Z433kAwy2uaW1cN:-Mq04Z433kAwy2uaW1cO:bhvjbqe) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4fa9163b2531d5353c4c6de2bfefc3997a4390cc/main.go#L55)):*
> ```Go
> }
> 
> func getVcdClientFromConfig(inputMap map[string]interface{}) (string, *vcdclient.OneArm, error) {
> ```

I think this function must be renamed as it doesn't help get the vcdClient.client reference anymore
___
*[controllers/vcdmachine_controller.go, line 543 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8#-Mq03Wg12HkZmaMjLDsb:-Mq03Wg12HkZmaMjLDsc:b-m6aa17) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4fa9163b2531d5353c4c6de2bfefc3997a4390cc/controllers/vcdmachine_controller.go#L543)):*
> ```Go
> 	// Note that this must be done before booting on the VM!
> 	if util.IsControlPlaneMachine(machine) {
> 		lbPoolName := vcdCluster.Name + "-" + vcdCluster.Status.ClusterRDEId + "-tcp"
> ```

lbPoolName that is created in vcdcluster_controller contains cluster.Name

Can vcdCluster.Name and cluster.Name be different?
___
*[controllers/vcdmachine_controller.go, line 700 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8#-Mq04BAzB-A2ZVdhC7uF:-Mq04BB-EdEn0NqXnkCb:b-okpegd) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4fa9163b2531d5353c4c6de2bfefc3997a4390cc/controllers/vcdmachine_controller.go#L700)):*
> ```Go
> 	if util.IsControlPlaneMachine(machine) {
> 		// remove the address from the lbpool
> 		lbPoolName := cluster.Name + "-" + workloadVCDClient.ClusterID + "-tcp"
> ```

Same comment as above. I think there will be an error here if cluster.Name is different from vcdCluster.Name

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 1 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8)* status: all files reviewed, 3 unresolved discussions (waiting on @arunmk and @sahithi)

**Review by ltimothy7 — APPROVED** [review]
:lgtm: with Aniruddha's comments addressed

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8#-:-Mq0FH7z3VxCxlk7E3rA:bcmzzji)* status: all files reviewed, 3 unresolved discussions (waiting on @arunmk and @sahithi)

**Comment by arunmk** [comment]
___
*[controllers/vcdmachine_controller.go, line 543 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8#-Mq03Wg12HkZmaMjLDsb:-Mq0KMvq2jKuabPlXhZ6:b-2y71a4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4fa9163b2531d5353c4c6de2bfefc3997a4390cc/controllers/vcdmachine_controller.go#L543)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

lbPoolName that is created in vcdcluster_controller contains cluster.Name

Can vcdCluster.Name and cluster.Name be different?
</blockquote></details>

These cannot be different and mandatorily will be identical.

**Comment by arunmk** [comment]
___
*[controllers/vcdmachine_controller.go, line 700 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8#-Mq04BAzB-A2ZVdhC7uF:-Mq0K_kO0ocLCxMiqwsw:b-t7w53s) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4fa9163b2531d5353c4c6de2bfefc3997a4390cc/controllers/vcdmachine_controller.go#L700)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Same comment as above. I think there will be an error here if cluster.Name is different from vcdCluster.Name
</blockquote></details>

OK, let me reuse the same variable in this case as well.

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8)* status: all files reviewed, 7 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[api/v1alpha4/vcdcluster_types.go, line 40 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8#-Mq0JNhPAv9RKPoDWKVv:-Mq0JNhPAv9RKPoDWKVw:bfacd86) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/231a38d5c723a03d9f2da19b5e1f8d7ce027fcf8/api/v1alpha4/vcdcluster_types.go#L40)):*
> ```Go
> 	// +optional
> 	Org string `json:"org,omitempty"`
> 	// +optional
> ```

The reason I marked them as optional was to take the defaults from configmap of the management cluster itself. Do you think we need to make these mandatory fields?
___
*[api/v1alpha4/vcdcluster_types.go, line 50 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8#-Mq0KHXNBPAd_bFbogv0:-Mq0KHXNBPAd_bFbogv1:b-a4hwjm) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4fa9163b2531d5353c4c6de2bfefc3997a4390cc/api/v1alpha4/vcdcluster_types.go#L50)):*
> ```Go
> 	// +kubebuilder:validation:Required
> 	Ovdc string `json:"ovdc,omitempty"`
> 	// +kubebuilder:validation:Required
> ```

for my benefit, what kind of validation does kubebuilder do, and at what point?
___
*[api/v1alpha4/vcdcluster_types.go, line 53 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8#-Mq0JjTi4zemdJWqILVa:-Mq0JjTi4zemdJWqILVb:bxzf1gp) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4fa9163b2531d5353c4c6de2bfefc3997a4390cc/api/v1alpha4/vcdcluster_types.go#L53)):*
> ```Go
> 	OvdcNetwork string `json:"ovdcNetwork,omitempty"`
> 	// +kubebuilder:validation:Required
> 	UserCredentialsContext UserCredentialsContext `json:"context"`
> ```

how about  'json: "userContext"' to be more clear?
___
*[config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml, line 74 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8#-Mq0KykoDzmvLNjempps:-Mq0KykoDzmvLNjemppt:b-qf6si0) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4fa9163b2531d5353c4c6de2bfefc3997a4390cc/config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml#L74)):*
> ```YAML
>             required:
>             - context
>             - site
> ```

You marked org, ovdc also as required in the structs, is it not intentional?

**Comment by arunmk** [comment]
___
*[main.go, line 55 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8#-Mq04Z433kAwy2uaW1cN:-Mq0sAQI3BJrZhuLHLmJ:b1wpzl0) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4fa9163b2531d5353c4c6de2bfefc3997a4390cc/main.go#L55)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think this function must be renamed as it doesn't help get the vcdClient.client reference anymore
</blockquote></details>

I modified it to behave as it was earlier after some discussion with Sahithi

**Comment by arunmk** [comment]
___
*[api/v1alpha4/vcdcluster_types.go, line 40 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8#-Mq0JNhPAv9RKPoDWKVv:-Mq0sMYr7GFqE6tWI0ao:b-wqkrb4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/231a38d5c723a03d9f2da19b5e1f8d7ce027fcf8/api/v1alpha4/vcdcluster_types.go#L40)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

The reason I marked them as optional was to take the defaults from configmap of the management cluster itself. Do you think we need to make these mandatory fields?
</blockquote></details>

After discussion, since the errors are clear and before k8s accepts the CRD, it seemed ok to have these as mandatory

**Comment by arunmk** [comment]
___
*[api/v1alpha4/vcdcluster_types.go, line 50 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8#-Mq0KHXNBPAd_bFbogv0:-Mq1-eZOASFafbEHHyGM:b-d2m7tv) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4fa9163b2531d5353c4c6de2bfefc3997a4390cc/api/v1alpha4/vcdcluster_types.go#L50)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

for my benefit, what kind of validation does kubebuilder do, and at what point?
</blockquote></details>

discussed offline

**Comment by arunmk** [comment]
___
*[config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml, line 74 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8#-Mq0KykoDzmvLNjempps:-Mq11WJo5oJtGOVKrdgy:b-d2m7tv) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4fa9163b2531d5353c4c6de2bfefc3997a4390cc/config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml#L74)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

You marked org, ovdc also as required in the structs, is it not intentional?
</blockquote></details>

discussed offline

**Comment by arunmk** [comment]
___
*[api/v1alpha4/vcdcluster_types.go, line 53 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/8#-Mq0JjTi4zemdJWqILVa:-Mq11a_p4YEkbuzS1kKr:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4fa9163b2531d5353c4c6de2bfefc3997a4390cc/api/v1alpha4/vcdcluster_types.go#L53)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

how about  'json: "userContext"' to be more clear?
</blockquote></details>

Done.

**Pull request merged**
