### PR TITLE
Update infrastructure-components.yaml

### PR DESCRIPTION
**Pull request by Anirudh9794**
* Run `make release-manifests` to update infrastructure-components.yaml after fixes to CAPVCD manifests

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/78)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sahithi)

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/78)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[infrastructure-vcd/v0.5.1/infrastructure-components.yaml, line 771 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/78#-MzS7i1n048E4mjHFPBD:-MzS7i1n048E4mjHFPBE:b-4dn25x) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/d014bfd8efe58a68fd27f67599c8fb5814da0603/infrastructure-vcd/v0.5.1/infrastructure-components.yaml#L771)):*
> ```YAML
> ---
> apiVersion: admissionregistration.k8s.io/v1beta1
> kind: ValidatingWebhookConfiguration
> ```

Aniruddh, are you updating v0.5.1 with the changes in the main branch repo?
I have added this webhook to the main branch recently. We should be creating a separate infrastructure_components yaml for each release.

**Comment by Anirudh9794** [comment]
*[infrastructure-vcd/v0.5.1/infrastructure-components.yaml, line 771 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/78#-MzS7i1n048E4mjHFPBD:-Mzv8PP94Cbfzxm87wP0:b7p128) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/d014bfd8efe58a68fd27f67599c8fb5814da0603/infrastructure-vcd/v0.5.1/infrastructure-components.yaml#L771)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Aniruddh, are you updating v0.5.1 with the changes in the main branch repo?
I have added this webhook to the main branch recently. We should be creating a separate infrastructure_components yaml for each release.
</blockquote></details>

renamed the release directory to v0.8.0 as discussed

**Review by sahithi — APPROVED** [review]
:lgtm: after addressing the comment

> Reviewed 6 of 6 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/78#-:-MzvDzojCkOcGSRWaD60:b-4g7kf)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[infrastructure-vcd/v0.8.0/clusterctl.yaml, line 16 at r4](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/78#-MzvDkNACN-YBeyx0-2Y:-MzvDkNACN-YBeyx0-2Z:b-k4qxit) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/320431dd49a2ce6a0a2acc854b4d5bca0bab87f3/infrastructure-vcd/v0.8.0/clusterctl.yaml#L16)):*
> ```YAML
> providers:
>   - name: "vcd"
>     url: "~/go/cluster-api-provider-cloud-director/infrastructure-vcd/v0.5.1/infrastructure-components.yaml"
> ```

v0.8.0

**Review by sahithi — COMMENTED** [review]
infrastructure-components.yaml is missing from v0.5.1 folder, please restore that. It should not have CAPVCD upgrade changes.

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/78#-:-MzvEyuL4ynKx5reXfX6:b-djltne)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/78)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @sahithi)

___
*[infrastructure-vcd/v0.8.0/clusterctl.yaml, line 16 at r4](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/78#-MzvDkNACN-YBeyx0-2Y:-MzvJm2cC6Io2_e_TbQZ:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/320431dd49a2ce6a0a2acc854b4d5bca0bab87f3/infrastructure-vcd/v0.8.0/clusterctl.yaml#L16)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

v0.8.0
</blockquote></details>

Done.

**Review by Anirudh9794 — COMMENTED** [review]
As discussed, removed v0.5.1 directory

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/78#-:-MzvJqjB7kL4s4XSfepZ:bbtr0u3)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @sahithi)

**Pull request merged**
