### PR TITLE
[CAFV-169] update outdated CAPVCD 1.1.0 schema AND CAPVCD 1.2.0 schema

### PR DESCRIPTION
**Pull request by ymo24**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- update outdated CAPVCD 1.1.0 schema AND CAPVCD 1.2.0 schema

## Checklist
- [ ] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/392)

### CODE REVIEW

**Review by ltimothy7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/392)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @sahithi and @ymo24)

___
*[`release/version` line 1 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/392#-NOpDc_l0cOnuwIiGG5B:-NOpDc_m70epV6Zx1t1d:b-u2frk3) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/bca37a14d8fde705e37f3436406a22f43a94e719/release/version#L1)):*
> ```
> main-branch-yanmo
> ```

this should just be main-branch
___
*[`templates/infrastructure-components.yaml` line 1166 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/392#-NOpDkpJ6t32pyzNQN4E:-NOpDkpJ6t32pyzNQN4F:b-idcdon) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/bca37a14d8fde705e37f3436406a22f43a94e719/templates/infrastructure-components.yaml#L1166)):*
> ```YAML
>       - command:
>         - /opt/vcloud/bin/cluster-api-provider-cloud-director
>         image: harbor-repo.vmware.com/vcloud/cluster-api-provider-cloud-director:main-branch-yanmo
> ```

Should this be reverted?

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/392)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @ltimothy7 and @sahithi)

___
*[`release/version` line 1 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/392#-NOpDc_l0cOnuwIiGG5B:-NOpOXc7Bwkw-XE1PM4B:b6y5rtn) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/bca37a14d8fde705e37f3436406a22f43a94e719/release/version#L1)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

this should just be main-branch
</blockquote></details>

Oh sorry, let me revert it.
___
*[`templates/infrastructure-components.yaml` line 1166 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/392#-NOpDkpJ6t32pyzNQN4E:-NOpPHVb7iRnVPaRceZv:b-b5alfp) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/bca37a14d8fde705e37f3436406a22f43a94e719/templates/infrastructure-components.yaml#L1166)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Should this be reverted?
</blockquote></details>

Thanks, Tim. I have removed all the testing file.

**Review by lzichong — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/392)* status: all files reviewed, 2 unresolved discussions (waiting on @ltimothy7)

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/392)* status: all files reviewed, 2 unresolved discussions (waiting on @ymo24)

**Pull request merged**
