### PR TITLE
[CAFV-162]sync with common-core for TKG 1.6.1 support

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy7 <ltimothy@vmware.com>

## Description
Please provide a brief description of the changes proposed in this Pull Request

- 

## Checklist
- [ ] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/381)

### CODE REVIEW

**Review by lzichong — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/381#-:-NNOGaUQBcALbQoLFcHY:bg7igkv)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ltimothy7)

**Review by lzichong — COMMENTED** [review]
Is there another ticket/another PR coming that will use this method in CAPVCD?

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/381#-:-NNOHISqBNiPj3pzgXdj:b6inf8h)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ltimothy7)

**Review by rliang88 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/381#-:-NNOMTSf2NoDSJn4BWzF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Comment by ltimothy7** [comment]
Yes, going forward, we are having syncing tasks and tasks to consume the common core funcitonality @lzichong

**Pull request merged**
