### PR TITLE
VCDA-3582, 3740: Store CRS in RDE, remove CNI

### PR DESCRIPTION
**Pull request by arunmk**
## Description
Please provide a brief description of the changes proposed in this Pull Request
Iterate through ClusterResourceSetBindings and update RDE. Also remove CNI hardcoded
- 

## Checklist
- [X] tested locally
- [X] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [X] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/195)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/195#-:-N5vsmxAEC_HJHFR52gf:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 317 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/195#-N5vsIjoCORjAsmKscaa:-N5vsIjoCORjAsmKscab:b-9jjpwz) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/134e9ebe6c7da3e63ab345251444051aad897416/controllers/vcdcluster_controller.go#L317)):*
> ```Go
> 	if crsBindingList != nil {
> 		for _, crsBinding := range crsBindingList.Items {
> 			fmt.Printf("ClusterResourceBinding is [%v]\n", crsBinding.Spec.Bindings)
> ```

is this a debug statement?

**Comment by arunmk** [comment]
*[`controllers/vcdcluster_controller.go` line 317 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/195#-N5vsIjoCORjAsmKscaa:-N5w1LxPBOBe7EhMFli8:b-s62bsp) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/134e9ebe6c7da3e63ab345251444051aad897416/controllers/vcdcluster_controller.go#L317)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

is this a debug statement?
</blockquote></details>

ah yes, I'll remove the block, thanks!

**Comment by arunmk** [comment]
*[`controllers/vcdcluster_controller.go` line 317 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/195#-N5vsIjoCORjAsmKscaa:-N5w1iIs-AAbYTbtHykH:bb7f2mf) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/134e9ebe6c7da3e63ab345251444051aad897416/controllers/vcdcluster_controller.go#L317)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

ah yes, I'll remove the block, thanks!
</blockquote></details>

done

**Review by sahithi — APPROVED** [review]
:lgtm: after comments

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/195#-:-N5w5Du3DE8KYuvRJgy9:b-lquxi1)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go` line 109 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/195#-N5w54pr7zbDXSVcl1w0:-N5w54pr7zbDXSVcl1w1:b-1lwktc) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b8c22bb24c69e48be6c715c24f35010f73dc057b/pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go#L109)):*
> ```Go
> }
> 
> type CAPVCDStatus struct {
> ```

Can you also update schema.json file of capvcd 1.1.0?
___
*[`pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go` line 125 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/195#-N5w4PD52ZuL9L2AjOIn:-N5w4PD52ZuL9L2AjOIo:bu1rqg6) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b8c22bb24c69e48be6c715c24f35010f73dc057b/pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go#L125)):*
> ```Go
> 	VCDResourceSet                 []VCDResource                   `json:"vcdResourceSet,omitempty"`
> 	CapiStatusYaml                 string                          `json:"capiStatusYaml,omitempty"`
> 	ClusterResourceSetBindingSpecs []ClusterResourceSetBindingSpec `json:"clusterResourceSetBindingSpecs,omitempty"`
> ```

Can we name it just "ClusterResourceSet"? 
"BindingSpec" sounds a bit technical to K8s. ClusterResourceSet is also in line with VcdResourceSet, errorSet and eventSet.

**Comment by arunmk** [comment]
*[`pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go` line 109 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/195#-N5w54pr7zbDXSVcl1w0:-N5w5ZLMA7ODTn7DkHM_:bb7f2mf) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b8c22bb24c69e48be6c715c24f35010f73dc057b/pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go#L109)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you also update schema.json file of capvcd 1.1.0?
</blockquote></details>

done

**Comment by arunmk** [comment]
*[`pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go` line 125 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/195#-N5w4PD52ZuL9L2AjOIn:-N5w5WPt5imxyzpmyvo3:b-os7fab) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b8c22bb24c69e48be6c715c24f35010f73dc057b/pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go#L125)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can we name it just "ClusterResourceSet"? 
"BindingSpec" sounds a bit technical to K8s. ClusterResourceSet is also in line with VcdResourceSet, errorSet and eventSet.

</blockquote></details>

changed after discussion

**Pull request merged**
