### PR TITLE
[CAFV-55] Update README Document about registering the RDE Entitytype payload from the schema.json

### PR DESCRIPTION
**Pull request by lzichong**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- Added new schema file which holds the all the fields required for registering CAPVCD Entity Type.
- Updated VCD_SETUP.md doc to reference to this file, along with added note indicating that the `entity_type.json` file contains `schema` and other fields with `schema` linked to the proper file

## Checklist
- [ ] tested locally
- [ ] updated any relevant dependencies
- [x] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/365)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/365)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sahithi)

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/365)* status: all files reviewed, 3 unresolved discussions (waiting on @lzichong)

___
*[`docs/VCD_SETUP.md` line 52 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/365#-NLN5oh30NAA_87kunls:-NLN5oh30NAA_87kunlt:b-b2bo90) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/573b8eb20dcf0652f76a04e7eb72370f57ce370b/docs/VCD_SETUP.md#L52)):*
> ```Markdown
> * Note: The reference file contains the full body/payload required for registering CAPVCD Entity Type which also includes [schema](https://github.com/vmware/cluster-api-provider-cloud-director/tree/main/schema/schema_1_1_0.json) and other fields.
> 
> POST `https://<vcd>/cloudapi/1.0.0/entityTypes` with the provided payload (identical with referenced file)
> ```

Files will always reflect the latest. POST payload in the documentation may sometimes remain stale until we are close to shipping a new version.
___
*[`schema/entity_type.json` line 2 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/365#-NLN6H-57_IAozkRYe-S:-NLN6H-57_IAozkRYe-T:be7n0oz) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/573b8eb20dcf0652f76a04e7eb72370f57ce370b/schema/entity_type.json#L2)):*
> ```JSON
> {
>   "name": "CAPVCD Cluster",
> ```

Rename the file entity_type_1_1_0.json
___
*[`schema/entity_type.json` line 8 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/365#-NLN5P3OAzoaJmyEy5vd:-NLN5P3PCUv_aVm4uyam:b-r96xk2) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/573b8eb20dcf0652f76a04e7eb72370f57ce370b/schema/entity_type.json#L8)):*
> ```JSON
>   "inheritedVersion": null,
>   "externalId": null,
>   "schema": {
> ```

Zichong, sorry If I was not clear before, schema field should just refer to the contents of schema_1_1_0.json.
Jsonschema.org will have a way to refer to the contents of other files. Please look it up

We should avoid updating two files for the same content.

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/365)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`docs/VCD_SETUP.md` line 52 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/365#-NLN5oh30NAA_87kunls:-NLSxaKl7w1tEJk44pYi:b-bdhb5x) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/573b8eb20dcf0652f76a04e7eb72370f57ce370b/docs/VCD_SETUP.md#L52)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Files will always reflect the latest. POST payload in the documentation may sometimes remain stale until we are close to shipping a new version.
</blockquote></details>

That makes sense, I have updated the docs to remove `identical with referenced file` as the docs may get stale and that statement would no longer be true, thank you Sahithi!
___
*[`schema/entity_type.json` line 2 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/365#-NLN6H-57_IAozkRYe-S:-NLSxIQd9x9DY_Jf0pdx:b31oao8) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/573b8eb20dcf0652f76a04e7eb72370f57ce370b/schema/entity_type.json#L2)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Rename the file entity_type_1_1_0.json
</blockquote></details>

Updated, thanks Sahithi!
___
*[`schema/entity_type.json` line 8 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/365#-NLN5P3OAzoaJmyEy5vd:-NLSxKZd45a6-H4PDKzf:b-vr4oxi) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/573b8eb20dcf0652f76a04e7eb72370f57ce370b/schema/entity_type.json#L8)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Zichong, sorry If I was not clear before, schema field should just refer to the contents of schema_1_1_0.json.
Jsonschema.org will have a way to refer to the contents of other files. Please look it up

We should avoid updating two files for the same content.
</blockquote></details>

No worries Sahithi, thank you for clarifying! I have updated the entity type schema key to use `$ref` and point to the schema file itself.

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/365#-:-NM1MDCL2QYPjjMRLx0y:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @lzichong)

**Pull request merged**
