### PR TITLE
[VCDA-3260] Add descriptive comments to the example capi-yaml input

### PR DESCRIPTION
**Pull request by Anirudh9794**
- Added descriptive comments for the example input for CAPVCD.

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[examples/capi-quickstart.yaml, line 24 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MtzSv4D0azyZlSiLbb_:-MtzSv4D0azyZlSiLbba:b-jy67sn) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/423e5ae046de9c4bb9fa6c78d446d1122d4e40c4/examples/capi-quickstart.yaml#L24)):*
> ```YAML
>     kind: VCDCluster
>     name: capi-cluster # name of the VCDCluster object associated with the cluster.
>     namespace: default # kubernetes namespace in which the VCDCluster object. Ideally should be the same namespace as that of the Cluster object
> ```

I think it should say "in which the VCDCluster object resides " or "will be created"
___
*[examples/capi-quickstart.yaml, line 29 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MtzT0nO4OgmChoqmQxE:-MtzT0nO4OgmChoqmQxF:b-detc39) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/423e5ae046de9c4bb9fa6c78d446d1122d4e40c4/examples/capi-quickstart.yaml#L29)):*
> ```YAML
> kind: VCDCluster
> metadata:
>   name: capi-cluster # name of the VCDCluster object. It is Recommended to keep the VCDCluster object name to match the Cluster object name to avoid confusion.
> ```

nit: Recommended -> recommended

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ltimothy7 and @sahithi)

___
*[examples/capi-quickstart.yaml, line 24 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MtzSv4D0azyZlSiLbb_:-MuCTFRTB-k8fg72hXGm:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/423e5ae046de9c4bb9fa6c78d446d1122d4e40c4/examples/capi-quickstart.yaml#L24)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I think it should say "in which the VCDCluster object resides " or "will be created"
</blockquote></details>

Done.

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39)* status: all files reviewed, 9 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[examples/capi-quickstart.yaml, line 4 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuC_ko47POSxrKaToMY:-MuC_ko47POSxrKaToMZ:bi594id) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3578b9121244393e0c45c36ca15ff56b3ee5a874/examples/capi-quickstart.yaml#L4)):*
> ```YAML
> kind: Cluster
> metadata:
>   name: capi-cluster # cluster name
> ```

I think we can skip describing the name and namespace properties of all the objects, as these are general K8s properties. 
___
*[examples/capi-quickstart.yaml, line 49 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCYqnnCQSH-O18dDu8:-MuCYqnnCQSH-O18dDu9:b-ovonj7) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3578b9121244393e0c45c36ca15ff56b3ee5a874/examples/capi-quickstart.yaml#L49)):*
> ```YAML
>   template:
>     spec:
>       catalog: cse-cat # catalog which contains the TKGm OVA used to deploy the control plane nodes
> ```

Catalog hosting the TKGm template, which will be used to deploy the control plane VMs.
___
*[examples/capi-quickstart.yaml, line 51 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCZOMn9XUfIlV3zrq4:-MuCZOMn9XUfIlV3zrq5:b-qx38yf) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3578b9121244393e0c45c36ca15ff56b3ee5a874/examples/capi-quickstart.yaml#L51)):*
> ```YAML
>       catalog: cse-cat # catalog which contains the TKGm OVA used to deploy the control plane nodes
>       template: ubuntu-2004-kube-v1.20.8+vmware.1-tkg.1-17589475007677388652 # name of the VCD template used to create the control plane nodes
>       computePolicy: 2core2gb # compute policy used to create the control plane VMs
> ```

sizing policy to be used for the control plane VMs (this must be pre-published on the chosen organization virtual datacenter).
___
*[examples/capi-quickstart.yaml, line 70 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCZmXI7gWiw4QB9J0G:-MuCZmXI7gWiw4QB9J0H:b-ytbl26) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3578b9121244393e0c45c36ca15ff56b3ee5a874/examples/capi-quickstart.yaml#L70)):*
> ```YAML
>       dns:
>         imageRepository: projects.registry.vmware.com/tkg # image repository to pull the DNS image from
>         imageTag: v1.7.0-vmware.12 # DNS image tag associated with the TKGm OVA used
> ```

# DNS image tag associated with the TKGm OVA used
 -  The values must be retrieved from the TKGm ova BOM. Refer to the github documentation for more details
___
*[examples/capi-quickstart.yaml, line 99 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCalzy79GFGwQAb7Ik:-MuCalzy79GFGwQAb7Il:bm9q6vw) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3578b9121244393e0c45c36ca15ff56b3ee5a874/examples/capi-quickstart.yaml#L99)):*
> ```YAML
>       namespace: default # kubernetes namespace of the VCDMachineTemplate object. Ideally should be the same namespace as that of the Cluster object
>   replicas: 1 # desired number of control plane nodes for the cluster
>   version: v1.20.8-vmware.1 # kubernetes version used by the control plane nodes
> ```

Kubernetes version to be used to create (or) upgrade the worker nodes. The value needs to be retrieved from the respective TKGm ova BOM. Refer to the documentation.
___
*[examples/capi-quickstart.yaml, line 110 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCa6Yz2PXssAv-XkAB:-MuCa6Yz2PXssAv-XkAC:bfla7w6) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3578b9121244393e0c45c36ca15ff56b3ee5a874/examples/capi-quickstart.yaml#L110)):*
> ```YAML
>     spec:
>       catalog: cse-cat # catalog which contains the TKGm OVA used to deploy the worker nodes
>       template: ubuntu-2004-kube-v1.20.8+vmware.1-tkg.1-17589475007677388652 # name of the VCD template used to create the worker nodes
> ```

Name of the template to be used to create (or) upgrade the worker nodes.
___
*[examples/capi-quickstart.yaml, line 112 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCbBlW6Kl9fkoPNdEN:-MuCbBlW6Kl9fkoPNdEO:bc870bq) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3578b9121244393e0c45c36ca15ff56b3ee5a874/examples/capi-quickstart.yaml#L112)):*
> ```YAML
>       template: ubuntu-2004-kube-v1.20.8+vmware.1-tkg.1-17589475007677388652 # name of the VCD template used to create the worker nodes
>       computePolicy: "" # compute policy used to create the worker VMs
> ---
> ```

sizing policy to be used for the worker VMs (this must be pre-published on the chosen organization virtual datacenter).
___
*[examples/capi-quickstart.yaml, line 156 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCaMttErncmbTY6DjN:-MuCaMttErncmbTY6DjO:bm9q6vw) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3578b9121244393e0c45c36ca15ff56b3ee5a874/examples/capi-quickstart.yaml#L156)):*
> ```YAML
>         name: capi-md0 # name of the VCDMachineTemplate object used to deploy worker nodes
>         namespace: default # kubernetes namespace of the VCDMachineTemplate object used to deploy worker nodes
>       version: v1.20.8-vmware.1 # kubernetes version used by the worker nodes
> ```

Kubernetes version to be used to create (or) upgrade the worker nodes. The value needs to be retrieved from the respective TKGm ova BOM. Refer to the documentation.

**Review by arunmk — APPROVED** [review]
:lgtm:

Mainly some comments on default values and some wording

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-:-MuCLSh23hq_9FQBU8UT:bf7mdto)* status: all files reviewed, 16 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[examples/capi-quickstart.yaml, line 10 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCEKmR5Dtrs8bbrLh-:-MuCEKmSEU_1LbYqgTBQ:b-yhjh6y) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/423e5ae046de9c4bb9fa6c78d446d1122d4e40c4/examples/capi-quickstart.yaml#L10)):*
> ```YAML
>     pods:
>       cidrBlocks:
>       - 192.168.0.0/16 # pod CIDR for the cluster
> ```

Can we change this to the same as the one in TKGm
___
*[examples/capi-quickstart.yaml, line 14 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCEOJm-6iFC6qxvicN:-MuCEOJm-6iFC6qxvicO:bw311lo) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/423e5ae046de9c4bb9fa6c78d446d1122d4e40c4/examples/capi-quickstart.yaml#L14)):*
> ```YAML
>     services:
>       cidrBlocks:
>       - 10.96.0.0/12 # service CIDR for the cluster
> ```

This must also match the TKGm values
___
*[examples/capi-quickstart.yaml, line 19 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCKuFW5nezqQpc9kV7:-MuCKuFW5nezqQpc9kV8:bv4jgwc) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/423e5ae046de9c4bb9fa6c78d446d1122d4e40c4/examples/capi-quickstart.yaml#L19)):*
> ```YAML
>     kind: KubeadmControlPlane
>     name: capi-control-plane # name of the KubeadmControlPlane object associated with the cluster.
>     namespace: default # kubernetes namespace in which the KubeadmControlPlane object reside. Ideally should be the same namespace as that of the Cluster object
> ```

Can we replace all such instances of `Ideally should` with `Should`
___
*[examples/capi-quickstart.yaml, line 32 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCL08vDBwp9Gxmgoxs:-MuCL08vDBwp9Gxmgoxt:b-rxf2lh) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/423e5ae046de9c4bb9fa6c78d446d1122d4e40c4/examples/capi-quickstart.yaml#L32)):*
> ```YAML
>   namespace: default # kubernetes namespace in which the VCDCluster object will be created. Ideally should be the same namespace as that of the Cluster object
> spec:
>   site: https://bos1-vcloud-static-170-210.eng.vmware.com # VCD endpoint with the format https://VCD_HOST. No trailing '/'
> ```

name should be randomized (`vcd.vmware.com` or some such site)
___
*[examples/capi-quickstart.yaml, line 37 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCL6gs1xNsFTpwQE4p:-MuCL6gs1xNsFTpwQE4q:b-tr370k) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/423e5ae046de9c4bb9fa6c78d446d1122d4e40c4/examples/capi-quickstart.yaml#L37)):*
> ```YAML
>   ovdcNetwork: test_orgvdc_net # VCD virtual datacenter network to be used by the cluster
>   userContext:
>     username: user_admin # username of the VCD persona creating the cluster
> ```

can we name it as some other thing rather than admin?
___
*[examples/capi-quickstart.yaml, line 49 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCJYm-5tqiPxSbWZT1:-MuCJYm05vYTedbjZR4X:b1ubn3j) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/423e5ae046de9c4bb9fa6c78d446d1122d4e40c4/examples/capi-quickstart.yaml#L49)):*
> ```YAML
>   template:
>     spec:
>       catalog: cse-cat # catalog which contains the TKGm OVA used to deploy the control plane nodes
> ```

Can we remove the cse name here. Maybe `tkgm-cat` ?
___
*[examples/capi-quickstart.yaml, line 51 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCJfgy9Y1v_-VjIR3t:-MuCJfgy9Y1v_-VjIR3u:b-x237ni) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/423e5ae046de9c4bb9fa6c78d446d1122d4e40c4/examples/capi-quickstart.yaml#L51)):*
> ```YAML
>       catalog: cse-cat # catalog which contains the TKGm OVA used to deploy the control plane nodes
>       template: ubuntu-2004-kube-v1.20.8+vmware.1-tkg.1-17589475007677388652 # name of the VCD template used to create the control plane nodes
>       computePolicy: 2core2gb # compute policy used to create the control plane VMs
> ```

the `2core2gb` should also be named as some `tkgm-compute-policy` so that people don't use 2core2gb as a recommendation.

Should we also say it is optional?

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39)* status: all files reviewed, 16 unresolved discussions (waiting on @arunmk, @ltimothy7, and @sahithi)

___
*[examples/capi-quickstart.yaml, line 10 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCEKmR5Dtrs8bbrLh-:-MuCsmoj5GQ7ixNiy9lU:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/423e5ae046de9c4bb9fa6c78d446d1122d4e40c4/examples/capi-quickstart.yaml#L10)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we change this to the same as the one in TKGm
</blockquote></details>

Done.
___
*[examples/capi-quickstart.yaml, line 14 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCEOJm-6iFC6qxvicN:-MuCsnh_7MzN2hDSh8Oh:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/423e5ae046de9c4bb9fa6c78d446d1122d4e40c4/examples/capi-quickstart.yaml#L14)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This must also match the TKGm values
</blockquote></details>

Done.
___
*[examples/capi-quickstart.yaml, line 19 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCKuFW5nezqQpc9kV7:-MuCtIKe8lb7fAWk5ZrR:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/423e5ae046de9c4bb9fa6c78d446d1122d4e40c4/examples/capi-quickstart.yaml#L19)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we replace all such instances of `Ideally should` with `Should`
</blockquote></details>

Done.
___
*[examples/capi-quickstart.yaml, line 32 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCL08vDBwp9Gxmgoxs:-MuCtOUj2R-GzQ5ug5TT:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/423e5ae046de9c4bb9fa6c78d446d1122d4e40c4/examples/capi-quickstart.yaml#L32)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

name should be randomized (`vcd.vmware.com` or some such site)
</blockquote></details>

Done.
___
*[examples/capi-quickstart.yaml, line 37 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCL6gs1xNsFTpwQE4p:-MuCtS_D1P6FiEwM58TR:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/423e5ae046de9c4bb9fa6c78d446d1122d4e40c4/examples/capi-quickstart.yaml#L37)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

can we name it as some other thing rather than admin?
</blockquote></details>

Done.
___
*[examples/capi-quickstart.yaml, line 49 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCJYm-5tqiPxSbWZT1:-MuCtjaEARBLdCqOFcmi:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/423e5ae046de9c4bb9fa6c78d446d1122d4e40c4/examples/capi-quickstart.yaml#L49)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we remove the cse name here. Maybe `tkgm-cat` ?
</blockquote></details>

Done.
___
*[examples/capi-quickstart.yaml, line 51 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCJfgy9Y1v_-VjIR3t:-MuCuK6S61I0-vAu1Ary:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/423e5ae046de9c4bb9fa6c78d446d1122d4e40c4/examples/capi-quickstart.yaml#L51)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

the `2core2gb` should also be named as some `tkgm-compute-policy` so that people don't use 2core2gb as a recommendation.

Should we also say it is optional?
</blockquote></details>

Done.
___
*[examples/capi-quickstart.yaml, line 4 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuC_ko47POSxrKaToMY:-MuCsLAzCNRMdWxJKcD3:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3578b9121244393e0c45c36ca15ff56b3ee5a874/examples/capi-quickstart.yaml#L4)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I think we can skip describing the name and namespace properties of all the objects, as these are general K8s properties. 
</blockquote></details>

Done.
___
*[examples/capi-quickstart.yaml, line 49 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCYqnnCQSH-O18dDu8:-MuCtfs5CSZRzMj3SmeH:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3578b9121244393e0c45c36ca15ff56b3ee5a874/examples/capi-quickstart.yaml#L49)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Catalog hosting the TKGm template, which will be used to deploy the control plane VMs.
</blockquote></details>

Done.
___
*[examples/capi-quickstart.yaml, line 51 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCZOMn9XUfIlV3zrq4:-MuCtt2hDVYb-h86tP-N:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3578b9121244393e0c45c36ca15ff56b3ee5a874/examples/capi-quickstart.yaml#L51)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

sizing policy to be used for the control plane VMs (this must be pre-published on the chosen organization virtual datacenter).
</blockquote></details>

Done.
___
*[examples/capi-quickstart.yaml, line 70 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCZmXI7gWiw4QB9J0G:-MuCuTjY1XanrNWvcBXT:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3578b9121244393e0c45c36ca15ff56b3ee5a874/examples/capi-quickstart.yaml#L70)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

# DNS image tag associated with the TKGm OVA used
 -  The values must be retrieved from the TKGm ova BOM. Refer to the github documentation for more details
</blockquote></details>

Done.
___
*[examples/capi-quickstart.yaml, line 99 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCalzy79GFGwQAb7Ik:-MuCueje2JtByustQrxO:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3578b9121244393e0c45c36ca15ff56b3ee5a874/examples/capi-quickstart.yaml#L99)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Kubernetes version to be used to create (or) upgrade the worker nodes. The value needs to be retrieved from the respective TKGm ova BOM. Refer to the documentation.
</blockquote></details>

Done.
___
*[examples/capi-quickstart.yaml, line 110 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCa6Yz2PXssAv-XkAB:-MuCuuVX-ACl563psyjR:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3578b9121244393e0c45c36ca15ff56b3ee5a874/examples/capi-quickstart.yaml#L110)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Name of the template to be used to create (or) upgrade the worker nodes.
</blockquote></details>

Done.
___
*[examples/capi-quickstart.yaml, line 112 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCbBlW6Kl9fkoPNdEN:-MuCv0pI50rdB-0QQcVs:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3578b9121244393e0c45c36ca15ff56b3ee5a874/examples/capi-quickstart.yaml#L112)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

sizing policy to be used for the worker VMs (this must be pre-published on the chosen organization virtual datacenter).
</blockquote></details>

Done.
___
*[examples/capi-quickstart.yaml, line 156 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39#-MuCaMttErncmbTY6DjN:-MuCv2hiEEugp72PrNJ2:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3578b9121244393e0c45c36ca15ff56b3ee5a874/examples/capi-quickstart.yaml#L156)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Kubernetes version to be used to create (or) upgrade the worker nodes. The value needs to be retrieved from the respective TKGm ova BOM. Refer to the documentation.
</blockquote></details>

Done.

**Pull request merged**
