### PR TITLE
CAFV-261: Use projects-stg as build registry

### PR DESCRIPTION
**Pull request by arunmk**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- Use projects-stg as internal registry

## Checklist
- [X] tested locally
- [X] updated any relevant dependencies
- [NA] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [X] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
NA

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/449)

### CODE REVIEW

**Review by lzichong — APPROVED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/449)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @arunmk and @ymo24)

___
*[`config/manager/manager.yaml` line 25 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/449#-NVehjzs5jYslnPHVIYD:-NVehjzs5jYslnPHVIYE:bowif7y) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/efdd6789fad37988661941bcbcbcfdf9a6b397d2/config/manager/manager.yaml#L25)):*
> ```YAML
>       - command:
>         - /opt/vcloud/bin/cluster-api-provider-cloud-director
>         image: projects.registry.vmware.com/vmware-cloud-director/cluster-api-provider-cloud-director:main-branch-a647055
> ```

I think these ones may need to be manually updated with `projects-stg.registry.vmware.com`. Currently in `manager.yaml.template`, Aritra has suggested to use the public harbor as CSE 4.1 cluster creation does not care for the registry anymore due to the fact that it gets overwritten by `clusterctl.yaml`. As a result, it was suggested to include public harbor URL in airgapped components so that it can be migrated easily from internal harbor to public harbor

**Comment by arunmk** [comment]
*[`config/manager/manager.yaml` line 25 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/449#-NVehjzs5jYslnPHVIYD:-NVeu8F59NlW35RNBw06:b4vcg25) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/efdd6789fad37988661941bcbcbcfdf9a6b397d2/config/manager/manager.yaml#L25)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

I think these ones may need to be manually updated with `projects-stg.registry.vmware.com`. Currently in `manager.yaml.template`, Aritra has suggested to use the public harbor as CSE 4.1 cluster creation does not care for the registry anymore due to the fact that it gets overwritten by `clusterctl.yaml`. As a result, it was suggested to include public harbor URL in airgapped components so that it can be migrated easily from internal harbor to public harbor
</blockquote></details>

Thanks @lzichong I have fixed this.

**Review by ymo24 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/449#-:-NVevZyKAUqhWbOePdw2:bnfp4nl)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @lzichong)

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/449)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @arunmk)

___
*[`templates/infrastructure-components.yaml` line 1563 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/449#-NVf2dwdCGdZu8tnahbb:-NVf2dwdCGdZu8tnahbc:b-q6rhz3) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/be8b03169e3d0de0acef35495d337b29568d139f/templates/infrastructure-components.yaml#L1563)):*
> ```YAML
>       - command:
>         - /opt/vcloud/bin/cluster-api-provider-cloud-director
>         image: projects.registry.vmware.com/vmware-cloud-director/cluster-api-provider-cloud-director:main-branch-05911c8
> ```

For the image on `infrastructure-components.yaml`, `manager.yaml`, I think we can switch to `projects-stg.registry`. This way I think it won't confuse the users who may attempt to use the main-branch but sees this and thinks this image is on public harbor, but we can keep the manager.yaml.template with public harbor

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/449#-:-NVfDLoo3sSq7TgHyBNQ:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk and @lzichong)

**Review by arunmk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/449)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @lzichong and @rocknes)

___
*[`templates/infrastructure-components.yaml` line 1563 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/449#-NVf2dwdCGdZu8tnahbb:-NVg-mDDDDcRG7LmiLPX:b-o0cbpz) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/be8b03169e3d0de0acef35495d337b29568d139f/templates/infrastructure-components.yaml#L1563)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

For the image on `infrastructure-components.yaml`, `manager.yaml`, I think we can switch to `projects-stg.registry`. This way I think it won't confuse the users who may attempt to use the main-branch but sees this and thinks this image is on public harbor, but we can keep the manager.yaml.template with public harbor
</blockquote></details>

Fixed. This is a problem because `make dev` undoes it.

**Pull request merged**
