### PR TITLE
[CAFV-254] Update clusterctl/core capi references to v1.4.0

### PR DESCRIPTION
**Pull request by lzichong**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- Update references of clusterctl/core capi to v1.4.0

## Checklist
- [ ] tested locally
- [ ] updated any relevant dependencies
- [x] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/459)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/459)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sahithi)

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/459)* status: all files reviewed, 1 unresolved discussion (waiting on @lzichong)

___
*[`README.md` line 17 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/459#-NWnhFHD4PVCRgPxtA5O:-NWnhFHEAz_Xn6MEObY1:b-9817vq) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6a2e713d10697c165f33a5d591c24e97f6baa951/README.md#L17)):*
> ```Markdown
> |                                  CAPVCD Version                                   | VMware Cloud Director API |                              VMware Cloud Director Installation                              |                                                                CoreCAPI/Clusterctl CLI version                                                                | Kubernetes Versions                                                        | CSI Versions                                                                                                                   | CPI Versions                                                                                                                                                                                              | 
> |:---------------------------------------------------------------------------------:|:-------------------------:|:--------------------------------------------------------------------------------------------:|:-------------------------------------------------------------------------------------------------------------------------------------------------------------:|:---------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
> |  [main](https://github.com/vmware/cluster-api-provider-cloud-director/tree/main)  |           36.0+           | 10.3.1+ <br/>(10.3.1 needs hot-patch to prevent VCD cell crashes in multi-cell environments) |                                          [1.4.0](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.4.0) <br/> [1.1.3](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.1.3)                                          | <ul><li>1.24</li><li>1.23</li><li>1.22</li><li>1.21</li><li>1.20</li></ul> | <ul><li>[1.3.1](https://github.com/vmware/cloud-director-named-disk-csi-driver/releases/tag/1.3.1)</li><li>[1.3.0](https://github.com/vmware/cloud-director-named-disk-csi-driver/releases/tag/1.3.0)</li></ul> | <ul><li>[1.3.0](https://github.com/vmware/cloud-provider-for-cloud-director/releases/tag/1.3.0)</li><li>[1.2.0](https://github.com/vmware/cloud-provider-for-cloud-director/releases/tag/1.2.0)</li></ul> |
> ```

You can remove 1.1.3 from here.
Any specific releason why you left it as is?

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/459)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @sahithi)

___
*[`README.md` line 17 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/459#-NWnhFHD4PVCRgPxtA5O:-NWniKw-2jh7r8KfQmP9:b-idzj5p) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6a2e713d10697c165f33a5d591c24e97f6baa951/README.md#L17)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

You can remove 1.1.3 from here.
Any specific releason why you left it as is?
</blockquote></details>

Updated, I kept it as we've qualified with it on main branch and that it can work with main branch, but I think it makes sense to remove it as suggested due to the go.mod update to `cluster-api v1.4.0`

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/459)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @lzichong)

___
*[`docs/CLUSTERCTL.md` line 23 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/459#-NWnj5uk5zU8hfPc6IPU:-NWnj5uk5zU8hfPc6IPV:b-wzuf78) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/95ded42a819d6c7234dfd35ca89814e8c42edd1b/docs/CLUSTERCTL.md#L23)):*
> ```Markdown
> ## Initialize Management cluster
> 1. Run the below command to initialize the management cluster with the Cluster API and the associated provider for VMware Cloud Director
> `clusterctl init --core cluster-api:v1.4.0 -b kubeadm:v1.4.0 -c kubeadm:v1.4.0 -i vcd:v1.0.0`
> ```

This command as-is may not work with capvcd 1.0.0

We can leave the old command as-is for 1.0.0 as an example.

Please mention the required steps that need to be done with the main branch.

**Pull request merged**
