### PR TITLE
Enable validate/mutate/conversion webhooks; converters between v1alpha4 and v1 beta1

### PR DESCRIPTION
**Pull request by sahithi**
Previous changesets mentioned below focused on the framework for API upgrades, hub and spoke setup, webhook enablement through kustomize/manifests, and the placeholder definitions for the validation, mutation, and conversion logic.

- https://github.com/vmware/cluster-api-provider-cloud-director/commit/40fdd099f79627451c5774324d9bf283a62940d9
- https://github.com/vmware/cluster-api-provider-cloud-director/commit/40fdd099f79627451c5774324d9bf283a62940d9

-------------------------

The current changeset focuses on
- Few more additions in the `api/v1alpha4` and `api/v1beta1` directories to get the prior plumbing fully functional.
- Autogenerated converter code via [conversion-gen](https://pkg.go.dev/k8s.io/code-generator@v0.23.5/cmd/conversion-gen) tool, example: `api/v1alpha4/zz_generated.conversion.go`
- Actual converter logic between `v1alpha4` and `v1beta1` for all the CAPVCD APIs, example: `api/v1alpha4/vcdcluster_conversion.go`
- Added minimal logic for the validation/mutate webhooks (create, update, delete). 
- Few more changes in the config manifests to fix cert-manager issues.
- Few dependencies in the Vendor package.

-------------------------

Tests done:
- CAPVCD deployment installation and start-up.
- Cluster creation through CAPI yaml of both v1alpha4 and v1beta1 APIs.
- One can retrieve CAPVCD objects via both v1alpha4 and v1beta1 format. 
`kubectl get vcdcluster.v1alpha4.infrastructure.cluster.x-k8s.io myCluster -o yaml`
`kubectl get vcdcluster.v1beta1.infrastructure.cluster.x-k8s.io myCluster -o yaml`  

-----------------------
Pending items:
1. Add a target in the MAKE file to use [conversion-gen](https://pkg.go.dev/k8s.io/code-generator@v0.23.5/cmd/conversion-gen). We will need to run the target every time we add new properties in v1beta1.
2. After I enabled the validation webhook, it expects "defaultStorageClassOptions" to be non-null value. We need to investigate further and do the necessary changes.
3. Figure out the debug setup of CAPVCD with the newly included manifests. 
--------------------
Conversion-gen command usage:

> ./conversion-gen --input-dirs=./api/v1alpha4 --output-file-base=zz_generated.conversion --go-header-file=./boilerplate.go.txt --build-tag=ignore_autogenerated_conversions

This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/82)

### CODE REVIEW

**Review by arunmk — APPROVED** [review]
:lgtm: just some questions to understand better and some comments on getting conversion-gen automatically.

Can we also put the command used into the commit description to help users. Maybe having it in a small readme will also help.

> Reviewed 34 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/82#-:-N-8kyMiEFCN_8bfXHXy:b-j8gcxx)* status: 34 of 38 files reviewed, 4 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[conversion-gen, line 0 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/82#-N-8eRcX8H2YkNoIjGpL:-N-8eRcX8H2YkNoIjGpM:bdjbhp8) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/5225a6524d9ea7dedb635474f27baed7d06e14eb/conversion-gen#L0)):*
Maybe we need to download this dynamically. I think the current Makefile has a similar thing for similar code-generator tools.
___
*[api/v1alpha4/vcdcluster_types.go, line 37 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/82#-N-8fhVf5JParHQy0L3t:-N-8fhVf5JParHQy0L3u:bql4n4t) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/48a4e344106e0e5a10dda6c1a9d0c8a3c1e8bf18/api/v1alpha4/vcdcluster_types.go#L37)):*
> ```Go
> }
> 
> type DefaultStorageClassOptions struct {
> ```

Why did this get removed in v1alpha4 but added to v1beta1?
___
*[api/v1beta1/vcdcluster_types.go, line 72 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/82#-N-8gJME2yR3N4aaPU8-:-N-8gJME2yR3N4aaPU80:bumf5q3) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/5225a6524d9ea7dedb635474f27baed7d06e14eb/api/v1beta1/vcdcluster_types.go#L72)):*
> ```Go
> 	UserCredentialsContext UserCredentialsContext `json:"userContext"`
> 	// +optional
> 	DefaultStorageClassOptions *DefaultStorageClassOptions `json:"defaultStorageClassOptions"`
> ```

I am not sure about using pointers in operators. I remember reading something about it. Does it work well?
___
*[controllers/vcdcluster_controller.go, line 131 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/82#-N-8i3ZP0AldqMLZI2mS:-N-8i3ZP0AldqMLZI2mT:bezfgrb) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/5225a6524d9ea7dedb635474f27baed7d06e14eb/controllers/vcdcluster_controller.go#L131)):*
> ```Go
> 	conditions.SetSummary(vcdCluster,
> 		conditions.WithConditions(
> 			LoadBalancerAvailableCondition,
> ```

Curious to know how does this work without `infrav1`? Same for the rest elsewhere

**Review by abaruni — APPROVED** [review]
> Reviewed 38 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/82)* status: all files reviewed, 4 unresolved discussions (waiting on @sahithi)

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/82)* status: 38 of 39 files reviewed, 1 unresolved discussion (waiting on @abaruni and @arunmk)

**Review by Anirudh9794 — COMMENTED** [review]
> Reviewed 12 of 38 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/82)* status: all files reviewed, 5 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[api/v1alpha4/vcdcluster_types.go, line 36 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/82#-N-9W2X17QqKeYKh9Wx3:-N-9W2X2BG_croMxtqyk:bamdrj3) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/48a4e344106e0e5a10dda6c1a9d0c8a3c1e8bf18/api/v1alpha4/vcdcluster_types.go#L36)):*
> ```Go
> 	RefreshToken string `json:"refreshToken,omitempty"`
> }
> ```

So does this mean that DefaultStorageClass feature is only supported with v1beta1?
___
*[api/v1alpha4/vcdmachine_conversion.go, line 8 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/82#-N-9V0k91LDRIPm92Q4W:-N-9V0k91LDRIPm92Q4X:bqqjmo) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/470f13cffa72df55aa8002e629de94a19ea58751/api/v1alpha4/vcdmachine_conversion.go#L8)):*
> ```Go
> )
> 
> // ConvertTo converts this (v1alpha4)VCDCluster to the Hub version (v1alpha5).
> ```

comment should be changed to 
// ConvertTo converts this (v1alpha4)VCDCluster to the Hub version (**v1beta1**).
___
*[api/v1alpha4/vcdmachine_conversion.go, line 19 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/82#-N-9VD1y-Rc1KY8tt03S:-N-9VD1y-Rc1KY8tt03T:b-ucc3l2) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/470f13cffa72df55aa8002e629de94a19ea58751/api/v1alpha4/vcdmachine_conversion.go#L19)):*
> ```Go
> }
> 
> // ConvertFrom converts from the Hub version (v1alpha5) to this version (v1alpha4).
> ```

comment should be changed to
// ConvertTo converts this (v1beta1)VCDCluster to the Hub version (v1alpha4).
___
*[api/v1beta1/vcdcluster_types.go, line 51 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/82#-N-9OdNm2eyfkKM6egqi:-N-9OdNm2eyfkKM6egqj:b2kc4tz) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/48a4e344106e0e5a10dda6c1a9d0c8a3c1e8bf18/api/v1beta1/vcdcluster_types.go#L51)):*
> ```Go
> 	UseDeleteReclaimPolicy bool `json:"useDeleteReclaimPolicy,omitempty"`
> 	// +kubebuilder:default=ext4
> 	FileSystemFormat string `json:"fileSystemFormat,omitempty"`
> ```

Ideally should be part of another PR. Sorry I saw this mistake a couple of days back but delayed submitting a change.

I can create a different change set to address this.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: Few questions and comments.

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/82#-:-N-9bILyEJiAHd6TIi8S:b-lsejbt)* status: all files reviewed, 5 unresolved discussions (waiting on @arunmk and @sahithi)

**Pull request merged**
