### PR TITLE
VCDA-3012: Allow specification of ssh key from KCP

### PR DESCRIPTION
**Pull request by arunmk**
In KCP, the ssh key can be specified under `kubeadmConfigSpec` as follows:
```
    users:
    - name: root
      sshAuthorizedKeys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAHCCo7SxtKx7o1SE2BfNiNsA+irrLyVYwtlvL4TUase akrishnakuma@vmware.com"
```

This results in the jinja script having the ssh key as part of the cloud init config itself. However the current way of converting the jinja script into a shell script and embedding it into the vcd cloud init does not work. Hence I did the following:
1. Parse the jinja and vcd cloudinit yaml files
2. Merge the yaml files
3. Treat the runcmd slightly specially (embed the runcmd of jinja into the vcd script)

Testing:
Created a cluster with my ssh key. After creating the dnat rule, the control plane node got the ssh key and was accessible. The worker nodes did not get the ssh key and were not accessible as a result.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/11)

### CODE REVIEW

**Review by sahithi — APPROVED** [review]
:lgtm: with few clarifications

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/11#-:-MqQxVQBCXq_QvDwlWc5:b-ep72im)* status: all files reviewed, 5 unresolved discussions (waiting on @arunmk)

___
*[controllers/vcdmachine_controller.go, line 420 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/11#-MqQO5I64GrIzRvjV7UO:-MqQO5I64GrIzRvjV7UP:bdjibwc) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0cb1f5e3e042df1e579e47943106223f48688845/controllers/vcdmachine_controller.go#L420)):*
> ```Go
> 		if err != nil {
> 			return ctrl.Result{}, errors.Wrapf(err,
> 				"unable to merge bootstrap jinja script [%s]", bootstrapJinjaScript)
> ```

Please include cluster name and worker node name as part of the log message
___
*[controllers/vcdmachine_controller.go, line 879 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/11#-MqQubQ34DqwBtuTY96V:-MqQubQ4BqaFyes1mFpg:bml0z4e) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0cb1f5e3e042df1e579e47943106223f48688845/controllers/vcdmachine_controller.go#L879)):*
> ```Go
> 	}
> 
> 	// eat the remaining keys not used in VCD
> ```

By "eating", you mean "appending"? At first, I thought it meant "deleting" :-)
___
*[controllers/vcdmachine_controller.go, line 888 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/11#-MqQwvmo5m22U8OJUIN3:-MqQwvmo5m22U8OJUIN4:byugogh) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0cb1f5e3e042df1e579e47943106223f48688845/controllers/vcdmachine_controller.go#L888)):*
> ```Go
> 
> 	out := []byte("#cloud-config\n")
> 	for _, key := range []string{
> ```

For my benefit, do the keys have exactly the same names in both the scripts? Could there be a different key name with the same intent?
For example "runcmd" ~ "executecmd" (or) "disable_root" ~ "disableroot"

Does cloud-init understand all of the other keys present in the Jinja script?

**Comment by arunmk** [comment]
___
*[controllers/vcdmachine_controller.go, line 879 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/11#-MqQubQ34DqwBtuTY96V:-MqR7wWB1JsDGXtAbsoH:b19rba9) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0cb1f5e3e042df1e579e47943106223f48688845/controllers/vcdmachine_controller.go#L879)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

By "eating", you mean "appending"? At first, I thought it meant "deleting" :-)
</blockquote></details>

I meant consuming :) Will change

**Comment by arunmk** [comment]
___
*[controllers/vcdmachine_controller.go, line 888 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/11#-MqQwvmo5m22U8OJUIN3:-MqR8-VA08hD47ZRSVN9:b-bk2gd3) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0cb1f5e3e042df1e579e47943106223f48688845/controllers/vcdmachine_controller.go#L888)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

For my benefit, do the keys have exactly the same names in both the scripts? Could there be a different key name with the same intent?
For example "runcmd" ~ "executecmd" (or) "disable_root" ~ "disableroot"

Does cloud-init understand all of the other keys present in the Jinja script?
</blockquote></details>

The "runcmd" is a cloudinit keyword and needs to be the same.

**Comment by arunmk** [comment]
___
*[controllers/vcdmachine_controller.go, line 843 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/11#-MqQ3nPbAorSVhjnys-v:-MqR8Bns3RnVIQwwh4dE:b-fheax) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0cb1f5e3e042df1e579e47943106223f48688845/controllers/vcdmachine_controller.go#L843)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Could the indentation be different for control plane and workers here? Just for my knowledge
</blockquote></details>

It will be the same. Basically we are changing the write_files section, so it will always be 4

**Comment by arunmk** [comment]
___
*[controllers/vcdmachine_controller.go, line 858 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/11#-MqQIFAT1WJ9ic8jUfC5:-MqR8MNy46OXQM-CN3D_:bu9nxbi) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0cb1f5e3e042df1e579e47943106223f48688845/controllers/vcdmachine_controller.go#L858)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

won't `cloudInitModified` be empty if `runcmd` is not present in `jinja`?
</blockquote></details>

No...so the `__JINJA_RUNCMD_REPLACE_ME__` within cloudInitConfig will be replaced by "", so it will just be a blank line.

**Comment by arunmk** [comment]
___
*[controllers/vcdmachine_controller.go, line 420 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/11#-MqQO5I64GrIzRvjV7UO:-MqR8f3B6kZV-ip6Gc-h:b2nha9w) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0cb1f5e3e042df1e579e47943106223f48688845/controllers/vcdmachine_controller.go#L420)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please include cluster name and worker node name as part of the log message
</blockquote></details>

ACK

**Comment by Anirudh9794** [comment]
___
*[controllers/vcdmachine_controller.go, line 858 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/11#-MqQIFAT1WJ9ic8jUfC5:-MqRBWU_95db9jeW1jQO:b216prj) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0cb1f5e3e042df1e579e47943106223f48688845/controllers/vcdmachine_controller.go#L858)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

No...so the `__JINJA_RUNCMD_REPLACE_ME__` within cloudInitConfig will be replaced by "", so it will just be a blank line.
</blockquote></details>

The above replacement will happen only if `ok` is true in `jinjaRunCmd, ok := jinja["runcmd"]` right?,

**Comment by Anirudh9794** [comment]
___
*[controllers/vcdmachine_controller.go, line 858 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/11#-MqQIFAT1WJ9ic8jUfC5:-MqRBuIYCfoS0DpGUZBI:b-6zoem2) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0cb1f5e3e042df1e579e47943106223f48688845/controllers/vcdmachine_controller.go#L858)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

The above replacement will happen only if `ok` is true in `jinjaRunCmd, ok := jinja["runcmd"]` right?,
</blockquote></details>

otherwise, cloudInitModified will be ""

**Pull request merged**
