### PR TITLE
 [VCDA-3468] Error and event reporting to RDE.status.capvcd

### PR DESCRIPTION
**Pull request by sahithi**
Error and event reporting to RDE.
This does not cover all possible errors and events I mentioned in the confluence document. Please see the list of <event, error> pairs this PR has here - https://confluence.eng.vmware.com/display/VCD/CAPVCD+Errors+and+Events

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166)

### CODE REVIEW

**Review by ymo24 — COMMENTED** [review]
:lgtm: with one comment about log. 

> Reviewed 9 of 12 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166#-:-N3zfSWuEPxtjdECXTIY:b6n9t19)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @sahithi and @ymo24)

___
*[`controllers/vcdcluster_controller.go` line 640 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166#-N3zbQs78Ljy9QpBWtGu:-N3zbQs78Ljy9QpBWtGv:b-tl55s0) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/29d79597155e3e032a059e93c8ec1b92f83366ee/controllers/vcdcluster_controller.go#L640)):*
> ```Go
> 	err = capvcdRdeManager.AddToEventSet(ctx, capisdk.LoadBalancerAvailable, virtualServiceHref, "", "")
> 	if err != nil {
> 		log.Error(err, "failed to add LoadBalancerAvailable event into RDE", "rdeID", infraID)
> ```

nit ---- It would look better to have a few spaces:
`log.Error(err, " failed to add LoadBalancerAvailable event into RDE ", "rdeID: ", infraID)`



_Code quote:_
```Go
log.Error(err, "failed to add LoadBalancerAvailable event into RDE", "rdeID", infraID)
```

**Review by ymo24 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @sahithi and @ymo24)

**Review by lzichong — APPROVED** [review]
:lgtm: after addressing comments

> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166#-:-N3znBVo-MlkF58IfHB3:b-98fkod)* status: 10 of 12 files reviewed, 6 unresolved discussions (waiting on @lzichong, @sahithi, and @ymo24)

___
*[`controllers/vcdcluster_controller.go` line 507 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166#-N3z3xK18MC9vGkldhkG:-N3z3xK18MC9vGkldhkH:bef8ze0) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/29d79597155e3e032a059e93c8ec1b92f83366ee/controllers/vcdcluster_controller.go#L507)):*
> ```Go
> 				log.Error(err, "failed to add RDE-upgrade event (RDE upgraded successfully) ", "rdeID", infraID)
> 			}
> 			err = capvcdRdeManager.RdeManager.RemoveErrorByNameOrIdFromErrorSet(ctx, vcdsdk.ComponentCAPVCD, capisdk.RdeUpgradeError, "", "")
> ```

Should this include vcdCluster.Name instead of empty string as the addToError used vcdCluster.Name?



_Code quote:_
```Go
err = capvcdRdeManager.RdeManager.RemoveErrorByNameOrIdFromErrorSet(ctx, vcdsdk.ComponentCAPVCD, capisdk.RdeUpgradeError, "", "")
```
___
*[`controllers/vcdcluster_controller.go` line 642 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166#-N3zE6F91aj48eWAqJVH:-N3zE6F91aj48eWAqJVI:b7ar4n8) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/29d79597155e3e032a059e93c8ec1b92f83366ee/controllers/vcdcluster_controller.go#L642)):*
> ```Go
> 		log.Error(err, "failed to add LoadBalancerAvailable event into RDE", "rdeID", infraID)
> 	}
> 	err = capvcdRdeManager.RdeManager.RemoveErrorByNameOrIdFromErrorSet(ctx, vcdsdk.ComponentCAPVCD, capisdk.LoadbalancerPending, "", "")
> ```

Should this also include virtualServiceHref instead of empty string?



_Code quote:_
```Go
err = capvcdRdeManager.RdeManager.RemoveErrorByNameOrIdFromErrorSet(ctx, vcdsdk.ComponentCAPVCD, capisdk.LoadbalancerPending, "", "")
```
___
*[`controllers/vcdcluster_controller.go` line 697 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166#-N3zEZo5541bK70c5JxJ:-N3zEZo5541bK70c5JxK:b-f7xmn) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/29d79597155e3e032a059e93c8ec1b92f83366ee/controllers/vcdcluster_controller.go#L697)):*
> ```Go
> 		log.Error(err, "failed to add InfraVappAvailable event into RDE", "rdeID", infraID)
> 	}
> 	err = capvcdRdeManager.RdeManager.RemoveErrorByNameOrIdFromErrorSet(ctx, vcdsdk.ComponentCAPVCD, capisdk.VappCreationError, "", "")
> ```

 vcdCluster.Name missing as vcdResourceName



_Code quote:_
```Go
	err = capvcdRdeManager.RdeManager.RemoveErrorByNameOrIdFromErrorSet(ctx, vcdsdk.ComponentCAPVCD, capisdk.VappCreationError, "", "")
```
___
*[`controllers/vcdcluster_controller.go` line 780 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166#-N3zlUA-4yBGWtTuacbD:-N3zlUA-4yBGWtTuacbE:bwwtxh8) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/29d79597155e3e032a059e93c8ec1b92f83366ee/controllers/vcdcluster_controller.go#L780)):*
> ```Go
> 		log.Error(err, "failed to add LoadBalancerDeleted event into RDE", "rdeID", vcdCluster.Status.InfraId)
> 	}
> 	err = capvcdRdeManager.RdeManager.RemoveErrorByNameOrIdFromErrorSet(ctx, vcdsdk.ComponentCAPVCD, capisdk.LoadBalancerDeleteError, "", "")
> ```

Missing virtualServiceNamePrefix as vcdResourceName



_Code quote:_
```Go
err = capvcdRdeManager.RdeManager.RemoveErrorByNameOrIdFromErrorSet(ctx, vcdsdk.ComponentCAPVCD, capisdk.LoadBalancerDeleteError, "", "")
```
___
*[`controllers/vcdcluster_controller.go` line 841 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166#-N3zm6So2NgIYVwLCNY4:-N3zm6So2NgIYVwLCNY5:b-19ydyt) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/29d79597155e3e032a059e93c8ec1b92f83366ee/controllers/vcdcluster_controller.go#L841)):*
> ```Go
> 		log.Error(err, "failed to add vAppDeleted event into RDE", "rdeID", vcdCluster.Status.InfraId)
> 	}
> 	err = capvcdRdeManager.RdeManager.RemoveErrorByNameOrIdFromErrorSet(ctx, vcdsdk.ComponentCAPVCD, capisdk.VappDeleteError, "", "")
> ```

vcdCluster.Name missing as vcdResourceName



_Code quote:_
```Go
err = capvcdRdeManager.RdeManager.RemoveErrorByNameOrIdFromErrorSet(ctx, vcdsdk.ComponentCAPVCD, capisdk.VappDeleteError, "", "")
```

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166)* status: 10 of 12 files reviewed, 6 unresolved discussions (waiting on @lzichong and @ymo24)

___
*[`controllers/vcdcluster_controller.go` line 507 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166#-N3z3xK18MC9vGkldhkG:-N4-wWAa7NZ1jMs5QZEM:bl2lotg) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/29d79597155e3e032a059e93c8ec1b92f83366ee/controllers/vcdcluster_controller.go#L507)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Should this include vcdCluster.Name instead of empty string as the addToError used vcdCluster.Name?
</blockquote></details>

All the RDE events and errors are associated with only one RDE, so there is no issue of uniqueness. So, I left it empty so that removal always succeeds despite any failures to add these properties while adding errors.
___
*[`controllers/vcdcluster_controller.go` line 640 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166#-N3zbQs78Ljy9QpBWtGu:-N4-x0CGEwJq5N6cI04J:b-ep39b6) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/29d79597155e3e032a059e93c8ec1b92f83366ee/controllers/vcdcluster_controller.go#L640)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

nit ---- It would look better to have a few spaces:
`log.Error(err, " failed to add LoadBalancerAvailable event into RDE ", "rdeID: ", infraID)`
</blockquote></details>

It is the exact name of the event. I should have put it in the quotes.
I will do that, thanks.
___
*[`controllers/vcdcluster_controller.go` line 642 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166#-N3zE6F91aj48eWAqJVH:-N4-xKlG8g9T4J-g3Zki:b1pmzae) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/29d79597155e3e032a059e93c8ec1b92f83366ee/controllers/vcdcluster_controller.go#L642)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Should this also include virtualServiceHref instead of empty string?
</blockquote></details>

Same here, in the case of CAPVCD (as opposed to CPI), there will always be only one Loadbalancer. The uniqueness is already taken care of.
Any time we want to remove LoadBalancerPendingError, we are free to remove all the entries of that type.

I actually tried to pass in virtualServiceHref, but at a few places, href was not readily available and extra VCD API calls were needed to get href. So, I decided to pass empty strings as there is no uniqueness issue here in the first place.
___
*[`controllers/vcdcluster_controller.go` line 697 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166#-N3zEZo5541bK70c5JxJ:-N4-yVxPBQj3TGvUzgrY:bxe5wft) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/29d79597155e3e032a059e93c8ec1b92f83366ee/controllers/vcdcluster_controller.go#L697)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

 vcdCluster.Name missing as vcdResourceName
</blockquote></details>

same here, there exists only one vApp associated with the cluster.
___
*[`controllers/vcdcluster_controller.go` line 780 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166#-N3zlUA-4yBGWtTuacbD:-N4-zH65122hVmqGfXzk:b7cv3aj) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/29d79597155e3e032a059e93c8ec1b92f83366ee/controllers/vcdcluster_controller.go#L780)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Missing virtualServiceNamePrefix as vcdResourceName
</blockquote></details>

same explanation as above
___
*[`controllers/vcdcluster_controller.go` line 841 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166#-N3zm6So2NgIYVwLCNY4:-N4-zcIHBng8tR0G7CHX:b5srirv) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/29d79597155e3e032a059e93c8ec1b92f83366ee/controllers/vcdcluster_controller.go#L841)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

vcdCluster.Name missing as vcdResourceName
</blockquote></details>


same explanation as above

**Pull request merged**
