### PR TITLE
[VCDA-4059] Update Log VM details when network address check fails

### PR DESCRIPTION
**Pull request by lzichong**
Signed-off-by: lzichong <lzichong@vmware.com>

## Description
Please provide a brief description of the changes proposed in this Pull Request

-  Updated logging information to show the VM info if exists other than just a pointer.
- Separate conditions and logs for future root causes and understandings

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies [N/A]
- [ ] updated any relevant documentation or examples [N/A]

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [x] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [x] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [x] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [x] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [x] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/209)

### CODE REVIEW

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/209)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk and @lzichong)

___
*[`controllers/vcdmachine_controller.go` line 560 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/209#-N7XU0iv2mn5B2LkorYt:-N7XU0iv2mn5B2LkorYu:b-doggko) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c5477be709b474cf5798e341e47589c3638dd362/controllers/vcdmachine_controller.go#L560)):*
> ```Go
> 	}
> 	if vm.VM.NetworkConnectionSection == nil || len(vm.VM.NetworkConnectionSection.NetworkConnection) == 0 {
> 		log.Error(nil, fmt.Sprintf("Requeuing...; failed to get the network connection section for vm [%s(%s)]: [%#v]", vm.VM.Name, vm.VM.ID, vm.VM))
> ```

The logs are again the same in this block and the next one. I think the log statements need to change

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/209)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @arunmk)

___
*[`controllers/vcdmachine_controller.go` line 560 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/209#-N7XU0iv2mn5B2LkorYt:-N7axZ004s2fe3KCr2eL:b7u4l58) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c5477be709b474cf5798e341e47589c3638dd362/controllers/vcdmachine_controller.go#L560)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

The logs are again the same in this block and the next one. I think the log statements need to change
</blockquote></details>

Do you think it'd be more helpful if we change the log in this block to 'network connection not found for VM' and the next as 'failed to get existing network connection information'?

**Review by arunmk — APPROVED** [review]
:lgtm: with a couple of small comments

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/209#-:-N7b06qr5BGbKrKL63ln:b-w1syxs)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @lzichong)

___
*[`controllers/vcdmachine_controller.go` line 556 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/209#-N7b-YCD33k7xLSwgHoo:-N7b-YCD33k7xLSwgHop:bbhe69i) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c5477be709b474cf5798e341e47589c3638dd362/controllers/vcdmachine_controller.go#L556)):*
> ```Go
> 	// checks before setting address in machine status
> 	if vm.VM == nil {
> 		log.Error(nil, fmt.Sprintf("Requeuing...; failed to get the machine address of vm [%#v]", vm))
> ```

This should be `vm.VM should not be nil` or something like that
___
*[`controllers/vcdmachine_controller.go` line 564 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/209#-N7b-nU5CI8uNoPfmFq8:-N7b-nU5CI8uNoPfmFq9:bjwv0pk) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c5477be709b474cf5798e341e47589c3638dd362/controllers/vcdmachine_controller.go#L564)):*
> ```Go
> 	}
> 
> 	if vm.VM.NetworkConnectionSection.NetworkConnection[0] == nil || vm.VM.NetworkConnectionSection.NetworkConnection[0].IPAddress == "" {
> ```

Can we split this into two sections where there is a nil check and a log, and another which prints the `*vm.VM.NetworkConnectionSection[0]` (the dereferenced object and not the pointer)

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/209)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`controllers/vcdmachine_controller.go` line 556 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/209#-N7b-YCD33k7xLSwgHoo:-N7bToPW4JHP8N4SJilj:b-8z84mu) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c5477be709b474cf5798e341e47589c3638dd362/controllers/vcdmachine_controller.go#L556)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This should be `vm.VM should not be nil` or something like that
</blockquote></details>

Updated, thanks Arun!
___
*[`controllers/vcdmachine_controller.go` line 560 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/209#-N7XU0iv2mn5B2LkorYt:-N7bThes4k6TMuM0KBNU:bwh67gv) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c5477be709b474cf5798e341e47589c3638dd362/controllers/vcdmachine_controller.go#L560)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Do you think it'd be more helpful if we change the log in this block to 'network connection not found for VM' and the next as 'failed to get existing network connection information'? 
</blockquote></details>

Updated log statements to be different/identifiable, thanks Aniruddh!
___
*[`controllers/vcdmachine_controller.go` line 564 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/209#-N7b-nU5CI8uNoPfmFq8:-N7bTfRyCQkhTUSAhFCq:b-8z84mu) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c5477be709b474cf5798e341e47589c3638dd362/controllers/vcdmachine_controller.go#L564)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we split this into two sections where there is a nil check and a log, and another which prints the `*vm.VM.NetworkConnectionSection[0]` (the dereferenced object and not the pointer)
</blockquote></details>

Updated, thanks Arun!

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/209)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

**Pull request merged**
