### PR TITLE
[CAFV-267] Clutser upgrade test automation

### PR DESCRIPTION
**Pull request by ymo24**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- 

## Checklist
- [ ] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475)

### CODE REVIEW

**Review by rliang88 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-:-N_AMTeP8PYlQAfGgxlI:bnfp4nl)* status: 2 of 7 files reviewed, all discussions resolved (waiting on @Anirudh9794 and @sahithi)

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sahithi)

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi and @ymo24)

___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 375 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_AOVnnDfi9FKxQHO6p:-N_AOVnnDfi9FKxQHO6q:bc4o7bl) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L375)):*
> ```Go
> 			break
> 		case VCDMachineTemplate:
> 			specMap, err := testingsdk.GetMapBySpecName(unstructuredObj.Object, "spec", "VCDMachineTemplate")
> ```

We should ideally create a new VCDMachineTemplate object and change the reference in the Machine Deployment and KCP.
But I am okay with the current changes.
I don't know if we are planning to use VCDMachineTemplate this way. Can you please add a TODO for this ?

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475)* status: all files reviewed, 12 unresolved discussions (waiting on @Anirudh9794 and @ymo24)

___
*[`tests/e2e/e2e_suite_test.go` line 13 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_AKDKZ9jqzK6vePqG9:-N_AKDKZ9jqzK6vePqGA:b-rbikbo) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/e2e_suite_test.go#L13)):*
> ```Go
> 	PathToMngmntClusterKubecfg    string
> 	PathToWorkloadClusterCapiYaml string
> 	TargetTKGVersion              string
> ```

It is not clear if these variables TargetTKGVersion and TargetK8SVersion are meant to be used for cluster creation (or) cluster upgrades.

Please rename them to TargetTKGVersionForUpgradeTest, TargetK8sVersionForUpgradeTest
___
*[`tests/e2e/workload_cluster_upgrade_test.go` line 32 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_AJYum8eLrfAFb40qs:-N_AJYum8eLrfAFb40qt:bw8xtku) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/workload_cluster_upgrade_test.go#L32)):*
> ```Go
> 
> var _ = Describe("Workload Cluster Life cycle management", func() {
> 	When("create, upgrade, and delete the workload cluster", func() {
> ```

For my benefit, what is the purpose of this "When"? 
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 68 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_AZpbaBbPj9XwFWFGF:-N_AZpbaBbPj9XwFWFGG:bz2os58) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L68)):*
> ```Go
> // @param currTkgVersion - the cluster's current tkg version
> // @param tkgMap - tkg_map.json, but marshalled into map[string]interface{}
> // @return map[string]interface{} - map of all possible upgrade paths; it is a subset of tkgMap
> ```

Can you mention an example of return map? It is a good practice to identify key-value pairs by an example.
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 150 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_AbtPi3bgHdMMMWmvK:-N_AbtPi3bgHdMMMWmvL:b-354yph) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L150)):*
> ```Go
> 		}
> 
> 		tkgVersionIsGreater, err := isGreaterThanOrEqual(tkgVersionStr, currTkgVersion)
> ```

you can rename this to isTkgVersionCompatible.

TKG version need not be greater.
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 177 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_Ae6h7BiIVCfj6NRft:-N_Ae6h7BiIVCfj6NRfu:bgj8ws6) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L177)):*
> ```Go
> func getRDEUpgradeResources(supportedUpgrades map[string]interface{}, allVappTemplates []*types.QueryResultVappTemplateType, targetK8sVersion, targetTkgVersion string) (string, *types.QueryResultVappTemplateType, error) {
> 	// Create a map to store the tkgOva data based on the k8s version
> 	tkgOvaMap := make(map[string]map[string]interface{})
> ```

Please provide examples on how these maps will look like.
for example, what is the key - tkg version? K8s version? ova name? and what is the value?

I had to read through the entire method and then tkgmap.json to find that out.
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 252 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_AiC7-AcbcLVenXyRq:-N_AiC7-AcbcLVenXyRr:bb05elz) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L252)):*
> ```Go
> // - string: The Kubernetes version that the cluster is being upgraded to.
> // - error: nil if there is no error, otherwise the encountered error.
> func getCapiYamlAfterUpgrade(ctx context.Context, r runtimeclient.Client, capiYaml string, tkgMapKey string, tkgMap map[string]interface{}, vappTemplate *types.QueryResultVappTemplateType) (string, error) {
> ```

Method name and return value do not match.

Please change it to ApplyK8sVersionUpgrade()
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 375 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_AOVnnDfi9FKxQHO6p:-N_Ah3BnDL7zW8H-DlBr:b-2vhl93) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L375)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

We should ideally create a new VCDMachineTemplate object and change the reference in the Machine Deployment and KCP.
But I am okay with the current changes.
I don't know if we are planning to use VCDMachineTemplate this way. Can you please add a TODO for this ?
</blockquote></details>

It is fine if testing triggered the upgrades. Just ensure VCDMachineTemplate object is updated first before MachineDeployment
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 425 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_AZRgSC_CH6BBBHFpM:-N_AZRgT0LGUqJ0YCL77:b3krale) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L425)):*
> ```Go
> 	currTkgVersion, err := getTkgVersionFromTKGMap(currK8sVersion, tkgMap)
> 	if err != nil {
> 		return "", fmt.Errorf("error retrieving TKG version from capiyaml: [%v]", err)
> ```

error retrieving TKG version for a given K8s version [%s] from the tkgmap
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 428 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_Aey5m9VDiKr5ieHl1:-N_Aey5m9VDiKr5ieHl2:b-p2tswc) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L428)):*
> ```Go
> 	}
> 
> 	supportedUpgrades, err := getSupportedUpgrades(currK8sVersion, currTkgVersion, tkgMap)
> ```

I am unsure if we need to get the entire supported upgrade list, we could pass the target tkg version and target K8s version also into just one method, and the output could be tkgmapKey and vAppTemplate.

I don't see a need for two methods, "getSupportedUpgrades" and "getRdeUpgradeResources".

It is okay for now, please create a task to refactor this. Please don't hesitate to chat if you think I am missing something.

We just want one reusable method
- getTKGInfoForAGivenK8sAndTKGVersion // get all the tkg details for a given K8s and tkg version 
// parses through entire tkg json and outputs the map (tkg details)

And then see if that ova exists in vApp templates.
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 439 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_AiaYS4VcNc1PaaOMA:-N_AiaYS4VcNc1PaaOMB:b-yjz3qv) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L439)):*
> ```Go
> 	updatedK8sVersion, err := getCapiYamlAfterUpgrade(ctx, r, capiYaml, tkgMapKey, tkgMap, vappTemplate)
> 	if err != nil {
> 		return "", fmt.Errorf("error constructing new capiyaml: [%v]", err)
> ```

error applying the modified objects of KCP, MD, VCDMachineTemplate for upgrade operation
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 454 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_Aj_LMApbxiMHNWEL0:-N_Aj_LMApbxiMHNWEL1:b-8c3ljt) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L454)):*
> ```Go
> 	testClient *testingsdk.TestClient, runtimeClient runtimeclient.Client, targetK8sVersion string,
> ) error {
> 	timeout := timeoutMinutes * time.Minute
> ```

what are the timeout and poll interval values? What is the value of timeoutMinutes?
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 459 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_Ake4p1Eixtrf3X0HR:-N_Ake4p1Eixtrf3X0HS:b88teq6) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L459)):*
> ```Go
> 	return wait.PollImmediate(pollInterval, timeout, func() (bool, error) {
> 		// getting all nodes
> 		nodeList, err := testClient.GetNodes(context.Background())
> ```

Is there a need to get the node details?

I think we can just wait on the machines.
Machines also has K8 version as one of its columns.

if every machine has target k8s version and is in running state, that is good enough check.Please verify

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475)* status: 4 of 7 files reviewed, 12 unresolved discussions (waiting on @Anirudh9794, @rliang88, and @sahithi)

___
*[`tests/e2e/e2e_suite_test.go` line 13 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_AKDKZ9jqzK6vePqG9:-N_AnOfw9yWXusgEN2MG:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/e2e_suite_test.go#L13)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

It is not clear if these variables TargetTKGVersion and TargetK8SVersion are meant to be used for cluster creation (or) cluster upgrades.

Please rename them to TargetTKGVersionForUpgradeTest, TargetK8sVersionForUpgradeTest
</blockquote></details>

Done.
___
*[`tests/e2e/workload_cluster_upgrade_test.go` line 32 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_AJYum8eLrfAFb40qs:-N_AnWaxEeBktdGotqx9:b1m7qma) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/workload_cluster_upgrade_test.go#L32)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

For my benefit, what is the purpose of this "When"? 
</blockquote></details>

It's a specific explanation for Describe(). It will not conduct any functional effect on the CAPVCD test.
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 68 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_AZpbaBbPj9XwFWFGF:-N_AqgSQ5nqR6r3ICsZt:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L68)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you mention an example of return map? It is a good practice to identify key-value pairs by an example.
</blockquote></details>

Done.
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 150 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_AbtPi3bgHdMMMWmvK:-N_Aqtbe5I67Gl1F2Pxg:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L150)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

you can rename this to isTkgVersionCompatible.

TKG version need not be greater.
</blockquote></details>

Done.
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 177 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_Ae6h7BiIVCfj6NRft:-N_AtWaFCXUe5JF8mfL5:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L177)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please provide examples on how these maps will look like.
for example, what is the key - tkg version? K8s version? ova name? and what is the value?

I had to read through the entire method and then tkgmap.json to find that out.
</blockquote></details>

Done.
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 252 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_AiC7-AcbcLVenXyRq:-N_As8csBZ7SiGlmIqD-:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L252)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Method name and return value do not match.

Please change it to ApplyK8sVersionUpgrade()
</blockquote></details>

Done.
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 425 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_AZRgSC_CH6BBBHFpM:-N_AtoGB0YhYudF6E1O-:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L425)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

error retrieving TKG version for a given K8s version [%s] from the tkgmap
</blockquote></details>

Done.
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 428 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_Aey5m9VDiKr5ieHl1:-N_AwkXn9utxm_CYfgJv:b8ejobf) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L428)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I am unsure if we need to get the entire supported upgrade list, we could pass the target tkg version and target K8s version also into just one method, and the output could be tkgmapKey and vAppTemplate.

I don't see a need for two methods, "getSupportedUpgrades" and "getRdeUpgradeResources".

It is okay for now, please create a task to refactor this. Please don't hesitate to chat if you think I am missing something.

We just want one reusable method
- getTKGInfoForAGivenK8sAndTKGVersion // get all the tkg details for a given K8s and tkg version 
// parses through entire tkg json and outputs the map (tkg details)

And then see if that ova exists in vApp templates.


</blockquote></details>

Will create a task for all the refractor work post GA
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 439 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_AiaYS4VcNc1PaaOMA:-N_AwrxLB5Fo_dINm2iS:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L439)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

error applying the modified objects of KCP, MD, VCDMachineTemplate for upgrade operation
</blockquote></details>

Done.
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 454 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_Aj_LMApbxiMHNWEL0:-N_Awwxw5Zf_IiVNBD1w:b67d4sn) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L454)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

what are the timeout and poll interval values? What is the value of timeoutMinutes?
</blockquote></details>

all these params are from testingSdk common code. Already added a comment here



_Code snippet:_
```Go
// timeout: 40 minutes; pollInterval: 2 minutes
```
___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 459 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_Ake4p1Eixtrf3X0HR:-N_ApUQY2MAE5gRVSpDY:byp5mml) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L459)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Is there a need to get the node details?

I think we can just wait on the machines.
Machines also has K8 version as one of its columns.

if every machine has target k8s version and is in running state, that is good enough check.Please verify
</blockquote></details>

yeah sure, Sahithi. I am using node check because it's already in the testing common code. 
I will refract this function post GA

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475)* status: 4 of 7 files reviewed, 12 unresolved discussions (waiting on @Anirudh9794, @rliang88, and @sahithi)

___
*[`tests/e2e/utils/cluster_upgrade_utils.go` line 375 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-N_AOVnnDfi9FKxQHO6p:-N_BE0WhChmCs20aDyPQ:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3d0842c3c8494ca348c7a8c9cdddcae20932a7a1/tests/e2e/utils/cluster_upgrade_utils.go#L375)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

It is fine if testing triggered the upgrades. Just ensure VCDMachineTemplate object is updated first before MachineDeployment
</blockquote></details>

Done.

**Review by sahithi — APPROVED** [review]
:lgtm: after you create a jira task with two things a) refactor retrieving tkg info details b) remove node check details from the monitor code

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/475#-:-N_BQc9rEqmLLfuB3oN0:ba9iqnf)* status: 4 of 7 files reviewed, 12 unresolved discussions (waiting on @Anirudh9794 and @rliang88)

**Pull request merged**
