### PR TITLE
[VCDA-3837] Remove capvcd yaml

### PR DESCRIPTION
**Pull request by ltimothy7**
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/188)

### CODE REVIEW

**Comment by ltimothy7** [comment]
Pushed the image - [harbor-repo.vmware.com/vcloud/cluster-api-provider-cloud-director:vkp-branch](http://harbor-repo.vmware.com/vcloud/cluster-api-provider-cloud-director:vkp-branch)? No
Are there API changes? - No
Updated conversions? Yes
Updated CRDs? - Yes
Updated capiYaml Examples? - Yes
Updated infrastructure-components.yaml? - Yes
Updated VCD-KE with the latest CAPVCD library? - N

**Comment by ltimothy7** [comment]
Get rid of vipsubnet, onearm, cpi, csi, cni properties.
Read vipsubnet from capi yaml
Read cpi, csi, cni from CRS definitions. - hardcode for now.
Get rid of onearm functionality from capvcd code base

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/188)* status: 0 of 34 files reviewed, 4 unresolved discussions (waiting on @ltimothy7 and @sahithi)

___
*[`api/v1beta1/vcdcluster_types.go` line 72 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/188#-N5LAqy64kCOuxX8Xxbq:-N5LDw-oDxx07dhBTPGw:buu21fb) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8ce10835382fb524a67b91dc9b598cc194a06452/api/v1beta1/vcdcluster_types.go#L72)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We don't need oneArm anymore. These properties can be removed.
</blockquote></details>

Kube api server port can be hardcoded to 6443.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/188)* status: 0 of 36 files reviewed, 2 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[`api/v1beta1/vcdcluster_types.go` line 72 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/188#-N5LAqy64kCOuxX8Xxbq:-N5hcEmu2Mvk3ATMge1D:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8ce10835382fb524a67b91dc9b598cc194a06452/api/v1beta1/vcdcluster_types.go#L72)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Kube api server port can be hardcoded to 6443.
</blockquote></details>

Done.
___
*[`api/v1beta1/vcdcluster_types.go` line 106 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/188#-N5LB0i_CHfRGwBRirRw:-N5hcFr7ACQcBhV4N0t0:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8ce10835382fb524a67b91dc9b598cc194a06452/api/v1beta1/vcdcluster_types.go#L106)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

this property can be moved to Loadbalancer section @arunmk what do you think? 
</blockquote></details>

Done.

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 11 of 33 files at r1, 8 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/188)* status: 19 of 36 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 64 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/188#-N5q9-LmAG1v9pQJSEL_:-N5q9-LmAG1v9pQJSELa:blrak5f) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/392df03a10c9e96819a613c9371b12b95da4799c/controllers/vcdcluster_controller.go#L64)):*
> ```Go
> 	CsiDefaultVersion = "1.2.0"
> 	CniDefaultVersion = "0.13.1"
> 	CapvcdVersion     = "1.0.0"
> ```

CapvcdVersion can be obtained using `release. CAPVCDVersion`

**Comment by ltimothy7** [comment]
*[`controllers/vcdcluster_controller.go` line 64 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/188#-N5q9-LmAG1v9pQJSEL_:-N5r2VJD5wQLmzkycUuo:bk3dig1) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/392df03a10c9e96819a613c9371b12b95da4799c/controllers/vcdcluster_controller.go#L64)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

CapvcdVersion can be obtained using `release. CAPVCDVersion`
</blockquote></details>

How can I access this?

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 26 of 33 files at r1, 9 of 10 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/188#-:-N5rPl3U-hyG_ujfXZkM:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 242 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/188#-N5aqSce5nGjAICjCePR:-N5aqSce5nGjAICjCePS:b-rebtfu) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8ce10835382fb524a67b91dc9b598cc194a06452/controllers/vcdcluster_controller.go#L242)):*
> ```Go
> 			NodeStatus:          make(map[string]string),
> 			IsManagementCluster: vcdCluster.Spec.UseAsManagementCluster,
> 			CapvcdVersion:       "1.0.0", // TODO: read from CRS
> ```

capvcd version needs to come from /release

**Pull request merged**
