### PR TITLE
[CAFV-176] Update tagging manifests with version-gitcommit

### PR DESCRIPTION
**Pull request by lzichong**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- Updates tagging for containers

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/401)

### CODE REVIEW

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/401)* status: all files reviewed, 1 unresolved discussion (waiting on @lzichong and @sakthisunda)

___
*[`Makefile` line 183 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/401#-NP4Isyq5tc8Ze9RRZ6O:-NP4Isyq5tc8Ze9RRZ6P:b-1lv5qa) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3767e0eb03676099c4ba7c85b75c70694e846d4e/Makefile#L183)):*
> ```Makefile
> 
> dev: capi dev-capvcd-artifacts
> 	docker push $(IMG).$(GITCOMMIT)
> ```

shouldn't this line also get the version-gitcommit treatment?

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/401)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes and @sakthisunda)

___
*[`Makefile` line 183 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/401#-NP4Isyq5tc8Ze9RRZ6O:-NP4KPaj-ZGUw3TNv7L_:bn3hdp4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3767e0eb03676099c4ba7c85b75c70694e846d4e/Makefile#L183)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

shouldn't this line also get the version-gitcommit treatment?
</blockquote></details>

Since this one pushes just the CAPVCD image (image using .gitCommit has no issues), so I left it as is to keep the image consistency across all projects the same. We only need to ensure CAPVCD gets pulled (CAPVCD version), it needs to be semver compliant. Do you think I should still change it?

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/401#-:-NP4iiaI1D7Qp-TM4W_x:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/401)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lzichong)

**Review by sakthisunda — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/401#-:-NP4jufSEmKzlp-yqLeb:bg7igk9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lzichong)

**Pull request merged**
