### PR TITLE
[CAFV-265][Test] Workload cluster creation based on a completed mgmt cluster

### PR DESCRIPTION
**Pull request by ymo24**
Signed-off-by: ymo24 <ymo@vmware.com>

## Description
Please provide a brief description of the changes proposed in this Pull Request

- [Test] Workload cluster creation based on a completed mgmt cluster

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #
Screenshot 2023-06-12 at 6 44 15 PM

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462)

### CODE REVIEW

**Comment by Anirudh9794** [comment]
*[`tests/e2e/e2e_suite_test.go` line 38 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NXqkIFkEBIOoEAwLMy3:-NXqkIFkEBIOoEAwLMy4:b-i4ll0y) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1dfed5c2d93187b9914aa1462e24a744b6c46661/tests/e2e/e2e_suite_test.go#L38)):*
> ```Go
> var _ = BeforeSuite(func() {
> 
> 	Expect(kubeCfgPath).NotTo(BeZero(), "Please make sure --kubeCfgPath WaitFor set correctly.")
> ```

 I didn't understand the meaning of the term `WaitFor`

**Comment by Anirudh9794** [comment]
*[`tests/e2e/doc.md` line 16 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NXqkjiUDLyxW1tZLf9G:-NXqkjiUDLyxW1tZLf9H:b-lydb6t) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1dfed5c2d93187b9914aa1462e24a744b6c46661/tests/e2e/doc.md#L16)):*
> ```Markdown
> 
> - Test Preflight
>   - The management cluster can be accessible - **You can also use [setup script](setup_kind_cluster.sh) to set up the kind cluster**
> ```

setup_kind_cluster.sh seems to be empty

**Comment by Anirudh9794** [comment]
*[`tests/e2e/e2e_suite_test.go` line 51 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NXqkbab0dc5RUDjlr0I:-NXqkbab0dc5RUDjlr0J:b-dqggjg) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1dfed5c2d93187b9914aa1462e24a744b6c46661/tests/e2e/e2e_suite_test.go#L51)):*
> ```Go
> func TestCSIAutomation(t *testing.T) {
> 	RegisterFailHandler(Fail)
> 	RunSpecs(t, "CSI Testing Suite")
> ```

RunSpecs(t, "CAPVCD Testing Suite")



_Code quote:_
```Go
RunSpecs(t, "CSI Testing Suite")
```

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462)* status: 0 of 15 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

___
*[`tests/e2e/doc.md` line 16 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NXqkjiUDLyxW1tZLf9G:-NY-7ull9adaDgRXOjuZ:bpfhbz8) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1dfed5c2d93187b9914aa1462e24a744b6c46661/tests/e2e/doc.md#L16)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

setup_kind_cluster.sh seems to be empty
</blockquote></details>

Thanks for the catching. I pushed the missing file
___
*[`tests/e2e/e2e_suite_test.go` line 38 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NXqkIFkEBIOoEAwLMy3:-NY-9XT45T43KCgvk-PI:b-3uax6z) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1dfed5c2d93187b9914aa1462e24a744b6c46661/tests/e2e/e2e_suite_test.go#L38)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

 I didn't understand the meaning of the term `WaitFor`
</blockquote></details>

Already changed them
___
*[`tests/e2e/e2e_suite_test.go` line 51 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NXqkbab0dc5RUDjlr0I:-NY-9V_MB2IO6BcFHz36:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1dfed5c2d93187b9914aa1462e24a744b6c46661/tests/e2e/e2e_suite_test.go#L51)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

RunSpecs(t, "CAPVCD Testing Suite")
</blockquote></details>

Done.

**Review by Anirudh9794 — COMMENTED** [review]
> Reviewed 4 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462)* status: 4 of 15 files reviewed, 8 unresolved discussions (waiting on @ymo24)

___
*[`tests/e2e/setup_kind_cluster.sh` line 3 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-JlYv4uwGgpK49Br9:-NY-JlYv4uwGgpK49BrA:b-24obgu) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/setup_kind_cluster.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> export GOROOT=~/go
> ```

I don't think we should be setting GOROOT here. This should be a configured before the script is executed.
Can you remove export from the script and mention that the script expects that the GOROOT is exported?
___
*[`tests/e2e/setup_kind_cluster.sh` line 10 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-KRgECEdPwvKL56FE:-NY-KRgECEdPwvKL56FF:b8vrie6) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/setup_kind_cluster.sh#L10)):*
> ```Shell
> 
> # Install clusterctl on Mac
> curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/clusterctl-darwin-amd64 -o clusterctl
> ```

This makes the script tied to only mac OS. We should mention this in `doc.md` that the script only works for mac OS. Please add a comment in the script as well.
___
*[`tests/e2e/workload_cluster_test.go` line 92 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-MfDGEA_y_NNlGvU7:-NY-MfDGEA_y_NNlGvU8:br6iwak) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/workload_cluster_test.go#L92)):*
> ```Go
> 			Expect(cluster).NotTo(BeNil(), "cluster is nil")
> 
> 			err = utils.WaitForClusterReady(ctx, runtimeClient, cluster)
> ```

Does this wait for cluster go to "Ready" state? If so, how will the CRS for antrea and CPI already be applied?
___
*[`tests/e2e/utils/cluster_util.go` line 32 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-NXkq0PMR5NiFPV-z:-NY-NXkq0PMR5NiFPV0-:b7g3e20) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/utils/cluster_util.go#L32)):*
> ```Go
> 	}
> 
> 	podList, err := csConfig.CoreV1().Pods("").List(ctx, metav1.ListOptions{})
> ```

does this list pods in the default namespace? if so i think there may not  be any pods in the default namespace.
___
*[`tests/e2e/utils/cluster_util.go` line 68 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-O9jR2hCI0JxnP-Ia:-NY-O9jR2hCI0JxnP-Ib:br007gc) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/utils/cluster_util.go#L68)):*
> ```Go
> 	}
> 
> 	return vcdCluster.Spec.RDEId, nil
> ```

I think maybe it is more accurate if we use RDEId from the status. You can just add a TODO to change in the future if this breaks the current tests.

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462)* status: 4 of 15 files reviewed, 12 unresolved discussions (waiting on @ymo24)

___
*[`tests/e2e/utils/k8s_util.go` line 255 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-SkeA57_4dC2qie3Y:-NY-SkeA57_4dC2qie3Z:b45slla) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/utils/k8s_util.go#L255)):*
> ```Go
> 	var immutable bool
> 	immutable = true
> 	injectedData := injectValues(data, map[string]string{
> ```

we could directly use "text/template" library which is the same library we use for generating cloud init scripts.
___
*[`tests/e2e/utils/k8s_util.go` line 357 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-QthlA5iAWxdso0pv:-NY-QthlA5iAWxdso0pw:b-wdo2wj) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/utils/k8s_util.go#L357)):*
> ```Go
> 	hundredKB := 100 * 1024
> 	cluster := &clusterv1.Cluster{}
> 	resp, err := cs.RESTClient().Get().AbsPath("/apis/cluster.x-k8s.io/v1beta1").Resource("clusters").
> ```

can we declare constants create constants for  v1beta1 and v1beta2 values ? Will help us update the tests later on when we upgrade CAPI / CAPVCD.



_Code snippet:_
```Go
CAPIObjectVersion = "v1beta1"
CAPVCDObjectVersion = "v1beta2

# following is just an example for CAPI objects
resp, err := cs.RESTClient().Get().AbsPath(fmt.Sprintf("/apis/cluster.x-k8s.io/%s", CAPIObjectVersion)).Resource("clusters") 

# following is just an example for CAPVCD objects
_, err = cs.RESTClient().
	Post().
	AbsPath(fmt.Sprintf("/apis/infrastructure.cluster.x-k8s.io/%s/namespaces/%s/vcdclusters",CAPVCDObjectVersion namespace)).
	Body(body).
	DoRaw(ctx)
```
___
*[`tests/e2e/utils/node_pool_scaling_utils.go` line 21 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-U04W18gEFH7UDM_7:-NY-U04W18gEFH7UDM_8:by3vfng) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/utils/node_pool_scaling_utils.go#L21)):*
> ```Go
> )
> 
> func ScaleNodePool(ctx context.Context, cs *kubernetes.Clientset, desiredNodePoolSize int64, yamlContent []byte) error {
> ```

where these functions already not part of common core library in CPI?
___
*[`tests/e2e/utils/node_pool_scaling_utils.go` line 138 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-UKDV4U0ZEO8DPeTS:-NY-UKDV4U0ZEO8DPeTT:b7091wm) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/utils/node_pool_scaling_utils.go#L138)):*
> ```Go
> 			}
> 
> 			if machine.Status.NodeRef == nil || machine.Status.Phase == machinePhaseProvisioning {
> ```

This function seems to only wait for Provisioned state of the cluster.

Can you please add a comment on what this function really does?

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462)* status: 4 of 15 files reviewed, 21 unresolved discussions (waiting on @Anirudh9794 and @ymo24)

___
*[`tests/e2e/doc.md` line 6 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-Ieo17sgJBJct-tsr:-NY-Ieo17sgJBJct-tss:b-9qxs66) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/doc.md#L6)):*
> ```Markdown
> 
> - Test input
>   - KubeConfigPath (absolute path to find the file)
> ```

nit: PathToKubeconfigOfManagementCluster
nit: PathToCapiYamlOfWorkloadCluster
___
*[`tests/e2e/doc.md` line 15 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-Iy1P3ZINWFDdOvl2:-NY-Iy1P3ZINWFDdOvl3:binghto) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/doc.md#L15)):*
> ```Markdown
>   - refreshToken
> 
> - Test Preflight
> ```

"Test Prerequisites" - can you move this section to the top?

Preflights has different meaning.
___
*[`tests/e2e/doc.md` line 23 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-JWZJ7gKp2H0tfStY:-NY-JWZJ7gKp2H0tfStZ:b-qovaov) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/doc.md#L23)):*
> ```Markdown
> - Test Workflow
>   - use kubeConfigPath and capiYamlPath to get kubeConfig and capiYaml.
>   - use kubeConfigPath of management to apply capiYaml.
> ```

of management cluster
___
*[`tests/e2e/e2e_suite_test.go` line 11 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-JhtQE9JPoU9d59pJ:-NY-JhtQE9JPoU9d59pK:btelofa) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/e2e_suite_test.go#L11)):*
> ```Go
> 
> var (
> 	kubeCfgPath  string
> ```

PathToMngmntClusterKubecfg
PathToWorkloadClusterCapiYaml
___
*[`tests/e2e/e2e_suite_test.go` line 33 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-K6ta5WiZvOwClIUq:-NY-K6ta5WiZvOwClIUr:b-oa7fef) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/e2e_suite_test.go#L33)):*
> ```Go
> 	flag.StringVar(&ovdcNetwork, "ovdcNetwork", "", "Ovdc Network Name to generate client")
> 	flag.StringVar(&userName, "userName", "", "Username for login to generate client")
> 	flag.StringVar(&refreshToken, "refreshToken", "", "Refresh token of user to generate client")
> ```

Why do we need these variables? They are all part of capiYaml, right?
___
*[`tests/e2e/e2e_suite_test.go` line 49 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-KIxQ53On5wLsnVH8:-NY-KIxQ53On5wLsnVH9:bwo3xwz) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/e2e_suite_test.go#L49)):*
> ```Go
> })
> 
> func TestCSIAutomation(t *testing.T) {
> ```

TestCAPVCDAutomation
___
*[`tests/e2e/setup_kind_cluster.sh` line 10 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-KO8T41ttpXDpvZ6_:-NY-KO8T41ttpXDpvZ6a:b-aum1t2) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/setup_kind_cluster.sh#L10)):*
> ```Shell
> 
> # Install clusterctl on Mac
> curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/clusterctl-darwin-amd64 -o clusterctl
> ```

Update this to 1.1.3 to 1.4 and the relevant Kind
Let us recommend the latest
___
*[`tests/e2e/workload_cluster_test.go` line 21 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-Lykq3IrebdwR_BPs:-NY-Lykq3IrebdwR_BPt:b5p9tp4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/workload_cluster_test.go#L21)):*
> ```Go
> )
> 
> var _ = Describe("Workload Cluster CRUD based the completed management Cluster", func() {
> ```

"Workload Cluster Life cycle management". You can remove "based the completed management cluster"
___
*[`tests/e2e/workload_cluster_test.go` line 22 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-Wuji3ztZShmjR5rL:-NY-Wuji3ztZShmjR5rM:b6cu1jj) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/workload_cluster_test.go#L22)):*
> ```Go
> 
> var _ = Describe("Workload Cluster CRUD based the completed management Cluster", func() {
> 	When("create, resize and delete the workload cluster", func() {
> ```

Spec tree organization can be improved.

Currently, it is like below, can you make it look like the latter?



_Code snippet (i):_
```Go
Describe (cluster LCM)
  When (create LCM) // This container node doesn't seem to add any value
     It (clusterLCM)
       By
       By
       By
  
```



_Code snippet (ii):_
```Go
Describe (clusterLCM)..
   //setup
   It(should create cluster)..
      By..
      By..
   It(should resize cluster)..
      By..
   It(should delete cluster)..
  
```

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462)* status: 4 of 15 files reviewed, 22 unresolved discussions (waiting on @Anirudh9794 and @ymo24)

___
*[`tests/e2e/utils/k8s_util.go` line 49 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-p4VG5YJlBzAlj-rb:-NY-p4VG5YJlBzAlj-rc:bkr9cj6) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/utils/k8s_util.go#L49)):*
> ```Go
> 
> 		switch kind {
> 		case "Cluster":
> ```

Yan, As discussed can you add a detailed comment on how controller runtime client can be used to apply unstructured objects directly here.

Also about how structured object can be used to patch using patchHelper like how we do in the VCDCluster_controller.go
___
*[`tests/e2e/utils/k8s_util.go` line 357 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-QthlA5iAWxdso0pv:-NY-_6_rCKugLI0bH1WL:b9gmf35) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/utils/k8s_util.go#L357)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

can we declare constants create constants for  v1beta1 and v1beta2 values ? Will help us update the tests later on when we upgrade CAPI / CAPVCD.
</blockquote></details>

+1 

We don't want these tests to be broken when we update CAPI API version in the future.

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462)* status: 4 of 15 files reviewed, 22 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`tests/e2e/e2e_suite_test.go` line 49 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-KIxQ53On5wLsnVH8:-NY0CzR225lye7oEf3lD:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/e2e_suite_test.go#L49)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

TestCAPVCDAutomation
</blockquote></details>

Done.
___
*[`tests/e2e/utils/cluster_util.go` line 32 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-NXkq0PMR5NiFPV-z:-NY0DDyzA5w0MuPR5SJ3:b-fg7v61) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/utils/cluster_util.go#L32)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

does this list pods in the default namespace? if so i think there may not  be any pods in the default namespace.
</blockquote></details>

This operation lists all the pods. You can take it as the following operation



_Code snippet:_
```Go
Kubectl get po -A
```

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462)* status: 0 of 17 files reviewed, 21 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`tests/e2e/doc.md` line 15 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-Iy1P3ZINWFDdOvl2:-NYyyAEZ0CE60KbB88SU:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/doc.md#L15)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

"Test Prerequisites" - can you move this section to the top?

Preflights has different meaning.
</blockquote></details>

Done.
___
*[`tests/e2e/doc.md` line 23 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-JWZJ7gKp2H0tfStY:-NYyyGJcCJqG7XV3UhRd:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/doc.md#L23)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

of management cluster
</blockquote></details>

Done.
___
*[`tests/e2e/e2e_suite_test.go` line 11 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-JhtQE9JPoU9d59pJ:-NY7X-Ds149v8Fy5CLtz:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/e2e_suite_test.go#L11)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

PathToMngmntClusterKubecfg
PathToWorkloadClusterCapiYaml
</blockquote></details>

Done.
___
*[`tests/e2e/e2e_suite_test.go` line 33 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-K6ta5WiZvOwClIUq:-NYOKQZ2EG7bOK-TXshg:b-hbpbci) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/e2e_suite_test.go#L33)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Why do we need these variables? They are all part of capiYaml, right?
</blockquote></details>

Already removed them. Thanks, Sahithi
___
*[`tests/e2e/setup_kind_cluster.sh` line 3 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-JlYv4uwGgpK49Br9:-NYOKOeC9oBJD1OZxIRL:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/setup_kind_cluster.sh#L3)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I don't think we should be setting GOROOT here. This should be a configured before the script is executed.
Can you remove export from the script and mention that the script expects that the GOROOT is exported?
</blockquote></details>

Done.
___
*[`tests/e2e/setup_kind_cluster.sh` line 10 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-KO8T41ttpXDpvZ6_:-NYOK2imARAUAF5IAXY6:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/setup_kind_cluster.sh#L10)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Update this to 1.1.3 to 1.4 and the relevant Kind
Let us recommend the latest
</blockquote></details>

Done.
___
*[`tests/e2e/setup_kind_cluster.sh` line 10 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-KRgECEdPwvKL56FE:-NYOK3Zv9jEdz9mhy69d:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/setup_kind_cluster.sh#L10)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

This makes the script tied to only mac OS. We should mention this in `doc.md` that the script only works for mac OS. Please add a comment in the script as well.
</blockquote></details>

Done.
___
*[`tests/e2e/workload_cluster_test.go` line 21 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-Lykq3IrebdwR_BPs:-NY7NjltExrAP8ZZaRyv:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/workload_cluster_test.go#L21)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

"Workload Cluster Life cycle management". You can remove "based the completed management cluster"
</blockquote></details>

Done.
___
*[`tests/e2e/workload_cluster_test.go` line 22 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-Wuji3ztZShmjR5rL:-NY7NinKBb5YF9PMXK3s:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/workload_cluster_test.go#L22)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Spec tree organization can be improved.

Currently, it is like below, can you make it look like the latter?

</blockquote></details>

Done.
___
*[`tests/e2e/workload_cluster_test.go` line 92 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-MfDGEA_y_NNlGvU7:-NYxyz7f1-X7SDWw7XKG:b-v75jm6) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/workload_cluster_test.go#L92)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Does this wait for cluster go to "Ready" state? If so, how will the CRS for antrea and CPI already be applied?
</blockquote></details>

Plan:
1. WaitForClusterProvisioned(): 
2. Apply CRS for CSI/CPI
3. WaitforMachinesRunning()
___
*[`tests/e2e/utils/cluster_util.go` line 68 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-O9jR2hCI0JxnP-Ia:-NY7X1uJ6AWfRiMuTCgG:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/utils/cluster_util.go#L68)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think maybe it is more accurate if we use RDEId from the status. You can just add a TODO to change in the future if this breaks the current tests.
</blockquote></details>

Done.
___
*[`tests/e2e/utils/k8s_util.go` line 49 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-p4VG5YJlBzAlj-rb:-NYyyHvcBlujYD792cUR:b344vm7) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/utils/k8s_util.go#L49)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Yan, As discussed can you add a detailed comment on how controller runtime client can be used to apply unstructured objects directly here.

Also about how structured object can be used to patch using patchHelper like how we do in the VCDCluster_controller.go
</blockquote></details>

It will be addressed in CAFV-285.
___
*[`tests/e2e/utils/k8s_util.go` line 255 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-SkeA57_4dC2qie3Y:-NYyykJM1iuoiH7-5inh:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/utils/k8s_util.go#L255)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

we could directly use "text/template" library which is the same library we use for generating cloud init scripts.
</blockquote></details>

Done.
___
*[`tests/e2e/utils/k8s_util.go` line 357 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-QthlA5iAWxdso0pv:-NY7X3s451OGMQ4Pr5TV:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/utils/k8s_util.go#L357)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

+1 

We don't want these tests to be broken when we update CAPI API version in the future.
</blockquote></details>

Done.
___
*[`tests/e2e/utils/node_pool_scaling_utils.go` line 21 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-U04W18gEFH7UDM_7:-NYyymA9-qISqYr3I0BH:b-xjgwto) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/utils/node_pool_scaling_utils.go#L21)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

where these functions already not part of common core library in CPI?
</blockquote></details>

Created a new ticket to do investigation post GA
___
*[`tests/e2e/utils/node_pool_scaling_utils.go` line 138 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/462#-NY-UKDV4U0ZEO8DPeTS:-NYyyqTa3FdMFZobcs-t:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2894b3654b3991f1006a2b12a6066abb51ac4c61/tests/e2e/utils/node_pool_scaling_utils.go#L138)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

This function seems to only wait for Provisioned state of the cluster.

Can you please add a comment on what this function really does?
</blockquote></details>

Done.

**Pull request closed without merging**
