### PR TITLE
VCDA-3502: Add parentUid and useAsManagementCluster support - vkp branch

### PR DESCRIPTION
**Pull request by lzichong**
* Added optional `ParentUID`, `UseAsManagementCluster` in VCDClusterSpec
* Regenerated `zz_generated.conversion.go` from conversion gen tool
* Added fields in `reconcileRDE` to update RDE Status to be same with cluster spec
* Testing Done:
  - Built image from vkp branch -> apply capi yaml on existing cluster -> used Postman for RDE details -> update values and reapply capi yaml -> observed new values in Postman after some time for it to update where `userIntendsToUseItAsAManagementCluster` is inside of RDE.Status.CAPVCD 
  - `parentUid` is in RDE.Status

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/102)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/102)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @lzichong)

___
*[`controllers/vcdcluster_controller.go` line 405 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/102#-N0X582BBgHiHL2TX0pl:-N0X582C27JEYcxG5il-:bad6cpz) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/77d28a154fbb5e583d5d6bf9fa6706cbae1198c3/controllers/vcdcluster_controller.go#L405)):*
> ```Go
> 	}
> 
> 	if capvcdEntity.Status.CAPVCDStatus.UsedAsManagementCluster != vcdCluster.Status.UseAsManagementCluster {
> ```

Can we rename this property to "capvcdEntity.Status.CAPVCDStatus.UsedAsManagementCluster" to UseAsManagementCluster to keep it consistent .

This entails RDE schema changes.

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/102)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 405 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/102#-N0X582BBgHiHL2TX0pl:-N0XQC2a-xTCD-9qWzJB:b-iuy53l) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/77d28a154fbb5e583d5d6bf9fa6706cbae1198c3/controllers/vcdcluster_controller.go#L405)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can we rename this property to "capvcdEntity.Status.CAPVCDStatus.UsedAsManagementCluster" to UseAsManagementCluster to keep it consistent .

This entails RDE schema changes.
</blockquote></details>

Updated `UsedAsManagementCluster` to `UseAsManagementCluster`, thanks!

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/102)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @lzichong, and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 406 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/102#-N0XZZy5EnOmmORAG9-J:-N0XZZy5EnOmmORAG9-K:btydo5s) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a9d04400a193fc3edfaaf551b2984f2a81224bdf/controllers/vcdcluster_controller.go#L406)):*
> ```Go
> 
> 	if capvcdEntity.Status.CAPVCDStatus.UseAsManagementCluster != vcdCluster.Status.UseAsManagementCluster {
> 		updatePatch["Status.CAPVCDStatus.UsedAsManagementCluster"] = vcdCluster.Status.UseAsManagementCluster
> ```

updatePatch key needs to be changed to Status.CAPVCDStatus.UseAsManagementCluster
___
*[`pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go` line 86 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/102#-N0XZoHcErF1Qu4w2U0T:-N0XZoHcErF1Qu4w2U0U:bmx9lhw) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a9d04400a193fc3edfaaf551b2984f2a81224bdf/pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go#L86)):*
> ```Go
> 	NodeStatus             map[string]string `json:"nodeStatus,omitempty"`
> 	CapvcdVersion          string            `json:"capvcdVersion,omitempty"`
> 	UseAsManagementCluster bool              `json:"userIntendsToUseItAsAManagementCluster,omitempty"`
> ```

Update WIP_schema_1_1_0.json file as well with the same.

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/102)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 406 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/102#-N0XZZy5EnOmmORAG9-J:-N0Xs-Sj3qFXJZzDPXB8:bf0vvji) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a9d04400a193fc3edfaaf551b2984f2a81224bdf/controllers/vcdcluster_controller.go#L406)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

updatePatch key needs to be changed to Status.CAPVCDStatus.UseAsManagementCluster
</blockquote></details>

Updated, thanks for catching this!
___
*[`pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go` line 86 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/102#-N0XZoHcErF1Qu4w2U0T:-N0XruAT59nGUyItSR3-:bf89o79) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a9d04400a193fc3edfaaf551b2984f2a81224bdf/pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go#L86)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Update WIP_schema_1_1_0.json file as well with the same.
</blockquote></details>

Updated WIP schema with useAsManagementCluster

**Review by Anirudh9794 — APPROVED** [review]
please run `make release-manifests` to update the infrastructure-components.yaml as well.

> Reviewed 2 of 4 files at r1, 4 of 6 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/102#-:-N0gQxlv3vjP3GXmTKg2:b-c4lgoa)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

**Review by sahithi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/102#-:-N0gTJBw5UcIEeIOL1O1:bg7igkv)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

**Pull request merged**
