### PR TITLE
[VCDA-3660] Dockerize rdeProjector and create a deployment manifest

### PR DESCRIPTION
**Pull request by ymo24**
* Rewrite Dockerfile and make it consistent with other VCD project repositories.
* Add `make build-within-docker` and `make rde-projector` in Makefile and update `manifests deployment`.
* Add necessary changes on vendor file and config/manager/manager.yaml.
* Testing done: creating the pod successfully and red-projector could retrieve Capi Yaml.

This PR is only created for review. It would be merged to new gitlab repo finally.
Signed-off-by: ymo24 <ymo@vmware.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/146)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
LGTM

**Review by arunmk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/146)* status: 5 of 9 files reviewed, 6 unresolved discussions (waiting on @sahithi and @ymo24)

___
*[`rdeprojector/Dockerfile` line 1 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/146#-N2SWwBmD68L0Du7cXOs:-N2SWwBmD68L0Du7cXOt:bu09xhs) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2d6ce2c9c235d0354dac6ca142978626492f1c6e/rdeprojector/Dockerfile#L1)):*
> ```Dockerfile
> FROM golang:1.16 as builder
> ```

This should be 1.17
___
*[`rdeprojector/Dockerfile` line 12 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/146#-N2SWSnX4E_PZdUAikcC:-N2SWSnX4E_PZdUAikcD:b-vmx1k5) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2d6ce2c9c235d0354dac6ca142978626492f1c6e/rdeprojector/Dockerfile#L12)):*
> ```Dockerfile
> WORKDIR /go/src/github.com/vmware/rdeprojector
> 
> ENV	CGO_ENABLED=0
> ```

space better? there is only one added in any case
___
*[`rdeprojector/go.mod` line 3 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/146#-N2SX9JR3UcXssiqhEUE:-N2SX9JR3UcXssiqhEUF:b6v5llv) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2d6ce2c9c235d0354dac6ca142978626492f1c6e/rdeprojector/go.mod#L3)):*
> ```XML
> module github.com/vmware/cluster-api-provider-cloud-director
> 
> go 1.16
> ```

This also should become 1.17.
___
*[`rdeprojector/go.mod` line 8 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/146#-N2SXEHG1CrwEkkyZ9fj:-N2SXEHG1CrwEkkyZ9fk:basg7l1) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2d6ce2c9c235d0354dac6ca142978626492f1c6e/rdeprojector/go.mod#L8)):*
> ```XML
> 	github.com/onsi/ginkgo v1.16.4
> 	github.com/onsi/gomega v1.15.0
> 	github.com/pkg/errors v0.9.1
> ```

Why did this need to come up? Can u run go mod tidy to check? (In any case making it go 1.17 will change a bunch of things here)
___
*[`rdeprojector/api/v1alpha1/zz_generated.deepcopy.go` line 1 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/146#-N2SXUux1pbW9yD3gHNG:-N2SXUux1pbW9yD3gHNH:becmgau) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2d6ce2c9c235d0354dac6ca142978626492f1c6e/rdeprojector/api/v1alpha1/zz_generated.deepcopy.go#L1)):*
> ```Go
> //go:build !ignore_autogenerated
> ```

This I think will come back due to go 1.17. Better to run a make generate etc (like the make vendor in other code repos) once the update to go 1.17 is done
___
*[`rdeprojector/config/rbac/role.yaml` line 1 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/146#-N2SWkazBwk-rwCaXECY:-N2SWkazBwk-rwCaXECZ:b-hv8w7u) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2d6ce2c9c235d0354dac6ca142978626492f1c6e/rdeprojector/config/rbac/role.yaml#L1)):*
> ```YAML
> 
> ```

This should have been auto-generated, correct?

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/146)* status: 5 of 9 files reviewed, 6 unresolved discussions (waiting on @arunmk, @sahithi, and @ymo24)

___
*[`rdeprojector/config/rbac/role.yaml` line 1 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/146#-N2SWkazBwk-rwCaXECY:-N2SZTw02kV9oF7RbpMq:b-50z0y4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2d6ce2c9c235d0354dac6ca142978626492f1c6e/rdeprojector/config/rbac/role.yaml#L1)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This should have been auto-generated, correct?
</blockquote></details>

Yes. But we don't have one in repo now. That's why I uploaded this automated file.

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/146)* status: 3 of 70 files reviewed, 6 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[`rdeprojector/go.mod` line 3 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/146#-N2SX9JR3UcXssiqhEUE:-N2XfmqNB9WiGPqdK92Y:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/2d6ce2c9c235d0354dac6ca142978626492f1c6e/rdeprojector/go.mod#L3)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This also should become 1.17.
</blockquote></details>

Done.

**Pull request closed without merging**
