### PR TITLE
[VCDA-3254] checking for bootstrap success and logging cloud init output

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy7 <66969084+ltimothy7@users.noreply.github.com>

TODO: testing

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/40)

### CODE REVIEW

**Review by sahithi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/40)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[controllers/cluster_scripts/cloud_init_control_plane.yaml, line 30 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/40#-MuCdIJ_5_o3tsZS8W73:-MuCdIJ_5_o3tsZS8W74:bai7h2d) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/7ffe262106230c1bc29917068bcc57f7afed04a6/controllers/cluster_scripts/cloud_init_control_plane.yaml#L30)):*
> ```YAML
> 
>        cloud_init_output=""
>        if [[ -f /var/log/cloud-init-output.log ]]
> ```

When is this file actually created and updated - while the script is being executed (or) once it is fully completed?
Have you tested this out?

**Comment by arunmk** [comment]
___
*[controllers/cluster_scripts/cloud_init_control_plane.yaml, line 30 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/40#-MuCdIJ_5_o3tsZS8W73:-MuHoufcA44uHb6yYMZ-:bmm5yjn) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/7ffe262106230c1bc29917068bcc57f7afed04a6/controllers/cluster_scripts/cloud_init_control_plane.yaml#L30)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

When is this file actually created and updated - while the script is being executed (or) once it is fully completed?
Have you tested this out?
</blockquote></details>

Per my earlier understanding, this file will be there but the contents may not yet be flushed out. As in, we will see old details and not our script details in the file. We need to test it out.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/40)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[controllers/cluster_scripts/cloud_init_control_plane.yaml, line 30 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/40#-MuCdIJ_5_o3tsZS8W73:-MunJL_7-rlozOCnLi6p:b4tihza) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/7ffe262106230c1bc29917068bcc57f7afed04a6/controllers/cluster_scripts/cloud_init_control_plane.yaml#L30)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Per my earlier understanding, this file will be there but the contents may not yet be flushed out. As in, we will see old details and not our script details in the file. We need to test it out.
</blockquote></details>

I have tested this. If the file is present, we will store its output; otherwise, we will output an empty string value. With this design, we don't need to know when the script is fully complete since we will just see the current details of the file

**Review by ltimothy7 — COMMENTED** [review]
> [VCDA-3254] checking for bootstrap success and logging cloud init output
Testing: successful cluster creation and failure on control plane

TODO: failure on worker node

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/40#-:-MunJdSpAbeaPGbdmdXE:b-f1pyyr)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @sahithi)

**Comment by Anirudh9794** [comment]
___
*[controllers/cluster_scripts/cloud_init_node.yaml, line 45 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/40#-MuqkD2h4ft9TBzSZtBe:-MuqkD2h4ft9TBzSZtBf:b68yqkl) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/07a96887f751c06f17a9a0199f2e8da2b492c5f7/controllers/cluster_scripts/cloud_init_node.yaml#L45)):*
> ```YAML
>       if [[ ! -f /run/cluster-api/bootstrap-success.complete ]]
>       then
>         echo "file /run/cluster-api/bootstrap-success.complete not found" &>> /var/log/capvcd/customization/error.log
> ```

Is it guaranteed that this path will be present?

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: with a small question

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/40#-:-MuqkQJR2UdzMHJjeW05:bui71c9)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ltimothy7 and @sahithi)

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/40)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[controllers/cluster_scripts/cloud_init_node.yaml, line 45 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/40#-MuqkD2h4ft9TBzSZtBe:-Muqv0Be5MCg7CNoFNaE:b-ohxyax) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/07a96887f751c06f17a9a0199f2e8da2b492c5f7/controllers/cluster_scripts/cloud_init_node.yaml#L45)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Is it guaranteed that this path will be present?
</blockquote></details>

&>> will create the file is it is not present

**Review by ltimothy7 — COMMENTED** [review]
Testing complete for failure on cp and worker nodes

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/40#-:-Muqv54H0__qwLWXzy6P:b-ay96ev)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

**Review by sahithi — APPROVED** [review]
:lgtm: with questions

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/40#-:-Murfu76AOpe8MfW-dGu:b-t9t8bi)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sahithi)

___
*[controllers/cluster_scripts/cloud_init_node.yaml, line 48 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/40#-MurfRq4DxOKpAWf1mLC:-MurfRq5EREmhT5bweJi:b-m2ilct) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/5fd876b127d495787fb95ba1a27f9d1bbc4c0298/controllers/cluster_scripts/cloud_init_node.yaml#L48)):*
> ```YAML
>         exit 1
>       fi
>       export KUBECONFIG=/etc/kubernetes/kubelet.conf
> ```

What IP will it hold if it is a multimaster cluster? Loadbalancer IP (or) its own master node IP?

In the case of worker node join, what IP will it hold?

**Comment by arunmk** [comment]
___
*[controllers/cluster_scripts/cloud_init_node.yaml, line 48 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/40#-MurfRq4DxOKpAWf1mLC:-MuvZ5gj-AU2vSLGcoRy:b-gtq4e6) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/5fd876b127d495787fb95ba1a27f9d1bbc4c0298/controllers/cluster_scripts/cloud_init_node.yaml#L48)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

What IP will it hold if it is a multimaster cluster? Loadbalancer IP (or) its own master node IP?

In the case of worker node join, what IP will it hold?
</blockquote></details>

LoadBalancerIP will be the IP for a single and multu-master cluster.

**Pull request merged**
