### PR TITLE
[VCDA-4379] Add tkgVersion and kubernetes version as part of capvcd.upgrade in RDE

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

## Description
Please provide a brief description of the changes proposed in this Pull Request

- Change schema and controller code to add entity.status.upgrade containing current and previous kubernetes versions and tkg versions

## Checklist
- [x] tested locally
- [x] updated any relevant dependencies
- [x] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253)

### CODE REVIEW

**Review by lzichong — APPROVED** [review]
:lgtm:! Will update CAPVCD Schema in confluence after merge

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-:-NBtNdGhBj6EEdoqDkOB:b-cux7va)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Anirudh9794)

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @Anirudh9794)

___
*[`controllers/capi_objects_utils.go` line 444 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBwmIZqBTNllm08dj-R:-NBwmIZqBTNllm08dj-S:b-ilfl36) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/capi_objects_utils.go#L444)):*
> ```Go
> }
> 
> func isControlPlaneReady(kcp *kcpv1.KubeadmControlPlane) bool {
> ```

isControlPlaneReady - can be interpreted differently - whether API server is accessible or not. Let us be very specific to avoid confusion reading the code in the future.

Consider renaming it to exactly what the method does - hasKcpReconciledToDesiredK8Version() 
___
*[`controllers/vcdcluster_controller.go` line 414 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBwwO2W7NZ2Dk5-C6eb:-NBwwO2W7NZ2Dk5-C6ec:b5xt99r) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/vcdcluster_controller.go#L414)):*
> ```Go
> 			}
> 		} else {
> 			if !isControlPlaneReady(kcpObj) && kcpObj.Spec.Version != capvcdStatus.Upgrade.Current.K8sVersion {
> ```

why do we need !(isControlPlaneReadt(kcpObj) here?
___
*[`controllers/vcdcluster_controller.go` line 421 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBwwSeGAjBVvLB2Rlku:-NBwwSeGAjBVvLB2Rlkv:bgevgtg) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/vcdcluster_controller.go#L421)):*
> ```Go
> 					TkgVersion: tkgVersion,
> 				}
> 				upgradeObject.Ready = false
> ```

shouldn't this be isControlPlaneReady(kcpObj)
___
*[`schema/schema_1_1_0.json` line 193 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBwx3uI1wwwbuYMURJm:-NBwx3uI1wwwbuYMURJn:b-wghafm) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/schema/schema_1_1_0.json#L193)):*
> ```JSON
>             },
>             "upgrade": {
>               "type": "object",
> ```

We must begin to add "description". This request came from Aashima.

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @Anirudh9794)

___
*[`controllers/vcdcluster_controller.go` line 402 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBwxOuS8qw6-21Y8FPA:-NBwxOuS8qw6-21Y8FPB:b62zoxj) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/vcdcluster_controller.go#L402)):*
> ```Go
> 	}
> 
> 	upgradeObject := capvcdStatus.Upgrade
> ```

Is below logic getting executed for every reconcileRDE() - for every reconcileNormal() of vcdCluster?

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @Anirudh9794)

___
*[`controllers/capi_objects_utils.go` line 444 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBwmIZqBTNllm08dj-R:-NBwyAffA7N6DsSJ_W48:b-eeu28p) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/capi_objects_utils.go#L444)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

isControlPlaneReady - can be interpreted differently - whether API server is accessible or not. Let us be very specific to avoid confusion reading the code in the future.

Consider renaming it to exactly what the method does - hasKcpReconciledToDesiredK8Version() 
</blockquote></details>

Add a docstring to this method. why it is needed?

**Review by arunmk — APPROVED** [review]
One important fix needed. Else :lgtm: 

> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-:-NBwyaac9EMYDVvO8Gx-:bkvy2m4)* status: all files reviewed, 7 unresolved discussions (waiting on @Anirudh9794)

___
*[`controllers/capi_objects_utils.go` line 445 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBwurTY38R3lT40KHQW:-NBwurTY38R3lT40KHQX:b-lua1o5) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/capi_objects_utils.go#L445)):*
> ```Go
> 
> func isControlPlaneReady(kcp *kcpv1.KubeadmControlPlane) bool {
> 	return kcp != nil && kcp.Status.Ready &&
> ```

I assume `kcp.Status` is not a pointer
___
*[`controllers/vcdcluster_controller.go` line 245 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBwxkilAt-1cGGNYhRs:-NBwxkimBvdpQ5wlZH8Q:b-4egvfs) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/vcdcluster_controller.go#L245)):*
> ```Go
> 	for _, kcp := range kcpList.Items {
> 		kubernetesVersion = kcp.Spec.Version
> 		ready = isControlPlaneReady(&kcp)
> ```

We need to make ready `false` if there is one item false
So:
```
ready := true
for _, kcp := range kcpList.Items {
    if ready {
        ready = isControlPlaneReady(&kcp)
    }
    kubernetesVersion := kcp.Spec.Version // not sure what would be the right version if `ready == false`
}
```

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253)* status: all files reviewed, 8 unresolved discussions (waiting on @Anirudh9794)

___
*[`controllers/vcdcluster_controller.go` line 422 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBwzfnLExe_DXR9XG7k:-NBwzfnLExe_DXR9XG7l:ba097w7) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/vcdcluster_controller.go#L422)):*
> ```Go
> 				}
> 				upgradeObject.Ready = false
> 			}
> ```

upgradeObject.Ready = isControlPlaneReady() - pull it out of if block.

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253)* status: all files reviewed, 9 unresolved discussions (waiting on @Anirudh9794)

___
*[`controllers/vcdcluster_controller.go` line 426 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBx-A27DsZeSR-UTAoW:-NBx-6uS7m-e7i4bjZd4:bvmxlfw) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/vcdcluster_controller.go#L426)):*
> ```Go
> 	}
> 
> 	klog.Infof("upgradeObject prev: [%#v]", capvcdStatus.Upgrade)
> ```

Increase the verbosity level and please also mention RDE-ID and clustername for every log statement.
By the way, why are we using klog? Use log.Info()

**Comment by Anirudh9794** [comment]
*[`controllers/capi_objects_utils.go` line 445 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBwurTY38R3lT40KHQW:-NBx-UgC9nOKVXE54XM-:bs1l093) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/capi_objects_utils.go#L445)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

I assume `kcp.Status` is not a pointer
</blockquote></details>

kcp.status.version is a pointer. So I had to check for nil before de-referencing

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253)* status: all files reviewed, 9 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[`controllers/capi_objects_utils.go` line 444 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBwmIZqBTNllm08dj-R:-NBx2g3MD8YWxrbLZWG8:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/capi_objects_utils.go#L444)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Add a docstring to this method. why it is needed?
</blockquote></details>

Done.
___
*[`controllers/vcdcluster_controller.go` line 245 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBwxkilAt-1cGGNYhRs:-NBxAAPLDQnIoAhg9FsW:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/vcdcluster_controller.go#L245)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

We need to make ready `false` if there is one item false
So:
```
ready := true
for _, kcp := range kcpList.Items {
    if ready {
        ready = isControlPlaneReady(&kcp)
    }
    kubernetesVersion := kcp.Spec.Version // not sure what would be the right version if `ready == false`
}
```
</blockquote></details>

Done.
___
*[`controllers/vcdcluster_controller.go` line 402 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBwxOuS8qw6-21Y8FPA:-NBxABc5EGMlLvoJBiKN:b2nign6) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/vcdcluster_controller.go#L402)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Is below logic getting executed for every reconcileRDE() - for every reconcileNormal() of vcdCluster?
</blockquote></details>

yes
___
*[`controllers/vcdcluster_controller.go` line 414 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBwwO2W7NZ2Dk5-C6eb:-NBxAGCZB0K0WbOaku7O:bpj1idp) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/vcdcluster_controller.go#L414)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

why do we need !(isControlPlaneReadt(kcpObj) here?
</blockquote></details>

Yes, I also feel it is not needed. I have removed that check
___
*[`controllers/vcdcluster_controller.go` line 421 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBwwSeGAjBVvLB2Rlku:-NBxAKdV3KV0WZmw4tyA:bk71ptf) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/vcdcluster_controller.go#L421)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

shouldn't this be isControlPlaneReady(kcpObj)
</blockquote></details>

Updated the RHS to isControlPlaneReady(kcpObj)
___
*[`controllers/vcdcluster_controller.go` line 422 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBwzfnLExe_DXR9XG7k:-NBxARCa2AB2QG_OIR0f:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/vcdcluster_controller.go#L422)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

upgradeObject.Ready = isControlPlaneReady() - pull it out of if block.
</blockquote></details>

Done.
___
*[`controllers/vcdcluster_controller.go` line 426 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBx-A27DsZeSR-UTAoW:-NBxAWNX3qYipU55jM1e:bbvj68q) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/vcdcluster_controller.go#L426)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Increase the verbosity level and please also mention RDE-ID and clustername for every log statement.
By the way, why are we using klog? Use log.Info()
</blockquote></details>

Sorry, I added these logs for debugging. I will remove these and add a log.Info()

**Review by sahithi — APPROVED** [review]
2 more minor comments to be addressed :lgtm: 
log statement and description in the schema

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-:-NBxMRQXCIQ-izK-IuSr:brctox9)* status: 4 of 6 files reviewed, 9 unresolved discussions (waiting on @Anirudh9794, @arunmk, @lzichong, and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 426 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253#-NBx-A27DsZeSR-UTAoW:-NBxMIL78234JqWPK7ne:b-htt4jh) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/15b19f30bbbb618450fd67b179a2d739c659bc30/controllers/vcdcluster_controller.go#L426)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Sorry, I added these logs for debugging. I will remove these and add a log.Info()
</blockquote></details>

updated -> current
log.Info("upgrade section of the RDE", "previous", capvcdStatus.Upgrade, "current", upgradeObject)



_Code quote:_
```Go
log.Info("upgrade section of the RDE", "previous", capvcdStatus.Upgrade, "updated", upgradeObject)
```

**Pull request merged**
