### PR TITLE
disable host path provisioner for clusters

### PR DESCRIPTION
**Pull request by viveksyngh**
- disable host path provisioned for cluster templates

## Description
Please provide a brief description of the changes proposed in this Pull Request

- 

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/502)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]

**Comment by Anirudh9794** [comment]
hi @viveksyngh ,
can you please make similar changes for k8s 1.24 and 1.25 templates - cluster-template-v1.25.7.yaml , cluster-template-v1.25.7-crs.yaml , cluster-template-v1.24.10.yaml and cluster-template-v1.24.10-crs.yaml ?

Thanks,
Aniruddha

**Review by arunmk — APPROVED** [review]
LGTM with changes requested by Aniruddha

**Comment by Anirudh9794** [comment]
Hi @viveksyngh ,
Please let me know when the requested changes are done so that the changes can be merged.

Thanks,
Aniruddha

**Comment by viveksyngh** [comment]
Updated for new templates.

**Pull request merged**
