### PR TITLE
CAFV-281: Use same version methodology as other components

### PR DESCRIPTION
**Pull request by arunmk**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- Change version to be in line with other components, so that the git-sha is also embedded in it

## Checklist
- [X] tested locally
- [X] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [X] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/465)

### CODE REVIEW

**Review by abaruni — APPROVED** [review]
LGTM

**Review by lzichong — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/465)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk and @rocknes)

___
*[`release/version.go` line 9 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/465#-NY4dpnu7c9qbrE2HHm5:-NY4dpnu7c9qbrE2HHm6:b-ns4glt) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0f1364768b18b106b22f00c4c52267612b165a2c/release/version.go#L9)):*
> ```Go
> 
> // Version is to be set in the build process. Empty version will cause a panic.
> var Version string = ""
> ```

Do we need a `//go:embed` here?

**Comment by arunmk** [comment]
*[`release/version.go` line 9 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/465#-NY4dpnu7c9qbrE2HHm5:-NY4hh-W5TKpNdK-1h4u:b187r6d) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0f1364768b18b106b22f00c4c52267612b165a2c/release/version.go#L9)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Do we need a `//go:embed` here?
</blockquote></details>

No, and that was the reason for the earlier issue. The go-embed gets things from a file and is static (will not add the git-sha), while we do need it coming in from the build command itself.

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/465#-:-NY4hyWOEW3wbyk4mWdM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lzichong)

**Pull request merged**
