### PR TITLE
[VCDA-4376] Ensure all reconciliation errors are being added to the errorSet of CAPVCD

### PR DESCRIPTION
**Pull request by ymo24**
Signed-off-by: ymo24 <ymo@vmware.com>

## Description
Please provide a brief description of the changes proposed in this Pull Request
Ensure all reconciliation errors are being added to the errorSet of CAPVCD
- 

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263)

### CODE REVIEW

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @arunmk, @sahithi, and @ymo24)

___
*[`controllers/vcdcluster_controller.go` line 628 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NCXeP4xER10tga1RQVL:-NCXeP4xER10tga1RQVM:b-8x5fn5) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/961414ee89ff7bf3969a83f27ddfc2aa5abd6e50/controllers/vcdcluster_controller.go#L628)):*
> ```Go
> 
> 	// General note on RDE operations, always ensure CAPVCD cluster reconciliation progress
> 	infraID := vcdCluster.Status.InfraId
> ```

I think this line should be moved to after the comment in the next line.
___
*[`controllers/vcdcluster_controller.go` line 919 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NCXfbXt3HiQz31bP1Ix:-NCXfbXt3HiQz31bP1Iy:b-70sixl) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/961414ee89ff7bf3969a83f27ddfc2aa5abd6e50/controllers/vcdcluster_controller.go#L919)):*
> ```Go
> 		return ctrl.Result{}, errors.Wrapf(err, "failed to add load balancer resources to RDE [%s]", infraID)
> 	}
> 	if len(resourcesAllocated.Get(vcdsdk.VcdResourceVirtualService)) > 0 {
> ```

Should there be a removal of `capisdk.ResourceUpdateError` before this line?
___
*[`controllers/vcdcluster_controller.go` line 1092 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NCXg3SJ-BrATtfVYPlH:-NCXg3SJ-BrATtfVYPlI:b-jyvam4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/961414ee89ff7bf3969a83f27ddfc2aa5abd6e50/controllers/vcdcluster_controller.go#L1092)):*
> ```Go
> 		return ctrl.Result{}, errors.Wrapf(err, "failed to create gateway manager using the workload client to reconcile cluster [%s]", vcdCluster.Name)
> 	}
> ```

Should there be a removal of error here ?
___
*[`controllers/vcdmachine_controller.go` line 682 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NCXgq3W4wsmlCOgIZoN:-NCXgq3W4wsmlCOgIZoO:bl72dda) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/961414ee89ff7bf3969a83f27ddfc2aa5abd6e50/controllers/vcdmachine_controller.go#L682)):*
> ```Go
> 		}
> 	}
> ```

should we remove capisdk.InfraVMCreationError here?
___
*[`controllers/vcdmachine_controller.go` line 822 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NCXh8RL4Z_FGTjIxV4i:-NCXh8RL4Z_FGTjIxV4j:b-drwbo4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/961414ee89ff7bf3969a83f27ddfc2aa5abd6e50/controllers/vcdmachine_controller.go#L822)):*
> ```Go
> 		updatedErr := capvcdRdeManager.AddToErrorSet(ctx, capisdk.PostBoostrapError, "", machine.Name, fmt.Sprintf("Unable to refresh vm: %v", err))
> 		if updatedErr != nil {
> 			log.Error(updatedErr, "failed to add InfraVMCreationError into RDE", "rdeID", vcdCluster.Status.InfraId)
> ```

The logged error should be PostBootstrapError
___
*[`controllers/vcdmachine_controller.go` line 829 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NCXhITo5RNwee5FVOSz:-NCXhITo5RNwee5FVOT-:b-drwbo4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/961414ee89ff7bf3969a83f27ddfc2aa5abd6e50/controllers/vcdmachine_controller.go#L829)):*
> ```Go
> 		updatedErr := capvcdRdeManager.AddToErrorSet(ctx, capisdk.PostBoostrapError, "", machine.Name, fmt.Sprintf("Unable to refresh vApp: %v", err))
> 		if updatedErr != nil {
> 			log.Error(updatedErr, "failed to add InfraVMCreationError into RDE", "rdeID", vcdCluster.Status.InfraId)
> ```

The logged error should be PostBootstrapError
___
*[`controllers/vcdmachine_controller.go` line 1012 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NCXhZZNBE5irkGq77fo:-NCXhZZNBE5irkGq77fp:b-dkfs06) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/961414ee89ff7bf3969a83f27ddfc2aa5abd6e50/controllers/vcdmachine_controller.go#L1012)):*
> ```Go
> 			return ctrl.Result{}, errors.Wrapf(err, "Error while deleting the machine [%s/%s]; failed to find vapp by name", vAppName, machine.Name)
> 		}
> 	}
> ```

Should `VappCreationError` be removed over here?
___
*[`controllers/vcdmachine_controller.go` line 1044 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NCXhrqu1OA3gnZJdGKZ:-NCXhrqu1OA3gnZJdGK_:b-u2osj9) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/961414ee89ff7bf3969a83f27ddfc2aa5abd6e50/controllers/vcdmachine_controller.go#L1044)):*
> ```Go
> 			log.Error(err, "failed to remove VappCreationError from RDE", "rdeID", vcdCluster.Status.InfraId)
> 		}
> 		err = capvcdRdeManager.RdeManager.RemoveErrorByNameOrIdFromErrorSet(ctx, vcdsdk.ComponentCAPVCD, capisdk.MetaDataConfigError, "", "")
> ```

Vapp ConfigError and MetadataConfigError are not removed

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 628 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NCXeP4xER10tga1RQVL:-NDdHaVq5zcovyUbYkCS:b-p5hi43) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/961414ee89ff7bf3969a83f27ddfc2aa5abd6e50/controllers/vcdcluster_controller.go#L628)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think this line should be moved to after the comment in the next line.
</blockquote></details>

Already pushed the changes. Thanks Aniruddha
___
*[`controllers/vcdcluster_controller.go` line 919 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NCXfbXt3HiQz31bP1Ix:-NDdHigJ4MKQ159tGDPX:bpx4tjr) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/961414ee89ff7bf3969a83f27ddfc2aa5abd6e50/controllers/vcdcluster_controller.go#L919)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Should there be a removal of `capisdk.ResourceUpdateError` before this line?
</blockquote></details>

I have changed the error name to RdeError and also put errorRemoval here.
___
*[`controllers/vcdcluster_controller.go` line 1092 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NCXg3SJ-BrATtfVYPlH:-NDdHub8B366KIeq6Q0K:b-il39cr) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/961414ee89ff7bf3969a83f27ddfc2aa5abd6e50/controllers/vcdcluster_controller.go#L1092)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Should there be a removal of error here ?
</blockquote></details>

Yes, we already have one. Thanks Aniruddha
___
*[`controllers/vcdmachine_controller.go` line 682 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NCXgq3W4wsmlCOgIZoN:-NDdHyPzDmfUOITFbHhE:b-oiak0i) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/961414ee89ff7bf3969a83f27ddfc2aa5abd6e50/controllers/vcdmachine_controller.go#L682)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

should we remove capisdk.InfraVMCreationError here?
</blockquote></details>

Already put one. And I examined all the addError operations have corresponding removals.
___
*[`controllers/vcdmachine_controller.go` line 822 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NCXh8RL4Z_FGTjIxV4i:-NDdIBSK5Q0OmMPTzUxe:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/961414ee89ff7bf3969a83f27ddfc2aa5abd6e50/controllers/vcdmachine_controller.go#L822)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

The logged error should be PostBootstrapError
</blockquote></details>

Done.
___
*[`controllers/vcdmachine_controller.go` line 829 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NCXhITo5RNwee5FVOSz:-NDdIAyb5anOXql_6XC3:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/961414ee89ff7bf3969a83f27ddfc2aa5abd6e50/controllers/vcdmachine_controller.go#L829)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

The logged error should be PostBootstrapError
</blockquote></details>

Done.
___
*[`controllers/vcdmachine_controller.go` line 1012 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NCXhZZNBE5irkGq77fo:-NDdIAX86T2AHGCAKIKY:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/961414ee89ff7bf3969a83f27ddfc2aa5abd6e50/controllers/vcdmachine_controller.go#L1012)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Should `VappCreationError` be removed over here?
</blockquote></details>

Done.
___
*[`controllers/vcdmachine_controller.go` line 1044 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NCXhrqu1OA3gnZJdGKZ:-NDdIC8r7gKc7AaAqYlc:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/961414ee89ff7bf3969a83f27ddfc2aa5abd6e50/controllers/vcdmachine_controller.go#L1044)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Vapp ConfigError and MetadataConfigError are not removed
</blockquote></details>

Done.

**Review by Anirudh9794 — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-:-NDj_fSt9LBtstLiqS8j:bg7igkv)* status: 2 of 4 files reviewed, 8 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-:-NDj_irz27iW79dYZQ8J:bg7igkv)* status: 2 of 4 files reviewed, 8 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

**Review by sahithi — APPROVED** [review]
As discussed rename the errors in such away that all vcdcluster/vcdmachine errors are prefixed with VCDCluster** and VCDMachine**Error respectively
:lgtm: after that

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-:-NDoTLQdC6l4mSAdzc3a:broroq4)* status: 2 of 4 files reviewed, 11 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @ymo24)

___
*[`controllers/vcdcluster_controller.go` line 808 at r4](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NDeuWLc-zqwhKDRib0V:-NDeuWLc-zqwhKDRib0W:b-yyqv16) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ca1a75353a7d2778b9755553b3f4ce63e502d163/controllers/vcdcluster_controller.go#L808)):*
> ```Go
> 		vcdCluster.Status.RdeVersionInUse = rdeVersionInUse
> 		if err := r.Status().Patch(ctx, vcdCluster, client.MergeFrom(oldVCDCluster)); err != nil {
> 			updatedErr := capvcdRdeManager.AddToErrorSet(ctx, capisdk.VCDObjectPatchError, "", vcdCluster.Name, fmt.Sprintf("failed to patch vcdcluster: [%v]", err))
> ```

Please rename VCDObjectPatchError -> VCDClusterPatchError and also update the below log messages as well with the new name
___
*[`controllers/vcdmachine_controller.go` line 497 at r4](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NDevCYf6-PjPfCj3cX2:-NDevCYf6-PjPfCj3cX3:bqtipr7) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ca1a75353a7d2778b9755553b3f4ce63e502d163/controllers/vcdmachine_controller.go#L497)):*
> ```Go
> 	vm, err := vApp.GetVMByName(machine.Name, true)
> 	if err != nil && err != govcd.ErrorEntityNotFound {
> 		updatedErr := capvcdRdeManager.AddToErrorSet(ctx, capisdk.InfraVMCreationError, "", machine.Name, fmt.Sprintf("%v", err))
> ```

InfraVmCreationError -> VCDMachineCreationError
___
*[`pkg/capisdk/defined_entity.go` line 76 at r4](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NDevyzZEdg0ClBwVs0Z:-NDevyzZEdg0ClBwVs0_:b-1kljb0) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ca1a75353a7d2778b9755553b3f4ce63e502d163/pkg/capisdk/defined_entity.go#L76)):*
> ```Go
> 	VCDMachineError = "VCDMachineError"
> 	// Set VCDObjectPatchError for any errors during patch execution of vcdmachine object and vcdcluster object
> 	VCDObjectPatchError = "VCDObjectPatchError"
> ```

Rename this to CAPVCDObjectPatchError

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @Anirudh9794, @arunmk, @sahithi, and @ymo24)

___
*[`controllers/vcdmachine_controller.go` line 497 at r4](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NDevCYf6-PjPfCj3cX2:-NDoYIqF7oZDtv7u6j6o:b-iogeda) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ca1a75353a7d2778b9755553b3f4ce63e502d163/controllers/vcdmachine_controller.go#L497)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

InfraVmCreationError -> VCDMachineCreationError
</blockquote></details>

Already pushed that. Thanks Sahithi
___
*[`pkg/capisdk/defined_entity.go` line 76 at r4](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/263#-NDevyzZEdg0ClBwVs0Z:-NDobgbB3bSsiVmOdXoG:b-iogeda) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ca1a75353a7d2778b9755553b3f4ce63e502d163/pkg/capisdk/defined_entity.go#L76)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Rename this to CAPVCDObjectPatchError
</blockquote></details>

Already pushed that. Thanks Sahithi

**Pull request merged**
