### PR TITLE
[VCDA-4514] Add events only on create operations

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

## Description
Please provide a brief description of the changes proposed in this Pull Request

- Update event set in vcdcluster_controller only when cluster.status.phase is not "Provisioned"
- Update event set in vcdmachine_controller only when machine.status.bootstrapready is false

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [x] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [x] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [x] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/278)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/278)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 634 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/278#-NDU59ll9nYdBz4q9GGX:-NDU59ll9nYdBz4q9GGY:b-6gygfb) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ce03eaf12eeea6ebf92de325b4988bb275419388/controllers/vcdcluster_controller.go#L634)):*
> ```Go
> 
> 	// To avoid spamming RDEs with updates, only update the RDE with events when machine creation is ongoing
> 	shouldUpdateEvents := cluster.Status.Phase != "Provisioned"
> ```

Please consider this for better readability

skipEventUpdates := cluster.Status.Phase != "Provisioned"

Also, consider retrieving the constant variable for "Provisioned" from the CoreCAPI vendor directory
___
*[`controllers/vcdmachine_controller.go` line 330 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/278#-NDU4lxz6cdrQsY5shKI:-NDU4lxz6cdrQsY5shKJ:bx5yxuf) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ce03eaf12eeea6ebf92de325b4988bb275419388/controllers/vcdmachine_controller.go#L330)):*
> ```Go
> 
> 	// To avoid spamming RDEs with updates, only update the RDE with events when machine creation is ongoing
> 	shouldUpdateEvents := !machine.Status.BootstrapReady
> ```

Please consider this for better readability

skipEventUpdates := machine.Status.BootstrapReady
___
*[`pkg/capisdk/defined_entity.go` line 496 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/278#-NDU5WsaDwos-PYGC21O:-NDU5WsaDwos-PYGC21P:b311uf7) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ce03eaf12eeea6ebf92de325b4988bb275419388/pkg/capisdk/defined_entity.go#L496)):*
> ```Go
> 
> func (capvcdRdeManager *CapvcdRdeManager) AddToEventSet(ctx context.Context, eventName, vcdResourceId, vcdResourceName, detailedEventMsg string, shouldUpdateEvents bool) error {
> 	if !shouldUpdateEvents {
> ```

if skipUpdateEvents {}
___
*[`pkg/capisdk/defined_entity.go` line 497 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/278#-NDU2y8mEsbrC_ffIcxq:-NDU2y8mEsbrC_ffIcxr:b-8en68o) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ce03eaf12eeea6ebf92de325b4988bb275419388/pkg/capisdk/defined_entity.go#L497)):*
> ```Go
> func (capvcdRdeManager *CapvcdRdeManager) AddToEventSet(ctx context.Context, eventName, vcdResourceId, vcdResourceName, detailedEventMsg string, shouldUpdateEvents bool) error {
> 	if !shouldUpdateEvents {
> 		klog.V(4).Infof("skipping updates to event set as value for shouldUpdateEventSet is [%t]", shouldUpdateEvents)
> ```

please add cluster name and rde_id to the log message

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/278)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 634 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/278#-NDU59ll9nYdBz4q9GGX:-NDUefDM0ZIvD8WXxOt9:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ce03eaf12eeea6ebf92de325b4988bb275419388/controllers/vcdcluster_controller.go#L634)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please consider this for better readability

skipEventUpdates := cluster.Status.Phase != "Provisioned"

Also, consider retrieving the constant variable for "Provisioned" from the CoreCAPI vendor directory
</blockquote></details>

Done.
___
*[`controllers/vcdmachine_controller.go` line 330 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/278#-NDU4lxz6cdrQsY5shKI:-NDUeeQU9vEsIDOhJNgM:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ce03eaf12eeea6ebf92de325b4988bb275419388/controllers/vcdmachine_controller.go#L330)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please consider this for better readability

skipEventUpdates := machine.Status.BootstrapReady
</blockquote></details>

Done.
___
*[`pkg/capisdk/defined_entity.go` line 496 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/278#-NDU5WsaDwos-PYGC21O:-NDUfUNk84FNWiKt4eKX:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ce03eaf12eeea6ebf92de325b4988bb275419388/pkg/capisdk/defined_entity.go#L496)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

if skipUpdateEvents {}
</blockquote></details>

Done.
___
*[`pkg/capisdk/defined_entity.go` line 497 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/278#-NDU2y8mEsbrC_ffIcxq:-NDUfUbLBY2AxL1EHkU6:btx1rc0) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ce03eaf12eeea6ebf92de325b4988bb275419388/pkg/capisdk/defined_entity.go#L497)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

please add cluster name and rde_id to the log message
</blockquote></details>

Done. Cluster Name is not available at this point in the code. I have updated the log message with the cluster ID

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/278#-:-NDUtHxX6Td46Vv8HF1O:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`pkg/capisdk/defined_entity.go` line 497 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/278#-NDU2y8mEsbrC_ffIcxq:-NDUt7y46HNaOejv19iJ:bj971z4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ce03eaf12eeea6ebf92de325b4988bb275419388/pkg/capisdk/defined_entity.go#L497)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Done. Cluster Name is not available at this point in the code. I have updated the log message with the cluster ID
</blockquote></details>

Replace shouldUpdateEventSet with SkipRDEEventUpdates in the text of the log

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/278)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @sahithi)

___
*[`pkg/capisdk/defined_entity.go` line 497 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/278#-NDU2y8mEsbrC_ffIcxq:-NDYq3ZF3-XDOn3OKwNK:b-vjwgw0) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ce03eaf12eeea6ebf92de325b4988bb275419388/pkg/capisdk/defined_entity.go#L497)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Replace shouldUpdateEventSet with SkipRDEEventUpdates in the text of the log
</blockquote></details>

Thanks for catching this.

**Pull request merged**
