### PR TITLE
update to version 1.0.2 internal

### PR DESCRIPTION
**Pull request by ltimothy7**
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/451)

### CODE REVIEW

**Review by arunmk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/451)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @ltimothy7)

___
*[`go.mod` line 10 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/451#-NVfZTz68qS4G07ezP7U:-NVfZTz68qS4G07ezP7V:b6ae7hf) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c4b962435e31aa075cf3c9b4c06e569d2387405b/go.mod#L10)):*
> ```XML
> 	github.com/google/uuid v1.3.0
> 	github.com/onsi/ginkgo v1.16.5
> 	github.com/onsi/ginkgo/v2 v2.1.3
> ```

I think this should be reverted.
___
*[`release/version` line 1 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/451#-NVfZlugDokIHTbkJ5lf:-NVfZlugDokIHTbkJ5lg:b-jr3vd7) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c4b962435e31aa075cf3c9b4c06e569d2387405b/release/version#L1)):*
> ```
> 1.0.2
> ```

This is the only change needed.
___
*[`templates/infrastructure-components.yaml` line 1166 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/451#-NVfZe4SDyjsuOhcPq5i:-NVfZe4SDyjsuOhcPq5j:b-ia8z36) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c4b962435e31aa075cf3c9b4c06e569d2387405b/templates/infrastructure-components.yaml#L1166)):*
> ```YAML
>       - command:
>         - /opt/vcloud/bin/cluster-api-provider-cloud-director
>         image: harbor-repo.vmware.com/vcloud/cluster-api-provider-cloud-director:1.0.2
> ```

This should be reverted.

**Review by lzichong — APPROVED** [review]
:lgtm:, but I am curious what caused the ginkgo version bump. 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/451#-:-NVfZufQ5O4ki-Apc4Vo:b-98ozk4)* status: all files reviewed, 3 unresolved discussions (waiting on @ltimothy7)

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/451)* status: all files reviewed, 3 unresolved discussions (waiting on @arunmk and @ltimothy7)

___
*[`templates/infrastructure-components.yaml` line 1166 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/451#-NVfZe4SDyjsuOhcPq5i:-NVf_J3T8XHgYaf4uJsC:b96qco8) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c4b962435e31aa075cf3c9b4c06e569d2387405b/templates/infrastructure-components.yaml#L1166)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This should be reverted.
</blockquote></details>

I think we can keep this as Tim needs to supply `1.0.z` branch to VCDKEConfig in order to test 1.0.2; otherwise this is not testable using CSE 4.0.3 GA OVA

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/451)* status: all files reviewed, 3 unresolved discussions (waiting on @arunmk and @ltimothy7)

___
*[`templates/infrastructure-components.yaml` line 1166 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/451#-NVfZe4SDyjsuOhcPq5i:-NVfaFf55m6CBEioX6wP:b-mm68qx) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c4b962435e31aa075cf3c9b4c06e569d2387405b/templates/infrastructure-components.yaml#L1166)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

I think we can keep this as Tim needs to supply `1.0.z` branch to VCDKEConfig in order to test 1.0.2; otherwise this is not testable using CSE 4.0.3 GA OVA
</blockquote></details>

correction: otherwise we will be testing 1.0.2 using CAPVCD 1.0.1 image

**Comment by ltimothy7** [comment]
*[`go.mod` line 10 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/451#-NVfZTz68qS4G07ezP7U:-NVfal_B7st-P1qzzAW3:b5efyd6) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c4b962435e31aa075cf3c9b4c06e569d2387405b/go.mod#L10)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

I think this should be reverted.
</blockquote></details>

@lzichong could you confirm if this should be reverted?

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/451)* status: all files reviewed, 3 unresolved discussions (waiting on @arunmk and @ltimothy7)

___
*[`go.mod` line 10 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/451#-NVfZTz68qS4G07ezP7U:-NVf_8Q2-t6tnaaOubYB:bnyifil) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c4b962435e31aa075cf3c9b4c06e569d2387405b/go.mod#L10)):*
> I think this should be reverted.

@ltimothy7 Yes I think this should be reverted, I ran a `make vendor` on 1.0.z branch locally and mine didn't update `ginkgo/oauth2` packages

**Comment by ltimothy7** [comment]
*[`go.mod` line 10 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/451#-NVfZTz68qS4G07ezP7U:-NVfbCQc1VTF7RLFvy4w:b-144rrk) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c4b962435e31aa075cf3c9b4c06e569d2387405b/go.mod#L10)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

> I think this should be reverted.

@ltimothy7 Yes I think this should be reverted, I ran a `make vendor` on 1.0.z branch locally and mine didn't update `ginkgo/oauth2` packages
</blockquote></details>

Thank you, will revert, not sure why it got updated

**Review by ltimothy7 — COMMENTED** [review]
@arunmk Just updated. Only 2 files are now changed. Now sure what caused the gingko change

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/451#-:-NVfcTP_6fACn4hb4vVX:btkqek3)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @arunmk and @lzichong)

**Review by arunmk — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/451#-:-NVfe6TTDV8kLMZlTFhY:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @ltimothy7)

**Pull request merged**
