### PR TITLE
[CAFV-175] Create developer guide for CAPVCD Upgrade

### PR DESCRIPTION
**Pull request by ymo24**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- Create developer guide for CAPVCD Upgrade

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @ymo24)

___
*[`docs/DEVELOPER_GUIDE.md` line 1 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410#-NQ1Fash7ObncMsZD4_5:-NQ1Fash7ObncMsZD4_6:bqsug6m) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c00b4e34a378ff78ffc3570e3322ee57b404c647/docs/DEVELOPER_GUIDE.md#L1)):*
> ```Markdown
> ## RDE
> ```

Can you mention that developers must evaluate  RDE upgrades and CAPVCD API upgrades right every a minor version of capvcd is shipped?
___
*[`docs/DEVELOPER_GUIDE.md` line 19 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410#-NQ1Fzfc8HP4rLYEt-ny:-NQ1Fzfc8HP4rLYEt-nz:b-luz9ct) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c00b4e34a378ff78ffc3570e3322ee57b404c647/docs/DEVELOPER_GUIDE.md#L19)):*
> ```Markdown
> ## CAPVCD Upgrade
> 1. RDE schema registration: Ensure the correct runtime RDE version is chosen and register the appropriate schema if necessary.
> 2. Use [CAPVCD UPGRADE GUIDE](./UPGRADES.md) to upgrade CAPVCD to the desired version.
> ```

This section must be about capvcd API upgrades NOT capvcd upgrades itself.
The steps mentioned in this document must be evaluated and run - https://confluence.eng.vmware.com/display/VCD/CAPVCD+upgrades

**Review by sahithi — COMMENTED** [review]
Yan,, I Just noticed that the developer guide is under the docs folder. This should not be part of official capvcd docs.
There is a placeholder file that I created sometime ago - https://github.com/vmware/cluster-api-provider-cloud-director/blob/main/developer_guide.md

Please move the content there and follow the sections mentioned there.

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410#-:-NQQxlj-2DdX_Ag4okpg:b-rve3yy)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @ymo24)

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @ymo24)

___
*[`developer_guide.md` line 7 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410#-NQfiVRQArs1iNStyRA3:-NQfiVRR7nv8Es8Ves2T:bo2lp82) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6f3a46ab2a62c7fb38066516221fda7496aa8468/developer_guide.md#L7)):*
> ```Markdown
> ### Steps to Create New APIs with Version `v1beta1`
> 
> 1. Create new API files with the desired version (e.g., `v1beta1`) in the `api` directory of your project. 
> ```

We need not mention the details here, Yan. Just mention that API upgrades need to be evaluated and performed after every release and before beginning ne w release.
You can add a confluence link, that is good enough (it will be inaccessible from out of vmware though)

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`developer_guide.md` line 7 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410#-NQfiVRQArs1iNStyRA3:-NQgMOrH2_q77hatD2m5:b-x3xuoh) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6f3a46ab2a62c7fb38066516221fda7496aa8468/developer_guide.md#L7)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We need not mention the details here, Yan. Just mention that API upgrades need to be evaluated and performed after every release and before beginning ne w release.
You can add a confluence link, that is good enough (it will be inaccessible from out of vmware though)
</blockquote></details>

Thanks Sahithi, already pushed the fix
___
*[`docs/DEVELOPER_GUIDE.md` line 1 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410#-NQ1Fash7ObncMsZD4_5:-NQgMHGF2wxgsEXehEOz:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c00b4e34a378ff78ffc3570e3322ee57b404c647/docs/DEVELOPER_GUIDE.md#L1)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you mention that developers must evaluate  RDE upgrades and CAPVCD API upgrades right every a minor version of capvcd is shipped?
</blockquote></details>

Done.
___
*[`docs/DEVELOPER_GUIDE.md` line 19 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410#-NQ1Fzfc8HP4rLYEt-ny:-NQgMHvkC_smTLE0XqTq:b-x3xuoh) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c00b4e34a378ff78ffc3570e3322ee57b404c647/docs/DEVELOPER_GUIDE.md#L19)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This section must be about capvcd API upgrades NOT capvcd upgrades itself.
The steps mentioned in this document must be evaluated and run - https://confluence.eng.vmware.com/display/VCD/CAPVCD+upgrades
</blockquote></details>

Thanks Sahithi, already pushed the fix

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410#-:-NQgTWqP4nYyaUwIXQ9I:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: with a few comments.

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410#-:-NR-hK4u8zuuLyBloazD:bvqqs7c)* status: all files reviewed, 6 unresolved discussions (waiting on @sahithi and @ymo24)

___
*[`developer_guide.md` line 14 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410#-NR-f6uFAlB_LLvMsqxm:-NR-f6uFAlB_LLvMsqxn:b-mtvtb4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c55d0b5eec6f682e25d9f5f6bd692b696866a266/developer_guide.md#L14)):*
> ```Markdown
> ### opening Upgrade path (for minor/patch upgrade )
> 1. Create new schema file under /schemas/schema_x_y_z.json
> 2. Locate the function ConvertToLatestRDEVersionFormat in the vcdcluster_controller.go.
> ```

The definition of `ConvertToLatestRDEVersionFormat()` is in `/pkg/capisdk/defined_entity.go`.
I think having this path makes more sense as the following steps say that we need to add another `convertFromXFormat()` 



_Code quote:_
```Markdown
ocate the function ConvertToLatestRDEVersionFormat in the vcdcluster_controller.go.
```
___
*[`developer_guide.md` line 22 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410#-NR-gKTHBJ1jP6cSpUzq:-NR-gKTHBJ1jP6cSpUzr:bboilpy) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c55d0b5eec6f682e25d9f5f6bd692b696866a266/developer_guide.md#L22)):*
> ```Markdown
> - Call the API update call to update CAPVCD entity and persist data into VCD.
> 
> ## API Upgrade
> ```

I think this should be called CAPVCD API upgrade
___
*[`developer_guide.md` line 27 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410#-NR-gm1GEGC7tfolz2aH:-NR-ghM64aRS_omq2brc:br9uhrs) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c55d0b5eec6f682e25d9f5f6bd692b696866a266/developer_guide.md#L27)):*
> ```Markdown
> * Create New APIs with the new Version (e.g., `v1beta1`).
> * Enable clusterctl upgrade command and do the upgrade to the new version.
> * Enable CAPVCD handle other supported versions.
> ```

Can we change this to "Enable CAPVCD handle other supported **API versions** " ?



_Code quote:_
```Markdown
Enable CAPVCD handle other supported versions.
```

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410)* status: all files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`developer_guide.md` line 14 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410#-NR-f6uFAlB_LLvMsqxm:-NR0ynI_-V7MTA7AK4hH:b1ebp6k) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c55d0b5eec6f682e25d9f5f6bd692b696866a266/developer_guide.md#L14)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

The definition of `ConvertToLatestRDEVersionFormat()` is in `/pkg/capisdk/defined_entity.go`.
I think having this path makes more sense as the following steps say that we need to add another `convertFromXFormat()` 
</blockquote></details>


Thanks, Aniruddha! Already pushed the fix
___
*[`developer_guide.md` line 22 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410#-NR-gKTHBJ1jP6cSpUzq:-NR0yw-E3UhaEouUkYRG:b1ebp6k) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c55d0b5eec6f682e25d9f5f6bd692b696866a266/developer_guide.md#L22)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think this should be called CAPVCD API upgrade
</blockquote></details>


Thanks, Aniruddha! Already pushed the fix
___
*[`developer_guide.md` line 27 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/410#-NR-gm1GEGC7tfolz2aH:-NR0z6iC99mtpZyFm2c4:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c55d0b5eec6f682e25d9f5f6bd692b696866a266/developer_guide.md#L27)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Can we change this to "Enable CAPVCD handle other supported **API versions** " ?
</blockquote></details>

Done.

**Pull request merged**
