### PR TITLE
VCDA-3502: Add parentUid and useAsManagementCluster support for v1beta1 VCDCluster

### PR DESCRIPTION
**Pull request by lzichong**
* Added optional `parentUid` - Parent's Management Cluster Unique ID
* Added optional `useAsManagementCluster` - Intent to use cluster as a management cluster; removed omitempty to show `false` as false is considered empty
* Regenerated `zz_generated.conversion.go` from conversion gen tool
* Added fields in `reconcileRDE` to update RDE Status to be same with cluster spec
* Testing Done:
  - Applied capi yaml -> used Postman for RDE details -> update values and reapply capi yaml -> see updated change after sometime in Postman RDE

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98#-:-N04Xuwl1Fu9CZ0KsCag:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @lzichong and @sahithi)

___
*[api/v1alpha4/zz_generated.conversion.go, line 430 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98#-N04XLW-54WP8-sZqnx6:-N04XLW-54WP8-sZqnx7:b-u8a5cn) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0fb93d98fd190acb00729c5767b0c7b512c826f3/api/v1alpha4/zz_generated.conversion.go#L430)):*
> ```Go
> func autoConvert_v1beta1_VCDMachineList_To_v1alpha4_VCDMachineList(in *v1beta1.VCDMachineList, out *VCDMachineList, s conversion.Scope) error {
> 	out.ListMeta = in.ListMeta
> 	if in.Items != nil {
> ```

Im just wondering what might have triggered this change. Because you are not making changes to VCDMachine

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @sahithi)

___
*[api/v1alpha4/zz_generated.conversion.go, line 430 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98#-N04XLW-54WP8-sZqnx6:-N06l4Ew3zFLRdTJe9tQ:befglqp) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0fb93d98fd190acb00729c5767b0c7b512c826f3/api/v1alpha4/zz_generated.conversion.go#L430)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Im just wondering what might have triggered this change. Because you are not making changes to VCDMachine
</blockquote></details>

Can you run the conversion tool on your local main branch and see if that gets added for you as well? I just ran the conversion tool on my local main branch and it also gave this implementation back



_Code quote:_
```Go
func autoConvert_v1beta1_VCDMachineList_To_v1alpha4_VCDMachineList(in *v1beta1.VCDMachineList, out *VCDMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
```

**Review by sahithi — APPROVED** [review]
:lgtm: after addressing the comments

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98#-:-N08IyWE-b31zzYCUZAO:b-3tyihq)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @lzichong)

___
*[api/v1alpha4/vcdcluster_conversion.go, line 16 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98#-N08-vAUDvQ88noKN-or:-N08-vAVEltJk75k9L8M:br97vpd) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0fb93d98fd190acb00729c5767b0c7b512c826f3/api/v1alpha4/vcdcluster_conversion.go#L16)):*
> ```Go
> 	dst.Spec.DefaultStorageClassOptions = &v1beta1.DefaultStorageClassOptions{}
> 	dst.Spec.RDEId = ""
> 	dst.Spec.ParentUID = ""
> ```

Ideally this should have been below; we missed adding these params to status section in the last release. 
dst.Spec.ParentUID = src.status.ParentID,
dst.Spec.UseAsManagementCluster = src.status.IsManagementCluster 

Let's take an example. There is an existing v1alpha4 cluster created with CAPVCD 0.5.0 (previous release). Now, the user upgraded CAPVCD 0.5 to the current version. 

Now when the user attempts to retrieve the v1beta1 format of his/her existing cluster, some of the values (parent UID, IsManagementCluster) are getting reset, which is not good. 

RDE (1.0) can come to the rescue here. We do store these properties in the RDE.status.

So, it should look like below 

dst.Spec.RDEId = src.status.InfraId
if dst.Spec.RDEId is valid: 
    rde:= getrde(dst.Spec.RDEId)
dst.Spec.ParentUID = rde.status.parentUID
dst.Spec.UseAsManagementCluster = rde.status.IsManagementCluster


If all of the above seems confusing, let us take this in a separate PR and add a TODO here with the above info I mentioned.
___
*[api/v1beta1/vcdcluster_types.go, line 55 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98#-N08-Mv52NZYL78UjJZ6:-N08-Mv64Ej4Yj3tYMZO:bmuzoar) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0fb93d98fd190acb00729c5767b0c7b512c826f3/api/v1beta1/vcdcluster_types.go#L55)):*
> ```Go
> 
> // VCDClusterSpec defines the desired state of VCDCluster
> type VCDClusterSpec struct {
> ```

Regenerate CRDs and add those files to the PR
___
*[api/v1beta1/vcdcluster_types.go, line 80 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98#-N08-Fqc6sLgAGlm5p_a:-N08-Fqc6sLgAGlm5p_b:b-j4g0qv) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0fb93d98fd190acb00729c5767b0c7b512c826f3/api/v1beta1/vcdcluster_types.go#L80)):*
> ```Go
> 	ParentUID string `json:"parentUid,omitempty"`
> 	// +optional
> 	UseAsManagementCluster bool `json:"useAsManagementCluster"`
> ```

please add omitempty. Can you also add these properties to the VCDClusterStatus? This just occurred to me. 
These properties will be needed for the future API upgrades from v1beta1 to something else.

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[api/v1alpha4/vcdcluster_conversion.go, line 16 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98#-N08-vAUDvQ88noKN-or:-N0C4SU0Dr-6T42EFcqn:b-vedbc) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0fb93d98fd190acb00729c5767b0c7b512c826f3/api/v1alpha4/vcdcluster_conversion.go#L16)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Ideally this should have been below; we missed adding these params to status section in the last release. 
dst.Spec.ParentUID = src.status.ParentID,
dst.Spec.UseAsManagementCluster = src.status.IsManagementCluster 

Let's take an example. There is an existing v1alpha4 cluster created with CAPVCD 0.5.0 (previous release). Now, the user upgraded CAPVCD 0.5 to the current version. 

Now when the user attempts to retrieve the v1beta1 format of his/her existing cluster, some of the values (parent UID, IsManagementCluster) are getting reset, which is not good. 

RDE (1.0) can come to the rescue here. We do store these properties in the RDE.status.

So, it should look like below 

dst.Spec.RDEId = src.status.InfraId
if dst.Spec.RDEId is valid: 
    rde:= getrde(dst.Spec.RDEId)
dst.Spec.ParentUID = rde.status.parentUID
dst.Spec.UseAsManagementCluster = rde.status.IsManagementCluster


If all of the above seems confusing, let us take this in a separate PR and add a TODO here with the above info I mentioned.
</blockquote></details>

Added as TODO for now as we will discuss further, thanks!
___
*[api/v1beta1/vcdcluster_types.go, line 55 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98#-N08-Mv52NZYL78UjJZ6:-N0C3eNW9d0emJmeNs8d:b-53d0w9) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0fb93d98fd190acb00729c5767b0c7b512c826f3/api/v1beta1/vcdcluster_types.go#L55)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Regenerate CRDs and add those files to the PR
</blockquote></details>

Updated and added vcdcluster's CRD
___
*[api/v1beta1/vcdcluster_types.go, line 80 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98#-N08-Fqc6sLgAGlm5p_a:-N0C3cr4BPr0SUlzVObc:b-1x3emh) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/0fb93d98fd190acb00729c5767b0c7b512c826f3/api/v1beta1/vcdcluster_types.go#L80)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

please add omitempty. Can you also add these properties to the VCDClusterStatus? This just occurred to me. 
These properties will be needed for the future API upgrades from v1beta1 to something else.
</blockquote></details>

Done and added updated conversion gen, thanks!

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @lzichong, and @sahithi)

___
*[api/v1beta1/vcdcluster_types.go, line 101 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98#-N0CENlV2fqrTCCzXW8E:-N0CENlV2fqrTCCzXW8F:b-9cb05i) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6e866a060b13a582cf695fe969175c830cc38ce9/api/v1beta1/vcdcluster_types.go#L101)):*
> ```Go
> 	InfraId string `json:"infraId,omitempty"`
> 	// +optional
> 	ParentUID string `json:"parentUid,omitempty"`
> ```

Please update these params with the values in the vcdcluster_controller reconcile() (wherever we are updating vcd.status.infraid).

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[api/v1beta1/vcdcluster_types.go, line 101 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98#-N0CENlV2fqrTCCzXW8E:-N0D7kSW57MzVSrqmfSX:b-b1435j) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6e866a060b13a582cf695fe969175c830cc38ce9/api/v1beta1/vcdcluster_types.go#L101)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please update these params with the values in the vcdcluster_controller reconcile() (wherever we are updating vcd.status.infraid).
</blockquote></details>

Updated, values in Status match Spec after going through reconciling, and RDE via Postman also matches after a bit

**Review by sahithi — APPROVED** [review]
> Reviewed 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/98)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

**Pull request merged**
