### PR TITLE
Change CAPVCD version to 1.0.0 and regenerate manifests

### PR DESCRIPTION
**Pull request by Anirudh9794**
* update capvcd version to 1.0.0
* regenerate infrastructure-components.yaml
* add `-f` option to the `rm` command in `generate_conversions` make target

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/154)

### CODE REVIEW

**Review by ymo24 — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/154#-:-N31Gjt84vi4NHS23NSC:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sahithi)

**Review by sahithi — APPROVED** [review]
I think we need to update release/version as well?
:lgtm: after the above

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/154#-:-N35cvpx2elwjq5CZX7N:b6hly5t)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by sahithi — COMMENTED** [review]
And the image name to reflect the version both in Make file targets and manager.yaml
Mention vkp branch as well in the manager.yaml. Sakthi will use that image name in his testing.

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/154#-:-N35eOXXCkN9OqafDOqK:bo9yafn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by Anirudh9794 — COMMENTED** [review]
This PR is against main branch. Will update the version to `vkp-branch` in `vkp` feature branch of CAPVCD

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/154#-:-N35wQ-N07FCIsSBayPY:b-9sr0xy)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Pull request merged**
