### PR TITLE
[VCDA-3467] Add LoadBalancer components, Vapp and VMs to VCDResourceSet

### PR DESCRIPTION
**Pull request by Anirudh9794**
* add and remove loadbalancer components, vapp and VM details to VCDResourceSet in RDE.

Testing done:
* Create a cluster
* check if all the resources are getting added to VCDResourceSet
* Add / remove a node
* Check if the created / delete node is added to / removed from VCDResourceSet
* Delete cluster
* check if all the loadbalancer components get removed from VCDResourceSet before RDE is deleted.

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/147)

### CODE REVIEW

**Review by lzichong — APPROVED** [review]
:lgtm: after addressing comment

> Reviewed 1 of 6 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/147#-:-N2nVyYY1OGa2BMWb-yu:bkbnwf4)* status: 2 of 10 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @lzichong)

___
*[`pkg/capisdk/capi_gateway_manager.go` line 204 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/147#-N2nUftJ4GFS2t-zAJ9c:-N2nUftJ4GFS2t-zAJ9d:b-fmy94l) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a1c48072479ef6dd9a8f941bfcc500d77859d657/pkg/capisdk/capi_gateway_manager.go#L204)):*
> ```Go
> 		virtualServiceRef, err := capvcdGatewayManager.gatewayManager.CreateVirtualService(ctx, virtualServiceName, lbPoolRef, segRef,
> 			virtualServiceIP, portDetail.serviceType, portDetail.externalPort, portDetail.useSSL, portDetail.certificateAlias)
> 		if virtualServiceRef != nil {
> ```

the first err check should happen before virtualServiceRef gets nil checked and the second error should go inside the virtualServiceRef nil check block right?



_Code quote:_
```Go
		if virtualServiceRef != nil {
			// Add virtual service to vcd resource set
			err = rdeManager.AddToVCDResourceSet(ctx, vcdsdk.ComponentCAPVCD, vcdsdk.VcdResourceVirtualService,
				virtualServiceRef.Name, virtualServiceRef.Id, map[string]interface{}{
					"virtualIP": externalIP,
				})
		}
		if err != nil {
			return "", fmt.Errorf("unable to create virtual service [%s] with address [%s:%d]: [%v]",
				virtualServiceName, virtualServiceIP, portDetail.externalPort, err)
		}
		if err != nil {
			return "", fmt.Errorf("failed to add virtual service [%s] to VCDResourceSet of RDE [%s]", virtualServiceRef.Name, rdeManager.ClusterID)
		}
```

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/147)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @lzichong, and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 551 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/147#-N2nu0jPBAv4kgVMyPKP:-N2nu0jPBAv4kgVMyPKQ:b-48cf2n) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a1c48072479ef6dd9a8f941bfcc500d77859d657/controllers/vcdcluster_controller.go#L551)):*
> ```Go
> 	}
> 	// Add VApp to VCDResourceSet
> 	err = rdeManager.AddToVCDResourceSet(ctx, vcdsdk.ComponentCAPVCD, VCDResourceVApp,
> ```

I can't find this method with the right signature in the latest CPI code of VKP branch. Below is what I found.

func addToVCDResourceSet(component string, componentName string, componentVersion string, statusMap map[string]interface{}, vcdResource VCDResource) (map[s
___
*[`pkg/capisdk/capi_gateway_manager.go` line 117 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/147#-N2nruRn7gk0fPZpaZxn:-N2nruRn7gk0fPZpaZxo:b2iffdo) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a1c48072479ef6dd9a8f941bfcc500d77859d657/pkg/capisdk/capi_gateway_manager.go#L117)):*
> ```Go
> 			dnatRuleRef, err := capvcdGatewayManager.gatewayManager.GetNATRuleRef(ctx, dnatRuleName)
> 			if err != nil {
> 				return "", fmt.Errorf("failed to fetch DNAT rule [%s]: [%v]", dnatRuleName, err)
> ```

please check if the caller is printing the cluster id, if not add rdeId to the log statement at an appropriate place. 
check the same for other logs as well.

**Review by sahithi — APPROVED** [review]
:lgtm: after addressing comments.
Please ensure CPI-VKP branch is updated with the latest code.

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/147#-:-N2nuK599jVKjWkD-7QB:b-42emd9)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @lzichong, and @sahithi)

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/147)* status: 2 of 10 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @lzichong, and @sahithi)

___
*[`controllers/vcdmachine_controller.go` line 570 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/147#-N2nvKnN9sWhTAB64nq9:-N2nvKnN9sWhTAB64nqA:b4d0vwg) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a1c48072479ef6dd9a8f941bfcc500d77859d657/controllers/vcdmachine_controller.go#L570)):*
> ```Go
> 			return ctrl.Result{}, errors.Wrapf(err, "Obtained nil VM after creating VM [%s]", machine.Name)
> 		}
> 		// Add vm to VCDResourceSet
> ```

I think adding Vms is not necessary. Adding vApp is sufficient to vcdresourceset

RDE can bloat as the worker nodes go up.  What do you think?
Please get Arun's opinion as well.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/147)* status: 2 of 10 files reviewed, 4 unresolved discussions (waiting on @lzichong and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 551 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/147#-N2nu0jPBAv4kgVMyPKP:-N2rMfIjA-8DJ2whTYjn:b-i68rcs) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a1c48072479ef6dd9a8f941bfcc500d77859d657/controllers/vcdcluster_controller.go#L551)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I can't find this method with the right signature in the latest CPI code of VKP branch. Below is what I found.

func addToVCDResourceSet(component string, componentName string, componentVersion string, statusMap map[string]interface{}, vcdResource VCDResource) (map[s
</blockquote></details>

That is a helper function used by the exported function rdeManager.AddToVCDResourceSet()
https://github.com/vmware/cloud-provider-for-cloud-director/blob/vkp/pkg/vcdsdk/defined_entity.go#L149
___
*[`controllers/vcdmachine_controller.go` line 570 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/147#-N2nvKnN9sWhTAB64nq9:-N2r_7PYA8zCm7EUKneY:biumj7i) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a1c48072479ef6dd9a8f941bfcc500d77859d657/controllers/vcdmachine_controller.go#L570)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I think adding Vms is not necessary. Adding vApp is sufficient to vcdresourceset

RDE can bloat as the worker nodes go up.  What do you think?
Please get Arun's opinion as well.
</blockquote></details>

Makes sense. I will remove adding VMs to vcdResourceSetx`
___
*[`pkg/capisdk/capi_gateway_manager.go` line 117 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/147#-N2nruRn7gk0fPZpaZxn:-N2reXLYAx3yedSXZUL0:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a1c48072479ef6dd9a8f941bfcc500d77859d657/pkg/capisdk/capi_gateway_manager.go#L117)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

please check if the caller is printing the cluster id, if not add rdeId to the log statement at an appropriate place. 
check the same for other logs as well.
</blockquote></details>

Done.
___
*[`pkg/capisdk/capi_gateway_manager.go` line 204 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/147#-N2nUftJ4GFS2t-zAJ9c:-N2rejQV4toKqreOvd0D:bbckqqz) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a1c48072479ef6dd9a8f941bfcc500d77859d657/pkg/capisdk/capi_gateway_manager.go#L204)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

the first err check should happen before virtualServiceRef gets nil checked and the second error should go inside the virtualServiceRef nil check block right?
</blockquote></details>

The `CreateVirtualService` function returns an error during creation even if the virtual service creation goes through fine and if the VS is in a pending state. Ideally we should add the virtual service to the VCDResourceSet just after creating it. So, I have written the code this way.

**Pull request merged**
