### PR TITLE
[VCDA-3475] fix authentication issue with system admin refresh tokens by implementing fallback

### PR DESCRIPTION
**Pull request by Anirudh9794**
* when authenticating using refresh token, follow the following steps
* authenticate as a system org user
* if the above step fails, authenticate as a tenant user

* this PR also fixes authentication based tests which were broken

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/116)

### CODE REVIEW

**Review by arunmk — APPROVED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/116)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[`pkg/config/cloudconfig.go` line 124 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/116#-N0gfVT6ERnPXmbVhibB:-N0gfVT7Bc9MD3ZlsBqB:bo3rad8) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6628a163d515d020e13828e877dde5eca716a3f8/pkg/config/cloudconfig.go#L124)):*
> ```Go
> 		return nil, fmt.Errorf("Unable to decode yaml file: [%v]", err)
> 	}
> 	//config.VCD.Host = strings.TrimRight(config.VCD.Host, "/")
> ```

why is this commented out?
___
*[`pkg/vcdcapiclient/defined_entity.go` line 1 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/116#-N0gf_ucBVpRaw6a-ADw:-N0gf_ucBVpRaw6a-ADx:bvo3n9j) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6628a163d515d020e13828e877dde5eca716a3f8/pkg/vcdcapiclient/defined_entity.go#L1)):*
> ```Go
> package vcdcapiclient
> ```

I am guessing this is extra content?

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/116)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[`pkg/config/cloudconfig.go` line 124 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/116#-N0gfVT6ERnPXmbVhibB:-N0ghhbVCWQZSBuFYjsM:b-kz31hv) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6628a163d515d020e13828e877dde5eca716a3f8/pkg/config/cloudconfig.go#L124)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

why is this commented out?
</blockquote></details>

I missed removing this line before sending out the PR. Will remove the line

**Comment by Anirudh9794** [comment]
*[`pkg/vcdcapiclient/defined_entity.go` line 1 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/116#-N0gf_ucBVpRaw6a-ADw:-N0glhuG-rKfMUaVUcKg:br58iru) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6628a163d515d020e13828e877dde5eca716a3f8/pkg/vcdcapiclient/defined_entity.go#L1)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

I am guessing this is extra content?
</blockquote></details>

Yes, I deleted this file

**Review by sahithi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/116#-:-N0h23myA5KC8d69EwNO:b593w57)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`pkg/vcdclient/auth.go` line 51 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/116#-N0h2pQs5K0dm4uUstn-:-N0h2pQs5K0dm4uUstn0:b-2jhxdw) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/22001a9a7cc061c1bd24a218172194e06731ffb1/pkg/vcdclient/auth.go#L51)):*
> ```Go
> 		// NOTE: for a system admin user using refresh token, the userOrg will still be tenant org.
> 		// try setting authentication as a system org user
> 		err = vcdClient.SetToken("system",
> ```

Shouldn't the order be another way around? First, attempt with the tenant org and then use the system.

regardless, it shouldn't matter.

**Review by sahithi — COMMENTED** [review]
This code will go to common CPI, right?

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/116#-:-N0h3vQk7HoHiGhxJDzq:b-jisv7h)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

**Comment by Anirudh9794** [comment]
This is already in CPI common library.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/116)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[`pkg/vcdclient/auth.go` line 51 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/116#-N0h2pQs5K0dm4uUstn-:-N0hmISA0ahXm9eq5V8v:bb6un1j) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/22001a9a7cc061c1bd24a218172194e06731ffb1/pkg/vcdclient/auth.go#L51)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Shouldn't the order be another way around? First, attempt with the tenant org and then use the system.

regardless, it shouldn't matter.

</blockquote></details>

Done

**Pull request merged**
