### PR TITLE
[VCDA-4413] Change vcdOrg in vcdProperties to an array in the schema

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

## Description
Please provide a brief description of the changes proposed in this Pull Request
- Schema for vcdOrg should be changed from an object to an array

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [x] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/258)

### CODE REVIEW

**Review by lzichong — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/258#-:-NC2A6hZBtqaRv9c-Uwr:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/258)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @sahithi)

___
*[`schema/schema_1_1_0.json` line 180 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/258#-NC2DSgq3n6FCPrJDD7M:-NC2DSgq3n6FCPrJDD7N:bvlhruw) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1e4ce600a35725bafd891b8bf84cfd38d4b1e929/schema/schema_1_1_0.json#L180)):*
> ```JSON
>                 "vcdOrg": {
>                   "type": "array",
>                   "properties": {
> ```

When array, I think there should exist a property called "items". Please check

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/258)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[`schema/schema_1_1_0.json` line 180 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/258#-NC2DSgq3n6FCPrJDD7M:-NC2G6TT7F7fhmzwRLCO:b9r8n5o) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1e4ce600a35725bafd891b8bf84cfd38d4b1e929/schema/schema_1_1_0.json#L180)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

When array, I think there should exist a property called "items". Please check
</blockquote></details>

Yes I just fixed it. I also validated the schema again

**Review by sahithi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/258#-:-NC6Co9_-pcqeKBP6veC:bg7igkv)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @sahithi)

**Pull request merged**
