### PR TITLE
[VCDA-4430] Add available nodes to the node pools section in the RDE

### PR DESCRIPTION
**Pull request by Anirudh9794**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- Add available node pools to the RDE

## Checklist
- [x] tested locally
- [x] updated any relevant dependencies
- [x] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [x] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [x] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [x] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [x] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [x] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/264)

### CODE REVIEW

**Review by ymo24 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/264)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[`pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go` line 107 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/264#-NCRo2b1C04ZDRidVdTT:-NCRo2b1C04ZDRidVdTU:b-t1j9ol) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01f34c1a9dcb0245163abffe6516723b30841a79/pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go#L107)):*
> ```Go
> 	PlacementPolicy   string            `json:"placementPolicy,omitempty"`
> 	DiskSizeMb        int32             `json:"diskSizeMb,omitempty"`
> 	NvidiaGpu         bool              `json:"nvidiaGpu,omitempty"`
> ```

Shall we do this change? nvidiaGPU -> enableNvidiaGPU (bools are usually verbs )
I need to make this change in VCDMachineSpec. Maybe we also need to rename NvidiaGpu at this place.

**Comment by Anirudh9794** [comment]
*[`pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go` line 107 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/264#-NCRo2b1C04ZDRidVdTT:-NCWXqQZ57TVbpzbXeoF:brx49g) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01f34c1a9dcb0245163abffe6516723b30841a79/pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go#L107)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

@sahithi just wanted to confirm with you if making the above change is okay at this point in the release.
</blockquote></details>

Done. changed the name to `nvidiaGpuEnabled` as it is a derived property.

**Review by ymo24 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/264)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

**Review by lzichong — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/264#-:-NCW_-Ft7tjG1RT1uvnk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

**Review by sahithi — APPROVED** [review]
:lgtm: after addressing comments 

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/264#-:-NCWfKA18bc8U5ftE2CY:b-24yl1v)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`examples/rde1_1_0.json` line 78 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/264#-NCWfCVU8tCzcU4PQDit:-NCWfCVU8tCzcU4PQDiu:bmgezm0) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/88d6bb3d95c463f2810316866447de50b69e2183/examples/rde1_1_0.json#L78)):*
> ```JSON
>           "sizingPolicy": "TKG small",
>           "storageProfile": "*",
>           "availableReplicas": 1
> ```

missing gpu property
___
*[`examples/rde1_1_0.json` line 91 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/264#-NCWa7-60v15MaYunwDV:-NCWa7-60v15MaYunwDW:b-ay2wxj) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/88d6bb3d95c463f2810316866447de50b69e2183/examples/rde1_1_0.json#L91)):*
> ```JSON
>         }
>       ],
>       "nodeStatus": {
> ```

Please remove this nodeStatus. This is no longer present, right?
___
*[`schema/schema_1_1_0.json` line 141 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/264#-NCWeQeVC14MAu8UNGky:-NCWeQeVC14MAu8UNGkz:bk1qnsm) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/88d6bb3d95c463f2810316866447de50b69e2183/schema/schema_1_1_0.json#L141)):*
> ```JSON
>             },
>             "nodePool": {
>               "additionalProperties": {
> ```

why is this under additional properties? I am not asking to change it, but to ensure json schema allows defining properties under it. if not make it "properties"
___
*[`schema/schema_1_1_0.json` line 171 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/264#-NCWeGAk86hQfc-q-KTt:-NCWeGAk86hQfc-q-KTu:b-gz66ey) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/88d6bb3d95c463f2810316866447de50b69e2183/schema/schema_1_1_0.json#L171)):*
> ```JSON
>                   "desiredReplicas": {
>                     "type": "integer",
>                     "description": "number of VMs in the node pool"
> ```

Desired replica count of the node pool

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/264)* status: all files reviewed, 5 unresolved discussions (waiting on @sahithi)

___
*[`examples/rde1_1_0.json` line 78 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/264#-NCWfCVU8tCzcU4PQDit:-NCXCgJCCmZP_1Zkkna4:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/88d6bb3d95c463f2810316866447de50b69e2183/examples/rde1_1_0.json#L78)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

missing gpu property
</blockquote></details>

Done.
___
*[`examples/rde1_1_0.json` line 91 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/264#-NCWa7-60v15MaYunwDV:-NCXC1lr2EqyaMmQ6Ns1:bjxu86x) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/88d6bb3d95c463f2810316866447de50b69e2183/examples/rde1_1_0.json#L91)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please remove this nodeStatus. This is no longer present, right?
</blockquote></details>

Yes, it is not used. I have removed it
___
*[`schema/schema_1_1_0.json` line 141 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/264#-NCWeQeVC14MAu8UNGky:-NCXDA-N8nZtImxRl_yn:bgacpc1) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/88d6bb3d95c463f2810316866447de50b69e2183/schema/schema_1_1_0.json#L141)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

why is this under additional properties? I am not asking to change it, but to ensure json schema allows defining properties under it. if not make it "properties"
</blockquote></details>

Changed to "properties"
___
*[`schema/schema_1_1_0.json` line 171 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/264#-NCWeGAk86hQfc-q-KTt:-NCXDQXZ06_SkmuMb4zS:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/88d6bb3d95c463f2810316866447de50b69e2183/schema/schema_1_1_0.json#L171)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Desired replica count of the node pool
</blockquote></details>

Done.

**Pull request merged**
