### PR TITLE
RDE management updates for CAPVCD

### PR DESCRIPTION
**Pull request by Anirudh9794**
Changes:
- Logic to add worker count, control plane count, template name, sizing class
- Added capi-quickstart.yaml
- Fixed empty string for cluster id

Testing:
- Created Cluster and checked if the RDE is created with appropriate values

@arunmk @sahithi @ltimothy7

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10)

### CODE REVIEW

**Review by ltimothy7 — COMMENTED** [review]
> Reviewed 11 of 64 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10)* status: 11 of 64 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[controllers/vcdcluster_controller.go, line 335 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqFp6L63qvMd5i7zm7O:-MqFp6L63qvMd5i7zm7P:b-s4bbon) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9a13eead177ba6a5aec96d3c2ef38d3b3394ab41/controllers/vcdcluster_controller.go#L335)):*
> ```Go
> 		}
> 		topologyControlPlanes = append(topologyControlPlanes, topologyControlPlane)
> 		templateName = vcdMachineTemplate.Spec.Template.Spec.Template
> ```

The final templateName will be from the last item in this list; is this intentional? If so, a comment here to describe this would be helpful
___
*[controllers/vcdmachine_controller.go, line 581 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqFpQbz7Q0cBmphi1iO:-MqFpQbz7Q0cBmphi1iP:bmekkis) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9a13eead177ba6a5aec96d3c2ef38d3b3394ab41/controllers/vcdmachine_controller.go#L581)):*
> ```Go
> 			err = workloadVCDClient.SetVmExtraConfigKeyValue(vm, key, val, true)
> 			if err != nil {
> 				//log.Error(err, "error occurred while configuring machine", "machineName", vm.VM.Name)
> ```

Commented code should be removed
___
*[controllers/vcdmachine_controller.go, line 639 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqFpV2eBcE7XW40ShGR:-MqFpV2f4l17ZeGRpjnq:bmjgoho) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9a13eead177ba6a5aec96d3c2ef38d3b3394ab41/controllers/vcdmachine_controller.go#L639)):*
> ```Go
> 	for _, phase := range phases {
> 		if err = vApp.Refresh(); err != nil {
> 			//log.Error(err, "error occurred while configuring machine", "machineName", vm.VM.Name)
> ```

Similar here for commented code

**Review by sahithi — APPROVED** [review]
:lgtm: after addressing comments

> Reviewed 62 of 64 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-:-MqLDICuDM5LqayiLmbb:b-98fkod)* status: all files reviewed, 12 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[controllers/vcdcluster_controller.go, line 335 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqFp6L63qvMd5i7zm7O:-MqL9OMk6Y5ePIfi_Pb5:b-s4s37k) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9a13eead177ba6a5aec96d3c2ef38d3b3394ab41/controllers/vcdcluster_controller.go#L335)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

The final templateName will be from the last item in this list; is this intentional? If so, a comment here to describe this would be helpful
</blockquote></details>

Tim, Aniruddh and I discussed this, he will make changes to avoid confusion in the next PR.
___
*[controllers/vcdcluster_controller.go, line 88 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqKtkh530_afmAN8VVU:-MqKtkh530_afmAN8VVV:b-kocsxd) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L88)):*
> ```Go
> 		Name:      vcdMachineTemplateRef.Name,
> 	}
> 	if err := r.Client.Get(ctx, vcdMachineTemplateKey, vcdMachineTemplate); err != nil {
> ```

For my benefit, where does the client look for "Key" in? Is it always Metadata of the objects? (or) does it recursively look for the keys in the entire object?
___
*[controllers/vcdcluster_controller.go, line 184 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqKujZ955m4v_SQHcVB:-MqKujZ955m4v_SQHcVC:bb8gbxm) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L184)):*
> ```Go
> func (r *VCDClusterReconciler) constructCapvcdRDE(ctx context.Context, cluster *clusterv1.Cluster,
> 	vcdCluster *infrav1.VCDCluster) (*swagger.DefinedEntity, error) {
> 	// Refactor to remove workloadVCDClient and use vcdCluster object instead
> ```

You can remove the comment
___
*[controllers/vcdcluster_controller.go, line 198 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqL7ICaE24zp4o5OPf2:-MqL7ICaE24zp4o5OPf3:b-g9khke) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L198)):*
> ```Go
> 	kubernetesVersion := ""
> 	for _, kcp := range kcpList.Items {
> 		vcdMachineTemplate, err := r.getVCDMachineTemplateFromKCP(ctx, &kcp)
> ```

for my benefit, will it cause any error if we just pass "kcp" instead of "&kcp? (or) does it automatically retrieve the address of kcp?
I want to understand if we are just being good citizens (or) GO is indeed very strict about it?
___
*[controllers/vcdcluster_controller.go, line 200 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqKvvwo9xRgoCqM5fRI:-MqKvvwo9xRgoCqM5fRJ:b-x6ggt3) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L200)):*
> ```Go
> 		vcdMachineTemplate, err := r.getVCDMachineTemplateFromKCP(ctx, &kcp)
> 		if err != nil {
> 			return nil, fmt.Errorf("failed to get VCDMachineTemplate from KCP [%s] for cluster [%s]: [%v]", kcp.Name, cluster.Name, err)
> ```

The exact same error message is returned from r.getVCDMachineTemplateFromKCP, can we just return the error as-is instead of reconstructing the error.
___
*[controllers/vcdcluster_controller.go, line 203 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqL8IT6-9h3vCi0TT12:-MqL8IT6-9h3vCi0TT13:bu6zwq1) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L203)):*
> ```Go
> 		}
> 		topologyControlPlane := vcdtypes.ControlPlane{
> 			Count:       *kcp.Spec.Replicas,
> ```

same here, does it complain if we use "kcp.Spec.Replicas" without "*"?
___
*[controllers/vcdcluster_controller.go, line 249 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqL8k2y8BfNZoKpv36C:-MqL8k2z2EUCD8cC_G5J:b-xbmrk3) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L249)):*
> ```Go
> 					},
> 					Pods: vcdtypes.Pods{
> 						CidrBlocks: nil, // TODO: fetch pod CIDR
> ```

This info is readily available from cluster.spec.clusterNetwork.pods.cidrBlocks and cluster.spec.clusterNetwork.services.cidrBlocks
Please address this as part of this PR
___
*[controllers/vcdcluster_controller.go, line 340 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqLBB1L6As7CZCG2lXX:-MqLBB1L6As7CZCG2lXY:b-ac8w3g) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L340)):*
> ```Go
> 		topologyControlPlanes[idx] = topologyControlPlane
> 		templateName = vcdMachineTemplate.Spec.Template.Spec.Template
> 		// TODO: Update RDE with array of kubernetes versions when workload clusters are heterogeneous
> ```

Please remove this TODO, I checked with Arun and this is not a practical usecase
___
*[controllers/vcdcluster_controller.go, line 361 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqLC0lH-KiAQPXzYg5n:-MqLC0lH-KiAQPXzYg5o:b-itmz0x) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L361)):*
> ```Go
> 	}
> 
> 	// TODO: The following code only updates the spec portion of the RDE
> ```

this is just a general comment right, not TODO?
___
*[controllers/vcdcluster_controller.go, line 397 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqLCD-M9VCHJaszPDNT:-MqLCD-N2533NcA7NhHV:b-itmz0x) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L397)):*
> ```Go
> 		},
> 	}
> 	// TODO: We are updaitng status portion of the RDE in the following code
> ```

this is just a general comment right, not TODO?

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10)* status: all files reviewed, 12 unresolved discussions (waiting on @ltimothy7 and @sahithi)

___
*[controllers/vcdcluster_controller.go, line 335 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqFp6L63qvMd5i7zm7O:-MqLwwAyBw9dQVCX7xSE:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9a13eead177ba6a5aec96d3c2ef38d3b3394ab41/controllers/vcdcluster_controller.go#L335)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Tim, Aniruddh and I discussed this, he will make changes to avoid confusion in the next PR.
</blockquote></details>

Done.
___
*[controllers/vcdcluster_controller.go, line 88 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqKtkh530_afmAN8VVU:-MqLrgr85jpCvyiQ_5Bb:b-r5h7fv) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L88)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

For my benefit, where does the client look for "Key" in? Is it always Metadata of the objects? (or) does it recursively look for the keys in the entire object?
</blockquote></details>

I think it will look for "key" only in the metadata
___
*[controllers/vcdcluster_controller.go, line 184 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqKujZ955m4v_SQHcVB:-MqLsUbyBEXYDHhTl0NH:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L184)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

You can remove the comment
</blockquote></details>

Done.
___
*[controllers/vcdcluster_controller.go, line 198 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqL7ICaE24zp4o5OPf2:-MqLEB5D9RK0TC_USM4K:bh4pagn) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L198)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

for my benefit, will it cause any error if we just pass "kcp" instead of "&kcp? (or) does it automatically retrieve the address of kcp?
I want to understand if we are just being good citizens (or) GO is indeed very strict about it?
</blockquote></details>

Since I have declared `getVCDMachineTemplateFromKCP` to use the reference instead of the object itself, &kcp will be needed. Will change it to accept Kcp object directly.
___
*[controllers/vcdcluster_controller.go, line 200 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqKvvwo9xRgoCqM5fRI:-MqLt-7kAdYgEK9gcdGd:b6kkyxf) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L200)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

The exact same error message is returned from r.getVCDMachineTemplateFromKCP, can we just return the error as-is instead of reconstructing the error.
</blockquote></details>

Arun, in one of the older reviews, said it is better to encapsulate all errors.
I will change the string so that they are not the exact same errors.
___
*[controllers/vcdcluster_controller.go, line 203 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqL8IT6-9h3vCi0TT12:-MqLwZ7PBixj7ZtO4g9o:br55oew) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L203)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

same here, does it complain if we use "kcp.Spec.Replicas" without "*"?
</blockquote></details>

Yes, it will complain
___
*[controllers/vcdcluster_controller.go, line 249 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqL8k2y8BfNZoKpv36C:-MqLwtus24j4HhZiX_x6:bnma67e) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L249)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This info is readily available from cluster.spec.clusterNetwork.pods.cidrBlocks and cluster.spec.clusterNetwork.services.cidrBlocks
Please address this as part of this PR
</blockquote></details>

Thanks, Done.
___
*[controllers/vcdcluster_controller.go, line 340 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqLBB1L6As7CZCG2lXX:-MqLx33QDuduP_TdRCme:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L340)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please remove this TODO, I checked with Arun and this is not a practical usecase
</blockquote></details>

Done.
___
*[controllers/vcdcluster_controller.go, line 361 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqLC0lH-KiAQPXzYg5n:-MqLx97sD7vzyuNY3b33:bklmjju) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L361)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

this is just a general comment right, not TODO?
</blockquote></details>

Removed the TODO
___
*[controllers/vcdcluster_controller.go, line 397 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqLCD-M9VCHJaszPDNT:-MqLxJru9iB1V0mqkMNk:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c03b7e49583c51acdaec8a193b3b624fcf7d8065/controllers/vcdcluster_controller.go#L397)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

this is just a general comment right, not TODO?
</blockquote></details>

Done.
___
*[controllers/vcdmachine_controller.go, line 581 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqFpQbz7Q0cBmphi1iO:-MqLxKmq1KB2m1qS4Da6:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9a13eead177ba6a5aec96d3c2ef38d3b3394ab41/controllers/vcdmachine_controller.go#L581)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Commented code should be removed
</blockquote></details>

Done.
___
*[controllers/vcdmachine_controller.go, line 639 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqFpV2eBcE7XW40ShGR:-MqLxLDi-ZB7ZzNwkTuX:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9a13eead177ba6a5aec96d3c2ef38d3b3394ab41/controllers/vcdmachine_controller.go#L639)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Similar here for commented code
</blockquote></details>

Done.

**Review by sahithi — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10)* status: all files reviewed, 14 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sahithi)

___
*[main.go, line 191 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqM6oNIBePyS9iB2xLz:-MqM6oNIBePyS9iB2xM-:b-1ms3xt) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/93321433ef133148756e67c9da21284567939090/main.go#L191)):*
> ```Go
> 	if err != nil {
> 		setupLog.Error(err, "unable to set isManagementCluster flag")
> 		os.Exit(1)
> ```

Remove os.Exit(1)
Just log the error and proceed. Rename the method to be  - SetIsManagementClusterInRDE 
___
*[pkg/vcdclient/defined_entity.go, line 22 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqM7C_U5JYdB87OlBIl:-MqM7C_U5JYdB87OlBIm:bz6h0zd) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/93321433ef133148756e67c9da21284567939090/pkg/vcdclient/defined_entity.go#L22)):*
> ```Go
> 
> // SetIsManagementCluster: sets the isManagementCluster flag in RDE for the management cluster
> func (client *Client) SetIsManagementCluster(ctx context.Context) error {
> ```

I suggest renaming it to be more specific -  SetIsManagementClusterInRDE

**Comment by Anirudh9794** [comment]
___
*[main.go, line 191 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqM6oNIBePyS9iB2xLz:-MqMBVsv7HsImfFWumFh:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/93321433ef133148756e67c9da21284567939090/main.go#L191)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Remove os.Exit(1)
Just log the error and proceed. Rename the method to be  - SetIsManagementClusterInRDE 
</blockquote></details>

Done.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10)* status: 69 of 72 files reviewed, 14 unresolved discussions (waiting on @ltimothy7 and @sahithi)

___
*[pkg/vcdclient/defined_entity.go, line 22 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqM7C_U5JYdB87OlBIl:-MqMBOcs2MOAW_fNgpug:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/93321433ef133148756e67c9da21284567939090/pkg/vcdclient/defined_entity.go#L22)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I suggest renaming it to be more specific -  SetIsManagementClusterInRDE
</blockquote></details>

Done.

**Review by sahithi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10)* status: 68 of 72 files reviewed, 16 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sahithi)

___
*[controllers/vcdmachine_controller.go, line 770 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqQozXS1hBDWH2lB6E-:-MqQozXS1hBDWH2lB6E0:b-hfrzy5) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b5ddd2ed5e096555b493b776372e6d2155fdf447/controllers/vcdmachine_controller.go#L770)):*
> ```Go
> 	}
> 
> 	err = r.syncNodeInRDE(ctx, vcdCluster.Status.RDEId, vcdMachine.Name, machine.Status.Phase, workloadVCDClient)
> ```

reconcileNodeInRDE
___
*[controllers/vcdmachine_controller.go, line 772 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/10#-MqQp1HH5eig_xzISSeo:-MqQp1HIB2EsSXZnLz1F:b-xxqwy5) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b5ddd2ed5e096555b493b776372e6d2155fdf447/controllers/vcdmachine_controller.go#L772)):*
> ```Go
> 	err = r.syncNodeInRDE(ctx, vcdCluster.Status.RDEId, vcdMachine.Name, machine.Status.Phase, workloadVCDClient)
> 	if err != nil {
> 		klog.Errorf("failed to add VCDMachine [%s] to node status: [%v]", vcdMachine.Name, err)
> ```

Please add cluster name in the log messages

**Pull request merged**
