### PR TITLE
[VCDA-4369] Update createdBby version only when capvcd status is misisng

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

## Description
Please provide a brief description of the changes proposed in this Pull Request

- Update createdBy capvcd version before the first update to the capvcd RDE

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies - N/A
- [ ] updated any relevant documentation or examples - N/A

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/256)

### CODE REVIEW

**Review by arunmk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/256)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`controllers/vcdcluster_controller.go` line 585 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/256#-NCQrIeu1q8lQZO1_mas:-NCQrIeu1q8lQZO1_mat:b-kr9zq8) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4f45221a3349b4085cf5d9103b2949356e0b504d/controllers/vcdcluster_controller.go#L585)):*
> ```Go
> 		}
> 	}
> 	if release.CAPVCDVersion != capvcdStatus.CapvcdVersion {
> ```

I am a bit confused by this. When will the two be different? Will the RHS be empty when this occurs?
___
*[`pkg/capisdk/defined_entity.go` line 438 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/256#-NCQrtcLEWWdkEL70WD-:-NCQrtcLEWWdkEL70WD0:b-bhkino) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4f45221a3349b4085cf5d9103b2949356e0b504d/pkg/capisdk/defined_entity.go#L438)):*
> ```Go
> 
> // CheckForEmptyRDEAndUpdateCreatedByVersions updates createdBy version and also sets the value for capvcdVersion in the RDE
> func (capvcdRdeManager *CapvcdRdeManager) CheckForEmptyRDEAndUpdateCreatedByVersions(ctx context.Context, infraId string) error {
> ```

Can we not use the PatchRDE set of helpers here?

**Comment by Anirudh9794** [comment]
*[`controllers/vcdcluster_controller.go` line 585 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/256#-NCQrIeu1q8lQZO1_mas:-NCQxWnX8GYL-4VVJbP8:bx2umjp) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4f45221a3349b4085cf5d9103b2949356e0b504d/controllers/vcdcluster_controller.go#L585)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

I am a bit confused by this. When will the two be different? Will the RHS be empty when this occurs?
</blockquote></details>

Yes, If already populated, the version in the RHS cannot be different than the LHS. I was considering scenarios where CAPVCD gets upgraded to a future version.

**Comment by Anirudh9794** [comment]
*[`pkg/capisdk/defined_entity.go` line 438 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/256#-NCQrtcLEWWdkEL70WD-:-NCQyK0d4BkWVjkeTXv_:b-3739r1) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4f45221a3349b4085cf5d9103b2949356e0b504d/pkg/capisdk/defined_entity.go#L438)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we not use the PatchRDE set of helpers here?
</blockquote></details>

Made changes to include PatchRDE() in the function.
I tried using GetCapvcdRDE() but if capvcd status is empty (i.e "capvcd": {} in the RDE) the GetCapvcdRDE() function will parse the empty capvcd status into struct with default values.

**Review by arunmk — APPROVED** [review]
One small comment but :lgtm: 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/256#-:-NCT0_TG9ghlhmbITmmT:bl3fgik)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`controllers/vcdcluster_controller.go` line 585 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/256#-NCQrIeu1q8lQZO1_mas:-NCT0ACe2JdkaKPDySXR:b-icgmyg) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4f45221a3349b4085cf5d9103b2949356e0b504d/controllers/vcdcluster_controller.go#L585)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Yes, If already populated, the version in the RHS cannot be different than the LHS. I was considering scenarios where CAPVCD gets upgraded to a future version.
</blockquote></details>

yes, and I was worried about that. We should not upgrade the capvcd version to the future version. It should be the version that installed the cluster.

**Comment by Anirudh9794** [comment]
*[`controllers/vcdcluster_controller.go` line 585 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/256#-NCQrIeu1q8lQZO1_mas:-NCVo5ZM2CgsIYAqB4f7:be4104) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4f45221a3349b4085cf5d9103b2949356e0b504d/controllers/vcdcluster_controller.go#L585)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

yes, and I was worried about that. We should not upgrade the capvcd version to the future version. It should be the version that installed the cluster.
</blockquote></details>

After discussion, we decided that capvcdVersion should change while createdBy version should not change.

**Pull request merged**
