### PR TITLE
[VCDA-3797] RDE schema updates for the capvcd cluster

### PR DESCRIPTION
**Pull request by sahithi**
Updated RDE schema for CAPVCD cluster.
Removed all the required fields to ensure flexibility over backward compatibility in the next versions (until the schema stabilizes)

1. Pushed the image - [harbor-repo.vmware.com/vcloud/cluster-api-provider-cloud-director:vkp-branch]? Yes
2. Are there API changes? - No. If yes, please fill in the below
- Updated conversions? No
- Updated CRDs? - No
- Updated capiYaml Examples? - No
- Updated infrastructure-components.yaml? - No
3. Updated VCD-KE with the latest CAPVCD library? - No

Signed-off-by: sayloo <sahithi.ayloo@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/178)

### CODE REVIEW

**Comment by goelaashima** [comment]
*[`schema/schema_1_1_0.json` line 77 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/178#-N4nOlCM7iQVXj-avsfJ:-N4nOlCM7iQVXj-avsfK:b1tm3k9) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/7219a14a9b2b0a7a4944c49935015c4a055b9669/schema/schema_1_1_0.json#L77)):*
> ```JSON
>         "virtualDataCenterName": {
>           "type": "string",
>           "description": "The name of the Organization Virtual data center in which the cluster need to be created or managed."
> ```

one word - datacenter

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/178)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @goelaashima)

___
*[`schema/schema_1_1_0.json` line 77 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/178#-N4nOlCM7iQVXj-avsfJ:-N4rA3Hq8wQW365Mq12I:bfs7i0c) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/7219a14a9b2b0a7a4944c49935015c4a055b9669/schema/schema_1_1_0.json#L77)):*
<details><summary><i>Previously, goelaashima wrote…</i></summary><blockquote>

one word - datacenter
</blockquote></details>

Do you want me to rename virtualDataCenterName to dataCenter?

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/178)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @goelaashima)

___
*[`schema/schema_1_1_0.json` line 77 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/178#-N4nOlCM7iQVXj-avsfJ:-N4rBZWyD_4OttpWFNWD:bat6po8) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/7219a14a9b2b0a7a4944c49935015c4a055b9669/schema/schema_1_1_0.json#L77)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Do you want me to rename virtualDataCenterName to dataCenter?
</blockquote></details>

If yes, it is a breaking change in RDE API from 1.0.0 to 1.1.0, we need to add some extra code to handle it correctly during upgrades.

**Comment by goelaashima** [comment]
*[`schema/schema_1_1_0.json` line 77 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/178#-N4nOlCM7iQVXj-avsfJ:-N56J0L43Y88rA4ZLo2c:b-6qk3f7) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/7219a14a9b2b0a7a4944c49935015c4a055b9669/schema/schema_1_1_0.json#L77)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

If yes, it is a breaking change in RDE API from 1.0.0 to 1.1.0, we need to add some extra code to handle it correctly during upgrades. 
</blockquote></details>

I was talking about the stuff under 'description', there it says virtual data center. datacenter to be one-word. no need to break backward compatibility in any fashion.

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/178)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

**Review by arunmk — APPROVED** [review]
:lgtm: thanks

**Pull request merged**
