### PR TITLE
[VCDA-3166 & VCDA-3156]Redact secrets while printing cloud init & in RDE

### PR DESCRIPTION
**Pull request by Anirudh9794**
Remove Username, RefreshToken and Password from the RDE
Redact secrets from the cloud init scripts printed in the logs

The rest of the Vendor folder got updated as i ran `go mod tidy & go mod vendor`
@sahithi @ltimothy7 

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/17)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 278 of 639 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/17)* status: 278 of 639 files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/17)* status: 278 of 639 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sahithi)

___
*[controllers/capi_objects_utils.go, line 152 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/17#-MqzNtre9wBbfXlXajLw:-MqzNtre9wBbfXlXajLx:beo4gkq) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/5ca78fee06b2ae1f026f453ae2e817b13d52c4ad/controllers/capi_objects_utils.go#L152)):*
> ```Go
> 
> func getCapiYaml(ctx context.Context, cli client.Client, cluster clusterv1.Cluster, vcdCluster infrav1.VCDCluster) (string, error) {
> 	vcdCluster.Spec.UserCredentialsContext.Username = ""
> ```

Please add a comment as to why we are overwriting - redacting reason.
Also, it needs to say something like <REDACTED> rather than "". An empty string is also a value.
___
*[controllers/vcdmachine_controller.go, line 223 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/17#-MqzPYKdC7YP-SqM9zNu:-MqzPYKdC7YP-SqM9zNv:b1zn20n) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/5ca78fee06b2ae1f026f453ae2e817b13d52c4ad/controllers/vcdmachine_controller.go#L223)):*
> ```Go
> func redactCloudInit(cloudInitYaml string, path []string) (string, error) {
> 	yamlRunner := redact.NewYamlRedactor(strings.Join(path, "."), "", "cloudInitRedactor")
> 	outReader := yamlRunner.Redact(bytes.NewReader([]byte(cloudInitYaml)), "")
> ```

how does it know what keys to be redacted for? does it look for set of patterns?

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/17)* status: 275 of 642 files reviewed, 2 unresolved discussions (waiting on @ltimothy7 and @sahithi)

___
*[controllers/capi_objects_utils.go, line 152 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/17#-MqzNtre9wBbfXlXajLw:-Mqzgzu94qdZLLnbuj9r:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/5ca78fee06b2ae1f026f453ae2e817b13d52c4ad/controllers/capi_objects_utils.go#L152)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please add a comment as to why we are overwriting - redacting reason.
Also, it needs to say something like <REDACTED> rather than "". An empty string is also a value.
</blockquote></details>

Done.
___
*[controllers/vcdmachine_controller.go, line 223 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/17#-MqzPYKdC7YP-SqM9zNu:-MqzgDm1DXXzmvK7kCjd:b-i0wvh5) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/5ca78fee06b2ae1f026f453ae2e817b13d52c4ad/controllers/vcdmachine_controller.go#L223)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

how does it know what keys to be redacted for? does it look for set of patterns?
</blockquote></details>

the path represents the key that need to be redacted

**Review by sahithi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/17#-:-Mr-DF3iCJ-Jg04SITaa:bg7igkv)* status: 275 of 643 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sahithi)

___
*[controllers/vcdmachine_controller.go, line 223 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/17#-MqzPYKdC7YP-SqM9zNu:-Mr-CbOT2L_ksbb0gp7v:bwg8uxy) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/5ca78fee06b2ae1f026f453ae2e817b13d52c4ad/controllers/vcdmachine_controller.go#L223)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

the path represents the key that need to be redacted
</blockquote></details>

As discussed, please add a TODO to improve the redaction mechanism to the level of leag nodes (keys)
Please identify the path "path: /root/vcloud-basic-auth.yaml" first and then delete its content. 
Blind deletion of the first element in the list can cause unexpected errors if someone modifies the script.

**Pull request merged**
