### PR TITLE
[VCDA-4558] Update clusterctl, templates and CRS definitions, add v1.21, v1.22 template flavors for 1.0.z

### PR DESCRIPTION
**Pull request by lzichong**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- Contains changes that were recently merged into main, but cannot cherrypick over due to harbor links. This PR uses manifests from their corresponding release branches

## Checklist
- [ ] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/305)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: Some files are missing new line at the end

> Reviewed 13 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/305#-:-NEgt25y3Umi8ryYg14W:b-jre6xt)* status: 13 of 16 files reviewed, 1 unresolved discussion (waiting on @lzichong and @sahithi)

___
*[`templates/cluster-template-v1.20.8.yaml` line 53 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/305#-NEgsIhp80ny49YKT1bD:-NEgsIhp80ny49YKT1bE:bw31o10) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/cc0bba81d0bedd6519cf7a2b325d3187578b490d/templates/cluster-template-v1.20.8.yaml#L53)):*
> ```YAML
>       namespace: ${TARGET_NAMESPACE} # name of the secret containing the credentials of the VCD persona creating the cluster
>   loadBalancerConfigSpec:
>     vipSubnet: "" # Virtual IP CIDR for the external network
> ```

should this be ${VCD_VIP_CIDR} ?

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/305)* status: 13 of 16 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @sahithi)

___
*[`templates/cluster-template-v1.20.8.yaml` line 53 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/305#-NEgsIhp80ny49YKT1bD:-NEgtdFQ2lhNXVP1pZp_:b-nzh10w) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/cc0bba81d0bedd6519cf7a2b325d3187578b490d/templates/cluster-template-v1.20.8.yaml#L53)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

should this be ${VCD_VIP_CIDR} ?
</blockquote></details>

It was originally but Sahithi and I had discussed about this variable and we concluded that we can leave it as an empty string as this does not force users to input the IP as they may not know of the field, and since we also have a fallback mechanism in CAPVCD where if it is empty it will pull the next available IP on the gateway so we had decided to omit it for now and will revisit whether to add it to clusterctl variable or not post GA

**Review by sahithi — APPROVED** [review]
:lgtm: after last few comments are addressed

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/305#-:-NEwAg3fAgnJdBncFOaS:bnwbixm)* status: 9 of 16 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @lzichong)

___
*[`templates/cluster-template-v1.20.8.yaml` line 69 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/305#-NEwAHR6AxD0zh9qycHe:-NEwAHR6AxD0zh9qycHf:bd6ugy2) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f9d56cf9d612ad9a485ce06ed675756941f15335/templates/cluster-template-v1.20.8.yaml#L69)):*
> ```YAML
>       storageProfile: "${VCD_CONTROL_PLANE_STORAGE_PROFILE}" # Storage profile to be used for the control plane VMs (this must be pre-published on the chosen organization virtual datacenter)
>       diskSize: ${DISK_SIZE}
>       enableNvidiaGPU: false
> ```

Please remove this property, there is a decision made today by Aashima that we are pulling GPU feature out of GA - here and all other places
___
*[`templates/cluster-template-v1.20.8.yaml` line 133 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/305#-NEwATLdCGDPS2onHp3B:-NEwATLdCGDPS2onHp3C:b-pchx5r) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f9d56cf9d612ad9a485ce06ed675756941f15335/templates/cluster-template-v1.20.8.yaml#L133)):*
> ```YAML
>       storageProfile: "${VCD_WORKER_STORAGE_PROFILE}" # Storage profile to be used for the control plane VMs (this must be pre-published on the chosen organization virtual datacenter)
>       diskSize: ${DISK_SIZE}
>       enableNvidiaGPU: false
> ```

same here, please remove
___
*[`templates/cluster-template-v1.20.8-crs.yaml` line 73 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/305#-NEwAWZZ04nJgKda2Y1n:-NEwAWZZ04nJgKda2Y1o:bpgwxg1) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f9d56cf9d612ad9a485ce06ed675756941f15335/templates/cluster-template-v1.20.8-crs.yaml#L73)):*
> ```YAML
>       storageProfile: "${VCD_CONTROL_PLANE_STORAGE_PROFILE}" # Storage profile for control plane machine if any
>       diskSize: ${DISK_SIZE} # Disk size to use for the control plane machine, defaults to 20Gi
>       enableNvidiaGPU: false
> ```

here as well

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/305)* status: 7 of 16 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`templates/cluster-template-v1.20.8.yaml` line 69 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/305#-NEwAHR6AxD0zh9qycHe:-NEwIMuA7AmpP-7ue-_x:brtemkg) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f9d56cf9d612ad9a485ce06ed675756941f15335/templates/cluster-template-v1.20.8.yaml#L69)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please remove this property, there is a decision made today by Aashima that we are pulling GPU feature out of GA - here and all other places
</blockquote></details>

Hi Sahithi, I have removed all enableNvidiaGPU flags from all clusterctl-templates including base template and flavors, thanks for the update!
___
*[`templates/cluster-template-v1.20.8.yaml` line 133 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/305#-NEwATLdCGDPS2onHp3B:-NEwIGEr2Ew7KfWzjrFC:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f9d56cf9d612ad9a485ce06ed675756941f15335/templates/cluster-template-v1.20.8.yaml#L133)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

same here, please remove
</blockquote></details>

Done.
___
*[`templates/cluster-template-v1.20.8-crs.yaml` line 73 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/305#-NEwAWZZ04nJgKda2Y1n:-NEwIGvo6vNHBSV2dOtX:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f9d56cf9d612ad9a485ce06ed675756941f15335/templates/cluster-template-v1.20.8-crs.yaml#L73)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

here as well
</blockquote></details>

Done.

**Pull request merged**
