### PR TITLE
[CAFV-332] Changes to avoid failure during update to vcdResourceSet, eventSet or errorSet

### PR DESCRIPTION
**Pull request by Anirudh9794**
… errorSet

## Description
Please provide a brief description of the changes proposed in this Pull Request

- VCD has a bug where update to errorSet, eventSet or vcdResourceSet may fail. This PR ensures that RDE updates won't stop cluster creation/deletion.

## Checklist
- [x] tested locally
- [x] updated any relevant dependencies
- [x] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/537)

### CODE REVIEW

**Review by sahithi — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/537)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by sakthisunda — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/537)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 1166 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/537#-NiLbBUZ8mf8uWub4LuP:-NiLbBU_9kLagqjN88cs:b-y2kp1s) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/416041f95ba465be9c90463dbc9767e39d7aff1e/controllers/vcdcluster_controller.go#L1166)):*
> ```Go
> 			log.Error(err, "failed to add VApp ID to RDE", "rdeID", infraID, "vappID", clusterVApp.VApp.ID)
> 		}
> 		log.Info("successfully updated external ID of RDE with VApp ID", "infraID", infraID, "vAppID", clusterVApp.VApp.ID)
> ```

After removing the return statement, we have now two log statements

1. log.Error
2. log.Info

Question:  Is log.Info() message still valid?

**Review by sakthisunda — COMMENTED** [review]
LGTM after addressing review comment

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/537#-:-NiLcFqy6EQV17JT45FM:b-locnc2)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @sahithi)

**Review by sakthisunda — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/537#-:-NiLcMBQ2JExpHRkY79U:bnfp4nl)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @sahithi)

**Comment by Anirudh9794** [comment]
*[`controllers/vcdcluster_controller.go` line 1166 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/537#-NiLbBUZ8mf8uWub4LuP:-NiLcA433ijMnZw1wG1J:b6qhu3p) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/416041f95ba465be9c90463dbc9767e39d7aff1e/controllers/vcdcluster_controller.go#L1166)):*
<details><summary><i>Previously, sakthisunda (Sakthi Sundaram) wrote…</i></summary><blockquote>

After removing the return statement, we have now two log statements

1. log.Error
2. log.Info

Question:  Is log.Info() message still valid?
</blockquote></details>

Yes, the log.Info() doesn't make sense. I will add this log statement to an `else` block.

**Pull request merged**
