### PR TITLE
VCDA-3632 add support for specifying placement policy in vcdmachine manifest

### PR DESCRIPTION
**Pull request by abaruni**
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/127)

### CODE REVIEW

**Review by arunmk — APPROVED** [review]
:lgtm: with a few nits

> Reviewed 6 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/127#-:-N1CFO7x4UhlArUn-xu6:bhcznl8)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @abaruni and @arunmk)

___
*[`api/v1alpha4/zz_generated.deepcopy.go` line 1 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/127#-N1C-NpN-UPDttqU2RHh:-N1C-NpO1sid1nLAqEVc:b-fr2jut) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9b55d5dc8105c1d149116379152e68869a2d0d64/api/v1alpha4/zz_generated.deepcopy.go#L1)):*
> ```Go
> //go:build !ignore_autogenerated
> ```

can you run `make vendor`
___
*[`api/v1beta1/zz_generated.deepcopy.go` line 1 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/127#-N1C3Can5R90mRdQTpa5:-N1C3Can5R90mRdQTpa6:bluy7p8) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9b55d5dc8105c1d149116379152e68869a2d0d64/api/v1beta1/zz_generated.deepcopy.go#L1)):*
> ```Go
> //go:build !ignore_autogenerated
> ```

same here, a `make vendor` will put this back
___
*[`config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml` line 263 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/127#-N1C9ct6CzdREzCENxKs:-N1C9ct6CzdREzCENxKt:b-did9w3) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3192f2e0c48e1a54bbd73e2211710dae170fe8bb/config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml#L263)):*
> ```YAML
>                       type: string
>                   required:
>                   - lastTransitionTime
> ```

which change brought this in? I don't see removal of an `omitempty`

**Review by abaruni — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/127)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @arunmk)

___
*[`config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml` line 263 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/127#-N1C9ct6CzdREzCENxKs:-N1EZHON8WE496Tw7ohT:b-5y4cfl) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/3192f2e0c48e1a54bbd73e2211710dae170fe8bb/config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml#L263)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

which change brought this in? I don't see removal of an `omitempty`
</blockquote></details>

i'm not sure. i myself was wondering what brought this in. but this is where it comes from https://github.com/kubernetes-sigs/cluster-api/blob/main/api/v1alpha4/condition_types.go
___
*[`api/v1alpha4/zz_generated.deepcopy.go` line 1 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/127#-N1C-NpN-UPDttqU2RHh:-N1EZG6X3f4I8FtCPLmY:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9b55d5dc8105c1d149116379152e68869a2d0d64/api/v1alpha4/zz_generated.deepcopy.go#L1)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

can you run `make vendor`
</blockquote></details>

Done.
___
*[`api/v1beta1/zz_generated.deepcopy.go` line 1 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/127#-N1C3Can5R90mRdQTpa5:-N1EZGgzA1EpughuiYIE:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9b55d5dc8105c1d149116379152e68869a2d0d64/api/v1beta1/zz_generated.deepcopy.go#L1)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

same here, a `make vendor` will put this back
</blockquote></details>

Done.

**Review by sahithi — APPROVED** [review]
:lgtm: (after addressing above comments)

> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/127#-:-N1FyCRl2cJjrYM8XHvj:bb2659)* status: all files reviewed, 3 unresolved discussions (waiting on @arunmk)

**Review by sahithi — APPROVED** [review]
please updated example capiyaml

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/127#-:-N1FyWfA48-cIUajX3ke:b-anzcl2)* status: all files reviewed, 3 unresolved discussions (waiting on @arunmk)

**Review by abaruni — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/127#-:-N1GglgpAAcyKVXGFCfO:bb7f2mf)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @arunmk and @sahithi)

**Pull request merged**
