### PR TITLE
[VCDA-3636] Nvidia GPU support for containerd in cloud init script

### PR DESCRIPTION
**Pull request by abaruni**
- Addition of Nvidia runtime installation in cloud init script
- Installation and configuration of Nvidia plugin in containerd conf file
- Common cloud init template to reduce duplication between node types
- Conditional logic in cloud init template to handle presence of gpu support
- Support of common template inside vcdmachine controller

Testing done:
- compare cloud init output from common template for both control plane node and worker node with those generated without these changes
- create clusters with nvidiaGPU flag set and not set to ensure correct cloud init template is used
- ensure that containerd changes take effect and that containerd is able to start successfully
- following commands were run on vm to ensure containerd changes were picked up successfully

```
ctr image pull docker.io/nvidia/cuda:11.0-base
ctr run --rm --gpus 0 -t docker.io/nvidia/cuda:11.0-base cuda-11.0-base nvidia-smi
```

for template reference: https://pkg.go.dev/text/template

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152)

### CODE REVIEW

**Review by arunmk — APPROVED** [review]
:lgtm: thanks for doing this. I have a few small comments based on issues from past experience.

Regarding the templating itself, it is very nice! But I want to get your thoughts on how we can improve readability in the scripts. I want to know if we can make it clearer in terms of indentation, knowing where a template block starts (when we see the end block) etc. Could we chat about it sometime?

> Reviewed 1 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-:-N2sqPdlBIvosvePgNUC:b-gn4nb1)* status: 1 of 10 files reviewed, 12 unresolved discussions (waiting on @abaruni and @arunmk)

___
*[`api/v1beta1/zz_generated.deepcopy.go` line 65 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-N2si6IQ3cK01zo4Xn5W:-N2si6IQ3cK01zo4Xn5X:b-hmqjg4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f1f166ccebf6e9502eb3d4093c227073dd87d7ee/api/v1beta1/zz_generated.deepcopy.go#L65)):*
> ```Go
> 
> // DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyConfig.
> func (in *ProxyConfig) DeepCopy() *ProxyConfig {
> ```

@sakthisunda this should have come in as part of your changes. Just mentioning as fyi
___
*[`config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml` line 283 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-N2siK5uDTBNp1ZpZLke:-N2siK5uDTBNp1ZpZLkf:bltjc8e) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f1f166ccebf6e9502eb3d4093c227073dd87d7ee/config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml#L283)):*
> ```YAML
>               parentUid:
>                 type: string
>               proxyConfig:
> ```

hmm...I am getting confused...maybe this needs a rebase?
___
*[`controllers/vcdmachine_controller.go` line 523 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-N2sjmwM2WP200O_cMzK:-N2sjmwM2WP200O_cMzL:bilomaq) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f1f166ccebf6e9502eb3d4093c227073dd87d7ee/controllers/vcdmachine_controller.go#L523)):*
> ```Go
> 				EnableDefaultStorageClass: strconv.FormatBool(enableDefaultStorageClass),
> 			}
> 		} else if !util.IsControlPlaneMachine(machine) && vcdMachine.Spec.NvidiaGPU {
> ```

Ideally we don't have GPUs on control-plane nodes, but I have seen examples where customers want to buy homogenous very large nodes with GPUs and also schedule workloads on control-plane nodes. We should not add this restriction on our side and let it be handled by the taints system on the cluster.
___
*[`controllers/vcdmachine_controller.go` line 524 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-N2sjFLxEGTR6JA4W1J8:-N2sjFLxEGTR6JA4W1J9:bktj81t) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f1f166ccebf6e9502eb3d4093c227073dd87d7ee/controllers/vcdmachine_controller.go#L524)):*
> ```Go
> 			}
> 		} else if !util.IsControlPlaneMachine(machine) && vcdMachine.Spec.NvidiaGPU {
> 			if vcdMachine.Spec.PlacementPolicy == "" {
> ```

There is a check in VCD which covers this. Can we skip this validation? We don't want to add some checks which could be removed in VCD later, or implemented in a different way.
___
*[`controllers/vcdmachine_controller.go` line 1073 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-N2sljNCCqHYfJYewUxk:-N2sljNCCqHYfJYewUxl:b-q0j918) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f1f166ccebf6e9502eb3d4093c227073dd87d7ee/controllers/vcdmachine_controller.go#L1073)):*
> ```Go
> 			formattedJinjaCmd += indent + jinjaLineStr + "\n"
> 		}
> 		cloudInitConfig.BootstrapRunCmd = strings.Trim(strings.Trim(formattedJinjaCmd, "\n"), "\r\n")
> ```

Can we do this in a non-nested trim?
___
*[`controllers/vcdmachine_controller.go` line 1081 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-N2sm9_s3GSbOZ5_n1-Y:-N2sm9_s3GSbOZ5_n1-Z:be13g69) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f1f166ccebf6e9502eb3d4093c227073dd87d7ee/controllers/vcdmachine_controller.go#L1081)):*
> ```Go
> 	}
> 	buff := bytes.Buffer{}
> 	if err = cloudInitTemplate.Execute(&buff, cloudInitConfig); err != nil {
> ```

Is it possible to Execute the template and pass the expanded template as input to `MergeJinjaToCloudInitScript`? The reason I ask is because we don't have control over what bootstrap script is sent, and we don't want to have any templating in bootstrap which could collide with what we have here. (As a reference, when we used `%s` earlier, there were such placeholders in the jinja script from bootstrap).
___
*[`controllers/cluster_scripts/cloud_init.tmpl` line 54 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-N2snm2_50fobsOa6m6e:-N2snm2_50fobsOa6m6f:b-dui7y3) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f1f166ccebf6e9502eb3d4093c227073dd87d7ee/controllers/cluster_scripts/cloud_init.tmpl#L54)):*
> ```
>     set -ex
> 
>     echo "$(date) Post Customization script execution in progress" &>> /var/log/capvcd/customization/status.log {{- if .ControlPlane }}
> ```

should this be in the next line?
___
*[`controllers/cluster_scripts/cloud_init.tmpl` line 93 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-N2so1HW50ZWfzMsI8DI:-N2so1HW50ZWfzMsI8DJ:b-r6b9er) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f1f166ccebf6e9502eb3d4093c227073dd87d7ee/controllers/cluster_scripts/cloud_init.tmpl#L93)):*
> ```
>     vmtoolsd --cmd "info-set guestinfo.postcustomization.proxy.setting.status successful" {{- if .NvidiaGPU }}
> 
>     vmtoolsd --cmd "info-set guestinfo.postcustomization.nvidia.runtime.install.status in_progress"
> ```

Curious if we can put `{{- if .NvidiaGPU }}` at the start of this line? This lines up cleanly with putting `{{- end}}` at end of the successful mark below.



_Code quote:_
```
{{- if .NvidiaGPU }}
```
___
*[`controllers/cluster_scripts/cloud_init.tmpl` line 168 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-N2soo31Ch-O7Ro0vNcC:-N2soo31Ch-O7Ro0vNcD:b-ef466y) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f1f166ccebf6e9502eb3d4093c227073dd87d7ee/controllers/cluster_scripts/cloud_init.tmpl#L168)):*
> ```
>     vmtoolsd --cmd "info-set guestinfo.postcustomization.containerd.nvidia.configuration.status in_progress"
>     cat > /etc/containerd/config.toml << EOF
>     ## template: jinja
> ```

we can put this into the `write_files` section. That will make the script cleaner.
___
*[`controllers/cluster_scripts/cloud_init.tmpl` line 192 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-N2spNTs1jRK-lT9rqrP:-N2spNTs1jRK-lT9rqrQ:b3de3e1) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f1f166ccebf6e9502eb3d4093c227073dd87d7ee/controllers/cluster_scripts/cloud_init.tmpl#L192)):*
> ```
>         bin_dir = "/opt/cni/bin"
>         conf_dir = "/etc/cni/net.d"
>         [plugins."io.containerd.grpc.v1.cri".registry]
> ```

I think from this line onwards it's the docker login auth method. We can get rid of these until we have a story for that.
___
*[`controllers/cluster_scripts/cloud_init.tmpl` line 211 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-N2spuAjCe5K_XYWW89T:-N2spuAjCe5K_XYWW89U:b-eoqws2) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f1f166ccebf6e9502eb3d4093c227073dd87d7ee/controllers/cluster_scripts/cloud_init.tmpl#L211)):*
> ```
> runcmd: {{- if .ControlPlane }}
> - '[ ! -f /root/vcloud-basic-auth.yaml ] && cloud-init clean && sudo reboot' {{- end }}
> - '[ ! -f /root/ {{- if .ControlPlane -}} control_plane {{- else -}} node {{- end -}} .sh ] && cloud-init clean && sudo reboot'
> ```

I am thinking we should just call both files as `node.sh` so that we don't lose readability
___
*[`controllers/cluster_scripts/cloud_init.tmpl` line 214 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-N2sqBAd1ZPtidKF0Sjs:-N2sqBAd1ZPtidKF0Sjt:b-rqqszc) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f1f166ccebf6e9502eb3d4093c227073dd87d7ee/controllers/cluster_scripts/cloud_init.tmpl#L214)):*
> ```
> {{/* Only checking if /run/kubeadm/kubeadm(-join-config).yaml as this is the main file for kubeadm (init | join).*/}}
> {{/* Ignoring checks for .cert and .key files*/}}
> - '[ ! -f /run/kubeadm/kubeadm {{- if not .ControlPlane -}} -join-config {{- end -}} .yaml ] && cloud-init clean && sudo reboot'
> ```

maybe we should rename the join config also to a kubeadm config so as to make things more readable.

**Review by arunmk — COMMENTED** [review]
There is some issue where some of Sakthi's changes are here. Maybe he did not run the converter-gen or there is a rebase needed. Could you please check that as well.

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-:-N2srIOOBncmV9yFDxzd:bl5z9zx)* status: 1 of 10 files reviewed, 12 unresolved discussions (waiting on @abaruni and @arunmk)

**Review by abaruni — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152)* status: 0 of 10 files reviewed, 12 unresolved discussions (waiting on @abaruni and @arunmk)

___
*[`config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml` line 283 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-N2siK5uDTBNp1ZpZLke:-N3-vVWF1acQ3_edHER7:b-hm0ll1) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f1f166ccebf6e9502eb3d4093c227073dd87d7ee/config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml#L283)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

hmm...I am getting confused...maybe this needs a rebase?
</blockquote></details>

rebased

**Review by abaruni — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152)* status: 0 of 10 files reviewed, 12 unresolved discussions (waiting on @abaruni and @arunmk)

___
*[`controllers/vcdmachine_controller.go` line 523 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-N2sjmwM2WP200O_cMzK:-N3-y0C117wJPNb-Yoy9:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f1f166ccebf6e9502eb3d4093c227073dd87d7ee/controllers/vcdmachine_controller.go#L523)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Ideally we don't have GPUs on control-plane nodes, but I have seen examples where customers want to buy homogenous very large nodes with GPUs and also schedule workloads on control-plane nodes. We should not add this restriction on our side and let it be handled by the taints system on the cluster.
</blockquote></details>

Done.
___
*[`controllers/vcdmachine_controller.go` line 524 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-N2sjFLxEGTR6JA4W1J8:-N3-y1GO1h24fbvXQGlm:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f1f166ccebf6e9502eb3d4093c227073dd87d7ee/controllers/vcdmachine_controller.go#L524)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

There is a check in VCD which covers this. Can we skip this validation? We don't want to add some checks which could be removed in VCD later, or implemented in a different way.
</blockquote></details>

Done.
___
*[`controllers/vcdmachine_controller.go` line 1073 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-N2sljNCCqHYfJYewUxk:-N3-y3i640bBqatAXCA6:b-w650k5) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f1f166ccebf6e9502eb3d4093c227073dd87d7ee/controllers/vcdmachine_controller.go#L1073)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we do this in a non-nested trim?
</blockquote></details>

i'm honestly not sure. i copied what was being done before. i assumed the presence of an explicit carriage return meant we were handling some edge case(?)
___
*[`controllers/vcdmachine_controller.go` line 1081 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/152#-N2sm9_s3GSbOZ5_n1-Y:-N3-yIxZB3XnX4hSrHOJ:bbzb1y6) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f1f166ccebf6e9502eb3d4093c227073dd87d7ee/controllers/vcdmachine_controller.go#L1081)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Is it possible to Execute the template and pass the expanded template as input to `MergeJinjaToCloudInitScript`? The reason I ask is because we don't have control over what bootstrap script is sent, and we don't want to have any templating in bootstrap which could collide with what we have here. (As a reference, when we used `%s` earlier, there were such placeholders in the jinja script from bootstrap).
</blockquote></details>

discussed with @arunmk and we're good to keep as is in this PR and revisit should anything arise in the future due to presence of templating or format strings in the bootstrap cmd

**Pull request merged**
