### PR TITLE
[VCDA-3202] fix using default cloud config values

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy7 <66969084+ltimothy7@users.noreply.github.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/24)

### CODE REVIEW

**Comment by ltimothy7** [comment]
___
*[pkg/config/cloudconfig.go, line 111 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/24#-MrOlCvG5zyYFVVLBfOZ:-MrOlCvG5zyYFVVLBfO_:b4uul8k) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/7d3c1abfd037f7f0e886a40510c85f24c23c6ca5/pkg/config/cloudconfig.go#L111)):*
> ```Go
> 		},
> 		ClusterResources: ClusterResourcesConfig{
> 			CsiVersion: "1.0.x",
> ```

Changing these versions can be a separate task too

**Review by arunmk — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/24)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @arunmk and @ltimothy7)

___
*[pkg/config/cloudconfig.go, line 111 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/24#-MrOlFK74eVbBug6e8Yp:-MrOlFK89ntVwqU3I9iR:b4uuv9) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/7d3c1abfd037f7f0e886a40510c85f24c23c6ca5/pkg/config/cloudconfig.go#L111)):*
> ```Go
> 		},
> 		ClusterResources: ClusterResourcesConfig{
> 			CsiVersion: "1.0.x",
> ```

Can we use `main` here for CSI and CPI. We can use the right versions later as part of the other task.

**Review by arunmk — APPROVED** [review]
:lgtm: with a minor ask.

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/24#-:-MrOlT78-1cjcwIzagDO:b-v8x0xi)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @arunmk and @ltimothy7)

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/24#-:-MrOlo5i5zmbwniidj7T:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @ltimothy7)

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/24)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[pkg/config/cloudconfig.go, line 111 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/24#-MrOlFK74eVbBug6e8Yp:-MrOqhjX-Ef5jydZXYR9:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/7d3c1abfd037f7f0e886a40510c85f24c23c6ca5/pkg/config/cloudconfig.go#L111)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we use `main` here for CSI and CPI. We can use the right versions later as part of the other task.
</blockquote></details>

Done.

**Pull request merged**
