### PR TITLE
Clean up CAPVCD logs

### PR DESCRIPTION
**Pull request by sahithi**
Added more context  (cluster name, machine name) to all the logs coming from controllers
Edited all the log statements to follow the same format and terminology
Commented out few redundant logs coming from vcdClient files (did not delete them yet to ensure troubleshooting during our development).

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/18)

### CODE REVIEW

**Review by ltimothy7 — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/18)* status: all files reviewed, 3 unresolved discussions (waiting on @sahithi)

___
*[pkg/vcdclient/defined_entity.go, line 70 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/18#-MqyiylZ0UpaSjGEzTeh:-MqyiylZ0UpaSjGEzTei:bl55h82) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e9d8c82340ab04513e82f1f42ba60a0f574b344a/pkg/vcdclient/defined_entity.go#L70)):*
> ```Go
> 			fields := strings.Split(k, ".")
> 			updatedVal := reflect.ValueOf(v)
> 			// klog.Infof("Assigning value %v to key %s", v, k)
> ```

Should these lines be removed/replaced with a different logger based on ctx?
___
*[pkg/vcdclient/gateway.go, line 90 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/18#-Mqyj6J19spN3oRqgq0u:-Mqyj6J19spN3oRqgq0v:bmuqxk4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e9d8c82340ab04513e82f1f42ba60a0f574b344a/pkg/vcdclient/gateway.go#L90)):*
> ```Go
> 	gateway.NetworkBackingType = *ovdcNetwork.BackingNetworkType
> 
> 	//klog.Infof("Obtained GatewayManager [%s] for Network Name [%s] of type [%v]\n",
> ```

Same here: should this be removed and replaced by the logger from context?
___
*[pkg/vcdclient/vms.go, line 116 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/18#-MqyjCJY167RbNlfoJRO:-MqyjCJY167RbNlfoJRP:b-wb03ao) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e9d8c82340ab04513e82f1f42ba60a0f574b344a/pkg/vcdclient/vms.go#L116)):*
> ```Go
> 	guestCustScript string, acceptAllEulas bool, powerOn bool) (govcd.Task, error) {
> 
> 	// klog.Infof("start adding %d VMs\n", vmNum)
> ```

Same here about removing and replacing with logger from ctx

**Comment by Anirudh9794** [comment]
___
*[controllers/vcdcluster_controller.go, line 261 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/18#-Mqz5LEB5NhDYagmLrGq:-Mqz5LEB5NhDYagmLrGr:bjdgpi8) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e9d8c82340ab04513e82f1f42ba60a0f574b344a/controllers/vcdcluster_controller.go#L261)):*
> ```Go
> 	resp, err := workloadVCDClient.ApiClient.DefinedEntityApi.CreateDefinedEntity(ctx, *rde, rde.EntityType, nil)
> 	if err != nil {
> 		return "", fmt.Errorf("error occurred during RDE creation for the cluster [%s]: [%v]", vcdCluster.Name, err)
> ```

If there is a 400 bad request. We won't be able to detect which function failed from just the logs as both of the errors will say
"error occurred during RDE creation for the cluster [clustername]: [400 Bad Request]"

Should we make the errors slightly different so that it will be easier to debug?

**Review by Anirudh9794 — COMMENTED** [review]
:lgtm: minor comment

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/18#-:-Mqz83rJ-p7thMZhBn9e:basp5ut)* status: all files reviewed, 4 unresolved discussions (waiting on @sahithi)

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/18)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sahithi)

___
*[controllers/vcdcluster_controller.go, line 261 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/18#-Mqz5LEB5NhDYagmLrGq:-MqzWQqI2wNwLelw_F1V:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e9d8c82340ab04513e82f1f42ba60a0f574b344a/controllers/vcdcluster_controller.go#L261)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

If there is a 400 bad request. We won't be able to detect which function failed from just the logs as both of the errors will say
"error occurred during RDE creation for the cluster [clustername]: [400 Bad Request]"

Should we make the errors slightly different so that it will be easier to debug?
</blockquote></details>

Done.
___
*[pkg/vcdclient/defined_entity.go, line 70 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/18#-MqyiylZ0UpaSjGEzTeh:-MqzWVVx-q_qmjw-WM2x:b-amp0sm) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e9d8c82340ab04513e82f1f42ba60a0f574b344a/pkg/vcdclient/defined_entity.go#L70)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Should these lines be removed/replaced with a different logger based on ctx?
</blockquote></details>

As mentioned in the scrum, I have commented them out temporarily.
I have created another task to do the changes in the client files. The scope of this task is to just clean controller logs.

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/18)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sahithi)

**Pull request merged**
