### PR TITLE
[VCDA-3198, VCDA-3199] Check if VS not pending to retry with reconciliation and worker controller thread increase

### PR DESCRIPTION
**Pull request by Anirudh9794**
* Remove the retries in checkIfVSNotPending function. Make reconciliation retry the check
* Increase the worker controller threads to 10
* Remove lines to force systemd in cloud init scripts.

Testing done:
* Removed all the VS and checked if the cluster is waiting for VS to come up before attempting creation of a machine

@arunmk @ltimothy7 @sahithi

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/26)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/26)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by arunmk — APPROVED** [review]
:lgtm: with a minor recommendation

> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/26#-:-MrTg3890rXNZh_KbBq6:b7b531q)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @ltimothy7)

___
*[controllers/vcdcluster_controller.go, line 517 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/26#-MrTei7MEW42ZNBoCmAP:-MrTei7MEW42ZNBoCmAQ:b-ht3abb) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e28eba5221ff49384c9168e64ebcbdb50ced2376/controllers/vcdcluster_controller.go#L517)):*
> ```Go
> 		log.Info("Creating load balancer for the cluster")
> 		controlPlaneNodeIP, err = gateway.CreateL4LoadBalancer(ctx, virtualServiceNamePrefix, lbPoolNamePrefix,
> 			[]string{}, 6443)
> ```

Not part of this ticket, but we may need to use the port from the config.
___
*[pkg/vcdclient/gateway.go, line 950 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/26#-MrTfmaF3T1_TuLpp6EK:-MrTfmaF3T1_TuLpp6EL:b-g3ykgk) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e28eba5221ff49384c9168e64ebcbdb50ced2376/pkg/vcdclient/gateway.go#L950)):*
> ```Go
> 	}
> 
> 	klog.Errorf("Virtual service [%s] is still pending", virtualServiceName)
> ```

Can we print the current state of the virtual service here?

**Review by sahithi — APPROVED** [review]
:lgtm: please ensure log statements look clear in the case of error scenarios

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/26#-:-MrTkCcu6IH6sX86KNZM:b-6p9w4p)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, and @sahithi)

___
*[controllers/vcdcluster_controller.go, line 512 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/26#-MrTjFtT2OOVTcPqXR6L:-MrTjFtT2OOVTcPqXR6M:bz88uct) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e28eba5221ff49384c9168e64ebcbdb50ced2376/controllers/vcdcluster_controller.go#L512)):*
> ```Go
> 	if err != nil {
> 		if vsError, ok := err.(*vcdclient.VirtualServicePendingError); ok {
> 			return ctrl.Result{}, errors.Wrapf(err, "Error getting load balancer. Virtual Service [%s] is pending", vsError.VirtualServiceName)
> ```

Error statement needs to have cluster name. Extra key-value pairs get added only to log.Info and log.Error statements.
___
*[pkg/vcdclient/gateway.go, line 945 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/26#-MrTiC7-5RXMyOqXvYR9:-MrTiC70A6f1Xh3oHovg:b-3emeqo) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e28eba5221ff49384c9168e64ebcbdb50ced2376/pkg/vcdclient/gateway.go#L945)):*
> ```Go
> 	}
> 	if vsSummary.HealthStatus == "UP" || vsSummary.HealthStatus == "DOWN" {
> 		klog.Infof("Completed waiting for [%s] since healthStatus is [%s]",
> ```

change the log level to 3

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/26)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @arunmk, @ltimothy7, and @sahithi)

___
*[controllers/vcdcluster_controller.go, line 512 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/26#-MrTjFtT2OOVTcPqXR6L:-MrTnDxI73YCnw8y7xID:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e28eba5221ff49384c9168e64ebcbdb50ced2376/controllers/vcdcluster_controller.go#L512)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Error statement needs to have cluster name. Extra key-value pairs get added only to log.Info and log.Error statements.
</blockquote></details>

Done.
___
*[controllers/vcdcluster_controller.go, line 517 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/26#-MrTei7MEW42ZNBoCmAP:-MrTnRY0D3wiNdekrbEn:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e28eba5221ff49384c9168e64ebcbdb50ced2376/controllers/vcdcluster_controller.go#L517)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Not part of this ticket, but we may need to use the port from the config.
</blockquote></details>

Done.
___
*[pkg/vcdclient/gateway.go, line 945 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/26#-MrTiC7-5RXMyOqXvYR9:-MrTpgur6bUtu2f8NlS8:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e28eba5221ff49384c9168e64ebcbdb50ced2376/pkg/vcdclient/gateway.go#L945)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

change the log level to 3
</blockquote></details>

Done.
___
*[pkg/vcdclient/gateway.go, line 950 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/26#-MrTfmaF3T1_TuLpp6EK:-MrTqEGU3sT2mPCAUyEy:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e28eba5221ff49384c9168e64ebcbdb50ced2376/pkg/vcdclient/gateway.go#L950)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we print the current state of the virtual service here?
</blockquote></details>

Done.

**Pull request merged**
