### PR TITLE
[CAFV-220] Update UPGRADES doc for upgrading CAPVCD 1.0.x to CAPVCD 1.0.2

### PR DESCRIPTION
**Pull request by lzichong**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- Update UPGRADE docs to provide a command to update deployment image to version 1.0.2

## Checklist
- [ ] tested locally
- [ ] updated any relevant dependencies
- [x] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/432)

### CODE REVIEW

**Review by ymo24 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/432)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @Anirudh9794, @lzichong, and @sahithi)

___
*[`docs/UPGRADES.md` line 3 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/432#-NSwxg5-4VbTIw5faaQv:-NSwxg5-4VbTIw5faaQw:b-7pqqqn) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9bab73c17375839515f5fade6447ac84c7e5a27f/docs/UPGRADES.md#L3)):*
> ```Markdown
> # CAPVCD Upgrades
> 
> ## Upgrades from CAPVCD 0.5.0 to 1.0.0
> ```

Would you please use 0.5.x to replace 0.5.0. CAPVCD has two versions for 0.5.x: 0.5.0 and 0.5.1

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/432)* status: all files reviewed, 1 unresolved discussion (waiting on @lzichong and @sahithi)

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/432#-:-NWEPbKECTVLsv_cbosn:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @lzichong)

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/432)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @sahithi)

___
*[`docs/UPGRADES.md` line 11 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/432#-NWEPozsAtbY8jbru5zP:-NWEWqi13Rrh8v74lCWs:bdzjw53) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/abfa004b45a3759af88dfa911c17ed2e3b80c547/docs/UPGRADES.md#L11)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

for each cluster? Did you mean management cluster?
</blockquote></details>

Updated to management cluster, I initially was thinking about this from CSE clusters, but have corrected it to be more specific even for CAPVCD standalone. Thanks Sahithi!

**Pull request merged**
