### PR TITLE
[VCDA-4284] Remove DefaultStorageClass from RDE and vcdcluster object

### PR DESCRIPTION
**Pull request by lzichong**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- Removed DefaultStorageClass types from schema and reconciliation as it's being moved to VCDKE Status

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [x] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [x] Yes
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [x] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [x] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [x] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [x] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [x] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/240)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/240#-:-NAv5tYf4uNXLJoz-o2Z:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arunmk and @sahithi)

**Review by arunmk — APPROVED** [review]
:lgtm: thanks for this extensive change!

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/240#-:-NAvlvCkBzU5q-U7jusz:bntvrnh)* status: all files reviewed, 2 unresolved discussions (waiting on @lzichong and @sahithi)

___
*[`api/v1beta1/zz_generated.deepcopy.go` line 46 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/240#-NAvlTPFBeAoOjiQaIZ1:-NAvlTPFBeAoOjiQaIZ2:b-jreowm) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4bde65aa955ce05457c45557009043ea901552ff/api/v1beta1/zz_generated.deepcopy.go#L46)):*
> ```Go
> 
> // DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
> func (in *DefaultStorageClassOptions) DeepCopyInto(out *DefaultStorageClassOptions) {
> ```

to confirm: this file was autogenerated, correct?
___
*[`infrastructure-vcd/v1.0.0/infrastructure-components.yaml` line 195 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/240#-NAvldtr4RaKSNsJ7jWL:-NAvldtr4RaKSNsJ7jWM:b9llsxr) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4bde65aa955ce05457c45557009043ea901552ff/infrastructure-vcd/v1.0.0/infrastructure-components.yaml#L195)):*
> ```YAML
>                 - port
>                 type: object
>               defaultStorageClassOptions:
> ```

this change was autogenerated, correct?

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/240)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk, @lzichong, and @sahithi)

___
*[`infrastructure-vcd/v1.0.0/infrastructure-components.yaml` line 195 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/240#-NAvldtr4RaKSNsJ7jWL:-NAvo5MG0jyMnkxOT0qn:bu67aqq) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4bde65aa955ce05457c45557009043ea901552ff/infrastructure-vcd/v1.0.0/infrastructure-components.yaml#L195)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

this change was autogenerated, correct?
</blockquote></details>

yes it was, with `make manifests`

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/240)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[`api/v1beta1/zz_generated.deepcopy.go` line 46 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/240#-NAvlTPFBeAoOjiQaIZ1:-NAvo9pk74S9m3wWH7sl:b-q8y63y) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4bde65aa955ce05457c45557009043ea901552ff/api/v1beta1/zz_generated.deepcopy.go#L46)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

to confirm: this file was autogenerated, correct?
</blockquote></details>

yes it was

**Pull request merged**
