### PR TITLE
[CAFV-361] Add DCGroup Multi-AZ topology

### PR DESCRIPTION
**Pull request by Anirudh9794**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- Add DCGroup as a Multi-AZ topology
- tested by creating a multi-AZ cluster with DCGroup
- added some placeholders for other multi AZ topologies
- 

## Checklist
- [x] tested locally
- [x] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [x] Yes (Need to add vcdMachine.Spec.FailureDomain)
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [x] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [x] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [x] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595)* status: 0 of 16 files reviewed, 8 unresolved discussions (waiting on @abaruni, @Anirudh9794, and @arunmk)

___
*[`controllers/vcdcluster_controller.go` line 167 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq4qRgB3iuqrlme9usu:-Nq4qRgB3iuqrlme9usv:b6tnnd8) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L167)):*
> ```Go
> }
> 
> func loginVCD(ctx context.Context, cli client.Client, vcdCluster *infrav1beta3.VCDCluster, ovdcName string, ovdcScopedClient bool) (*vcdsdk.Client, error) {
> ```

Do we need to pass _ovdcName_ as a param?
If ovdcScopedClient is true, can we assume to get the ovdcname from _VCDCluster.spec.ovdc_?
___
*[`controllers/vcdcluster_controller.go` line 306 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq4qtHvDepPfEN9KAcH:-Nq4qtHvDepPfEN9KAcI:b6szrn0) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L306)):*
> ```Go
> 		return nil, fmt.Errorf("error creating VCD client from secrets to reconcile Cluster [%s] infrastructure: [%v]", vcdCluster.Name, err)
> 	}
> 	if ovdcScopedClient {
> ```

In this if block, can we populate ovdcname from vcdcluster.spec.ovdc?
___
*[`controllers/vcdcluster_controller.go` line 985 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq4sbzm-vdzuXZB-7_Q:-Nq4sbzm-vdzuXZB-7_R:b-3s4n49) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L985)):*
> ```Go
> 
> 	log := ctrl.LoggerFrom(ctx)
> 	capvcdRdeManager := capisdk.NewCapvcdRdeManager(vcdClient, vcdCluster.Status.InfraId)
> ```

do we need two RDE managers here? capvcdRDEManager should already have vcdsdk.RDEManager embedded in it.
I forgot the reason why we have such structure in the first place, but please check once.
___
*[`controllers/vcdcluster_controller.go` line 1025 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq4ueAh0btsP7-5zY34:-Nq4ueAh0btsP7-5zY35:b3fdeet) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L1025)):*
> ```Go
> 		vcdCluster.Status.Ovdc = ""
> 		vcdCluster.Status.FailureDomains = make(clusterv1.FailureDomains)
> 		edgeGatewayDetailsMap, err = getMapOfEdgeGateways(ctx, vcdClient, vcdClient.ClusterOrgName,
> ```

For DCgroup, is "multiple-edgegateways" a possibility? I thought all ovdc networks of all zones are supposed to be connected to a single edgegateway. 

Why can't we get a random zone and find the edgegateway of it and use it to create an LB?
___
*[`controllers/vcdcluster_controller.go` line 1162 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq51tN9ESBQpzAHPCNf:-Nq51tN9ESBQpzAHPCNg:b-cn30j9) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L1162)):*
> ```Go
> 			// here we set enableVirtualServiceSharedIP to ensure that we don't use a DNAT rule. The variable is possibly
> 			// badly named. Though the user-facing name is good, the internal variable name could be better.
> 			controlPlaneHost, err = gateway.CreateLoadBalancer(ctx, virtualServiceNamePrefix, lbPoolNamePrefix,
> ```

This logic seems to be creating LB for each edgegateway. Is that even a possibility? 
I will chat with you sometime tomorrow. Maybe I am missing some details.
___
*[`controllers/vcdcluster_controller.go` line 1562 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq5-5vs08Axhg4BQAKW:-Nq5-5vs08Axhg4BQAKX:bqvz7xs) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L1562)):*
> ```Go
> 				continue
> 			}
> 			vAppNamePrefix, err := vcdutil.CreateVAppNamePrefix(vcdCluster.Name, ovdcID)
> ```

Does this func consider the nodepool name as well?
___
*[`controllers/vcdcluster_controller.go` line 1581 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq5-LyqEy9FQaotdmHU:-Nq5-LyqEy9FQaotdmHV:b-ioymov) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L1581)):*
> ```Go
> 				// This is in the expected format and can be deleted if it has a matching ID
> 				log.Info("Deleting vApp", "vApp", vApp.Name, "Org", vcdCluster.Spec.Org, "OVDC", ovdcName)
> 				result, err := r.reconcileDeleteSingleVApp(ctx, ovdcName, vApp.Name,
> ```

Isn't this dangerous to delete every vApp that matches the prefix?
I think we should try to get to the level of nodepool name while constructing the vappname.
Let me know if I am missing something.
___
*[`controllers/vcdcluster_controller.go` line 1701 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq50O4i9aV09NDXsO3t:-Nq50O4i9aV09NDXsO3u:buy3q85) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L1701)):*
> ```Go
> 	// if zones are used, the OVDC networks of each zone needs to be connected to the same gateway, so choose an ovdc
> 	// network at random
> 	switch vcdCluster.Spec.MultiZoneSpec.ZoneTopology {
> ```

I suggest moving the entire switch logic here to reconcileDeleteLB() to ensure top-level reconcileDelete() getting too verbose/lengthy again?

**Review by sahithi — COMMENTED** [review]
Partial review only.

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-:-Nq53-hR7FgqZOF3EbE8:bi2nxni)* status: 0 of 16 files reviewed, 8 unresolved discussions (waiting on @abaruni, @Anirudh9794, and @arunmk)

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595)* status: 0 of 16 files reviewed, 8 unresolved discussions (waiting on @abaruni, @arunmk, and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 167 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq4qRgB3iuqrlme9usu:-Nq9Adl-79vjgrsoixVD:b9g2htl) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L167)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Do we need to pass _ovdcName_ as a param?
If ovdcScopedClient is true, can we assume to get the ovdcname from _VCDCluster.spec.ovdc_?
</blockquote></details>

This function is declared in vcdcluster_controller but is used by both vcdcluster_controller and vcdmachine_controller.

For VCDMachine controller, we would want to scope the client to the OVDC selected and it will be one of the values from `vcdCluster.spec.multiZonespec.zones`.

In the normal use case, CAPI selects the zone to which the machine should be deployed with the `machine.spec.failureDomain` field.

So we will have a scenario where the `vcdClient` needs to be scoped to a different VDC than `VCDCluster.spec.ovdc`
___
*[`controllers/vcdcluster_controller.go` line 306 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq4qtHvDepPfEN9KAcH:-Nq9C2-0AMgloFJrj74L:bf6v48j) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L306)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

In this if block, can we populate ovdcname from vcdcluster.spec.ovdc?
</blockquote></details>

As explained in a previous comment, we may have a case where we want to scope the client to a VDC other than `VCDCluster.spec.ovdc`
___
*[`controllers/vcdcluster_controller.go` line 985 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq4sbzm-vdzuXZB-7_Q:-Nq9CT_L9SKmmleCFOtL:bkqrsc0) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L985)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

do we need two RDE managers here? capvcdRDEManager should already have vcdsdk.RDEManager embedded in it.
I forgot the reason why we have such structure in the first place, but please check once.
</blockquote></details>

I think we have a `capvcdRDEManager` and an `RDEManager` because we use some functions which we have built on top of the functions from vcdsdk (using `capvcdRDEManager` object) . In some scenarios, we use the functions from vcdsdk directly (using `RDEManager` object)
___
*[`controllers/vcdcluster_controller.go` line 1025 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq4ueAh0btsP7-5zY34:-Nq9LVx36um7XBmtc5yh:b-cr38sb) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L1025)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

For DCgroup, is "multiple-edgegateways" a possibility? I thought all ovdc networks of all zones are supposed to be connected to a single edgegateway. 

Why can't we get a random zone and find the edgegateway of it and use it to create an LB?
</blockquote></details>

Yes, makes sense. I have updated the logic to cache the edge gateway details in case of single zone and dc group topologies.
___
*[`controllers/vcdcluster_controller.go` line 1162 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq51tN9ESBQpzAHPCNf:-Nq9ShDh3Sb4XlPJKDgl:b395d5e) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L1162)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This logic seems to be creating LB for each edgegateway. Is that even a possibility? 
I will chat with you sometime tomorrow. Maybe I am missing some details.
</blockquote></details>

I think the logic here is called for the number of zones defined. However since for DC group there is only one edge gateway, the load balancer will be created just once.

I have added a conditional break statement to stop the loop early for single zone and dc group use cases.
___
*[`controllers/vcdcluster_controller.go` line 1562 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq5-5vs08Axhg4BQAKW:-Nq9T1zF84hBsnzFiTDb:b-yvpuxi) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L1562)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Does this func consider the nodepool name as well?
</blockquote></details>

I think the changes to include nodepool name is done as a separate PR by Adnan. For the time being I just used the function which was copied over from multiAZ branch
___
*[`controllers/vcdcluster_controller.go` line 1701 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq50O4i9aV09NDXsO3t:-Nq9kLmN2TwWrqpXjR8K:b-ss962x) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L1701)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I suggest moving the entire switch logic here to reconcileDeleteLB() to ensure top-level reconcileDelete() getting too verbose/lengthy again?
</blockquote></details>

reduced the clutter in reconcileDelete() by separating out the part where variables are extracted based on the zone topology into a separate function

**Review by sahithi — APPROVED** [review]
:lgtm: after all comments are addressed.

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-:-NqV3nSA6rt4attKv9o9:b-3t6elz)* status: 0 of 16 files reviewed, 14 unresolved discussions (waiting on @abaruni, @Anirudh9794, and @arunmk)

___
*[`controllers/vcdcluster_controller.go` line 1562 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq5-5vs08Axhg4BQAKW:-NqV2woFChQfA3QA4STH:b-jnfk2i) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L1562)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think the changes to include nodepool name is done as a separate PR by Adnan. For the time being I just used the function which was copied over from multiAZ branch
</blockquote></details>

I see, can you add a TODO until then? Adnan's PR can fix it.
___
*[`controllers/vcdcluster_controller.go` line 1119 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-NqUwMPI4hiz1WD9PmEc:-NqUwMPI4hiz1WD9PmEd:b-cauzvi) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4904090d344db5d008193fdf8026453cd2372f71/controllers/vcdcluster_controller.go#L1119)):*
> ```Go
> 			}
> 
> 			vcdCluster.Status.FailureDomains[zone.Name] = clusterv1.FailureDomainSpec{
> ```

What happens if user changes their zone spec (like ovdc network and ovdc name) after LB is created?
This problem exists for all of the existing properties currently,  but just ensure right error gets thrown at the right place for now.
If needed, please create tasks or TODOs.
___
*[`controllers/vcdcluster_controller.go` line 1144 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-NqUxNKA2i_iecYJyjH2:-NqUxNKA2i_iecYJyjH3:bfnrnci) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4904090d344db5d008193fdf8026453cd2372f71/controllers/vcdcluster_controller.go#L1144)):*
> ```Go
> 		// this is an irreconcilable FATAL error; this should be handled by an Admission Controller
> 		err := fmt.Errorf("unknown zoneType [%s]", vcdCluster.Spec.MultiZoneSpec.ZoneTopology)
> 		log.Error(err, "Unable to process cluster with Zones but incorrect ZoneType")
> ```

Can you use the same term across the logs as well ?
ZoneType -> ZoneTopologyType
___
*[`controllers/vcdcluster_controller.go` line 1145 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-NqUxUXqA7LqP4r-q86A:-NqUxUXqA7LqP4r-q86B:bij91g1) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4904090d344db5d008193fdf8026453cd2372f71/controllers/vcdcluster_controller.go#L1145)):*
> ```Go
> 		err := fmt.Errorf("unknown zoneType [%s]", vcdCluster.Spec.MultiZoneSpec.ZoneTopology)
> 		log.Error(err, "Unable to process cluster with Zones but incorrect ZoneType")
> 		return ctrl.Result{}, errors.Wrapf(err,
> ```

nit: unable to process...
___
*[`controllers/vcdcluster_controller.go` line 1325 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-NqUzLtVDR-YgPo6mKpp:-NqUzLtVDR-YgPo6mKpq:bjorsmq) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4904090d344db5d008193fdf8026453cd2372f71/controllers/vcdcluster_controller.go#L1325)):*
> ```Go
> 	switch vcdCluster.Spec.MultiZoneSpec.ZoneTopology {
> 	case infrav1beta3.SingleZone, infrav1beta3.DCGroup, infrav1beta3.UserSpecifiedEdgeGateway:
> 		vcdCluster.Spec.ControlPlaneEndpoint = infrav1beta3.APIEndpoint{
> ```

Here as well, What if user changes controlplane endpoint after the LB is created? I am not asking to fix it in this PR, but please think about it.  If needed either add Jira task or TODO.
___
*[`controllers/vcdcluster_controller.go` line 1325 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-NqUzsan-VOMwt6W3VfU:-NqUzsan-VOMwt6W3VfV:br07iyj) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4904090d344db5d008193fdf8026453cd2372f71/controllers/vcdcluster_controller.go#L1325)):*
> ```Go
> 	switch vcdCluster.Spec.MultiZoneSpec.ZoneTopology {
> 	case infrav1beta3.SingleZone, infrav1beta3.DCGroup, infrav1beta3.UserSpecifiedEdgeGateway:
> 		vcdCluster.Spec.ControlPlaneEndpoint = infrav1beta3.APIEndpoint{
> ```

Don't we set ControlPlaneEndpoint in the VCDCluster.Status?
___
*[`controllers/vcdmachine_controller.go` line 563 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-NqV3RL57FbFegm9h9nx:-NqV3RL57FbFegm9h9ny:bqq0rno) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4904090d344db5d008193fdf8026453cd2372f71/controllers/vcdmachine_controller.go#L563)):*
> ```Go
> 			// This is not stable and has many other deficiencies, but this approach is okay since we don't need
> 			// a cryptographically strong random value.
> 			failureDomainName = vcdCluster.Spec.MultiZoneSpec.Zones[rand.Intn(len(vcdCluster.Spec.MultiZoneSpec.Zones))].Name
> ```

For controlplane, we need to selectively choose one of the controlplane enabled zones, right?
Where are we doing that?

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595)* status: 0 of 16 files reviewed, 14 unresolved discussions (waiting on @abaruni, @Anirudh9794, and @arunmk)

___
*[`controllers/vcdcluster_controller.go` line 1581 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq5-LyqEy9FQaotdmHU:-NqV42VF59Htd2UM0SnO:b-8omo6o) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L1581)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Isn't this dangerous to delete every vApp that matches the prefix?
I think we should try to get to the level of nodepool name while constructing the vappname.
Let me know if I am missing something.
</blockquote></details>

Aniruddha, I think you missed answering this one, please check.

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595)* status: 0 of 16 files reviewed, 15 unresolved discussions (waiting on @abaruni, @Anirudh9794, and @arunmk)

___
*[`controllers/vcdmachine_controller.go` line 555 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-NqV5lYy6viRoto0INh2:-NqV5lYzBXTxMF7J2ibV:bb9grm3) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4904090d344db5d008193fdf8026453cd2372f71/controllers/vcdmachine_controller.go#L555)):*
> ```Go
> 		failureDomainName := ""
> 		zoneName := vcdMachine.Spec.FailureDomain
> 		if zoneName == nil {
> ```

why do we need this if block of retrieving failureDomain from the Machine instead of VCDMachine? Won't capi set it on VCDMachine?

**Review by sahithi — COMMENTED** [review]
Please ensure all the log and error statements have all the details necessary to troubleshoot bugs, thanks

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-:-NqV6iM73i6UOCH4shf4:b1i9tl0)* status: 0 of 16 files reviewed, 16 unresolved discussions (waiting on @abaruni, @Anirudh9794, and @arunmk)

___
*[`controllers/vcdmachine_controller.go` line 571 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-NqV6BTD9-9Ifu7LTdEW:-NqV6BTH3Z1V1_jpqtmW:b-1laauo) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4904090d344db5d008193fdf8026453cd2372f71/controllers/vcdmachine_controller.go#L571)):*
> ```Go
> 		if !ok {
> 			err := fmt.Errorf("unknown failure domain name [%s]", failureDomainName)
> 			log.Error(err, "FailureDomainName not found in zones")
> ```

User-specified failure domain name for the Machine is not listed in the VCDCluster's Zone list....

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595)* status: 0 of 16 files reviewed, 15 unresolved discussions (waiting on @abaruni, @arunmk, and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 1562 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq5-5vs08Axhg4BQAKW:-NqYvnfk8R7RVgB_uJ1E:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L1562)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I see, can you add a TODO until then? Adnan's PR can fix it.
</blockquote></details>

Done.
___
*[`controllers/vcdcluster_controller.go` line 1581 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-Nq5-LyqEy9FQaotdmHU:-NqYvtFb7d0Pf77xYyaQ:b-opcqm8) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6cc652fe2e240c03b2b135c12b791256cd0ec787/controllers/vcdcluster_controller.go#L1581)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Aniruddha, I think you missed answering this one, please check.
</blockquote></details>

Adding node pool name to vapp name is done as part of a different task.

But we don't just match the prefix while deleting the vApp, we also check if the metadata has the correct infraID before deleting the VApp.

Added the TODO where we are getting the VApp name for clarity.
___
*[`controllers/vcdcluster_controller.go` line 1119 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-NqUwMPI4hiz1WD9PmEc:-NqYxyu5ArcCn8lm6o_P:b8qzagj) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4904090d344db5d008193fdf8026453cd2372f71/controllers/vcdcluster_controller.go#L1119)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

What happens if user changes their zone spec (like ovdc network and ovdc name) after LB is created?
This problem exists for all of the existing properties currently,  but just ensure right error gets thrown at the right place for now.
If needed, please create tasks or TODOs.
</blockquote></details>

For ovdc network change - 
___
*[`controllers/vcdcluster_controller.go` line 1144 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-NqUxNKA2i_iecYJyjH2:-NqYfL1_2wwvlEK25UuK:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4904090d344db5d008193fdf8026453cd2372f71/controllers/vcdcluster_controller.go#L1144)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you use the same term across the logs as well ?
ZoneType -> ZoneTopologyType
</blockquote></details>

Done.
___
*[`controllers/vcdcluster_controller.go` line 1145 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-NqUxUXqA7LqP4r-q86A:-NqYfS3eC4Bi-1JCBsIY:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4904090d344db5d008193fdf8026453cd2372f71/controllers/vcdcluster_controller.go#L1145)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

nit: unable to process...
</blockquote></details>

Done.
___
*[`controllers/vcdcluster_controller.go` line 1325 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-NqUzsan-VOMwt6W3VfU:-NqYwU2V2w-XtbtnmmwE:bagyu8b) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4904090d344db5d008193fdf8026453cd2372f71/controllers/vcdcluster_controller.go#L1325)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Don't we set ControlPlaneEndpoint in the VCDCluster.Status?
</blockquote></details>

No, I don't think we store the ControlPlaneEndpoint on the VCDCluster.Status. I think because we don't expect the controlplane host and port to change.
___
*[`controllers/vcdcluster_controller.go` line 1325 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-NqUzLtVDR-YgPo6mKpp:-NqYxN3tA4uPCS4YHU42:bgugdel) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4904090d344db5d008193fdf8026453cd2372f71/controllers/vcdcluster_controller.go#L1325)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Here as well, What if user changes controlplane endpoint after the LB is created? I am not asking to fix it in this PR, but please think about it.  If needed either add Jira task or TODO.
</blockquote></details>

We don't allow control plane endpoint updates. CAPVCD will overwrite the value. Except i think in the case of an external load balancer.

I will take this offline and create a ticket to add validation logic if necessary.
___
*[`controllers/vcdmachine_controller.go` line 555 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-NqV5lYy6viRoto0INh2:-NqYstz86GHenEMESwfe:bufqbhs) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4904090d344db5d008193fdf8026453cd2372f71/controllers/vcdmachine_controller.go#L555)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

why do we need this if block of retrieving failureDomain from the Machine instead of VCDMachine? Won't capi set it on VCDMachine?
</blockquote></details>

CAPI won't set the failureDomain on the VCDMachine. It will be set on the Machine object. However, a user might choose to set the failureDomain object on the VCDMachine object.
___
*[`controllers/vcdmachine_controller.go` line 563 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-NqV3RL57FbFegm9h9nx:-NqYtAw66-70iezukXqP:bu85jxn) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4904090d344db5d008193fdf8026453cd2372f71/controllers/vcdmachine_controller.go#L563)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

For controlplane, we need to selectively choose one of the controlplane enabled zones, right?
Where are we doing that?
</blockquote></details>

For controlPlane machines, CAPI looks at `vcdCluster.status.failureDomains` and picks one of the failureDomains and sets it on the machine object.

For Worker machines, CAPI sets the failureDomain on the machine object by looking at the attribute `machineDeployment.spec.failureDomain` . If `failureDomain` is not set on the machineDeployment, the machine object won't have any `failureDomain` . So we pick the failureDomain from the `vcdMachine`. If `failureDomain` on the `vcdMachine` is also not present, CAPVCD will randomly pick a failureDomain.

So to sum up my understanding, the failureDomain for a controlPlane node will be present at all times (for a multiAZ cluster) and will be picked by CAPI and set on the machine object. But for worker nodes, we may have to pick a failureDomain if it is not set on `MachineDeployment` or the `VCDMachine` object.

Added a comment regarding this information.
___
*[`controllers/vcdmachine_controller.go` line 571 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595#-NqV6BTD9-9Ifu7LTdEW:-NqYv9taCoVH4C5vbTTd:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4904090d344db5d008193fdf8026453cd2372f71/controllers/vcdmachine_controller.go#L571)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

User-specified failure domain name for the Machine is not listed in the VCDCluster's Zone list....
</blockquote></details>

Done.

**Review by abaruni — APPROVED** [review]
> Reviewed 13 of 16 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/595)* status: all files reviewed, 15 unresolved discussions (waiting on @arunmk and @sahithi)

**Pull request merged**
