### PR TITLE
[VCDA-4818] CAPVCD 1.0.0 documentation

### PR DESCRIPTION
**Pull request by sahithi**
## Description
CAPVCD 1.0.0 documentation
- Added new pages for clusterctl, crs, multitenancy

- 

## Checklist
- [ ] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: With few comments

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-:-NGIiiKO6Fs0N1s9HLGj:b-wk5yc9)* status: all files reviewed, 5 unresolved discussions (waiting on @sahithi)

___
*[`docs/CRS.md` line 51 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGIfpW_-aRzh6UNQaVK:-NGIfpW_-aRzh6UNQaVL:b-n74xoq) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4c6f02860a059e6b85dd4f02900392e5fa0e8e4b/docs/CRS.md#L51)):*
> ```Markdown
> 3. Retrieve RefreshToken of the user and create a secret with it on the workload cluster.
>    - `export REFRESH_TOKEN=$(kubectl --kubeconfig=bootstrap_cluster.conf get secret <secret name> -o jsonpath="{.data.refreshToken}" | base64 -D)`
>    - `kubectl --kubeconfig=workload_cluster.conf -n kube-system create secret generic vcloud-basic-auth --from-literal=refreshToken=${REFRESH_TOKEN}`
> ```

should we add `--from-lieteral=username="" --from-literal=password=""`?
___
*[`docs/CRS.md` line 74 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGIg3Mf-6Z1p6L1vy9B:-NGIg3Mf-6Z1p6L1vy9C:b-xquwkf) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4c6f02860a059e6b85dd4f02900392e5fa0e8e4b/docs/CRS.md#L74)):*
> ```Markdown
>    - Replace VCD_HOST, ORG, OVDC, VAPP, and CLUSTER_ID with the relevant values.
>    - Create the config map in the workload cluster:
>      `kubectl --kubeconfig=workload_cluster.conf create configmap --from-file=vcloud-csi-config.yaml`
> ```

We should not use `create configmap --from-file` here as the content will be embedded in another configmap.
 `kubectl apply -f vcloud-csi-config.yaml` should be the right command to create this configmap
___
*[`docs/CRS.md` line 106 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGIgeX55OhlDXoZp7C9:-NGIgeX55OhlDXoZp7CA:b-h53y8v) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4c6f02860a059e6b85dd4f02900392e5fa0e8e4b/docs/CRS.md#L106)):*
> ```Markdown
>    - Replace VCD_HOST, ORG, OVDC, NETWORK, VAPP, and CLUSTER_ID with the relevant values.
>    - Create the config map in the workload cluster:
>      `kubectl --kubeconfig=workload_cluster.conf create configmap --from-file=vcloud-ccm-config.yaml`
> ```

We should use
`kubectl apply -f vcloud-ccm-config.yaml`
instead.
___
*[`docs/MANAGEMENT_CLUSTER.md` line 18 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGIh1wy2tlWg5g0qgm8:-NGIh1wy2tlWg5g0qgm9:b-82w91l) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4c6f02860a059e6b85dd4f02900392e5fa0e8e4b/docs/MANAGEMENT_CLUSTER.md#L18)):*
> ```Markdown
> 2. [Kind as a bootstrap cluster](https://cluster-api.sigs.k8s.io/user/quick-start.html#install-andor-configure-a-kubernetes-cluster)
>    to create Management cluster in VCD tenant organization.
> The next step is to initialize the bootstrap cluster with the Cluster API   
> ```

Should we also mention that clusters deployed using CSE 4.0 comes with CAPVCD already installed?
___
*[`docs/MULTITENANCY.md` line 63 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGIi6YE-FLQm0l6h-19:-NGIi6YE-FLQm0l6h-1A:b-5lqyii) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4c6f02860a059e6b85dd4f02900392e5fa0e8e4b/docs/MULTITENANCY.md#L63)):*
> ```Markdown
> USERTOKEN=$(kubectl -n ${NAMESPACE} get secret ${SECRETNAME} -o "jsonpath={.data.token}" | base64 -d)
> CERT=$(kubectl -n ${NAMESPACE} get secret ${SECRETNAME} -o "jsonpath={.data['ca\.crt']}")
> KUBE_APISERVER_ADDRESS=https://127.0.0.1:64265
> ```

This can be other than 127.0.0.1 if the management cluster is not a kind cluster right?

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794)

___
*[`docs/CRS.md` line 51 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGIfpW_-aRzh6UNQaVK:-NGNNWTy6TLwgRmJrHg0:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4c6f02860a059e6b85dd4f02900392e5fa0e8e4b/docs/CRS.md#L51)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

should we add `--from-lieteral=username="" --from-literal=password=""`?
</blockquote></details>

Done.
___
*[`docs/CRS.md` line 74 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGIg3Mf-6Z1p6L1vy9B:-NGNNVnD5RhR0ho1t3Cq:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4c6f02860a059e6b85dd4f02900392e5fa0e8e4b/docs/CRS.md#L74)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

We should not use `create configmap --from-file` here as the content will be embedded in another configmap.
 `kubectl apply -f vcloud-csi-config.yaml` should be the right command to create this configmap
</blockquote></details>

Done.
___
*[`docs/CRS.md` line 106 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGIgeX55OhlDXoZp7C9:-NGNNVG63h8maO11yGPn:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4c6f02860a059e6b85dd4f02900392e5fa0e8e4b/docs/CRS.md#L106)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

We should use
`kubectl apply -f vcloud-ccm-config.yaml`
instead.
</blockquote></details>

Done.
___
*[`docs/MANAGEMENT_CLUSTER.md` line 18 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGIh1wy2tlWg5g0qgm8:-NGNNUk2070kxeN9mzo3:bs6red6) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4c6f02860a059e6b85dd4f02900392e5fa0e8e4b/docs/MANAGEMENT_CLUSTER.md#L18)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Should we also mention that clusters deployed using CSE 4.0 comes with CAPVCD already installed?
</blockquote></details>

Not needed. Standalone CAPVCD users may not be even aware of CSE 4.0's existence.

**Review by arunmk — APPROVED** [review]
:lgtm: with a few small suggestions

> Reviewed 5 of 6 files at r1, 3 of 3 files at r3, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-:-NGSE0aD5YSv64D5sJP0:b-3s055o)* status: 5 of 10 files reviewed, 10 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`README.md` line 25 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGSDrKHBYIsg9-oZhhm:-NGSDrKHBYIsg9-oZhhn:bn2thzk) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/93ba13b3caf9dfe1c7406104b0335deffa423a5d/README.md#L25)):*
> ```Markdown
> |--------------------------| --------------  |----------------|
> | CAPVCD v1alpha4 (v0.5)   |     ✓           | Not supported  |
> | CAPVCD v1beta1 (v1.0)    |     ✓           | ✓              |
> ```

Nit: justify to center
___
*[`README.md` line 32 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGSDuK63j1N911mpIDh:-NGSDuK63j1N911mpIDi:b-ix7wyi) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/93ba13b3caf9dfe1c7406104b0335deffa423a5d/README.md#L32)):*
> ```Markdown
> |                        | v1.20 | v1.21 | v1.22 |
> | -----------------------| ----- | ----- | ----- |
> | CAPVCD v1alpha4 (v0.5) | ✓     | ✓     |       |
> ```

Nit: center justify the ticks
___
*[`docs/CLUSTERCTL.md` line 6 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGI68KyBLHNAddlgfbn:-NGI68KyBLHNAddlgfbo:b89nh1a) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4c6f02860a059e6b85dd4f02900392e5fa0e8e4b/docs/CLUSTERCTL.md#L6)):*
> ```Markdown
> ## Set up
> Install [Clusterctl v1.1.3](https://cluster-api.sigs.k8s.io/user/quick-start.html#install-clusterctl)
> Currently, the below manual steps are required to enable clusterctl for CAPVCD.
> ```

Can we mention CAPVCD 1.0.0 since that version is hardcoded in the instructions below
___
*[`docs/CLUSTERCTL.md` line 30 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGI8TwXDWMddjm_ihYz:-NGI8TwXDWMddjm_ihZ-:bhop5dr) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4c6f02860a059e6b85dd4f02900392e5fa0e8e4b/docs/CLUSTERCTL.md#L30)):*
> ```Markdown
> 
> 1. Fill out the values for the environment variables in `~/.cluster-api/clusterctl.yaml`. 
>    - One of the variables is RefreshToken. Refer to [how to create refreshToken](https://docs.vmware.com/en/VMware-Cloud-Director/10.3/VMware-Cloud-Director-Tenant-Portal-Guide/GUID-A1B3B2FA-7B2C-4EE1-9D1B-188BE703EEDE.html).
> ```

Should we mention the VCD name here? The `RefreshToken` is the general security name.
___
*[`docs/VCD_SETUP.md` line 39 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGSDbl_2eINwUo_DUwg:-NGSDbl_2eINwUo_DUwh:b-2x28in) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/93ba13b3caf9dfe1c7406104b0335deffa423a5d/docs/VCD_SETUP.md#L39)):*
> ```Markdown
> * Set up DNS on the desired virtual datacenter networks.
> * Create tenant user role with the above mentioned [rights](#user_role)
> * For tenant admins to perform cluster management functions, you must hold the rights as mentioned above. In addition to 
> ```

Should we note that they can use the Provider UI here?
Should we also include the NO_RDE discussion someplace?

**Review by Anirudh9794 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 1 of 3 files at r4, 4 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347)* status: 9 of 10 files reviewed, 23 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[`docs/CLUSTERCTL.md` line 30 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGwUtyp45Uj9K_1ep1o:-NGwUtyq2j5Vjs7E4cbo:bv81344) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9508e5fb97fa0df6baa7ff4b20904271062264f0/docs/CLUSTERCTL.md#L30)):*
> ```Markdown
> 
> 1. Fill out the values for the environment variables in `~/.cluster-api/clusterctl.yaml`. 
>    - One of the variables is RefreshToken. Refer to [How to create refreshToken (or) API token in Cloud Director](https://docs.vmware.com/en/VMware-Cloud-Director/10.3/VMware-Cloud-Director-Tenant-Portal-Guide/GUID-A1B3B2FA-7B2C-4EE1-9D1B-188BE703EEDE.html).
> ```

Ankit had suggested us not to use the term Refresh tokens as it is implementation specific.
___
*[`docs/CLUSTERCTL.md` line 46 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGwXCAg2MCgiU-O5Ygr:-NGwXCAg2MCgiU-O5Ygs:b-qqm5cr) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9508e5fb97fa0df6baa7ff4b20904271062264f0/docs/CLUSTERCTL.md#L46)):*
> ```Markdown
> - All the flavors listed support only v1beta1 API versions of CAPVCD and Core CAPI.  
> - Currently, we have v1.20.8, v1.21.8, v1.22.9 as template flavors, and they each have their own etcd/dns versions pre-populated. 
> Please ensure your `~/.cluster-api/clusterctl.yaml` has VCD_TEMPLATE_NAME matching the correct versions of Kubernetes. 
> ```

can we use `VCD_TEMPLATE_NAME` (within ` quotes) to avoid formatting. I believe only the term TEMPLATE will be italicized if quotes are not used.



_Code quote:_
```Markdown
VCD_TEMPLATE_NAME
```
___
*[`docs/MULTITENANCY.md` line 10 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGwcGmr4EUhnwOlrdm5:-NGwcGms20AtrGbcTiD1:b-9iqr46) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9508e5fb97fa0df6baa7ff4b20904271062264f0/docs/MULTITENANCY.md#L10)):*
> ```Markdown
> required CRDs. This is a one-time operation per VCD tenant user.
> 
> Run below commands for each tenant user. The USERNAME and KUBE_APISERVER_ADDRESS parameter should be
> ```

`USERNAME` and `KUBE_APISERVER_ADDRESS` (with ` quotes)
___
*[`docs/VCD_SETUP.md` line 5 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGweDS641ouzFFjPgQY:-NGweDS641ouzFFjPgQZ:b-53rwza) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9508e5fb97fa0df6baa7ff4b20904271062264f0/docs/VCD_SETUP.md#L5)):*
> ```Markdown
> ## Provider steps
> 
> All of the provider steps mentioned below can be done from UI of the Cloud Director. Please refer to 
> ```

Should there be a link here to the UI docs?
___
*[`docs/VCD_SETUP.md` line 9 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGwf1ps2fRDQ8mD4NM4:-NGwf1ps2fRDQ8mD4NM5:b-ht7i8i) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9508e5fb97fa0df6baa7ff4b20904271062264f0/docs/VCD_SETUP.md#L9)):*
> ```Markdown
> ### NSX-T and Avi Setup
> The LoadBalancers fronting the multi-controlplane workload clusters need a preconfigured Avi Controller, NSX-T Cloud and Avi Service Engine Group.
> Refer to [load balancer set up](https://github.com/vmware/cloud-provider-for-cloud-director#provider-setup).
> ```

Is the link here still valid? because I don't see the `provider-setup` section in the README.md under `https://github.com/vmware/cloud-provider-for-cloud-director`
___
*[`docs/VCD_SETUP.md` line 13 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGwfWajEwG1q_FWuyXm:-NGwfWajEwG1q_FWuyXn:b-o7wu1a) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9508e5fb97fa0df6baa7ff4b20904271062264f0/docs/VCD_SETUP.md#L13)):*
> ```Markdown
> <a name="register_rde_schema"></a>
> ### Register Cluster API schema in Cloud Director
> Using Postman, register the Cluster API RDE (Runtime Defined Entity) schema with Cloud Director. This is required for CAPVCD to create 
> ```

shouldn't the term here be `Runtime Defined Entity Type` ?
___
*[`docs/VCD_SETUP.md` line 15 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGwfeQaBaEst1Fivqzr:-NGwfeQaBaEst1Fivqzs:b-r5ejbc) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9508e5fb97fa0df6baa7ff4b20904271062264f0/docs/VCD_SETUP.md#L15)):*
> ```Markdown
> Using Postman, register the Cluster API RDE (Runtime Defined Entity) schema with Cloud Director. This is required for CAPVCD to create 
> a logical object (RDE) in the Cloud Director for every workload cluster creation.
> RDE (Runtime Defined Entity) in Cloud Director is analogous to CRD (Custom Resource Definition) in Kubernetes. 
> ```

shouldn't it be the entity type which is analogous to CRD? as they both are type definitions and not actual objects?



_Code quote:_
```Markdown
a logical object (RDE) in the Cloud Director for every workload cluster creation.
RDE (Runtime Defined Entity) in Cloud Director is analogous to CRD (Custom Resource Definition) in Kubernetes.
```
___
*[`docs/VCD_SETUP.md` line 20 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGwgCEZ726DNPIPUx3F:-NGwgCEZ726DNPIPUx3G:b-u5a8zv) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9508e5fb97fa0df6baa7ff4b20904271062264f0/docs/VCD_SETUP.md#L20)):*
> ```Markdown
> Body: [payload](#capvcd_rde_schema)
> 
> As a side effect of the above schema registration, `vmware:capvcdCluster:1.1.0` right bundle gets automatically created.
> ```

Right bundle name should be `vmware:capvcdCluster Entitlement`, as per the UI.
Not sure if `vmware:capvcdCluster:1.1.0` is from a VCD API response. Please ignore the comment if it is so.
___
*[`docs/VCD_SETUP.md` line 24 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGwg_jvBeDj-IHYlbBj:-NGwg_jvBeDj-IHYlbBk:bjma3dm) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9508e5fb97fa0df6baa7ff4b20904271062264f0/docs/VCD_SETUP.md#L24)):*
> ```Markdown
> <a name="user_role"></a>  
> ### Publish the rights to the tenant organizations
> 1. Publish the `vmware:capvcdCluster:1.1.0` right bundle to the desired tenant organizations
> ```

The right bundle should be `vmware:capvcdCluster Entitlement`
___
*[`docs/VCD_SETUP.md` line 40 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGwh8Vr0GDt4SZB8nK8:-NGwh8Vr0GDt4SZB8nK9:b-gxii6q) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9508e5fb97fa0df6baa7ff4b20904271062264f0/docs/VCD_SETUP.md#L40)):*
> ```Markdown
> 
> ## Tenant Admin steps
> * A ServiceEngineGroup needs to be added to the gateway of the OVDC within which the Kubernetes cluster is to be created. The overall steps to achieve that are documented at Enable Load Balancer on an NSX-T Data Center Edge Gateway
> ```

should we have a link to the documentation here?



_Code quote:_
```Markdown
Enable Load Balancer on an NSX-T Data Center Edge Gateway
```
___
*[`docs/VCD_SETUP.md` line 41 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGwhGpb2lH4iH_TLbHw:-NGwhGpb2lH4iH_TLbHx:b-2jo9du) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9508e5fb97fa0df6baa7ff4b20904271062264f0/docs/VCD_SETUP.md#L41)):*
> ```Markdown
> ## Tenant Admin steps
> * A ServiceEngineGroup needs to be added to the gateway of the OVDC within which the Kubernetes cluster is to be created. The overall steps to achieve that are documented at Enable Load Balancer on an NSX-T Data Center Edge Gateway
> Create and publish the desired sizing policies on the chosen ovdc(s)
> ```

nit: OVDC(s)



_Code quote:_
```Markdown
ovdc(s)
```
___
*[`docs/VCD_SETUP.md` line 43 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGwhUXp93brioBS9qDf:-NGwhUXp93brioBS9qDg:byiwij7) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9508e5fb97fa0df6baa7ff4b20904271062264f0/docs/VCD_SETUP.md#L43)):*
> ```Markdown
> Create and publish the desired sizing policies on the chosen ovdc(s)
> * Ensure the OVDC gateway has outbound access. If required, set an SNAT rule with the internal IP range of the VMs.
> * Set up DNS on the desired virtual datacenter networks.
> ```

Should we also mention the step to create datacenter network?
___
*[`docs/WIRE_LOGS.md` line 3 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347#-NGwU6cK9c0dSkvp-gAq:-NGwU6cK9c0dSkvp-gAr:b-ne1tv1) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/9508e5fb97fa0df6baa7ff4b20904271062264f0/docs/WIRE_LOGS.md#L3)):*
> ```Markdown
> # Enable Wire Logs
> 
> Execute the following command to log HTTP requests to VCD and HTTP responses from VCD -
> ```

Wire logging is also documented in `scripts/README.md`. Can we remove that and refer the new md file in `scripts/README.md` ?

**Pull request merged**
