### PR TITLE
[CAFV-38] Remove hardcoded main-branch from building images and include infrastructure-components.yaml in image building

### PR DESCRIPTION
**Pull request by lzichong**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- Remove hardcoded main-branch from building images and include infrastructure-components.yaml in image building

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/363)

### CODE REVIEW

**Comment by arunmk** [comment]
This looks good to me

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/363)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @arunmk and @lzichong)

___
*[`Makefile` line 185 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/363#-NN8INP3BVlwviz5vwe7:-NN8INP4683UoMOCzBuF:b-ilyg5w) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ce4e0a2828a87db46e6481ae281ac578d8e22c6f/Makefile#L185)):*
> ```Makefile
> 	docker push $(IMG).$(GITCOMMIT)
> 	sed -e "s/__GIT_COMMIT__/$(GITCOMMIT)/g" -e "s/__VERSION__/$(version)/g" config/manager/manager.yaml.template > config/manager/manager.yaml
> 	sed -e "s/__GIT_COMMIT__/$(GITCOMMIT)/g" -e "s/__VERSION__/$(version)/g" templates/infrastructure-components.yaml.template > templates/infrastructure-components.yaml
> ```

please use the variable $(MANIFEST_DIR) for templates directory
___
*[`Makefile` line 190 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/363#-NN8IZQqD_nubEX2jTYB:-NN8IZQqD_nubEX2jTYC:b-ilyg5w) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ce4e0a2828a87db46e6481ae281ac578d8e22c6f/Makefile#L190)):*
> ```Makefile
> prod: capi
> 	sed -e "s/\.__GIT_COMMIT__//g" -e "s/__VERSION__/$(version)/g" config/manager/manager.yaml.template > config/manager/manager.yaml
> 	sed -e "s/\.__GIT_COMMIT__//g" -e "s/__VERSION__/$(version)/g"  templates/infrastructure-components.yaml.template > templates/infrastructure-components.yaml
> ```

please use the variable $(MANIFEST_DIR) for templates directory

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/363)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`Makefile` line 185 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/363#-NN8INP3BVlwviz5vwe7:-NNDYRacCWSDP45eugHy:b7ul5iy) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ce4e0a2828a87db46e6481ae281ac578d8e22c6f/Makefile#L185)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

please use the variable $(MANIFEST_DIR) for templates directory
</blockquote></details>

I have removed this line as discussed, this was not needed due to `release-manifests` will update `infrastructure-components.yaml` from `manager.yaml` change. Thanks Aniruddh!
___
*[`Makefile` line 190 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/363#-NN8IZQqD_nubEX2jTYB:-NNDYh1r90jQOtr9Nw_8:bg1ogz7) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ce4e0a2828a87db46e6481ae281ac578d8e22c6f/Makefile#L190)):*
> I have removed this line as discussed, this was not needed due to `release-manifests` will update from manager.yaml change. Thanks Aniruddh!

**Review by abaruni — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/363)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

**Pull request merged**
