### PR TITLE
VCDA-3208: Patch the vcdCluster.Status.InfraId

### PR DESCRIPTION
**Pull request by arunmk**
Also cleanup some logging

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-:-MsWA4xT8hHnsqKikgmg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sahithi)

**Review by sahithi — APPROVED** [review]
:lgtm: with minor comments

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-:-MsWtZkkD5wtd9TIoW9b:b-ij5eeu)* status: all files reviewed, 10 unresolved discussions (waiting on @arunmk)

___
*[controllers/errors.go, line 8 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWtd395wHHfc1haBI2:-MsWtd3ADAl3ips_pfnn:b-s3grxk) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6ae25b01bc5a4f06ba0a660d4a3471b42a07bf7a/controllers/errors.go#L8)):*
> ```Go
> )
> 
> type NoRDEError struct {
> ```

Please add a comment to describe when to use this.
___
*[controllers/vcdcluster_controller.go, line 361 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWlzI03NG3Mn7TYWx3:-MsWlzI03NG3Mn7TYWx4:bacwz2l) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a2d77fd2f21f82328b3510affae7ae80da14910c/controllers/vcdcluster_controller.go#L361)):*
> ```Go
> 	capiYaml, err := getCapiYaml(ctx, r.Client, *cluster, *vcdCluster)
> 	if err != nil {
> 		log.Error(err, "Error occurred during RDE reconciliation; failed to construct capi yaml using kubernetes resources for the cluster")
> ```

"Error during RDE reconciliation" - helps us to quickly understand the source from which the error is printed - RDE reconciliation logic.
___
*[controllers/vcdcluster_controller.go, line 464 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWnDre4Ym2v-ceL9Yk:-MsWnDre4Ym2v-ceL9Yl:b-ehlpxc) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6ae25b01bc5a4f06ba0a660d4a3471b42a07bf7a/controllers/vcdcluster_controller.go#L464)):*
> ```Go
> 	// NOTE: Since RDE is used just as a book-keeping mechanism, we should not fail reconciliation if RDE operations fail
> 	// create RDE for cluster
> 	infraID := vcdCluster.Status.InfraId
> ```

Can you please add a comment?
// Create (or) retrieve RDE Id for the cluster.
___
*[controllers/vcdcluster_controller.go, line 497 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWmafn9f39TnmRKMzH:-MsWmafn9f39TnmRKMzI:b-1snw2i) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6ae25b01bc5a4f06ba0a660d4a3471b42a07bf7a/controllers/vcdcluster_controller.go#L497)):*
> ```Go
> 		}
> 	} else {
> 		log.Info("Reusing already available InfraID", "infraID", infraID)
> ```

This log message will get printed for every reconcile operation. We can log it higher verbosity level
___
*[controllers/vcdcluster_controller.go, line 511 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWo5qz8EhnzCb4c0pn:-MsWo5qz8EhnzCb4c0po:b6ug51o) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6ae25b01bc5a4f06ba0a660d4a3471b42a07bf7a/controllers/vcdcluster_controller.go#L511)):*
> ```Go
> 		// This implies we have to set the infraID into the vcdCluster Object.
> 		vcdCluster.Status.InfraId = infraID
> 		if err := r.Status().Update(ctx, vcdCluster); err != nil {
> ```

For my benefit, how is this different from Patch? When to use Patch vs Update?
___
*[controllers/vcdcluster_controller.go, line 512 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWo0hL9pOeESz-HpLU:-MsWo0hL9pOeESz-HpLV:b-m17b5s) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6ae25b01bc5a4f06ba0a660d4a3471b42a07bf7a/controllers/vcdcluster_controller.go#L512)):*
> ```Go
> 		vcdCluster.Status.InfraId = infraID
> 		if err := r.Status().Update(ctx, vcdCluster); err != nil {
> 			return ctrl.Result{}, errors.Wrapf(err, "unable to update vcdCluster status with InfraID [%s]",
> ```

Please include the name of the cluster in the error statement.
___
*[controllers/vcdmachine_controller.go, line 289 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWqAXD-4sDzDUKnDDo:-MsWptXy8kPXeAZ2_Dzv:b1te3j7) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6ae25b01bc5a4f06ba0a660d4a3471b42a07bf7a/controllers/vcdmachine_controller.go#L289)):*
> ```Go
> 
> 	if rdeID == "" || strings.HasPrefix(rdeID, NoRdePrefix) {
> 		return NewNoRDEError("RDE ID is generated and hence will not be updated")
> ```

nit: "Infra Id seems to be auto-generated, hence skipping the RDE reconciliation of the Node status"
Also, we are catching two errors with one error type.
___
*[controllers/vcdmachine_controller.go, line 352 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWqsRO0zYPLKVfE7qM:-MsWqsRO0zYPLKVfE7qN:b-nsqq7z) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6ae25b01bc5a4f06ba0a660d4a3471b42a07bf7a/controllers/vcdmachine_controller.go#L352)):*
> ```Go
> 		if err != nil {
> 			if _, ok := err.(*NoRDEError); ok {
> 				log.Info("RDE NOT set up to track this cluster.",
> ```

We can increase the verbosity level of this message (at other places too). Logs can soon get spammed with these non-critical statements.

Also, can you prepend below to indicate the source of the log?
"Skipped RDE reconciliation of the Node status as RDE is not set up to track this cluster"
___
*[controllers/vcdmachine_controller.go, line 367 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWtGbl4FbuziU2HhIb:-MsWtGbl4FbuziU2HhIc:b-k2pczf) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6ae25b01bc5a4f06ba0a660d4a3471b42a07bf7a/controllers/vcdmachine_controller.go#L367)):*
> ```Go
> 	if err != nil {
> 		if _, ok := err.(*NoRDEError); ok {
> 			log.Info("RDE NOT set up to track this cluster.", "infraID", vcdCluster.Status.InfraId)
> ```

Here too.
___
*[controllers/vcdmachine_controller.go, line 673 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWtJC65z4lK6S53M_6:-MsWtJC65z4lK6S53M_7:bqujbyh) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6ae25b01bc5a4f06ba0a660d4a3471b42a07bf7a/controllers/vcdmachine_controller.go#L673)):*
> ```Go
> 	if err != nil {
> 		if _, ok := err.(*NoRDEError); ok {
> 			log.Info("RDE NOT set up to track this cluster.", "infraID", vcdCluster.Status.InfraId)
> ```

Here too

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28)* status: all files reviewed, 10 unresolved discussions (waiting on @arunmk)

___
*[controllers/vcdmachine_controller.go, line 352 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWqsRO0zYPLKVfE7qM:-MsWvO502m3XtN6ObiEL:bpoqeg0) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6ae25b01bc5a4f06ba0a660d4a3471b42a07bf7a/controllers/vcdmachine_controller.go#L352)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We can increase the verbosity level of this message (at other places too). Logs can soon get spammed with these non-critical statements.

Also, can you prepend below to indicate the source of the log?
"Skipped RDE reconciliation of the Node status as RDE is not set up to track this cluster"
</blockquote></details>

Actually, this if block tracks two error cases.
"Skipped RDE reconciliation of the Node status as Infra Id is either empty (or) auto-generated for this cluster"

**Comment by arunmk** [comment]
___
*[controllers/vcdmachine_controller.go, line 289 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWqAXD-4sDzDUKnDDo:-MsX5WKI8XqQOFSr2nrV:bbv3kzb) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6ae25b01bc5a4f06ba0a660d4a3471b42a07bf7a/controllers/vcdmachine_controller.go#L289)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

nit: "Infra Id seems to be auto-generated, hence skipping the RDE reconciliation of the Node status"
Also, we are catching two errors with one error type.
</blockquote></details>

I'll modify the error message to include both details.

**Comment by arunmk** [comment]
___
*[controllers/vcdmachine_controller.go, line 352 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWqsRO0zYPLKVfE7qM:-MsX5c2g0Wd-AhPVh-2Q:bbv3kzb) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6ae25b01bc5a4f06ba0a660d4a3471b42a07bf7a/controllers/vcdmachine_controller.go#L352)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Actually, this if block tracks two error cases.
"Skipped RDE reconciliation of the Node status as Infra Id is either empty (or) auto-generated for this cluster"
</blockquote></details>

I'll modify the error message to include both details.

**Comment by arunmk** [comment]
___
*[controllers/vcdmachine_controller.go, line 352 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWqsRO0zYPLKVfE7qM:-MsX73Ag-wjLfWKBkqbB:bhtlsc6) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6ae25b01bc5a4f06ba0a660d4a3471b42a07bf7a/controllers/vcdmachine_controller.go#L352)):*
> Error during RDE reconciliation
Actually, in both cases it means that the RDE is NOT set up to track the cluster. The error also prints the infra ID under consideration. So isn't it clearer @sahithi ?

**Review by arunmk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28)* status: all files reviewed, 10 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[controllers/vcdcluster_controller.go, line 511 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWo5qz8EhnzCb4c0pn:-MsX9kml3xc2cgSClD1v:bijla8g) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6ae25b01bc5a4f06ba0a660d4a3471b42a07bf7a/controllers/vcdcluster_controller.go#L511)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

For my benefit, how is this different from Patch? When to use Patch vs Update?
</blockquote></details>

Update updates all of the status with the current values. For Patch we need to mention the list of things that we want to update and then do it. It was a clean one-liner.
___
*[controllers/vcdmachine_controller.go, line 367 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWtGbl4FbuziU2HhIb:-MsX83EWDeNkYHwO_yhq:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6ae25b01bc5a4f06ba0a660d4a3471b42a07bf7a/controllers/vcdmachine_controller.go#L367)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Here too.
</blockquote></details>

Done.
___
*[controllers/vcdmachine_controller.go, line 673 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWtJC65z4lK6S53M_6:-MsX83gL2wK_4hGL2aeX:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6ae25b01bc5a4f06ba0a660d4a3471b42a07bf7a/controllers/vcdmachine_controller.go#L673)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Here too
</blockquote></details>

Done.

**Comment by arunmk** [comment]
___
*[controllers/vcdcluster_controller.go, line 512 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28#-MsWo0hL9pOeESz-HpLU:-MsX9vhW0JUoVDi_V4me:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/6ae25b01bc5a4f06ba0a660d4a3471b42a07bf7a/controllers/vcdcluster_controller.go#L512)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please include the name of the cluster in the error statement.
</blockquote></details>

Done.

**Pull request merged**
