### PR TITLE
Update tags to use + and _ instead of -

### PR DESCRIPTION
**Pull request by Anirudh9794**
Update tags in example/capi-quickstart.yaml

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/42)

### CODE REVIEW

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/42)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @arunmk, and @ltimothy7)

___
*[examples/capi-quickstart.yaml, line 74 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/42#-MuMkMvC5CMCdJwlD0Jr:-MuMkMvC5CMCdJwlD0Js:b24et9j) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8b62db63e0eb00653a599c886da2e5cea8423adb/examples/capi-quickstart.yaml#L74)):*
> ```YAML
>         local:
>           imageRepository: projects.registry.vmware.com/tkg # image repository to pull the etcd image from
>           imageTag: v3.4.13_vmware.14 # etcd image tag associated with the TKGm OVA used. The values must be retrieved from the TKGm ova BOM. Refer to the github documentation for more details
> ```

Is this not supposed to be + as the K8 version?

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/42)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @arunmk)

**Comment by Anirudh9794** [comment]
___
*[examples/capi-quickstart.yaml, line 74 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/42#-MuMkMvC5CMCdJwlD0Jr:-MuMpHaW2GwmGTTy0kID:b-z9odwu) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/8b62db63e0eb00653a599c886da2e5cea8423adb/examples/capi-quickstart.yaml#L74)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Is this not supposed to be + as the K8 version?
</blockquote></details>

etcd and dns should have `_` . I didn't test with etcd and dns having `+`

**Review by sahithi — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/42#-:-MuN1eP60t6VMOt3smWl:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk and @sahithi)

**Pull request merged**
