### PR TITLE
[VCDA-4558] Update clusterctl, templates and CRS definitions, add v1.21, v1.22 template flavors

### PR DESCRIPTION
**Pull request by lzichong**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- Update fields in clusterctl
- Removed useOneArm in templates
- Added v1.21.8, v1.22.9 templates
  - Tested both with and without CRS
  - CRS: Added labels to generated template `cni: antrea`, `ccm: external`, `csi: external` after applying CRS definitions
  - Non-CRS: Deployed a cluster successfully in VCD, with no CPI/CSI.

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [x] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295)

### CODE REVIEW

**Comment by Anirudh9794** [comment]
*[`templates/cluster-template-v1.21.8.yaml` line 28 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEDmy3FBePOmL1AzPy_:-NEDmy3FBePOmL1AzPya:b17pccj) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/99f5779f9a05a6ccdbae9aac48697b7cfd6934ff/templates/cluster-template-v1.21.8.yaml#L28)):*
> ```YAML
> kind: Secret
> metadata:
>   name: capi-user-credentials
> ```

Should we parameterize the name of the secret as well? We can see some unusual cases if more than one cluster exists in the same namespace

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: with some comment

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-:-NEDoe2V326WRkH_LeaR:b-sjo20y)* status: all files reviewed, 3 unresolved discussions (waiting on @lzichong and @sahithi)

___
*[`templates/cluster-template.yaml` line 54 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEDo2ox-5Z9QfX5hjPm:-NEDo2ox-5Z9QfX5hjPn:b-hiwugz) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/99f5779f9a05a6ccdbae9aac48697b7cfd6934ff/templates/cluster-template.yaml#L54)):*
> ```YAML
>   ovdc: ${VCD_ORGANIZATION_VDC} # VCD virtual datacenter name where the cluster should be deployed
>   ovdcNetwork: ${VCD_ORGANIZATION_VDC_NETWORK} # VCD virtual datacenter network to be used by the cluster
>   parentUid: ${PARENT_RDE_ID} # create the CAPVCD cluster from a specific management cluster associated with this UID.
> ```

Are we keeping parentUid?
___
*[`templates/clusterctl.yaml` line 55 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEDnx33EniO5vCqNCUQ:-NEDnx33EniO5vCqNCUR:b-31u4uu) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/99f5779f9a05a6ccdbae9aac48697b7cfd6934ff/templates/clusterctl.yaml#L55)):*
> ```YAML
> NO_PROXY:  ""
> ENABLE_NVIDIA_GPU: false
> PARENT_RDE_ID: vcdKE
> ```

Parent RDE Id should be removed if we are not keeping parentUid in the vcdcluster spec

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295)* status: all files reviewed, 3 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[`templates/cluster-template-v1.21.8.yaml` line 28 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEDmy3FBePOmL1AzPy_:-NEDotXT84HIV6ln85SO:b-lao467) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/99f5779f9a05a6ccdbae9aac48697b7cfd6934ff/templates/cluster-template-v1.21.8.yaml#L28)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Should we parameterize the name of the secret as well? We can see some unusual cases if more than one cluster exists in the same namespace
</blockquote></details>

I think we can parameterize it, I kept it for the sake of consistency with the UI generated CapiYaml. But looking at it from manual clusterctl perspective, I think it makes sense that we parameterize this. Is everyone okay with this @arunmk @sahithi ?

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[`templates/cluster-template.yaml` line 54 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEDo2ox-5Z9QfX5hjPm:-NEDrZyl-alZrWsrhv-f:b16ugkq) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/99f5779f9a05a6ccdbae9aac48697b7cfd6934ff/templates/cluster-template.yaml#L54)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Are we keeping parentUid?
</blockquote></details>

Updated, I recall @sahithi mentioning we can omit it. Thanks!
___
*[`templates/clusterctl.yaml` line 55 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEDnx33EniO5vCqNCUQ:-NEDrhub3wrIoZ5Lz1il:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/99f5779f9a05a6ccdbae9aac48697b7cfd6934ff/templates/clusterctl.yaml#L55)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Parent RDE Id should be removed if we are not keeping parentUid in the vcdcluster spec
</blockquote></details>

Done.

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295)* status: 8 of 11 files reviewed, 12 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @lzichong)

___
*[`templates/cluster-template.yaml` line 54 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEDo2ox-5Z9QfX5hjPm:-NESoW4b0Y8j3tKkTcvv:b-2eecly) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/99f5779f9a05a6ccdbae9aac48697b7cfd6934ff/templates/cluster-template.yaml#L54)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Updated, I recall @sahithi mentioning we can omit it. Thanks!
</blockquote></details>

Parent ID is not needed.
___
*[`templates/cluster-template.yaml` line 79 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NESoetN3EXkNsFwALrq:-NESoetN3EXkNsFwALrr:b-beortp) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/cluster-template.yaml#L79)):*
> ```YAML
>       sizingPolicy: ${VCD_CONTROL_PLANE_SIZING_POLICY} # Sizing policy to be used for the control plane VMs (this must be pre-published on the chosen organization virtual datacenter)
>       placementPolicy: ${VCD_CONTROL_PLANE_PLACEMENT_POLICY} # Placement policy to be used for worker VMs (this must be pre-published on the chosen organization virtual datacenter)
>       storageProfile: "${VCD_CONTROL_PLANE_STORAGE_PROFILE}" # Storage profile to be used for the control plane VMs (this must be pre-published on the chosen organization virtual datacenter)
> ```

Are these quotes intentional?
___
*[`templates/cluster-template-v1.21.8.yaml` line 28 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEDmy3FBePOmL1AzPy_:-NESou8r-9x3bmjQgvek:bgaohl3) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/99f5779f9a05a6ccdbae9aac48697b7cfd6934ff/templates/cluster-template-v1.21.8.yaml#L28)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

I think we can parameterize it, I kept it for the sake of consistency with the UI generated CapiYaml. But looking at it from manual clusterctl perspective, I think it makes sense that we parameterize this. Is everyone okay with this @arunmk @sahithi ?
</blockquote></details>

We can skip this. Let us see the feedback from the users. We don't want to overwhelm the users with the too many variables at once.
___
*[`templates/cluster-template-v1.21.8.yaml` line 3 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NESslyN8n58J3Bt5HfO:-NESslyN8n58J3Bt5HfP:b-9epdwf) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/cluster-template-v1.21.8.yaml#L3)):*
> ```YAML
> apiVersion: cluster.x-k8s.io/v1beta1
> kind: Cluster
> metadata:
> ```

Can you create another template with CRS labels added as well - one for each template? Please see how other providers are doing it. Let me know if they are doing it in any other unique way.
___
*[`templates/cluster-template-v1.21.8.yaml` line 4 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NESt4VPE9pc2oaK_Okz:-NESt4VPE9pc2oaK_Ol-:b1m0y9z) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/cluster-template-v1.21.8.yaml#L4)):*
> ```YAML
> kind: Cluster
> metadata:
>   name: ${CLUSTER_NAME}
> ```

Can you please create another task to include CNI in the templates?
Without CNI, the cluster is pretty much not ready.
___
*[`templates/cluster-template-v1.21.8.yaml` line 41 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEStwkRAP41Doi4sZDK:-NESrU0IEneSx_oyTrOC:b-hy2iok) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/cluster-template-v1.21.8.yaml#L41)):*
> ```YAML
>   name: ${CLUSTER_NAME}
>   namespace: ${TARGET_NAMESPACE}
> spec:
> ```

Please add defaults to any parameters that we intentionally decide to skip as clusterctl variables.
___
*[`templates/cluster-template-v1.21.8.yaml` line 46 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NESp5eO8nO0rro_5dVU:-NESp5eO8nO0rro_5dVV:bu1emvv) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/cluster-template-v1.21.8.yaml#L46)):*
> ```YAML
>   ovdc: ${VCD_ORGANIZATION_VDC} # VCD virtual datacenter name where the cluster should be deployed
>   ovdcNetwork: ${VCD_ORGANIZATION_VDC_NETWORK} # VCD virtual datacenter network to be used by the cluster
>   useAsManagementCluster: ${USE_AS_MANAGEMENT_CLUSTER} # intent to use the resultant CAPVCD cluster as a management cluster; defaults to false
> ```

We can skip UseAsManagemetCluster as a clusterctl variable. Can we set the default to false?
___
*[`templates/cluster-template-v1.21.8.yaml` line 171 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NESpl5-AcfkVJZ_CPWD:-NESpl50DXG4tMF6zpJw:b-7jbqan) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/cluster-template-v1.21.8.yaml#L171)):*
> ```YAML
>         name: ${CLUSTER_NAME}-md-0 # name of the VCDMachineTemplate object used to deploy worker nodes
>         namespace: ${TARGET_NAMESPACE} # kubernetes namespace of the VCDMachineTemplate object used to deploy worker nodes
>       version: v1.21.8+vmware.1 # Kubernetes version to be used to create (or) upgrade the worker nodes. Default version for this flavor is v1.21.8+vmware.1-tkg.2
> ```

space
___
*[`templates/cluster-template-v1.22.9.yaml` line 3 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NESs_7b3GhTKTjCmbUu:-NESs_7b3GhTKTjCmbUv:byshwmy) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/cluster-template-v1.22.9.yaml#L3)):*
> ```YAML
> apiVersion: cluster.x-k8s.io/v1beta1
> kind: Cluster
> metadata:
> ```

Are we missing CRS labels for CPI and CSI here?
___
*[`templates/clusterctl.yaml` line 16 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NESq9602JKn0SUdRmdF:-NESq9602JKn0SUdRmdG:b-s8c6gj) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/clusterctl.yaml#L16)):*
> ```YAML
> providers:
>   - name: "vcd"
>     url: "~/go/cluster-api-provider-cloud-director/templates/infrastructure-components.yaml"
> ```

We observed that the above url pattern would fail. Please fix this.
Also, add a comment here that clusterctl expects the directory location to follow a particular pattern.

Mention the clear instructions on the directory structure and what files need to be copied to where.
___
*[`templates/clusterctl.yaml` line 46 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NESten1B5Fx6zpmeggs:-NESten1B5Fx6zpmeggt:b9avkih) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/clusterctl.yaml#L46)):*
> ```YAML
> ETCD_VERSION: v3.4.13_vmware.14
> DNS_VERSION: v1.7.0_vmware.12
> IP_SUBNET: "10.XX.XX.XX/19"
> ```

Is  IP_SUBNET being used?

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295)* status: 6 of 16 files reviewed, 12 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[`templates/cluster-template.yaml` line 54 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEDo2ox-5Z9QfX5hjPm:-NEb5Fiw8QUCiq0VdNXS:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/99f5779f9a05a6ccdbae9aac48697b7cfd6934ff/templates/cluster-template.yaml#L54)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Parent ID is not needed.
</blockquote></details>

Done.
___
*[`templates/cluster-template.yaml` line 79 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NESoetN3EXkNsFwALrq:-NEb4GpSCNEW3eUzBRfI:b8atkhk) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/cluster-template.yaml#L79)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Are these quotes intentional?
</blockquote></details>

Yes they are, this is due to clusterctl being able to parse alphabetic or numeric values, but since we allow `'*'`, it will be unable to parse that without quotes. If clusterctl specifies '*' then the template will show `storageProfile: '*'` but if it's alphanumeric, it would show `storageProfile: Development1`
___
*[`templates/cluster-template-v1.21.8.yaml` line 28 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEDmy3FBePOmL1AzPy_:-NEb5Ehk1Io-1HBMEKoa:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/99f5779f9a05a6ccdbae9aac48697b7cfd6934ff/templates/cluster-template-v1.21.8.yaml#L28)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We can skip this. Let us see the feedback from the users. We don't want to overwhelm the users with the too many variables at once.
</blockquote></details>

Done.
___
*[`templates/cluster-template-v1.21.8.yaml` line 3 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NESslyN8n58J3Bt5HfO:-NEb4x9k0yw1JX8yDjE9:b7t38d) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/cluster-template-v1.21.8.yaml#L3)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you create another template with CRS labels added as well - one for each template? Please see how other providers are doing it. Let me know if they are doing it in any other unique way.
</blockquote></details>

As discussed we will have a meeting to fully reiterate, but currently have created CRS template files to unblock testing.
___
*[`templates/cluster-template-v1.21.8.yaml` line 4 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NESt4VPE9pc2oaK_Okz:-NEb4rmjChJCwCZxTPq3:bup9kmz) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/cluster-template-v1.21.8.yaml#L4)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you please create another task to include CNI in the templates?
Without CNI, the cluster is pretty much not ready.
</blockquote></details>

Done. Created VCDA-4698.
___
*[`templates/cluster-template-v1.21.8.yaml` line 41 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEStwkRAP41Doi4sZDK:-NEb5H2k0d7Kiwk7xlf4:ba92v8s) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/cluster-template-v1.21.8.yaml#L41)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please add defaults to any parameters that we intentionally decide to skip as clusterctl variables.
</blockquote></details>

Updated for `useAsManagementCluster` to default to false and removed from clusterctl, all the other fields seems necessary if not already filled with defaults
___
*[`templates/cluster-template-v1.21.8.yaml` line 46 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NESp5eO8nO0rro_5dVU:-NEb5RpZ0l7UoF9Oq6Fx:b5agi4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/cluster-template-v1.21.8.yaml#L46)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We can skip UseAsManagemetCluster as a clusterctl variable. Can we set the default to false?
</blockquote></details>

Done. Removed from clusterctl as well. 
___
*[`templates/cluster-template-v1.21.8.yaml` line 171 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NESpl5-AcfkVJZ_CPWD:-NEb5bzZDDOaB3ZGRSlw:b-e54owk) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/cluster-template-v1.21.8.yaml#L171)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

space
</blockquote></details>

In previous capiYaml, the version variable outside of infrastructureRef, I believe UI is also doing the same
___
*[`templates/cluster-template-v1.22.9.yaml` line 3 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NESs_7b3GhTKTjCmbUu:-NEb66_o5af6V09wPNqg:bozorv8) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/cluster-template-v1.22.9.yaml#L3)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Are we missing CRS labels for CPI and CSI here?
</blockquote></details>

Added new templates to include labels for CSI, CPI, CNI
___
*[`templates/clusterctl.yaml` line 16 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NESq9602JKn0SUdRmdF:-NEb68ocEe_A8mKLtd0G:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/clusterctl.yaml#L16)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We observed that the above url pattern would fail. Please fix this.
Also, add a comment here that clusterctl expects the directory location to follow a particular pattern.

Mention the clear instructions on the directory structure and what files need to be copied to where.

</blockquote></details>

Done.
___
*[`templates/clusterctl.yaml` line 46 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NESten1B5Fx6zpmeggs:-NEb69WX9JAeCO45OrAC:b-7yt453) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/clusterctl.yaml#L46)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Is  IP_SUBNET being used? 
</blockquote></details>

Removed this variable and is using VCD_VIP_CIDR instead, it is being used in loadBalancerConfigSpec

**Review by sahithi — APPROVED** [review]
:lgtm: after addressing last few comments

> Reviewed 6 of 11 files at r1, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-:-NEbS10Z2bt4si9DN0tl:b-xuni7t)* status: 15 of 16 files reviewed, 15 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @lzichong)

___
*[`templates/cluster-template-v1.21.8.yaml` line 44 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEbRsSm9shzio8pHm5x:-NEbRsSm9shzio8pHm5y:b-vp1ti5) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/61b94df359ac418e8d57ad7b82ee0f26b02fc08d/templates/cluster-template-v1.21.8.yaml#L44)):*
> ```YAML
>   site: ${VCD_SITE} # VCD endpoint with the format https://VCD_HOST. No trailing '/'
>   org: ${VCD_ORGANIZATION} # VCD organization name where the cluster should be deployed
>   ovdc: ${VCD_ORGANIZATION_VDC} # VCD virtual datacenter name where the cluster should be deployed
> ```

Missing Loadbalancer.vipsubnet section here and at a few other places.
___
*[`templates/cluster-template-v1.21.8.yaml` line 59 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEbQ6m8DlO61jFCkW2O:-NEbQ6m8DlO61jFCkW2P:b21sgyc) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/61b94df359ac418e8d57ad7b82ee0f26b02fc08d/templates/cluster-template-v1.21.8.yaml#L59)):*
> ```YAML
> spec:
>   template:
>     spec:
> ```

missing placementPolicy - please add a clusterctl variable
missing enableGPU - add a default value False (do not create a clusterctl variable for this as this is not a frequent choice and we may create separate gpu flavor in the future)
___
*[`templates/clusterctl.yaml` line 44 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEb4DFd5peo-ko6Qf0Z:-NEb4DFd5peo-ko6Qf0_:bw3z1ou) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/clusterctl.yaml#L44)):*
> ```YAML
> KUBERNETES_VERSION: v1.20.8+vmware.1
> VCD_TEMPLATE_NAME: Ubuntu 20.04 and Kubernetes v1.21.8+vmware.1
> ETCD_VERSION: v3.4.13_vmware.14
> ```

ETCD_VERSION

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295)* status: 7 of 17 files reviewed, 15 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[`templates/cluster-template-v1.21.8.yaml` line 44 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEbRsSm9shzio8pHm5x:-NEbkRBL0dsjWLlOBrp1:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/61b94df359ac418e8d57ad7b82ee0f26b02fc08d/templates/cluster-template-v1.21.8.yaml#L44)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Missing Loadbalancer.vipsubnet section here and at a few other places.
</blockquote></details>

Done.
___
*[`templates/cluster-template-v1.21.8.yaml` line 59 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEbQ6m8DlO61jFCkW2O:-NEby2w-0cNIkUhXESvL:b-ovbqz) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/61b94df359ac418e8d57ad7b82ee0f26b02fc08d/templates/cluster-template-v1.21.8.yaml#L59)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

missing placementPolicy - please add a clusterctl variable
missing enableGPU - add a default value False (do not create a clusterctl variable for this as this is not a frequent choice and we may create separate gpu flavor in the future)

</blockquote></details>

Updated placementPolicy for worker and control plane nodes across templates. Added `enableNvidiaGPU: false` to control plane and worker machines without clusterctl variable, thanks Sahith!
___
*[`templates/clusterctl.yaml` line 44 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEb4DFd5peo-ko6Qf0Z:-NEbyEqB6PH35gO-gfN6:b-9eoiaa) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/4ca9b966df840834a2179d78d89e6dff4cc1ad05/templates/clusterctl.yaml#L44)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

ETCD_VERSION
</blockquote></details>

We have 1 base template which lets users specifies the ETCD_VERSION, but for the individual flavors they have been manually added with the defaults

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 1 of 10 files at r3, 1 of 1 files at r4, 2 of 9 files at r5, 1 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295)* status: 11 of 17 files reviewed, 17 unresolved discussions (waiting on @arunmk, @lzichong, and @sahithi)

___
*[`templates/cluster-template.yaml` line 7 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEfy2AJ1zcQyFd1_WbG:-NEfy2AJ1zcQyFd1_WbH:bqwrnkj) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f7cc243b0070984684a45af215d2b667ba0b8b33/templates/cluster-template.yaml#L7)):*
> ```YAML
>   namespace: ${TARGET_NAMESPACE}
>   labels:
>     cluster-role.tkg.tanzu.vmware.com/management: ""
> ```

Are we keeping the crs lables in this template? Asking because it seems like the sample template for 1.20.8 doesn't have the CRS labels
___
*[`templates/cluster-template-v1.20.8.yaml` line 5 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEfxa52CFilIoczrTYA:-NEfxa52CFilIoczrTYB:b-a6ggvp) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/99f5779f9a05a6ccdbae9aac48697b7cfd6934ff/templates/cluster-template-v1.20.8.yaml#L5)):*
> ```YAML
> metadata:
>   name: ${CLUSTER_NAME}
>   namespace: ${TARGET_NAMESPACE}
> ```

namespace should be kept as is I think

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295)* status: 9 of 17 files reviewed, 17 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[`templates/cluster-template.yaml` line 7 at r6](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEfy2AJ1zcQyFd1_WbG:-NEgLBMc1mmk6PHIsIin:bavjrfw) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f7cc243b0070984684a45af215d2b667ba0b8b33/templates/cluster-template.yaml#L7)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Are we keeping the crs lables in this template? Asking because it seems like the sample template for 1.20.8 doesn't have the CRS labels
</blockquote></details>

Hi Aniruddh, after discussing CRS labels with Arun and Sahithi, we've concluded to omit Tanzu related labels from the base cluster-template.yaml as we want to bring try to have CAPVCD on it's own, and we will follow the other templates conventions for CRS labels such as: `cni: antrea`, `ccm: external`, etc as this convention is followed by other providers as well
___
*[`templates/cluster-template-v1.20.8.yaml` line 5 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/295#-NEfxa52CFilIoczrTYA:-NEgLaBx8uWTDLERZDtx:bvpr1mz) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/99f5779f9a05a6ccdbae9aac48697b7cfd6934ff/templates/cluster-template-v1.20.8.yaml#L5)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

namespace should be kept as is I think
</blockquote></details>

Updated, thanks Aniruddh!

**Pull request merged**
