### PR TITLE
[VCDA-3399] Create make targets to create release manifests

### PR DESCRIPTION
**Pull request by Anirudh9794**
* created make targets to create release manifests similar to capv
* uploading of assets is still a manual step: `gh release upload` command. Refer:https://cli.github.com/manual/gh_release_upload
* Unlike CAPV, the generation of the template files (cluster-template.yaml and their flavors) are not yet automated.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/66)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 4 of 10 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/66)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[config/default/secrets.yaml, line 10 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/66#-MxBnayUDVFrBK9Fjkin:-MxBnayUDVFrBK9Fjkio:b-svaqd4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1f3e2cf2d374a37572e96295a7697da50f1e5258/config/default/secrets.yaml#L10)):*
> ```YAML
>   password: ${VCD_PASSWORD_B64}
>   username: ${VCD_USERNAME_B64}
>   refreshToken: ${VCD_REFRESH_TOKEN_B64}
> ```

nit: missing new line

**Review by sahithi — APPROVED** [review]
:lgtm: after comments

> Reviewed 4 of 10 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/66#-:-MxBqFqD381afaHdKBCZ:b-lquxi1)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

___
*[config/default/secrets.yaml, line 10 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/66#-MxBqChn3ffGI4PMIm7R:-MxBqChn3ffGI4PMIm7S:bytr9j4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1f3e2cf2d374a37572e96295a7697da50f1e5258/config/default/secrets.yaml#L10)):*
> ```YAML
>   password: ${VCD_PASSWORD_B64}
>   username: ${VCD_USERNAME_B64}
>   refreshToken: ${VCD_REFRESH_TOKEN_B64}
> ```

I don't think we have code yet for refreshtoken
___
*[infrastructure-vcd/v0.5.1/infrastructure-components.yaml, line 644 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/66#-MxBpmeg8u5CnLm6Zt_o:-MxBpmeg8u5CnLm6Zt_p:b-ejadeh) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1f3e2cf2d374a37572e96295a7697da50f1e5258/infrastructure-vcd/v0.5.1/infrastructure-components.yaml#L644)):*
> ```YAML
> data:
>   password: ${VCD_PASSWORD_B64}
>   refreshToken: ${VCD_REFRESH_TOKEN_B64}
> ```

Do we process the refresh token currently?

**Review by sahithi — COMMENTED** [review]
can you also post in the channel - the make target we need to run to update the infrastructure-vcd folder?

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/66#-:-MxBqL5-4PPKOOa1pPMw:b-yrj5m0)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/66)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sahithi)

___
*[config/default/secrets.yaml, line 10 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/66#-MxBnayUDVFrBK9Fjkin:-MxC1Wa671ZqBx4uY-H-:b-yg10uq) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1f3e2cf2d374a37572e96295a7697da50f1e5258/config/default/secrets.yaml#L10)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

nit: missing new line
</blockquote></details>

Ah, sorry. Missing adding this new line very frequently lately
___
*[config/default/secrets.yaml, line 10 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/66#-MxBqChn3ffGI4PMIm7R:-MxC5WrR9kd_BdppCq9j:b-gfxk2) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1f3e2cf2d374a37572e96295a7697da50f1e5258/config/default/secrets.yaml#L10)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I don't think we have code yet for refreshtoken
</blockquote></details>

As discussed,  will remove this when addressing VCDA-3349

**Pull request merged**
