### PR TITLE
[VCDA-3336] Installation of default storage class on cluster creation

### PR DESCRIPTION
**Pull request by Anirudh9794**
* VCDCluster object changes to include default storage class options
* Control plane cloud init script to initialize default storage class
* Add check for default storage class creation in customization script statuses

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/59)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/59)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[api/v1alpha4/vcdcluster_types.go, line 38 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/59#-Mw3yS3p0FcSgmfxhVq_:-Mw3yS3p0FcSgmfxhVqa:b-5c3zlm) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/70c9b45437bd236cc7a4f1a7cf2d90fa3122df56/api/v1alpha4/vcdcluster_types.go#L38)):*
> ```Go
> 
> type DefaultStorageClassOptions struct {
> 	VCDStorageProfile         string `json:"VCDStorageProfile,omitempty"`
> ```

I remember Tim was having some issue with setting default values right in the struct sometime ago. Is that why you declared constants somewhere below for the defaults? constants can soon grow to an unmanageable level.

Can we write a constructor instead of constants (if setting defaults right in the struct is ruled out)? The next question is - can we force users to use the constructor always? See if this is doable in Go. If not, you can keep your current code as-is.
___
*[controllers/vcdmachine_controller.go, line 46 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/59#-Mw3mrp90_DBJJGryI5k:-Mw3mrpA3uV_mxLm9TO8:b-izqiig) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/70c9b45437bd236cc7a4f1a7cf2d90fa3122df56/controllers/vcdmachine_controller.go#L46)):*
> ```Go
> 	DEFAULT_VCD_STORAGE_PROFILE = "*"
> 	DEFAULT_FILESYSTEM          = "ext4"
> 	DEFAULT_RECLAIM_POLICY      = "Delete"
> ```

Didn't we decide the default reclaim policy to be "Retain"?
___
*[controllers/vcdmachine_controller.go, line 192 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/59#-Mw3zv6d0KNXBLD7eMV5:-Mw3zv6d0KNXBLD7eMV6:b-cwzfi7) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/70c9b45437bd236cc7a4f1a7cf2d90fa3122df56/controllers/vcdmachine_controller.go#L192)):*
> ```Go
> 	KubectlApplyCsi                        = "guestinfo.postcustomization.kubectl.csi.install.status"
> 	KubeadmTokenGenerate                   = "guestinfo.postcustomization.kubeadm.token.generate.status"
> 	KubectlApplyStorageClass               = "guestinfo.postcustomization.kubectl.default_storage_class.install.status"
> ```

nit: rename to KubectlApplyDefaultStorageClass
___
*[controllers/vcdmachine_controller.go, line 474 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/59#-Mw4-CMkC7HE3r0KdOKD:-Mw4-CMkC7HE3r0KdOKE:b-e4dgzx) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/70c9b45437bd236cc7a4f1a7cf2d90fa3122df56/controllers/vcdmachine_controller.go#L474)):*
> ```Go
> 				vcdCluster.Spec.UserCredentialsContext.RefreshToken))
> 			vcdHostFormatted := strings.Replace(vcdCluster.Spec.Site, "/", "\\/", -1)
> 			k8sStorageClassName := getOrDefault(vcdCluster.Spec.DefaultStorageClassOptions.StorageClassName, DEFAULT_STORAGE_CLASS_NAME)
> ```

As mentioned above, I think using a constructor would be clean here. Please see if you can do it.
___
*[controllers/cluster_scripts/cloud_init_control_plane.yaml, line 135 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/59#-Mw40kXAB2Ei9_lkh1Ag:-Mw40kXAB2Ei9_lkh1Ah:b-tviv5e) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/70c9b45437bd236cc7a4f1a7cf2d90fa3122df56/controllers/cluster_scripts/cloud_init_control_plane.yaml#L135)):*
> ```YAML
>     metadata:
>       annotations:
>         storageclass.kubernetes.io/is-default-class: "false"
> ```

storageclass.kubernetes.io/is-default-class: "true"

**Review by arunmk — APPROVED** [review]
:lgtm: with some changes needed

> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/59#-:-MwCbJc87cs57hLb3Wxs:bxl7ckz)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sahithi)

___
*[controllers/vcdmachine_controller.go, line 466 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/59#-MwCb3I71E13gQsIsuF7:-MwCb3I71E13gQsIsuF8:b-7ymfxc) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/57cb1337d044890714ee624c4c7e0928e7bc28d4/controllers/vcdmachine_controller.go#L466)):*
> ```Go
> 			enableDefaultStorageClass := vcdCluster.Spec.DefaultStorageClassOptions != nil
> 			k8sStorageClassName := ""
> 			fileSystemFormat := ""
> ```

ext4 by default
___
*[controllers/cluster_scripts/cloud_init_control_plane.yaml, line 135 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/59#-Mw40kXAB2Ei9_lkh1Ag:-MwCaZFq4V1OuD9rLnqV:b-bb1f7q) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/70c9b45437bd236cc7a4f1a7cf2d90fa3122df56/controllers/cluster_scripts/cloud_init_control_plane.yaml#L135)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

storageclass.kubernetes.io/is-default-class: "true"
</blockquote></details>

It will be better to create a `write_files` entry to this. The same golang way of `%s` can be used there as well.

**Review by sahithi — APPROVED** [review]
:lgtm: after the comment
Please update the examples file and _clusterctl generate_ variables.

> Reviewed 1 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/59#-:-MwDMqq_--i3bKyTbYo2:badk3i8)* status: all files reviewed, 6 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, and @sahithi)

___
*[api/v1alpha4/vcdcluster_types.go, line 37 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/59#-MwDMaMSEE9l5q2J0SEa:-MwDMaMSEE9l5q2J0SEb:b-ejt5oo) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/77ae360036e1bbcc51df61c48555258a76715615/api/v1alpha4/vcdcluster_types.go#L37)):*
> ```Go
> }
> 
> type DefaultStorageClassOptions struct {
> ```

Please update the examples file and _clusterctl generate_ variables.

**Review by ltimothy7 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/59#-:-MwDQDC30zCXPe2l383a:bg7igkv)* status: all files reviewed, 9 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

**Pull request merged**
