### PR TITLE
[CAFV-255] Implement phase1 fallback mechanism - update org and Ovdc inside vcdcluster.status in k8s

### PR DESCRIPTION
**Pull request by ymo24**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- Handle the customer bug: when VCD customers change the ovdc name, the CAPVCD can bring out the new ovdc name into vcd-cluster and then continue the reconciliation.
- Add data structure vcdResourceSet under vcdcluster.status
   - vcdResourceSet: [{orgID, orgName}, {ovdcID, ovdcName}].

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [x] Yes
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [x] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [x] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [x] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [x] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [x] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #
Screen Shot 2023-05-12 at 12 44 28 PM

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @ymo24)

___
*[`api/v1beta2/vcdcluster_types.go` line 130 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVBMt2W5f86ugo-f0f1:-NVBMt2W5f86ugo-f0f2:b4cnx3w) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b3a5ce1ec82234fc6905b9412849f7b458980f69/api/v1beta2/vcdcluster_types.go#L130)):*
> ```Go
> 
> 	//optional
> 	VcdResourceSet []VCDResource `json:"vcdResourceSet,omitempty"`
> ```

Can we have this as map (type -> array)?

org: []
ovdc: [{id:1234, name:ovdc1},{}]
___
*[`controllers/capi_objects_utils.go` line 138 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVBN8VSB_IhkPOxNIAL:-NVBN8VSB_IhkPOxNIAM:b-529iwa) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b3a5ce1ec82234fc6905b9412849f7b458980f69/controllers/capi_objects_utils.go#L138)):*
> ```Go
> }
> 
> func getOrgFromClusterByOrgName(client *vcdsdk.Client, orgName string) (*govcd.Org, error) {
> ```

getOrgByName()
___
*[`controllers/capi_objects_utils.go` line 149 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVBNCIb0f1H8r6-iRox:-NVBNCIb0f1H8r6-iRoy:b-l7yy9m) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b3a5ce1ec82234fc6905b9412849f7b458980f69/controllers/capi_objects_utils.go#L149)):*
> ```Go
> }
> 
> func getOrgFromClusterByOrgID(client *vcdsdk.Client, orgID string) (*govcd.Org, error) {
> ```

getOrgByID()
___
*[`controllers/vcdcluster_controller.go` line 708 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVBNJZU6Wk0XAO2j8P5:-NVBNJZU6Wk0XAO2j8P6:b-24vq) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b3a5ce1ec82234fc6905b9412849f7b458980f69/controllers/vcdcluster_controller.go#L708)):*
> ```Go
> 	if err != nil {
> 		// indicateEntityNotFound() only captures the ovdc name change error
> 		if indicateEntityNotFound(err) {
> ```

pseudocode:



_Code snippet:_
```Go
if entityNotFoundErr {
	ovdcName := getNewOvdcNameIfRenamed()
	//retry logging in
	workloadVCDClient = vcdsdk.NewVCdClientFromSecrets()
}

const (
	ResourceTypeOvdc = "ovdc"
)

func getNewOvdcNameIfRenamed() (string, error) {
	ovdcId = vcdcluster.status.vcdResource[ResourceTypeOvdc][0].["id"]
	vdc = getOvdcById(ovdcId)
	return vdc.name, nil
}
```
___
*[`controllers/vcdcluster_controller.go` line 727 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVBJNFP2RAr2dgySls2:-NVBJNFQ2mS_pL-1LdmL:brhg82f) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b3a5ce1ec82234fc6905b9412849f7b458980f69/controllers/vcdcluster_controller.go#L727)):*
> ```Go
> 			return ctrl.Result{}, errors.Wrapf(err, "Error getting ovdc to reconcile Cluster [%s] infrastructure", vcdCluster.Name)
> 		}
> 		vcdCluster.Status.VcdResourceSet = []infrav1.VCDResource{
> ```

We must include the type here.

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @ymo24)

___
*[`controllers/vcdcluster_controller.go` line 256 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVBOs7LC2MSlMSMAzy3:-NVBOs7LC2MSlMSMAzy4:b-hd1db9) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b3a5ce1ec82234fc6905b9412849f7b458980f69/controllers/vcdcluster_controller.go#L256)):*
> ```Go
> 		return nil, fmt.Errorf("the stored org/ovdc empty; fail to do the fallback mechanism and update the latest org or ovdc")
> 	}
> 	orgID := vcdCluster.Status.VcdResourceSet[0].ID
> ```

Yan, it is not a good idea to assume a particular element is at a particular index. In the future, someone may change the insertion order.
Please use map instead of array.

Also, see if the below mentioned code makes sense to you.

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`api/v1beta2/vcdcluster_types.go` line 130 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVBMt2W5f86ugo-f0f1:-NVBTq5wCw4-j7vMKSW8:b-rvfm60) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b3a5ce1ec82234fc6905b9412849f7b458980f69/api/v1beta2/vcdcluster_types.go#L130)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can we have this as map (type -> array)?

org: []
ovdc: [{id:1234, name:ovdc1},{}]

</blockquote></details>

Yes, it sounds better. Let me use this data struct instead

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @Anirudh9794 and @ymo24)

___
*[`controllers/vcdcluster_controller.go` line 708 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVBNJZU6Wk0XAO2j8P5:-NVBbz9c9RHGO53vSSzG:b-8okmmx) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b3a5ce1ec82234fc6905b9412849f7b458980f69/controllers/vcdcluster_controller.go#L708)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

pseudocode:
</blockquote></details>

(or)



_Code snippet:_
```Go
call NewVCDClientFromSecrets (with vdcClient=false)
updateClientWithVDC() {
		if checkIfOvdcNameHasBeenCHanged,
			getNewName
		update workloadVcdClient with VDC
	}
```
___
*[`controllers/vcdcluster_controller.go` line 714 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVBY6k07wi_S2cl7pMj:-NVBY6k07wi_S2cl7pMk:b-qi9vci) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b3a5ce1ec82234fc6905b9412849f7b458980f69/controllers/vcdcluster_controller.go#L714)):*
> ```Go
> 			}
> 			workloadVCDClient = vcdClient
> 			log.Info("The correct workloadClient was obtained and the operation was able to proceed after updating the ovdc name in the vcdCluster")
> ```

getVcdResourceFromVcdCluster(type) // return array or single element

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442)* status: 0 of 9 files reviewed, 7 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`controllers/capi_objects_utils.go` line 138 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVBN8VSB_IhkPOxNIAL:-NVGjQe28q6lA-ibjuDz:be4xp14) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b3a5ce1ec82234fc6905b9412849f7b458980f69/controllers/capi_objects_utils.go#L138)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

getOrgByName()
</blockquote></details>

Already changed the name, thanks Sahithi.
___
*[`controllers/capi_objects_utils.go` line 149 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVBNCIb0f1H8r6-iRox:-NVGjU2W-iL46hOPLxcR:be4xp14) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b3a5ce1ec82234fc6905b9412849f7b458980f69/controllers/capi_objects_utils.go#L149)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

getOrgByID()
</blockquote></details>

Already changed the name, thanks Sahithi.
___
*[`controllers/vcdcluster_controller.go` line 256 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVBOs7LC2MSlMSMAzy3:-NVGjW2a7V7LSq_otd_s:bh6ccwc) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b3a5ce1ec82234fc6905b9412849f7b458980f69/controllers/vcdcluster_controller.go#L256)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Yan, it is not a good idea to assume a particular element is at a particular index. In the future, someone may change the insertion order.
Please use map instead of array.

Also, see if the below mentioned code makes sense to you.
</blockquote></details>

Already pushed the changes. Thanks!

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442)* status: 0 of 9 files reviewed, 7 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 714 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVBY6k07wi_S2cl7pMj:-NVGjkKLCY9JzbLgU5ac:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b3a5ce1ec82234fc6905b9412849f7b458980f69/controllers/vcdcluster_controller.go#L714)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

getVcdResourceFromVcdCluster(type) // return array or single element 
</blockquote></details>

Done.
___
*[`controllers/vcdcluster_controller.go` line 727 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVBJNFP2RAr2dgySls2:-NVGjlzqAKjO357QWmsV:bgty61l) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b3a5ce1ec82234fc6905b9412849f7b458980f69/controllers/vcdcluster_controller.go#L727)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We must include the type here. 
</blockquote></details>

I did hard-code way here. Will implement insertVcdResourceIntoVcdCluster(type) in the future

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442)* status: 0 of 9 files reviewed, 11 unresolved discussions (waiting on @Anirudh9794 and @ymo24)

___
*[`controllers/capi_objects_utils.go` line 209 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVHZpPeAKKdw4rmIt-Z:-NVHZpPeAKKdw4rmIt-_:bs7nw45) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/66f25f18656a5155284e1c2f4906d16964888f0d/controllers/capi_objects_utils.go#L209)):*
> ```Go
> 		return fmt.Errorf("the key [%s] is not found in vcdcluster.status.vcdResourceMap", vcdResourceType)
> 	}
> 	for i := 0; i < len(resourceList); i++ {
> ```

I don't particularly appreciate parsing through entire list to find an element. This could also have been map (Id -> VCDresource).
But it is okay for now, as we are not anticipating many ovdcs in the near future.
___
*[`controllers/capi_objects_utils.go` line 226 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVHZiuQBrMbmiYysIFm:-NVHZiuQBrMbmiYysIFn:bdbqq4t) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/66f25f18656a5155284e1c2f4906d16964888f0d/controllers/capi_objects_utils.go#L226)):*
> ```Go
> 	}
> 	for i := 0; i < len(resourceList); i++ {
> 		if resourceList[i].ID == resourceID && resourceList[i].Name == resourceName {
> ```

resourceName check is not needed here. We can delete it if resourceId matches.
___
*[`controllers/capi_objects_utils.go` line 244 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVHbHw_CJ2-QxcKSviz:-NVHbHw_CJ2-QxcKSvj-:b-t20is8) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/66f25f18656a5155284e1c2f4906d16964888f0d/controllers/capi_objects_utils.go#L244)):*
> ```Go
> 	ovdcId := ""
> 	ovdcListIf, ovdcListFound := vcdCluster.Status.VcdResourceMap["ovdc"]
> 	if !ovdcListFound {
> ```

At the time of cluster creation, the map will be empty. Ensure cluster creation doesn't fail because of the empty vcdcluster.
Also, please check the upgrades of existing clusters from 1.0.0 to 1.1.0. Nothing should fail because of the absence of the empty vcdcluster.status.vcdresourceMap.
___
*[`controllers/vcdcluster_controller.go` line 699 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVHcRQ155MUEDARFv5j:-NVHcRQ24VyCOg46A66s:b-v2wzj2) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/66f25f18656a5155284e1c2f4906d16964888f0d/controllers/vcdcluster_controller.go#L699)):*
> ```Go
> 		return ctrl.Result{}, errors.Wrapf(err, "Error creating VCD client to reconcile Cluster [%s] infrastructure", vcdCluster.Name)
> 	}
> 	err = updateClientWithVDC(vcdCluster, workloadVCDClient)
> ```

Can you write a method to club NewVCDClientFromSecrets and UpdateClientWithVDC, and reuse it elsewhere?

**Review by ymo24 — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442)* status: 0 of 10 files reviewed, 11 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`controllers/capi_objects_utils.go` line 209 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVHZpPeAKKdw4rmIt-Z:-NVfd6y6D7CVTdZ0Vbbc:b-equtbg) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/66f25f18656a5155284e1c2f4906d16964888f0d/controllers/capi_objects_utils.go#L209)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I don't particularly appreciate parsing through entire list to find an element. This could also have been map (Id -> VCDresource).
But it is okay for now, as we are not anticipating many ovdcs in the near future.
</blockquote></details>

Will try to change the list to map post 4.1 GA
___
*[`controllers/capi_objects_utils.go` line 226 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVHZiuQBrMbmiYysIFm:-NVfdE1r-ldiFo_Xacpm:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/66f25f18656a5155284e1c2f4906d16964888f0d/controllers/capi_objects_utils.go#L226)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

resourceName check is not needed here. We can delete it if resourceId matches.
</blockquote></details>

Done.
___
*[`controllers/capi_objects_utils.go` line 244 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVHbHw_CJ2-QxcKSviz:-NVfdHIKA759pAgi04zz:buvub5m) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/66f25f18656a5155284e1c2f4906d16964888f0d/controllers/capi_objects_utils.go#L244)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

At the time of cluster creation, the map will be empty. Ensure cluster creation doesn't fail because of the empty vcdcluster.
Also, please check the upgrades of existing clusters from 1.0.0 to 1.1.0. Nothing should fail because of the absence of the empty vcdcluster.status.vcdresourceMap.


</blockquote></details>

Thanks, Sahithi. I already added the new logic
___
*[`controllers/vcdcluster_controller.go` line 708 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVBNJZU6Wk0XAO2j8P5:-NVWDtHeAmn43oiytLHT:bqdy9ia) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b3a5ce1ec82234fc6905b9412849f7b458980f69/controllers/vcdcluster_controller.go#L708)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

(or)
</blockquote></details>

Already fixed it. Thanks!
___
*[`controllers/vcdcluster_controller.go` line 699 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVHcRQ155MUEDARFv5j:-NVfd_zQ5Z19mObe8JvQ:b-ijn92c) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/66f25f18656a5155284e1c2f4906d16964888f0d/controllers/vcdcluster_controller.go#L699)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you write a method to club NewVCDClientFromSecrets and UpdateClientWithVDC, and reuse it elsewhere?
</blockquote></details>

Already created the function:



_Code snippet:_
```Go
workloadVCDClient, err := createVCDClientFromSecrets(ctx, r.Client, vcdCluster)
```

**Review by sahithi — APPROVED** [review]
:lgtm: after comments are addressed

Submit only after below tests are done:
1. Fresh cluster creation
     - change the ovdc name
     - cluster login should go through
     - vcdcluster.status.vdcresourcemap should have the new ovdcid and new ovdcname
2. Existing cluster created before this change 
    - It should continue to work just fine.
    - vcdcluster.status.vcdresourceMap should be populated with the values
3. Existing cluster created before this change 
    - change the ovdc name
    - login will fail - expected
4. Fresh cluster creation (stored version is v1beta2)
    - apply v1beta1 yaml
    - vcdcluster.status.vcdresourcemap should not be wiped off.
    - apply v1alpha4 yaml
    - vcdcluster.status.vcdresourcemap should not be wiped off.

Document the tests in a new file (ovdc fallback) under test folder to be automated for later.

> Reviewed 1 of 9 files at r2, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-:-NVlkCziDmCOOGhuJShb:b-ngyyl4)* status: all files reviewed, 12 unresolved discussions (waiting on @Anirudh9794 and @ymo24)

___
*[`api/v1beta1/vcdcluster_conversion.go` line 20 at r4](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVlfrxg4nkjHDseoV5D:-NVlfrxg4nkjHDseoV5E:b1423q7) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b9aa67dd9f4610abb7cf01e15b5550c6fa6cc010/api/v1beta1/vcdcluster_conversion.go#L20)):*
> ```Go
> 		return err
> 	}
> 	dst.Status.VcdResourceMap = restored.Status.VcdResourceMap
> ```

This must happen even in v1alpha4->v1beta2 convert
___
*[`controllers/vcdcluster_controller.go` line 262 at r4](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVljbCE6jeQ6dd5H8J4:-NVljbCE6jeQ6dd5H8J5:b40np19) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b9aa67dd9f4610abb7cf01e15b5550c6fa6cc010/controllers/vcdcluster_controller.go#L262)):*
> ```Go
> 		if NameChanged {
> 			ovdcName = newOvdc.Vdc.Name
> 			vcdCluster.Spec.Ovdc = newOvdc.Vdc.Name
> ```

Remove the logic of updating VCDCluster from here. You are doing it any way outside the method somewhere. There should only be one valid update in one right place. Ensure correctness.

This method as the name suggests, can just update the Client with the VDC object - not necessarily VCDCluster.Status.

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442)* status: 8 of 11 files reviewed, 12 unresolved discussions (waiting on @abaruni, @Anirudh9794, and @sahithi)

___
*[`api/v1beta1/vcdcluster_conversion.go` line 20 at r4](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVlfrxg4nkjHDseoV5D:-NVp0ib_0y3qMLV2ASGR:b-id6w68) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b9aa67dd9f4610abb7cf01e15b5550c6fa6cc010/api/v1beta1/vcdcluster_conversion.go#L20)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This must happen even in v1alpha4->v1beta2 convert
</blockquote></details>

Already pushed the change under the v1alpha4 folder. Thanks Sahithi
___
*[`controllers/vcdcluster_controller.go` line 262 at r4](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/442#-NVljbCE6jeQ6dd5H8J4:-NVps2R-B1V34YLaVOvC:bk08h4y) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/b9aa67dd9f4610abb7cf01e15b5550c6fa6cc010/controllers/vcdcluster_controller.go#L262)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Remove the logic of updating VCDCluster from here. You are doing it any way outside the method somewhere. There should only be one valid update in one right place. Ensure correctness.

This method as the name suggests, can just update the Client with the VDC object - not necessarily VCDCluster.Status.
</blockquote></details>

Already moved the operation out of updateClientWithVDC(). Thanks

**Pull request merged**
