### PR TITLE
logging for phase success and error

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy7 <66969084+ltimothy7@users.noreply.github.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/9)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by sahithi — APPROVED** [review]
:lgtm: after addressing the comment

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/9#-:-MqGT-vD8ooK7pYZ1sFZ:b-4g7kf)* status: all files reviewed, 2 unresolved discussions (waiting on @ltimothy7)

___
*[controllers/vcdmachine_controller.go, line 619 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/9#-MqGSm_SDUvzy_wW1gjm:-MqGSm_SDUvzy_wW1gjn:bleype3) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/234d8fd95a9489779820764295db6f6e2f58b67a/controllers/vcdmachine_controller.go#L619)):*
> ```Go
> 		}
> 		if err = r.waitForPostCustomizationPhase(workloadVCDClient, vm, phase); err != nil {
> 			fmt.Errorf("error waiting for phase [%s] for vm [%s]: [%v]", phase, vm.VM.Name, err)
> ```

Something like below

Error waiting for the bootstrapping phase [%s] of the machine [%s] of the cluster [%s]: [%v]
___
*[controllers/vcdmachine_controller.go, line 623 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/9#-MqGRjOfDpNJKXYzordl:-MqGRjOfDpNJKXYzordm:bu54mam) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/234d8fd95a9489779820764295db6f6e2f58b67a/controllers/vcdmachine_controller.go#L623)):*
> ```Go
> 				phase, err)
> 		}
> 		fmt.Sprintf("successfully completed phase [%s] for vm [%s]", phase, vm.VM.Name)
> ```

Please include the name of the cluster in the log message. It becomes very difficult to read and diagnose the logs from multiple worker nodes of multiple clusters.

Something like below
successfully completed bootstrapping phase [%s] for the machine [%s] of the cluster [%s]

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/9)* status: all files reviewed, 4 unresolved discussions (waiting on @ltimothy7)

___
*[controllers/vcdmachine_controller.go, line 618 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/9#-MqGaD9l6JxBBXrBiuu5:-MqGaD9l6JxBBXrBiuu6:bvth3ft) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/234d8fd95a9489779820764295db6f6e2f58b67a/controllers/vcdmachine_controller.go#L618)):*
> ```Go
> 			return ctrl.Result{}, errors.Wrapf(err, "unable to refresh vapp [%s]: [%v]", vAppName, err)
> 		}
> 		if err = r.waitForPostCustomizationPhase(workloadVCDClient, vm, phase); err != nil {
> ```

Above this line, can we print what we are waiting. Also, it is generally useful to have lines asligned like this:
```
klog.Infof("START: waiting for phase [%s] for vm [%s] in vApp [%s]")
klog.Infof("END  : waiting for phase [%s] for vm [%s] in vApp [%s]")
```

Also be sure to use `klog.Infof` instead of `fmt.Printf`
___
*[controllers/vcdmachine_controller.go, line 623 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/9#-MqGafWqB-rTmK8rlPzq:-MqGafWqB-rTmK8rlPzr:b-939gql) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/234d8fd95a9489779820764295db6f6e2f58b67a/controllers/vcdmachine_controller.go#L623)):*
> ```Go
> 				phase, err)
> 		}
> 		fmt.Sprintf("successfully completed phase [%s] for vm [%s]", phase, vm.VM.Name)
> ```

This should be replaced by klog.Infof. Also Sprintf won't print to console, so it's a typo I think.

**Comment by arunmk** [comment]
:lgtm: after applying some comments

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/9)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[controllers/vcdmachine_controller.go, line 618 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/9#-MqGaD9l6JxBBXrBiuu5:-MqGzk8J8osVer0ve45h:bauatva) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/234d8fd95a9489779820764295db6f6e2f58b67a/controllers/vcdmachine_controller.go#L618)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Above this line, can we print what we are waiting. Also, it is generally useful to have lines asligned like this:
```
klog.Infof("START: waiting for phase [%s] for vm [%s] in vApp [%s]")
klog.Infof("END  : waiting for phase [%s] for vm [%s] in vApp [%s]")
```

Also be sure to use `klog.Infof` instead of `fmt.Printf`
</blockquote></details>

Done. Thank you for this catch or klog
___
*[controllers/vcdmachine_controller.go, line 619 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/9#-MqGSm_SDUvzy_wW1gjm:-MqH-JWa0LQ4JZZmrY56:b-pt2ipc) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/234d8fd95a9489779820764295db6f6e2f58b67a/controllers/vcdmachine_controller.go#L619)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Something like below

Error waiting for the bootstrapping phase [%s] of the machine [%s] of the cluster [%s]: [%v]
</blockquote></details>

Done. Thank you
___
*[controllers/vcdmachine_controller.go, line 623 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/9#-MqGRjOfDpNJKXYzordl:-MqH-Kll8tSsPmwI0HbC:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/234d8fd95a9489779820764295db6f6e2f58b67a/controllers/vcdmachine_controller.go#L623)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please include the name of the cluster in the log message. It becomes very difficult to read and diagnose the logs from multiple worker nodes of multiple clusters.

Something like below
successfully completed bootstrapping phase [%s] for the machine [%s] of the cluster [%s]
</blockquote></details>

Done.
___
*[controllers/vcdmachine_controller.go, line 623 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/9#-MqGafWqB-rTmK8rlPzq:-MqH-Mh86jSEXpq6da-H:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/234d8fd95a9489779820764295db6f6e2f58b67a/controllers/vcdmachine_controller.go#L623)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This should be replaced by klog.Infof. Also Sprintf won't print to console, so it's a typo I think.
</blockquote></details>

Done.

**Pull request merged**
