### PR TITLE
VCDA-3666 small updates to cloud init and docs

### PR DESCRIPTION
**Pull request by abaruni**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- 

## Checklist
- [ ] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/236)

### CODE REVIEW

**Review by arunmk — APPROVED** [review]
:lgtm: thanks Adnan

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/236#-:-NAALWSl5vuDLUx_-E78:b-7se90w)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @abaruni)

**Review by arunmk — APPROVED** [review]
:lgtm:

Could you please also add details for the CPI and CSI configmap and basic auth

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/236#-:-NAAkaVpB_Ko7A5ovdgz:bijyq6s)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @arunmk)

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/236#-:-NAAxoLS656eTZTPA0TQ:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @abaruni)

**Review by arunmk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/236)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @abaruni)

**Pull request merged**
