### PR TITLE
Redo compute policy rename changes and regenerate conversion files

### PR DESCRIPTION
**Pull request by Anirudh9794**
* Revert the PR (https://github.com/vmware/cluster-api-provider-cloud-director/pull/91) as `zz_generated.conversion.go` file is wrong
* Redo the compute policy rename changes
* Add omitempty to rdeId as it is optional
* Regenerate `zz_generated.conversion.go` using conversion_gen tool

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/96)

### CODE REVIEW

**Comment by arunmk** [comment]
*[api/v1alpha4/zz_generated.conversion.go, line 431 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/96#-N-z5RRvClC4SL7wGHZ-:-N-z5RRvClC4SL7wGHZ0:b4c9lyr) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/5fa916beae1034feca3f025f0cc22b25288154a6/api/v1alpha4/zz_generated.conversion.go#L431)):*
> ```Go
> 	out.Catalog = in.Catalog
> 	out.Template = in.Template
> 	// WARNING: in.ComputePolicy requires manual conversion: does not exist in peer-type
> ```

:thumbsup:

**Comment by arunmk** [comment]
*[api/v1alpha4/zz_generated.conversion.go, line 440 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/96#-N-z5UKo21Jz1HI1-6rD:-N-z5UKo21Jz1HI1-6rE:b4c9lyr) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/5fa916beae1034feca3f025f0cc22b25288154a6/api/v1alpha4/zz_generated.conversion.go#L440)):*
> ```Go
> 	out.Catalog = in.Catalog
> 	out.Template = in.Template
> 	// WARNING: in.SizingPolicy requires manual conversion: does not exist in peer-type
> ```

:thumbsup:

**Review by arunmk — APPROVED** [review]
> Reviewed 8 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/96)* status: all files reviewed, 3 unresolved discussions (waiting on @abaruni, @Anirudh9794, and @sahithi)

___
*[api/v1alpha4/zz_generated.conversion.go, line 431 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/96#-N-z5es72u5MQe62hioG:-N-z5es72u5MQe62hioH:b4c9lyr) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/77ba27c59fb77b475e7878ab860e738265898702/api/v1alpha4/zz_generated.conversion.go#L431)):*
> ```Go
> 	out.Catalog = in.Catalog
> 	out.Template = in.Template
> 	// WARNING: in.ComputePolicy requires manual conversion: does not exist in peer-type
> ```

:thumbsup: 
___
*[api/v1alpha4/zz_generated.conversion.go, line 440 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/96#-N-z5giTCgmpcv_qfD9K:-N-z5giTCgmpcv_qfD9L:b4c9lyr) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/77ba27c59fb77b475e7878ab860e738265898702/api/v1alpha4/zz_generated.conversion.go#L440)):*
> ```Go
> 	out.Catalog = in.Catalog
> 	out.Template = in.Template
> 	// WARNING: in.SizingPolicy requires manual conversion: does not exist in peer-type
> ```

:thumbsup: 
___
*[api/v1beta1/vcdmachine_types.go, line 49 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/96#-N-z4tek37CSKxDBFjkL:-N-z4tek37CSKxDBFjkM:b-1qanjr) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/321e333b1455b3bca8a9c6b0efaa252617764b79/api/v1beta1/vcdmachine_types.go#L49)):*
> ```Go
> 
> 	// SizingPolicy is the sizing policy to be used on this machine.
> 	// If no sizing policy is specified, default sizing policy will be used to create the nodes
> ```

Why is this comment removed?

**Comment by arunmk** [comment]
:lgtm: this is what I was hoping for, thanks for doing this!

**Review by abaruni — APPROVED** [review]
> Reviewed 6 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/96)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

**Review by sahithi — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/96#-:-N01_v3ME5rGmYgfUiz8:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[api/v1beta1/vcdmachine_types.go, line 49 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/96#-N-z4tek37CSKxDBFjkL:-N01_lMM0RS4a47ynjNQ:bqcyfxf) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/321e333b1455b3bca8a9c6b0efaa252617764b79/api/v1beta1/vcdmachine_types.go#L49)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Why is this comment removed?
</blockquote></details>

VCDCluster also has a default sizing policy. We need to think about the real need for it. If not needed, we should remove it.

**Comment by Anirudh9794** [comment]
*[api/v1beta1/vcdmachine_types.go, line 49 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/96#-N-z4tek37CSKxDBFjkL:-N01rO1c7JACR2mEViOt:b-nb7v87) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/321e333b1455b3bca8a9c6b0efaa252617764b79/api/v1beta1/vcdmachine_types.go#L49)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

VCDCluster also has a default sizing policy. We need to think about the real need for it. If not needed, we should remove it.
</blockquote></details>

Created a separate task to address removing compute policy in VCDCluster.
I also added back the missing comment in v1beta1

**Pull request merged**
