### PR TITLE
[VCDA-3173] Control plane join using join script

### PR DESCRIPTION
**Pull request by ltimothy7**
For a multimaster cluster, the joining control plane nodes should use the join script instead of the control plane script. 

Testing: successfully deployed multimaster cluster

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/23)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/23#-:-MrNw4HJ3CYzXSQ15fED:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/23#-:-MrTmbjdAnevGfToiIlq:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[controllers/vcdmachine_controller.go, line 410 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/23#-MrTm86yBq1bBmz4DOnW:-MrTm86yBq1bBmz4DOnX:bu22c6d) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ad6c31e4b293a6e5907fb7a990298a9dfd68e970/controllers/vcdmachine_controller.go#L410)):*
> ```Go
> 	bootstrapJinjaScript, err := r.getBootstrapData(ctx, machine)
> 	if err != nil {
> 		return ctrl.Result{}, errors.Wrapf(err, "unable to get bootstrap data for machine [%s]",
> ```

Add cluster name to the error return statement.
"Error retrieving bootstrap data for machine %s of the cluster %s

**Review by arunmk — APPROVED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/23)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

**Comment by arunmk** [comment]
___
*[controllers/vcdmachine_controller.go, line 194 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/23#-MrTmpDd2UmI9BFi0TrE:-MrTmpDe8YD-BDclgWD1:bpax1z4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ad6c31e4b293a6e5907fb7a990298a9dfd68e970/controllers/vcdmachine_controller.go#L194)):*
> ```Go
> var joinPostCustPhases = []string{
> 	NetworkConfiguration,
> 	KubeadmNodeJoin,
> ```

are there two phases of the same name @ltimothy7 ?

**Review by arunmk — APPROVED** [review]
:lgtm: with a minor check

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/23#-:-MrTmvYy9wqHm_mO4g2-:bps1g1f)* status: all files reviewed, 2 unresolved discussions (waiting on @ltimothy7)

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/23)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[controllers/vcdmachine_controller.go, line 194 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/23#-MrTmpDd2UmI9BFi0TrE:-MrTrEm5CYbY1CcohvHh:b46abpz) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ad6c31e4b293a6e5907fb7a990298a9dfd68e970/controllers/vcdmachine_controller.go#L194)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

are there two phases of the same name @ltimothy7 ?
</blockquote></details>

Thanks for catching this Arun, there should be only one, and I reverted this change
___
*[controllers/vcdmachine_controller.go, line 410 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/23#-MrTm86yBq1bBmz4DOnW:-MrTnGpqC7mnCugNgmYg:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/ad6c31e4b293a6e5907fb7a990298a9dfd68e970/controllers/vcdmachine_controller.go#L410)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Add cluster name to the error return statement.
"Error retrieving bootstrap data for machine %s of the cluster %s
</blockquote></details>

Done.

**Pull request merged**
