### PR TITLE
VCDA-3561: add target to build conversion-gen and run with params

### PR DESCRIPTION
**Pull request by ymo24**
Signed-off-by: ymo24 <ymo@vmware.com>

* Created Make target: ```conversion-install``` to install the `conversion-gen`.
* Created Make target: ```generate_conversions``` to use conversion-gen tool to autogenerate conversion code.
* Testing done:
Add fields in vcdCluster -> run `make conversion-install` -> run `make generate_conversions` -> check the comments on ```api/v1alpha4/zz_generated.conversion.go```

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/113)

### CODE REVIEW

**Review by arunmk — APPROVED** [review]
:lgtm: with a few small nits. 

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/113#-:-N0bD4aJA87p82syzQRe:bfp6jdj)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @sahithi and @ymo24)

___
*[`Makefile` line 102 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/113#-N0bCeIR6Bj4P2KujmrF:-N0bCeIS4f22SoXVuCWH:bypeeay) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1b630306212dee12e0b568f8df2688b5c4b4a94c/Makefile#L102)):*
> ```Makefile
> CONVERSION_GEN_VER := v0.23.1
> CONVERSION_GEN_BIN := conversion-gen
> CONVERSION_GEN := $(shell pwd)/bin/$(CONVERSION_GEN_BIN)
> ```

nice :)
use GITROOT instead of `shell pwd`
___
*[`Makefile` line 140 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/113#-N0bCtTk3Y_zLThoEDDS:-N0bCtTk3Y_zLThoEDDT:b-kqdbtw) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1b630306212dee12e0b568f8df2688b5c4b4a94c/Makefile#L140)):*
> ```Makefile
> # Add a target to download and build conversion-gen; and then run it with the below params
> generate_conversions:  ## Runs Go related generate targets.
> 	$(CONVERSION_GEN) \
> ```

Can we delete the v1/alpha4/zz_generated.conversion.* files before running the tool so that we get clean files each time? @sahithi that should be okay, right?

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: once review comments are addressed

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/113#-:-N0bEuYQCVE4SJv9LDK-:blujttf)* status: all files reviewed, 2 unresolved discussions (waiting on @sahithi and @ymo24)

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/113)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk)

___
*[`Makefile` line 102 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/113#-N0bCeIR6Bj4P2KujmrF:-N0c5XVQDZI86-weVvII:b-kvtvpe) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1b630306212dee12e0b568f8df2688b5c4b4a94c/Makefile#L102)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

nice :)
use GITROOT instead of `shell pwd`
</blockquote></details>

Any specific reason why GITROOT? we do want to check in the "cluster-api-provider-cloud-director/bin/conversion_gen" into the repo, correct?  It goes alongside other binaries like controller-gen.
___
*[`Makefile` line 140 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/113#-N0bCtTk3Y_zLThoEDDS:-N0c4QUO7GOOXwNQ5c2L:bfq15qg) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1b630306212dee12e0b568f8df2688b5c4b4a94c/Makefile#L140)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we delete the v1/alpha4/zz_generated.conversion.* files before running the tool so that we get clean files each time? @sahithi that should be okay, right?
</blockquote></details>

I think yes, deleting it will avoid the issue Aniruddh has seen. 
conversion-gen seems to be doing merge rather than overwrite.

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/113)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk)

___
*[`Makefile` line 140 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/113#-N0bCtTk3Y_zLThoEDDS:-N0cNuma4mq8xT0T_SJC:bdlenpm) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1b630306212dee12e0b568f8df2688b5c4b4a94c/Makefile#L140)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I think yes, deleting it will avoid the issue Aniruddh has seen. 
conversion-gen seems to be doing merge rather than overwrite.
</blockquote></details>

Yeah, I have tested that. Every time I would get a brand-new zz_generated.conversion.go file.

**Review by arunmk — APPROVED** [review]
:lgtm: with a nit. Thanks for doing this!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/113#-:-N0gtWARD-Dt4btfuMIG:bwqg5d9)* status: all files reviewed, 3 unresolved discussions (waiting on @arunmk and @ymo24)

___
*[`Makefile` line 144 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/113#-N0gtJyW-cFmEL1NF_x3:-N0gtJyX1c5e3pAAOW61:b-57exfo) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/66ab56939bacaedead9460b7aa7c44898f0973e5/Makefile#L144)):*
> ```Makefile
> # Add a target to download and build conversion-gen; and then run it with the below params
> generate_conversions:  ## Runs Go related generate targets.
> 	rm ./api/v1alpha4/zz_generated.conversion.*
> ```

nit: better to do `rm $(GITROOT)/api/v1alpha4/zz_generated.conversion.*`

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/113)* status: all files reviewed, 3 unresolved discussions (waiting on @arunmk)

___
*[`Makefile` line 144 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/113#-N0gtJyW-cFmEL1NF_x3:-N0h62JjAEeg2Rwfx1DG:b-evgdnp) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/66ab56939bacaedead9460b7aa7c44898f0973e5/Makefile#L144)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

nit: better to do `rm $(GITROOT)/api/v1alpha4/zz_generated.conversion.*`
</blockquote></details>

Sure. Thank you for your feedback! It's much better to use full path than relative path.

**Review by sahithi — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/113#-:-N0qjoUv-7Cd2tC2whq5:bg7igkv)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @arunmk)

**Pull request merged**
