### PR TITLE
[VCDA-3290] Restart nodes in cloud-init if files are absent

### PR DESCRIPTION
**Pull request by Anirudh9794**
* Reboot nodes if files written during `write_files` are not present on the machine

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/53)

### CODE REVIEW

**Review by arunmk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/53#-:-Mv-ck0HCNPJz1cxZ1nL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7 and @sahithi)

**Review by ltimothy7 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/53)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sahithi)

**Review by sahithi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/53)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[controllers/cluster_scripts/cloud_init_control_plane.yaml, line 126 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/53#-Mv-iD5b-CsHA6GUELoK:-Mv-iD5b-CsHA6GUELoL:bdm3wn4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/43481e556d6b9a60067ba29c5200ee378de9daa5/controllers/cluster_scripts/cloud_init_control_plane.yaml#L126)):*
> ```YAML
>     exit 0
> runcmd:
> - '[ ! -f /root/vcloud-basic-auth.yaml ] && cloud-init clean && sudo reboot'
> ```

Why aren't we looking for the presence of other files - like kubeadm.yaml? Is it because it's part of the autogenerated bootstrap script?

**Comment by Anirudh9794** [comment]
___
*[controllers/cluster_scripts/cloud_init_control_plane.yaml, line 126 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/53#-Mv-iD5b-CsHA6GUELoK:-Mv-kYtMArhFLKI834yf:b-mb3tde) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/43481e556d6b9a60067ba29c5200ee378de9daa5/controllers/cluster_scripts/cloud_init_control_plane.yaml#L126)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Why aren't we looking for the presence of other files - like kubeadm.yaml? Is it because it's part of the autogenerated bootstrap script?
</blockquote></details>

Oh, I missed this. I was using `write_files` path present in this file. Will check this

**Pull request merged**
